# Contents {-}

<h3 class="TOC_TOC-F-B-Matter">[Guide to Electronic Versions](#G2EV)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Preface xi](#preface)</h3>
<div class="TOC-Part-Title-Container">
<h2 class="TOC_Huge-TOC-Part-Number">[Part 1](#the-scriptural-teaching)</h2>
<h2 class="TOC-Part-Title">[<span class="No-Ligatures">Th</span>e Scrip&#173;tural Teach&#173;ing&#160;&#160;&#160;1](#the-scriptural-teaching)</h2>
</div>
<!--<h3 class="TOC-Chapter-Num">[1](#_idTextAnchor004)</h3>-->
<ol>
<li class="TOC_TOC-Chapter">[From the Begin&#173;ning&#160;&#160;&#160;3](#from-the-beginning)
<h4 class="TOC_TOC-Subsection">[Genesis and Truth&#160;&#160;&#160;5](#_idTextAnchor008)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Beginning of Genesis&#160;&#160;&#160;9](#_idTextAnchor016)</h4>
<h4 class="TOC_TOC-Subsection">[Genesis 1&#160;&#160;▷&#160; Male and Female&#160;&#160;&#160;10](#_idTextAnchor019)</h4>
<h4 class="TOC_TOC-Subsection">[Genesis 2&#160;&#160;▷&#160; Flesh of My Flesh&#160;&#160;&#160;15](#_idTextAnchor022)</h4>
<h4 class="TOC_TOC-Subsection">[Genesis 2&#160;&#160;▷&#160; Subordi&#173;nation&#160;&#160;&#160;23](#_idTextAnchor038)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[2](#_idTextAnchor049)</h3>-->
<li class="TOC_TOC-Chapter">[Sin and the New Adam&#160;&#160;&#160;29](#sin-and-the-new-adam)
<h4 class="TOC_TOC-Subsection">[Genesis 3&#160;&#160;▷&#160; <span class="No-Ligatures">Th</span>e Man’s Rule&#160;&#160;&#160;31](#_idTextAnchor052)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e New Man&#173;kind&#160;&#160;&#160;36](#_idTextAnchor056)</h4>
<h4 class="TOC_TOC-Subsection">[Community and Subordi&#173;nation&#160;&#160;&#160;39](#_idTextAnchor063)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[3](#_idTextAnchor072)</h3>-->
<li class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e Family&#160;&#160;▷&#160; Husbands and Wives&#160;&#160;&#160;46](#the-family-husbands-and-wives)
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Husband’s Role&#160;&#160;&#160;48](#_idTextAnchor074)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Wife’s Role&#160;&#160;&#160;56](#_idTextAnchor088)</h4>
<h4 class="TOC_TOC-Subsection">[Raising Chil&#173;dren&#160;&#160;&#160;64](#_idTextAnchor104)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[4](#_idTextAnchor119)</h3>-->
<li class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e Family&#160;&#160;▷&#160; Key Texts&#160;&#160;&#160;72](#the-family-key-texts)
<h4 class="TOC_TOC-Subsection">[Ephesians 5:22<span class="No-Break">–3</span>3&#160;&#160;▷&#160; As Christ&#160;&#160;&#160;73](#_idTextAnchor121)</h4>
<h4 class="TOC_TOC-Subsection">[1&#160;Peter 3:1<span class="No-Break">–7</span>&#160;&#160;▷&#160; Joint Heirs&#160;&#160;&#160;88](#_idTextAnchor153)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Roles of Husbands and Wives&#160;&#160;&#160;95](#_idTextAnchor174)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[5](#_idTextAnchor183)</h3>-->
<li class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e People&#160;&#160;▷&#160; Service and Posi&#173;tion&#160;&#160;&#160;102](#the-people-service-and-position)
<h4 class="TOC_TOC-Subsection">[Prophesying, Teaching, Charitable Service&#160;&#160;&#160;104](#_idTextAnchor186)</h4>
<h4 class="TOC_TOC-Subsection">[Women in Missionary and Pastoral Service&#160;&#160;&#160;114](#_idTextAnchor196)</h4>
<h4 class="TOC_TOC-Subsection">[Men and Governmental Posi&#173;tions&#160;&#160;&#160;124](#_idTextAnchor226)</h4>
<h4 class="TOC_TOC-Subsection">[Roles and Community Struc&#173;ture&#160;&#160;&#160;134](#_idTextAnchor251)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[6](#_idTextAnchor261)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Social Roles and Galatians 3:28&#160;&#160;&#160;140](#social-roles-and-galatians-328)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e <span class="No-Ligatures">Th</span>rust of Galatians 3:28&#160;&#160;&#160;142](#_idTextAnchor266)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Galatians 3:28 and Social Differ&#173;ences&#160;&#160;&#160;152](#_idTextAnchor282)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Aboli&#173;tionism&#160;&#160;&#160;159](#_idTextAnchor295)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Value of Role Differ&#173;ences&#160;&#160;▷&#160; <br /><span class="No-Ligatures">Th</span>e New Testament View&#160;&#160;&#160;164](#_idTextAnchor303)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[7](#_idTextAnchor307)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[<span class="No-Ligatures">Th</span>e Community&#160;&#160;▷&#160; Key Texts <br />(1&#160;Corinthians 11:2<span class="No-Break">–1</span>6; 14:33<span class="No-Break">–3</span>6)&#160;&#160;&#160;168](#the-community-key-texts-1-corinthians-11216-143336)
<h4 class="TOC_TOC-Subsection-Scrunch">[1&#160;Corinthians 11:2<span class="No-Break">–1</span>6&#160;&#160;▷&#160; Dishonoring <span class="No-Ligatures">Th</span>eir Heads&#160;&#160;&#160;169](#_idTextAnchor308)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[1&#160;Corinthians 14:33<span class="No-Break">–3</span>6&#160;&#160;▷&#160; She Should Be Subordi&#173;nate&#160;&#160;&#160;187](#_idTextAnchor331)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[8](#_idTextAnchor341)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[<span class="No-Ligatures">Th</span>e Community&#160;&#160;▷&#160; Key Texts <br />(1&#160;Timothy 2:8<span class="No-Break">–1</span>5)&#160;&#160;&#160;194](#the-community-key-texts-1-timothy-2815)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e <span class="No-Ligatures">Th</span>rust of the Pas&#173;sage&#160;&#160;&#160;196](#_idTextAnchor344)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Grounding of the Pas&#173;sage&#160;&#160;&#160;204](#_idTextAnchor358)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[9](#_idTextAnchor375)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Summary&#160;&#160;▷&#160; <span class="No-Ligatures">Th</span>e New Testament Teaching as a Whole&#160;&#160;&#160;212](#summary-the-new-testament-teaching-as-a-whole)
<h4 class="TOC_TOC-Subsection-Scrunch">[Summary of the New Testament Teach&#173;ing&#160;&#160;&#160;213](#_idTextAnchor376)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Authority of the Teach&#173;ing&#160;&#160;&#160;216](#_idTextAnchor382)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Intent of the Teach&#173;ing&#160;&#160;&#160;218](#_idTextAnchor383)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Concluding Obser&#173;vations&#160;&#160;&#160;222](#_idTextAnchor386)</h4>
</li>
<li class="TOC_TOC-No-Num-Scrunch">[Note on Method&#160;&#160;▷&#160; Exegesis&#160;&#160;&#160;225](#note-on-method-exegesis)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Exegetical Ap&#173;proach&#160;&#160;&#160;225](#_idTextAnchor388)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Christian Liberationist Exe&#173;gesis&#160;&#160;&#160;230](#_idTextAnchor393)</h4>
</li>
</ol>
<div class="TOC-Part-Title-Container">
<h2 class="TOC_Huge-TOC-Part-Number">[Part 2](#assessing-the-scriptural-teaching)</h2>
<h2 class="TOC-Part-Title">[Assessing the Scrip&#173;tural Teach&#173;ing&#160;&#160;&#160;237](#assessing-the-scriptural-teaching)</h2>
</div>
<!--<h3 class="TOC-Chapter-Num">[10](#_idTextAnchor420)</h3>-->
<ol>
<li value="10" class="TOC_TOC-Chapter-Scrunch">[<span class="No-Ligatures">Th</span>e New Testament Approach&#160;&#160;▷&#160; <br />Jesus and Paul&#160;&#160;&#160;239](#the-new-testament-approach-jesus-and-paul)
<h4 class="TOC_TOC-Subsection-Scrunch">[A Distinctive New Testament Ap&#173;proach&#160;&#160;&#160;240](#_idTextAnchor421)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Jesus and First-Century Juda&#173;ism&#160;&#160;&#160;243](#_idTextAnchor426)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Paul and Pagan Cul&#173;ture&#160;&#160;&#160;255](#_idTextAnchor449)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[11](#_idTextAnchor460)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[<span class="No-Ligatures">Th</span>e New Testament Approach&#160;&#160;▷&#160; <br />Setting and Cul&#173;ture&#160;&#160;&#160;260](#the-new-testament-approach-setting-and-culture)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e New Testament and Social Struc&#173;ture&#160;&#160;&#160;261](#_idTextAnchor462)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e New Testament in Its Setting&#160;&#160;&#160;267](#_idTextAnchor469)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Question of “Cul&#173;ture”&#160;&#160;&#160;276](#_idTextAnchor478)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[12](#_idTextAnchor495)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Christian Tradition&#160;&#160;▷&#160; Husbands and Wives&#160;&#160;&#160;286](#christian-tradition-husbands-and-wives)
<h4 class="TOC_TOC-Subsection-Scrunch">[What Is Tradi&#173;tion?&#160;&#160;&#160;288](#_idTextAnchor496)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Family Order in Tradi&#173;tion&#160;&#160;&#160;290](#_idTextAnchor503)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[13](#_idTextAnchor534)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Christian Tradition&#160;&#160;▷&#160; Government of the Commu&#173;nity&#160;&#160;&#160;303](#christian-tradition-government-of-the-community)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Evidence for Governing Posi&#173;tions&#160;&#160;&#160;304](#_idTextAnchor535)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Strength of Tradi&#173;tion&#160;&#160;&#160;322](#_idTextAnchor577)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[14](#_idTextAnchor592)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[<span class="No-Ligatures">Th</span>e Authority of Scripture&#160;&#160;&#160;333](#the-authority-of-scripture)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Nature of Scriptural Author&#173;ity&#160;&#160;&#160;335](#_idTextAnchor595)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Submission to Scrip&#173;ture&#160;&#160;&#160;339](#_idTextAnchor608)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Is <span class="No-Ligatures">Th</span>is Fundamen&#173;talism?&#160;&#160;&#160;352](#_idTextAnchor627)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[15](#_idTextAnchor637)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Bypassing Scriptural Authority&#160;&#160;&#160;358](#bypassing-scriptural-authority)
<h4 class="TOC_TOC-Subsection-Scrunch">[Modern By&#173;passes&#160;&#160;&#160;358](#_idTextAnchor638)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Real Chal&#173;lenge&#160;&#160;&#160;373](#_idTextAnchor659)</h4>
</li>
</ol>
<div class="TOC-Part-Title-Container">
<h2 class="TOC_Huge-TOC-Part-Number">[Part 3](#the-scriptural-teaching-in-contemporary-society)</h2>
<h2 class="TOC-Part-Title">[<span class="No-Ligatures">Th</span>e Scrip&#173;tural Teach&#173;ing in Contem&#173;porary Society&#160;&#160;&#160;377](#the-scriptural-teaching-in-contemporary-society)</h2>
</div>
<!--<h3 class="TOC-Chapter-Num">[16](#_idTextAnchor663)</h3>-->
<ol>
<li value="16" class="TOC_TOC-Chapter-Scrunch">[Men’s and Women’s Differ&#173;ences&#160;&#160;▷&#160; <br />Individual Charac&#173;teristics&#160;&#160;&#160;379](#mens-and-womens-differences-individual-characteristics)
<h4 class="TOC_TOC-Subsection-Scrunch">[Understanding Men’s and Women’s Differ&#173;ences&#160;&#160;&#160;382](#_idTextAnchor664)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Descriptive Social Sci&#173;ence&#160;&#160;&#160;385](#_idTextAnchor669)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Experimental Psychol&#173;ogy&#160;&#160;&#160;402](#_idTextAnchor708)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[17](#_idTextAnchor766)</h3>-->
<li class="TOC_TOC-Chapter-Scrunch">[Men’s and Women’s Differ&#173;ences&#160;&#160;▷&#160; <br />Social Structural Charac&#173;teristics&#160;&#160;&#160;421](#mens-and-womens-differences-social-structural-characteristics)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Social Structural Patterns of Men and Wom&#173;en&#160;&#160;&#160;422](#_idTextAnchor767)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Explaining the Social Structural Data&#160;&#160;&#160;439](#_idTextAnchor837)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Conclusion&#160;&#160;▷&#160; Individual Charac&#173;teristics and Social Structural Charac&#173;teris&#173;tics&#160;&#160;&#160;448](#_idTextAnchor856)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Consequences and Direc&#173;tions&#160;&#160;&#160;451](#_idTextAnchor858)</h4>
</li>
<li class="TOC_TOC-No-Num-Scrunch">[Note on Method&#160;&#160;▷&#160; Social Science&#160;&#160;&#160;460](#note-on-method-social-science)
<h4 class="TOC_TOC-Subsection-Scrunch">[<span class="No-Ligatures">Th</span>e Distinc&#173;tiveness of <span class="No-Ligatures">Th</span>is Book’s Ap&#173;proach&#160;&#160;&#160;460](#_idTextAnchor878)</h4>
<h4 class="TOC_TOC-Subsection-Scrunch">[Feminist Social Science&#160;&#160;&#160;464](#_idTextAnchor883)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[18](#_idTextAnchor914)</h3>-->
<li value="18" class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e New Social Environ&#173;ment&#160;&#160;▷&#160; <br />Techno&#173;logical Society&#160;&#160;&#160;478](#the-new-social-environment-technological-society)
<h4 class="TOC_TOC-Subsection">[Technological and Traditional Soci&#173;eties&#160;&#160;&#160;479](#_idTextAnchor917)</h4>
<h4 class="TOC_TOC-Subsection">[Functional and Relational Principles of Social Struc&#173;ture&#160;&#160;&#160;483](#_idTextAnchor926)</h4>
<h4 class="TOC_TOC-Subsection">[Social Structure in Techno&#173;logical Society&#160;&#160;&#160;491](#_idTextAnchor941)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Family in Techno&#173;logical Society&#160;&#160;&#160;502](#_idTextAnchor967)</h4>
<h4 class="TOC_TOC-Subsection">[Men’s and Women’s Roles and the Misin&#173;terpre&#173;tation of Social History&#160;&#160;&#160;510](#_idTextAnchor996)</h4>
<h4 class="TOC_TOC-Subsection">[Evaluating Techno&#173;logical Society&#160;&#160;&#160;514](#_idTextAnchor1001)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[19](#_idTextAnchor1010)</h3>-->
<li class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e New Intellectual Environ&#173;ment&#160;&#160;▷&#160; <br />Ideology and Christi&#173;anity&#160;&#160;&#160;519](#the-new-intellectual-environment-ideology-and-christianity)
<h4 class="TOC_TOC-Subsection">[Modern Ideological Posi&#173;tions&#160;&#160;&#160;520](#_idTextAnchor1011)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Christian Re&#173;sponse&#160;&#160;&#160;536](#_idTextAnchor1061)</h4>
<h4 class="TOC_TOC-Subsection">[Concluding Obser&#173;vations&#160;&#160;&#160;551](#_idTextAnchor1067)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[20](#_idTextAnchor1069)</h3>-->
<li class="TOC_TOC-Chapter">[Applying Scrip&#173;tural Teach&#173;ing&#160;&#160;&#160;554](#applying-scriptural-teaching)
<h4 class="TOC_TOC-Subsection">[What Is Its Meaning for Now?&#160;&#160;&#160;556](#_idTextAnchor1072)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Intent of Scrip&#173;ture&#160;&#160;&#160;571](#_idTextAnchor1095)</h4>
<h4 class="TOC_TOC-Subsection">[Some Principles of Appli&#173;cation&#160;&#160;&#160;579](#_idTextAnchor1101)</h4>
</li>
</ol>
<div class="TOC-Part-Title-Container">
<h2 class="TOC_Huge-TOC-Part-Number">[Part 4](#a-christian-approach-for-today)</h2>
<h2 class="TOC-Part-Title">[A Christian Approach for To&#173;day&#160;&#160;&#160;587](#a-christian-approach-for-today)</h2>
</div>
<ol>
<!--<h3 class="TOC-Chapter-Num">[21](#_idTextAnchor1110)</h3>-->
<li value="21" class="TOC_TOC-Chapter">[<span class="No-Ligatures">Th</span>e Bases of a Christian Approach Today&#160;&#160;&#160;589](#the-bases-of-a-christian-approach-today)
<h4 class="TOC_TOC-Subsection">[Becoming a People&#160;&#160;&#160;591](#_idTextAnchor1111)</h4>
<h4 class="TOC_TOC-Subsection">[Restoring Christian Relation&#173;ships&#160;&#160;▷&#160; <br />Relational Group&#173;ings&#160;&#160;&#160;594](#_idTextAnchor1115)</h4>
<h4 class="TOC_TOC-Subsection">[Restoring Christian Social Struc&#173;ture&#160;&#160;▷&#160; <br />Social Roles&#160;&#160;&#160;599](#_idTextAnchor1120)</h4>
<h4 class="TOC_TOC-Subsection">[Alternate Social Patterns&#160;&#160;▷&#160; <br />Tradition&#173;alism and Social&#173;ism&#160;&#160;&#160;608](#_idTextAnchor1142)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[22](#_idTextAnchor1148)</h3>-->
<li class="TOC_TOC-Chapter">[Guidelines for a Modern Christian Approach to Men’s and Women’s Roles&#160;&#160;&#160;614](#guidelines-for-a-modern-christian-approach-to-mens-and-womens-roles)
<h4 class="TOC_TOC-Subsection">[Basic Prerequisites for Men’s and Women’s Roles&#160;&#160;&#160;615](#_idTextAnchor1149)</h4>
<h4 class="TOC_TOC-Subsection">[Key Biblical Teaching on Men’s and Women’s Roles&#160;&#160;&#160;618](#_idTextAnchor1153)</h4>
<h4 class="TOC_TOC-Subsection">[Adapting to Techno&#173;logical Society&#160;&#160;&#160;626](#_idTextAnchor1159)</h4>
<h4 class="TOC_TOC-Subsection">[Relating Outside of Christian Commu&#173;nity&#160;&#160;&#160;629](#_idTextAnchor1160)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Feasibility of a Christian Resto&#173;ration of Men’s and Women’s Roles&#160;&#160;&#160;636](#_idTextAnchor1161)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[23](#_idTextAnchor1162)</h3>-->
<li class="TOC_TOC-Chapter">[Special Issues in Constructing a Modern Christian Social Struc&#173;ture&#160;&#160;&#160;637](#special-issues-in-constructing-a-modern-christian-social-structure)
<h4 class="TOC_TOC-Subsection">[Strengthening Family Life&#160;&#160;&#160;638](#_idTextAnchor1163)</h4>
<h4 class="TOC_TOC-Subsection">[Structures of Christian Leader&#173;ship&#160;&#160;&#160;642](#_idTextAnchor1164)</h4>
<h4 class="TOC_TOC-Subsection">[Male and Female Person&#173;ality&#160;&#160;&#160;650](#_idTextAnchor1165)</h4>
<h4 class="TOC_TOC-Subsection">[Relationships between Men and Wom&#173;en&#160;&#160;&#160;666](#_idTextAnchor1188)</h4>
<h4 class="TOC_TOC-Subsection">[Single People&#160;&#160;&#160;669](#_idTextAnchor1192)</h4>
<h4 class="TOC_TOC-Subsection">[<span class="No-Ligatures">Th</span>e Need for a Pastoral Strat&#173;egy&#160;&#160;&#160;671](#_idTextAnchor1194)</h4>
</li>
<!--<h3 class="TOC-Chapter-Num">[24](#_idTextAnchor1195)</h3>-->
<li class="TOC_TOC-Chapter">[Ordination, Occupation, Legislation&#160;&#160;&#160;673](#ordination-occupation-legislation)
<h4 class="TOC_TOC-Subsection">[Ordination of Wom&#173;en&#160;&#160;&#160;674](#_idTextAnchor1196)</h4>
<h4 class="TOC_TOC-Subsection">[Women and Occu&#173;pations&#160;&#160;&#160;678](#_idTextAnchor1206)</h4>
<h4 class="TOC_TOC-Subsection">[Legis&#173;lation&#160;&#160;&#160;683](#_idTextAnchor1207)</h4>
<h4 class="TOC_TOC-Subsection">[Christians in the World&#160;&#160;&#160;687](#_idTextAnchor1208)</h4>
</li>
</ol>
<h3 class="TOC_TOC-F-B-Matter">[Afterword&#160;&#160;&#160;689](#afterword)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Bibliog&#173;raphy&#160;&#160;&#160;691](#bibliography)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Notes&#160;&#160;&#160;697](#notes)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Scripture Index&#160;&#160;&#160;779](#scripture-index)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Topical Index&#160;&#160;&#160;783](#topical-index)</h3>
<h3 class="TOC_TOC-F-B-Matter">[Publication Info](#publication-info)</h3>
