# Guide to Electronic Versions {- #G2EV}

<p class="BODY-STYLES_Chapter-Opening"><span class="MaWiC_Subhead-Drop-Words">As</span> far as possible, we have coordinated the electronic versions of this 2021 re-release of <span class="Italic">Man and Woman in Christ</span> with the hardcover print version, which can be purchased on <a href="https://www.amazon.com/dp/1940017300/ref=cm_sw_em_r_mt_dp_E8EBSPCHBCXJH1FSTSE7">Amazon</a> or at discounted bulk rates directly from <a href="https://warhornmedia.com/2021/03/30/book-orders/">Warhorn Media</a>.</p>
<p class="BODY-STYLES_Body">In the print version, footnotes are referenced in the text using symbols (*, †, ‡, §, ¶), and the footnote text appears at the bottom of the page. In this electronic version, footnotes are referenced with the same symbols as the print version, but the footnote text appears at the end of the chapter, preceded by the print version page number and the footnote symbol. For example, the footnote which is referenced by a dagger (†) in the text on page&#160;90 of the print version is referenced by the same symbol (†) in the electronic version, but the footnote text is placed at the end of Chapter Four and numbered as 90†. When you reach the end of a chapter in the electronic version, click on <span class="Italic">Skip footnotes ▸</span> to jump to the beginning of the next section of the book.</p>
<p class="BODY-STYLES_Body">Endnotes are referenced by superscript numbers in the text; these numbers are identical in the print and electronic versions. As in the print version, all endnotes are placed at the end of the book in the section titled “Notes.” On some devices, tapping on an endnote reference may trigger a popup which incorrectly labels the endnotes as “Footnotes.” <span class="No-Ligatures">Th</span>is popup also might only display a portion of the endnote text. You may need to click on something like “Go To Footnotes” to see the full endnote text.</p>
<p class="BODY-STYLES_Body">To return to the main text of the book from a footnote or endnote, tap or click on the footnote number or endnote number.</p>
<p class="BODY-STYLES_Body">Cross references within the electronic version use page numbers from the print version as their references, but they are hyperlinked for easy navigation. Print page numbers are also used in the [Scripture Index](#scripture-index){style="font-weight:normal;"} and [Topical Index](#topical-index){style="font-weight:normal;"} of the electronic version, and these cross references are also hyperlinked.</p>
<p class="BODY-STYLES_Body">Don’t be surprised if there is a brief delay between clicking or tapping a hyperlink and being taken to the referenced footnote, endnote, or cross reference. <span class="No-Ligatures">Th</span>e book is very long, and your ebook reader might take a few seconds to find the location of the hyperlink.</p>
<p class="BODY-STYLES_Body">If you find any typos or experience problems with ebook functionality, or for sales information, please contact us at <a href="mailto:admin@warhornmedia.com">admin@warhornmedia.com</a>.</p>
<div class="Buy-Buttons">
<p class="Buy-Button"><a href="https://www.amazon.com/dp/1940017300/ref=cm_sw_em_r_mt_dp_E8EBSPCHBCXJH1FSTSE7">Buy on Amazon</a></p>
<p class="Buy-Button"><a href="https://warhornmedia.com/contact-us/">Contact WARHORN Sales</a></p>
</div>