# Preface {-}

<a id="_idTextAnchor000"></a>
<p class="BODY-STYLES_Body-NI"><span class="MaWiC_Subhead-Drop-Words">When</span> a group of Christians I belonged to used to gather together for prayer, we would sometimes sing songs that had separate parts for men and women. For a while, however, we did not pay much attention to the fact that men and women were supposed to sing different parts. We felt that when men and women did things together, they should do them in basically the same way. So when our music leaders would introduce a song that had different parts for men and women, they would instruct everyone to sing the whole song together.</p>
<p class="BODY-STYLES_Body">At one point, however, under the encouragement of some who were convinced of the value of separate parts for men and women, we began to sing some of these songs the way they were originally written. When we did this, the consensus was that something worthwhile had been added to our ability to sing and worship the Lord. In fact, most people were enthusiastic about the new dimension of beauty and expression that had been added to our life together.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is lesson was symbolic of an important truth. Men and women should live together in love and serve the Lord together. Most of what they should be doing is the same. But as we learn how to perceive and draw upon the value of what is distinctive to men and to women, our life together becomes stronger and more beautiful. <span class="No-Ligatures">Th</span>ere is something worthwhile about women for which men cannot substitute, and vice versa. When we live our life together as Christians “the way it was written,” it becomes better.</p>
<p class="BODY-STYLES_Body">Today there is a flood of books on women. Most of them are written by women who in one way or another are part of the modern feminist movement. A high percentage of them are Americans. <span class="No-Ligatures">Th</span>ey press for equality between men and women and for the elimination of many of the differences between them which have been part of life in contemporary Western society. <span class="No-Ligatures">Th</span>eir writings are a symptom of a serious problem area in our society, and are fair warning that it is no longer possible to approach men and women in a traditional way or even with the remnants of a traditional approach.</p>
<p class="BODY-STYLES_Body">With all these books and articles, one would think that enough had been written about the issues bearing on men and women. In fact, too much has been written on the subject: <span class="No-Ligatures">Th</span>e flood of material has produced a certain amount of confusion and unclarity. Before people in our society are rushed down a steep bank into the sea, Christians need to look again at this area to understand how they should approach it.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is book is written in the conviction that the modern discussion about men and women normally misses something crucial: the perspective of social roles. Much of the modern feminist movement in church and society is advocating measures that would destroy social roles that have performed a useful function in all of past societies. At the same time, they seem to be unaware that their proposals lead to a restructuring of the very bases of our society. Hence, they miss many of the real issues. In the last three hundred years there has been a significant cultural change in Western society, a change that makes it difficult to understand the significance of social roles. Before dismantling the last elements of the social roles of the past, we need to ask what useful social function they performed and what we are going to do to replace that social function. Such a view can give us a greater respect for many elements of scriptural teaching, because the scriptures were written from within a culture that understood some things better than our own. Seeing men-women differences in the perspective of social roles makes a major difference in understanding the past and the present. Discussions of men-women issues without this perspective are seriously deficient.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is is not a book on the political issues raised by the feminist movement. Most people expect a Christian book on the roles of men and women to focus on the issue of ordination. While there is much material in the book relevant to the question of ordination, and while during the discussion of scriptural teaching it might appear as though ordination is the issue, this book does not really treat the question. If there was any issue that gave rise to the ideas in this book, it was the issue of raising children. What are we to say to children about the fact that they are boys and girls?&#160;How are we to teach them to relate to their maleness and their femaleness?</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e feminist movement in church and society is a political movement. <span class="No-Ligatures">Th</span>is book is not and was not produced as a counter to the feminist movement. With some regularity, arguments and assertions of feminist authors have to be dealt with in this book because they seriously cloud important truths. But the book is not concerned to address, much less oppose, most of the feminist program. Its thrust is rather to say that some important human realities are increasingly being neglected, and that the Christian people will suffer as a result.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is, then, is a book on social roles for men and women. <span class="No-Ligatures">Th</span>ere is, of course, much more about men and women that could profitably be discussed. Very little is said, for instance, with regard to the sexual relationship between men and women, although it is certainly of foundational importance. <span class="No-Ligatures">Th</span>e topic is restricted, but only so that the question of social roles can be seen more clearly. It should also be emphasized that this is a book about the social roles of both men and women. While much of the literature on social roles has focused on women, this book is written in the conviction that the roles of men and women are complementary and that one cannot be understood without the other.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e pages that follow were written primarily for Christians. Others might well learn from them, but they were written from a Christian perspective. In this perspective, the data of revelation are of primary importance. <span class="No-Ligatures">Th</span>e first and most important question in considering the roles of men and women is whether the Lord has said or taught anything about them and, if so, how Christians should respond to his word. Today many Christians are eager to say that there is nothing clear about social roles in scripture (or Christian tradition) that they have to be bound by. <span class="No-Ligatures">Th</span>ey say that there is a great cultural gap between New Testament times and the modern world which makes it impossible to view scriptural teaching as being directly intended for us. Indeed, there is a great cultural gap, a gap that makes traditionalism in social roles impossible. Nonetheless, such an offhand dismissal of the teaching of scripture and tradition makes it possible for modern Christians to leave an entire area of life out of their submission to the Lord. Since it is such an important area personally, and since it is an area that is a crucial piece in a great cultural development taking place in our society and among Christians, those who adopt this attitude are saying that they are free to make their own decisions without the guidance of Christian revelation in an area that is central to the way human beings are formed.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e pages that follow include as a special concern the life of Christian communities. If this book were written solely for Christians who were not part of something that could be described as a Christian community, it would have to be written differently. Much would have to be left out or refocused. <span class="No-Ligatures">Th</span>erefore, only those who are in Christian communities will find all of it helpful. <span class="No-Ligatures">Th</span>is does not mean, however, that most Christians will not find the book helpful. In fact, for those who do not belong to a Christian community, the pages on the usefulness of Christian community for dealing with some of the social problems facing Christians today might be one of the more helpful aspects of the book.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is book advocates an approach to men-women roles for Christians. Its purpose is practical, or pastoral. <span class="No-Ligatures">Th</span>is book could even be described as a book in pastoral theology. But the discussion is not intended just for theologians; it is intended for all those who are taking a concern for how Christian life should be formed in the twentieth century.</p>
<p class="BODY-STYLES_Body">Since this book is written for the layman as well as the theologian, much of the technical material has been kept out of the text. <span class="No-Ligatures">Th</span>e footnotes at the bottom of the page and the special Notes on Method have been written to provide a more in-depth treatment of certain technical issues which can clarify the basic argument in the text. <span class="No-Ligatures">Th</span>e notes at the back of the book contain most of the bibliographical references as well as the discussions that call for special acquaintance with the scholarly literature or scholarly tools. <span class="No-Ligatures">Th</span>e reader can omit all the footnotes and the Notes on Method and still grasp the argument of the book.</p>
<p class="BODY-STYLES_Body">Finally, this book was also written with an ecumenical audience in mind. Many questions that face Christians will be approached and solved differently by Christians from different church and theological traditions. Ordination of women, for instance, is one of them. Catholic and Orthodox discussions of ordination focus a great deal on sacramental and canonical considerations that are strange reading to an Evangelical Protestant. But the broader question of the roles of men and women presents itself in much the same way to Orthodox, Catholic, Lutheran, Reformed, Evangelical, Pentecostal. Many of the same positions are heard in every church, and much the same arguments are used. Orthodox and Catholics will want to rely more heavily on Christian tradition (perhaps), but a consideration from tradition does not significantly modify the results of a consideration from scripture. Moreover, the methods of scriptural interpretation used by the different church traditions to determine what Christians should do are not materially different when it comes to questions of social roles. <span class="No-Ligatures">Th</span>is may be due to the fact that theological thought with regard to social roles is underdeveloped in all traditions. It may also be due to the fact that in past centuries there has been relatively little controversy over the roles of men and women in comparison with controversies over Christology or Soteriology. At any rate, the differences of method in this area are not significant between, for instance, Catholic and Evangelical. <span class="No-Ligatures">Th</span>eir divisions lie elsewhere.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is book was written with the help of many. It depends, first of all, on the experiences and input of a large number of Christian men and women who have tried to seek and live out God’s will in the area of social roles. <span class="No-Ligatures">Th</span>is book also depends on the work of a smaller group of people who critiqued talks and manuscripts and made suggestions for new approaches or new materials: Here I would particularly like to thank John Keating, Mark Kinzer, James Manney, Barbara Morgan, Philip O’Mara, and Juliet Pressel for their many hours of dedicated work. Besides these there are a number of men and women who read the manuscript after its completion and made valuable comments leading to significant improvements. Among these I would particularly like to thank Rev.&#160;Donald Basham, Dr.&#160;Donald Bloesch, Rev.&#160;Larry Christenson, Dr.&#160;George Drum, Dr.&#160;Gregory Gavrilides, Rev.&#160;<span class="No-Ligatures">Th</span>eodore Jungkuntz, Dr.&#160;Kerry Koller, Fr.&#160;Francis Martin, Ralph Martin, Previtera Alexandra Poulos, Dr.&#160;Kevin and Dorothy Ranaghan, and, although he was unable to read the entire manuscript and evaluate its conclusions, I would like to thank Fr.&#160;George Montague for his helpful comments and suggestions which bore especially on the first few chapters of this work. <span class="No-Ligatures">Th</span>anks also is due to the many who worked on research, translation, editing and typing, especially to Stephen Lucchetti for his work on the index. Particular thanks goes to John Keating and Mark Kinzer for the great amount of time and energy they spent in researching the book. A book like this could not be written today without much more research than one person could do alone, unless the writing of it were to take many more years than it has in this case taken. Of course, the final responsibility for the arguments and conclusions found in this book is my own. In an area as controversial as that of men’s and women’s roles, no one should be held responsible for another’s opinions, even when a person might agree with a good part of those opinions.</p>
