# Summary&#160;&#160;▷&#160; The New Testament Teaching as a Whole

<a id="_idParaDest-37"></a><a id="_idTextAnchor375"></a>
<p class="BODY-STYLES_Chapter-Opening"><span class="Drop-Cap"><a id="_idIndexMarker520"></a></span><span class="Drop-Cap">T</span><span class="Opening-Drop-Words">his chapter</span> will summarize the teaching contained in the six key texts discussed in Chapters Four, Seven, and Eight. Key texts are those texts which explicitly and authoritatively address our subject—the roles of men and women. Of course other material from the New Testament is relevant for understanding the New Testament approach to the roles of men and women. Much of this additional material has already been considered, and Chapter Ten will consider further scriptural data in an attempt to see the teaching and patterns in a historical perspective. <span class="No-Ligatures">Th</span>is chapter, however, simply summarizes those passages which explicitly teach about the roles of men and women.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is summary is a synthesis of the New Testament teaching, not a descriptive summary of attitudes toward men and women in the New Testament. <span class="No-Ligatures">Th</span>e texts are approached here as teaching, instruction given authoritatively to direct the life of the Christian people. <span class="No-Ligatures">Th</span>at teaching will be synthesized and the direction which emerges from it as a whole will be stated. Of course, the six key texts contain different perspectives and approaches, but they do not cancel one another out. <span class="No-Ligatures">Th</span>ey are basically compatible. <span class="No-Ligatures">Th</span>is synthesis may leave out observations which would be of interest if the goal were to create a descriptive summary for historical purposes, or for the purposes of studying biblical theology as found in various works and authors. It does not, however, have to be imposed upon the texts by doing violence to any of them, or ignoring relevant elements of their teaching.</p>

<a id="_idTextAnchor376"></a><a id="_idIndexMarker521"></a><a id="_idParaDest-38"></a>

## Summary of the New Testament Teaching {-}

<p class="BODY-STYLES_Subhead-Opening-SA"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e </span>New Testament teaching can be summarized in the four points which follow.</p>
<ol>
<li class="BODY-STYLES_L-O-Ltr-L1-1st"><!--<span class="Body-List-Counter-Float">A.</span>--><span class="Italic"><a id="_idTextAnchor377"></a><span class="No-Ligatures">Th</span>e primary context of the New Testament teaching on the roles of men and women is the teaching on the nature of the redeemed community as the new humanity.</span> <span class="No-Ligatures">Th</span>e Christian people are called to be the human race living according to God’s original intention. <span class="No-Ligatures">Th</span>ey are able to fulfill that call because they have been restored in Christ to the image of God—corporately and individually. Men and women alike share in this fundamental truth. Men and women alike are fully in Christ, equally forming part of his body. Both are called to fulfill God’s commission for humanity. From this point of view, the fact that men and women are Christians or (redeemed) humans is more important than the fact that they are males and females. Moreover, the daily relating of men and women to one another is not primarily determined by their sex differences. Rather, their relating is determined by their status as brothers and sisters in the Lord who are called to love one another and build one another up in him.
<p class="BODY-STYLES_Para-w-in-List-Item-L1"><span class="No-Ligatures">Th</span>is last point could be stressed even more. An extensive discussion of the roles of men and women such as the one in this book seems to imply that nothing in human relationships is as important as the fact that human beings are male and female. <span class="No-Ligatures">Th</span>e danger is that of overemphasizing the importance of sex differences—to the point of treating men and women as two utterly different creatures. In the New Testament teaching, the male-female difference is very important and conditions much of the way that members of the Christian community relate to one another. However, it is far from the most important aspect of human beings. Most New Testament teaching applies to men and women alike. <span class="No-Ligatures">Th</span>e primary directives for daily life found in the New Testament are instructions to love one another, to forgive one another as Christ forgave us, to put away resentment, strife, and all the other obstacles to the love that Christ teaches. <span class="No-Ligatures">Th</span>is daily life of mutual care and service is the core of the New Testament message about how to live as a Christian, and it applies to men and women alike.</p>
</li>
<li class="BODY-STYLES_L-O-Ltr-L1"><!--<span class="Body-List-Counter-Float">B.</span>--><a id="_idIndexMarker522"></a><a id="_idIndexMarker523"></a><span class="Italic">Within the redeemed community, relationships have an order based on the structure of the roles of men and women.</span> <span class="No-Ligatures">Th</span>is order stems from God’s purposes for the human race as expressed in his original creation. <span class="No-Ligatures">Th</span>ere are two key elements in this order of relationships: (1)&#160;within the family, the man is the head of the woman and has the primary governmental authority over the family; (2)&#160;within the Christian people as a whole, the elders—those with governmental authority—are men. <span class="No-Ligatures">Th</span>e order for the people as a whole is based upon and supports the family order. <span class="No-Ligatures">Th</span>e purpose of the order in both the family and the Christian community is to create a unity where each member is ordered under another so that the family or community can function effectively as one. Such a unity and harmony also makes possible proper care for all the members of the community. <span class="No-Ligatures">Th</span>e early Christians strove to be a body in good order, with every need being cared for and with the whole body providing an image of God’s purpose for the human race.</li>
<li class="BODY-STYLES_L-O-Ltr-L1"><!--<span class="Body-List-Counter-Float">C.</span>--><span class="Italic"><a id="_idTextAnchor378"></a><span class="No-Ligatures">Th</span>e basic order of the roles of men and women in the Christian community is incarnated in certain explicit expressions.</span> Men and women should dress differently at the assemblies of the community (<a id="_idIndexMarker524"></a><span class="Lining-Nums">1&#160;</span>Cor 11:2<span class="No-Break">–1</span>6). Men and women should likewise speak at the assemblies differently (<a id="_idIndexMarker525"></a><span class="Lining-Nums">1&#160;</span>Cor 14:33<span class="No-Break">–3</span>5). Women, at least in the appropriate situations, should manifest character traits of respectfulness and quietness that express their submission to the men that they are subordinate to (<a id="_idIndexMarker526"></a><span class="Lining-Nums">1&#160;</span>Pt 3:4; <a id="_idIndexMarker527"></a><span class="Lining-Nums">1&#160;</span>Tm 2:11). <span class="No-Ligatures">Th</span>e men should honor their women such that the value and the respect they deserve is not undercut by their subordination (<a id="_idIndexMarker528"></a><span class="Lining-Nums">1&#160;</span>Pt 3:7). In essence, the basic order for men and women should be worked into the daily life of the Christian people. It should be expressed so that it can be seen and experienced, not just inferred from hearing the correct teaching.
<p class="BODY-STYLES_Para-w-in-List-Item-L1"><span class="No-Ligatures">Th</span>ere are some significant unclarities about the manner of cultural expression taught among the early Christians. <span class="No-Ligatures">Th</span>e scripture directs women to avoid active participation in the teaching of the community and perhaps other directional matters that are being discussed, but exactly what might be permitted and prohibited is not clear. <span class="No-Ligatures">Th</span>e concrete situation to which the rule applied is no longer part of our experience. <span class="No-Ligatures">Th</span>e scripture directs women to wear some kind of headcovering at the assemblies of the community, but what qualifies as a suitable headcovering is unclear. <span class="No-Ligatures">Th</span>e scripture teaches husbands to honor their wives, but what constitutes honoring them is not recorded. In short, the scripture clearly teaches that there should be an appropriate expression in the community of the order of the roles of men and women. However, the exact manner of expression is not stated clearly enough that a contemporary group of Christians could try to copy the early Christians exactly and be confident that they were actually succeeding. In other words, the New Testament teaching encourages adequate cultural expressions, but does not enjoin an exact pattern of cultural expressions.<a id="_idTextAnchor379"></a></p>
</li>
<li value="4" class="BODY-STYLES_L-O-Ltr-L1-SA"><!--<span class="Body-List-Counter-Float">D.</span>--><span class="Italic">In the early Christian communities, a broader role difference between men and women underlay the specific injunctions in the New Testament about man-woman order and about expressions of that order.</span> <span class="No-Ligatures">Th</span>e teaching about man-woman order made sense because it ordered a role difference that was important in the conduct of daily life. <span class="No-Ligatures">Th</span>e full roles of men and women as they were lived out in the early Christian community can only be pieced together. <span class="No-Ligatures">Th</span>ese roles are not taught or enjoined in the New Testament. But it is important to grasp some element of this broad difference between men and women in their roles, because that difference underlies the meaning of the statements about government in the family and Christian community.</li>
</ol>
<p class="BODY-STYLES_Body-SA"><a id="_idTextAnchor380"></a><span class="No-Ligatures">Th</span>ree points are especially helpful for filling out the picture provided by the key points of order stated in <span class="OT-All-Small-Caps">B</span>:</p>
<ol>
<li class="BODY-STYLES_L-O-Num-L1-1st"><!--<span class="Body-List-Counter-Float">1.</span>-->Women normally functioned in positions of responsibility for others, but subordinate to the men. In the family, wives were to rule their households under their husbands; in the community, women were appointed as deaconesses (widows) to assist the men pastors in caring for the people. Women were not passive. <span class="No-Ligatures">Th</span>ey took active responsibility, but in a way shaped by their working relationship with the man who had the primary governmental authority.</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">2.</span>-->In “rearing” and caring for the Christian people, men took the primary responsibility for other men, and women for other women.</li>
<li class="BODY-STYLES_L-O-Num-L1-SA"><!--<span class="Body-List-Counter-Float">3.</span>-->Men and women had different spheres of responsibility in each communal situation. <span class="No-Ligatures">Th</span>e men were “providers” and the women served the more immediate needs. Men and women between them divided up the responsibilities for the family and community.</li>
</ol>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e New Testament teaching on the roles of men and women is a teaching for relationships in the Christian community. Different roles for men and women provide a way of patterning relationships so that the life of the community is built up most effectively. <span class="No-Ligatures">Th</span>e order enjoined in the New Testament is primarily intended for communal relationships—the family and the Christian community as a whole. It does not necessarily or easily apply to functional relationships of the sort one might find in a modern factory. <span class="No-Ligatures">Th</span>e New Testament teaching does not focus on jobs or activities, nor is it necessarily based on ability differences. <span class="No-Ligatures">Th</span>e teaching centers on relationships and patterns for those relationships which adequately take into account the differences between men and women as they were created. It uses those differences as an advantage to build the life of the Christian community.<a id="_idTextAnchor381"></a></p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e scriptural teaching deals with the social structure of a people—the early Christian community. <span class="No-Ligatures">Th</span>is can help us to understand it in a new light. It does not derive from some prejudice against women or a biased view about women’s weakness or lesser competence. Rather, behind the teaching is an instinct for how daily life should be patterned. Women were needed as women. For the communal life of the Christian people to flourish, the women’s role was essential and had to be filled competently. Later chapters of this book will take up the question of whether the social structure taught by scripture can provide helpful guidelines for the social structure of contemporary Christians who live in a technological society. However, it can profitably be pointed out now that much of what Christians need to have successful community was performed by men and women in the early church instinctively because they knew how to care for social life according to their roles.</p>

<a id="_idTextAnchor382"></a><a id="_idIndexMarker529"></a><a id="_idParaDest-39"></a>

## Authority of the Teaching {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> above four points (<span class="OT-All-Small-Caps">A</span> through <span class="OT-All-Small-Caps">D</span>) summarize the teaching of the New Testament on the roles of men and women. A question still remains: Which elements of New Testament teaching are taught in a directive way? First, the principles of order are clearly enjoined. Women are urged to subordinate themselves to their husbands in the passages in Ephesians&#160;5, Colossians&#160;3, <span class="Lining-Nums">1&#160;</span>Peter&#160;3, (and Titus&#160;2). <span class="Lining-Nums">1&#160;</span>Timothy&#160;2 requires that those who govern the whole people be men. <span class="No-Ligatures">Th</span>e explicit directive in <span class="Lining-Nums">1&#160;</span>Timothy&#160;2 is strengthened by the instructions for the choosing of elders in <span class="Lining-Nums">1&#160;</span>Timothy&#160;3 and Titus&#160;1 and the choosing of apostles in Acts&#160;1, all of which envision only choosing men. Secondly, Paul strongly enjoins some of the expressions of the role differences between men and women—namely, the wearing and not wearing of headcoverings and the rule about speaking in instructional situations in the assemblies of the community. However, the “occasional” character of these passages suggests that Paul was concerned about two expressions of role difference among many, two that happened to be at issue. <span class="No-Ligatures">Th</span>e implication is that Paul would have been equally concerned about other violations of what he considered the proper order. In other words, the passages in <span class="Lining-Nums">1&#160;</span>Corinthians enjoin proper expression of the order for men and women in a broader way than the two items under consideration. To summarize, the New Testament provides us with (1)&#160;strong directives about order in men’s and women’s relationships; and (2)&#160;directives about expressions of that order which are considered important to maintain it.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e New Testament does not enjoin the broader pattern of roles (point&#160;<span class="OT-All-Small-Caps">D</span>) which underlies the teachings on order with the same directiveness. <span class="No-Ligatures">Th</span>e pastoral epistles give instructions for the order of the Christian community which incarnate some of the broader pattern of roles. It would be too strong to say that the pastoral epistles insist on these patterns, but it probably would not be too strong to say that they expect these patterns will be followed. <span class="No-Ligatures">Th</span>ere is, however, another important reason for taking the broader pattern of rules seriously. <span class="No-Ligatures">Th</span>e directives on order and on the expression of this order are not given legalistically, as if bare compliance with the letter of the law is all that the New Testament envisioned. <span class="No-Ligatures">Th</span>ese directives make sense only within a broader understanding of role differences for men and women that the directives were regulating. If the only difference between men’s and women’s roles in the Christian community were that the heads of the family and the governors of the community were men, keeping the rules would tend to be legalistic. A broader role difference is necessary for the directives on order to work maximally well. <span class="No-Ligatures">Th</span>e New Testament does not insist that Christians for all time follow Israelite or early Christian social patterns in all their detail. But the New Testament does expect Christians to structure their relationships as men and women in a pattern similar to that of the early Christians.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker530"></a>Finally, it would probably not be accurate to say that the New Testament enjoins oneness between men and women in Christ. Rather, that oneness is given as the goal and the background. It is the fact upon which everything else rests. Christ was sent to be the source of a new humanity, and men and women alike are in Christ. <span class="No-Ligatures">Th</span>ere are consequences which follow from this fact. Both men and women worship together in spirit and in truth as responsible members of the body of Christ and both receive the same care and service. No distinctions may be made in spiritual status or in love between men and women. Also, in order to be one person, there should be an order of subordination which creates a strong unity, and this order builds upon role differences between men and women. Both sameness of status and love and differences in role follow from the same fact; they are two ways of achieving the oneness intended by God. <span class="No-Ligatures">Th</span>us, practical consequences follow from the fact, but the fact itself is more of a truth upon which a way of life rests than something which can properly be said to be enjoined. Of course, oneness between men and women in Christ is taught with full authority and is by no means less in importance than explicit injunctions.</p>

<a id="_idTextAnchor383"></a><a id="_idIndexMarker531"></a><a id="_idParaDest-40"></a>

## <span class="No-Ligatures">Th</span>e Intent of the Teaching {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">It </span>is clear that scripture teaches the basic pattern of men’s and women’s roles authoritatively. However, the intent or motive of the teaching must also be examined. An understanding of intent will allow us to better apply the teaching. For instance, if the scriptural teaching on the roles of men and women was intended to protect the early church against proto-Gnostic currents, or to deal with a handful of difficult women in Corinth and Ephesus, it could easily be decided that this teaching is not intended for us. In such a case, it could be agreed that the teaching was given authoritatively, but one might not feel called upon to respond to it any more than if we heard our father tell our little brother that he was not to cross the street. <span class="No-Ligatures">Th</span>e intent of the teaching will be examined simply by an analysis of what the key texts are saying. <span class="No-Ligatures">Th</span>e next chapter will concern itself with a discussion of the historical influences on the passages.</p>
<p class="BODY-STYLES_Body"><a id="_idTextAnchor384"></a>One approach to this question is that the key texts on men’s and women’s roles were all written to deal with a particular situation peculiar to the early church. <span class="No-Ligatures">Th</span>e passages are often interpreted in terms of a specific difficulty in some of the first-century churches. For instance, it is sometimes said that the rules about speech, headcovering, and teaching were aimed at women who were talking too much and making a disturbance, or were designed to avoid scandal and ridicule from Greeks, or to avoid having women appear like prostitutes, or to avoid having them relapse into paganism. All these reasons have been discussed in the foregoing interpretations of the passages. Sometimes this position is stated in broader terms: <span class="No-Ligatures">Th</span>e rules were laid down either because women were not educated enough or because the writer wanted to ensure that Christian women fit in with the customs of the surrounding peoples.</p>
<p class="BODY-STYLES_Body-SA"><span class="No-Ligatures">Th</span>e following is a list of these reasons, drawn from writers who think the New Testament teaching was aimed at particular problems or cultural circumstances in the early church. <span class="No-Ligatures">Th</span>ey say that the key texts were intended:</p>
<ol>
<li class="BODY-STYLES_L-O-Num-L1-1st"><!--<span class="Body-List-Counter-Float">1.</span>-->to avoid scandal and ridicule from the Greeks (<span class="Lining-Nums">1&#160;</span>Cor&#160;11)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">2.</span>-->to ensure that Christian women fit in with the customs of the surrounding peoples (<span class="Lining-Nums">1&#160;</span>Cor 11,&#160;14)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">3.</span>-->to keep Christian women from looking like prostitutes (<span class="Lining-Nums">1&#160;</span>Cor&#160;11)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">4.</span>-->to prevent women from relapsing into paganism (<span class="Lining-Nums">1&#160;</span>Cor 11,&#160;14; <span class="Lining-Nums">1&#160;</span>Tm&#160;2)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">5.</span>-->to enhance evangelism by doing things in a way more acceptable to Greeks or Jews (<span class="Lining-Nums">1&#160;</span>Cor 11,&#160;14)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">6.</span>-->to avoid scandal to the Jews (<span class="Lining-Nums">1&#160;</span>Cor&#160;14, perhaps <span class="Lining-Nums">1&#160;</span>Tm&#160;2)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">7.</span>-->to handle a situation in which women were talking too much, and causing a disturbance (<span class="Lining-Nums">1&#160;</span>Cor&#160;14)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">8.</span>-->to correct a situation in which the women seated on one side of the assembly were calling out questions to their husbands on the other (<span class="Lining-Nums">1&#160;</span>Cor&#160;14)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">9.</span>-->to restrict women in their speech in open meetings where their freedom might offend newcomers (<span class="Lining-Nums">1&#160;</span>Cor&#160;14)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">10.</span>-->to keep women from speaking or teaching because they are not sufficiently educated (<span class="Lining-Nums">1&#160;</span>Cor&#160;14, <span class="Lining-Nums">1&#160;</span>Tm&#160;2)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">11.</span>-->to produce conformity to the social order of the time (Col&#160;3)</li>
<li class="BODY-STYLES_L-O-Num-L1-SA"><!--<span class="Body-List-Counter-Float">12.</span>-->to enable Christian women to win their non-Christian husbands (<span class="Lining-Nums">1&#160;</span>Pt&#160;3)<span class="Footnote-Ref"><span id="footnote-096-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-096">\*</a></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>is list falls into two broad categories of explanation: (a)&#160;explanations that see the teaching as aimed at situations in the churches (#1,&#160;#2, #3, #4, #5, #6, #7, #8, #9, #10,&#160;#12); and (b)&#160;explanations that see the teaching as designed to deal with the cultural situation of the ancient world in respect to women (#10,&#160;#11). All these views would point to something special about the situation of the New Testament church that might motivate different passages and hence make them inapplicable to modern Christians. Relatedly, all of them tend to avoid the explanation that the passages are directed to men simply because they are men and women simply because they are women.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e most important observation about this list of twelve reasons is that none of them are actually stated in the texts as the reasons for the teaching.<span class="Footnote-Ref"><span id="footnote-095-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-095">\*</a></span></span> <span class="No-Ligatures">Th</span>ey are all suggestions given by various authors, hypotheses about the intention of the scriptural writer which are different than the actual reasons for the teaching given in the texts themselves. Most of these reasons are not even suggested by the texts themselves. Only #1, #11, and #12 are suggested by materials in the texts and, as has already been seen, these opinions develop the suggestions in the texts into theories that have no foundation in what the texts actually say. In fact, the key texts themselves state a rather different set of reasons and manifest a different set of concerns than those proposed by advocates of the “special situation of the early church” views.</p>
<p class="BODY-STYLES_Body-SA">It is interesting to compare the reasons given by the authors of the various key texts for their teaching. <span class="No-Ligatures">Th</span>e following is a list drawn from the discussions in Chapters Four, Seven, and Eight of the main grounding given for all the instructions: the instructions on the sameness of status, the instructions on subordination of woman to man, and the instructions on the various practices expressing order among men and women:</p>
<ol>
<li class="BODY-STYLES_L-O-Num-L1-1st"><!--<span class="Body-List-Counter-Float">1.</span>--><span class="No-Ligatures">Th</span>e fear of Christ (<a id="_idIndexMarker532"></a>Eph&#160;5:21)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">2.</span>--><span class="No-Ligatures">Th</span>e example of Christ and the church (<a id="_idIndexMarker533"></a>Eph&#160;5:22<span class="No-Break">–3</span>0)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">3.</span>--><span class="No-Ligatures">Th</span>e truth of the relationship (man and wife being one person) (<a id="_idIndexMarker534"></a>Eph&#160;5:28<span class="No-Break">–3</span>0)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">4.</span>--><span class="No-Ligatures">Th</span>e one flesh of Adam and Eve in their marriage (<a id="_idIndexMarker535"></a>Eph&#160;5:31)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">5.</span>-->What is fitting in the Lord (<a id="_idIndexMarker536"></a>Col&#160;1:18)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">6.</span>-->To win the unbelieving husband (<a id="_idIndexMarker537"></a><span class="Lining-Nums">1&#160;</span>Pt&#160;3:1<span class="No-Break">–2</span>)<span class="Footnote-Ref"><span id="footnote-094-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-094">†</a></span></span></li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">7.</span>--><span class="No-Ligatures">Th</span>e value God places on a quiet and gentle spirit in women (<a id="_idIndexMarker538"></a><span class="Lining-Nums">1&#160;</span>Pt&#160;3:4)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">8.</span>--><span class="No-Ligatures">Th</span>e example of the holy women of old (<a id="_idIndexMarker539"></a><span class="Lining-Nums">1&#160;</span>Pt&#160;3:7)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">9.</span>--><span class="No-Ligatures">Th</span>e weakness of woman (<span class="Lining-Nums">1&#160;</span>Pt&#160;3:7)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">10.</span>-->Women and men as joint-heirs of the grace of life (<span class="Lining-Nums">1&#160;</span>Pt&#160;3:7)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">11.</span>-->In order that your prayers not be hindered (<span class="Lining-Nums">1&#160;</span>Pt 3:7)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">12.</span>-->Maintaining the traditions (<a id="_idIndexMarker540"></a><span class="Lining-Nums">1&#160;</span>Cor&#160;11:2)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">13.</span>--><span class="No-Ligatures">Th</span>e order of headship (God–Christ–the man–the woman) (<a id="_idIndexMarker541"></a><span class="Lining-Nums">1&#160;</span>Cor&#160;11:3)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">14.</span>--><span class="No-Ligatures">Th</span>e example of Christ as head and subordinate (<span class="Lining-Nums">1&#160;</span>Cor&#160;11:3)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">15.</span>-->Man as the image and glory of God, woman as the glory of man; woman made from and for man (<a id="_idIndexMarker542"></a><span class="Lining-Nums">1&#160;</span>Cor 11:7<span class="No-Break">–9</span>)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">16.</span>--><span class="No-Ligatures">Th</span>e presence of the angels (<a id="_idIndexMarker543"></a><span class="Lining-Nums">1&#160;</span>Cor&#160;11:10)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">17.</span>-->Man dependent upon woman, born from woman (<a id="_idIndexMarker544"></a><span class="Lining-Nums">1&#160;</span>Cor 11:11<span class="No-Break">–1</span>2)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">18.</span>--><span class="No-Ligatures">Th</span>e comparison with hair (<a id="_idIndexMarker545"></a><span class="Lining-Nums">1&#160;</span>Cor 11:5<span class="No-Break">–6</span>, 14<span class="No-Break">–1</span>5)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">19.</span>--><span class="No-Ligatures">Th</span>e universal practice of the churches (<a id="_idIndexMarker546"></a><span class="Lining-Nums">1&#160;</span>Cor 14:33b,&#160;36) and of the churches and the apostle (<span class="Lining-Nums">1&#160;</span>Cor 11:2,&#160;16)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">20.</span>-->Even the law’s example (<a id="_idIndexMarker547"></a><span class="Lining-Nums">1&#160;</span>Cor 14:37)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">21.</span>--><span class="No-Ligatures">Th</span>e command of the Lord (<span class="Lining-Nums">1&#160;</span>Cor 14:37)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">22.</span>--><span class="No-Ligatures">Th</span>e authority of the apostle (<a id="_idIndexMarker548"></a><span class="Lining-Nums">1&#160;</span>Cor 14:38; <a id="_idIndexMarker549"></a><span class="Lining-Nums">1&#160;</span>Tm&#160;2:12)</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">23.</span>-->Adam was formed first (<a id="_idIndexMarker550"></a><span class="Lining-Nums">1&#160;</span>Tm 2:13)</li>
<li class="BODY-STYLES_L-O-Num-L1-SA"><!--<span class="Body-List-Counter-Float">24.</span>-->Eve was deceived (<a id="_idIndexMarker551"></a><span class="Lining-Nums">1&#160;</span>Tm 2:14)</li>
</ol>
<p class="BODY-STYLES_Body-NI">Of these reasons, the comparison with hair (#18) is not properly speaking a grounding, since it is a comparison to strengthen a point, not an argument. It is incidentally the only item in the list which may be an appeal to something cultural. <span class="No-Ligatures">Th</span>e rest fall into five main categories: (a)&#160;an appeal to authority, either that of Christ, the apostle, or the universal practice of the churches (#1,&#160;#5, #7, #12, #16, #19, #20, #21,&#160;#22); (b)&#160;the example of a model person (#2, #8, #14); (c)&#160;practical reasons leading to Christian goals, obtaining conversion to Christ and freer worship of God (#6, #11); (d)&#160;a weakness in woman (#9, #24); (e)&#160;revealed realities showing God’s purposes and intentions (#2,&#160;#3, #4, #10, #13, #14, #15, #16, #17, #23,&#160;#24).</p>
<p class="BODY-STYLES_Body">In short, the view that the New Testament teaching on men and women derives from “the special situation of the early church” is a hypothesis unsupported by the key texts we have considered. Moreover, these texts are the only direct source of evidence for the intentions of the New Testament writers. If one prefers other reasons than those given in the key texts, one chooses conjecture and speculation based on what might seem plausible instead of the direct evidence in our possession.<a id="_idTextAnchor385"></a></p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ere is a further view of the motivation for the teaching in the key texts that has to be considered. Some hold that the teaching in the key texts rests largely upon the scripture writers’ view of the weakness, incapability, or inferiority of women. Two of the key texts do contain a reference to women’s weakness: <span class="Lining-Nums">1&#160;</span>Peter 3:7 and <span class="Lining-Nums">1&#160;</span>Timothy 2:14. <span class="No-Ligatures">Th</span>e interpretation of these two passages is somewhat problematic, as the discussions of each one have indicated, but three observations can be made with confidence. First, the passage in <span class="Lining-Nums">1&#160;</span>Peter 3:7 does refer to the woman’s weakness, but this reference is a basis for the injunction that the husband should honor the woman. It is not given as a reason for the woman to be subordinate to the man. Secondly, the New Testament does seem to attribute various strengths and weaknesses to both men and women, but it by no means attributes all weakness to women. Men as well as women are prone to characteristic defects. All that can be said here is that the New Testament seems to understand that men’s particular combination of strengths and weaknesses better equip them for a governing position. (<span class="Lining-Nums">1&#160;</span>Timothy&#160;2 is the only possible explicit reference here, depending on how it is understood.) <span class="No-Ligatures">Th</span>irdly, the primary reason that the key texts give for role differences is not weakness in women, but God’s purpose for men and women. If the relative strengths and weaknesses of men and women are a factor, it is strictly a secondary consideration.</p>

<a id="_idTextAnchor386"></a><a id="_idParaDest-41"></a>

## Concluding Observations {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> key texts, then, take a different stand on the intent or motive of the New Testament teaching on the roles of men and women than the various hypotheses considered above. <span class="No-Ligatures">Th</span>e reasons the texts give for the teaching are primarily (1)&#160;an appeal to something considered authoritative for the life of Christians, and (2)&#160;an appeal to revealed realities showing God’s purpose and intentions. <span class="Lining-Nums">1&#160;</span>Peter&#160;3 is something of an exception to this observation, since the reasoning is primarily homiletic, either appealing to practical Christian advantages derived from following the instructions, or to the model of the holy women of old, or to the pleasure God takes in the submission of women.<span class="Footnote-Ref"><span id="footnote-093-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-093">\*</a></span></span> Taken as a whole, however, the texts put most of the weight on the appeal to authority and on the appeal to God’s purpose for men and women.</p>
<p class="BODY-STYLES_Body">Of the two primary reasons, the more fundamental is the teaching on God’s purposes for men and women. It takes up the bulk of the material that grounds the practical instructions in Ephesians&#160;5, <span class="Lining-Nums">1&#160;</span>Corinthians&#160;11, and <span class="Lining-Nums">1&#160;</span>Timothy&#160;2. In addition it lies behind <a id="_idIndexMarker553"></a>Galatians 3:28. <span class="No-Ligatures">Th</span>e key texts, therefore, indicate that the teaching on men and women in the New Testament is given because they are men and women (and not because of some special situation of the early church) and because God created them differently because he had different purposes for them. <span class="No-Ligatures">Th</span>e second main reason—the appeal to authority—is likewise an important reason, although it is not as fundamental as the teaching on God’s purpose. <span class="No-Ligatures">Th</span>e appeal to authority is often a deliberate appeal to an approach taken by the highest teaching authorities of the newly formed Christian people. <span class="No-Ligatures">Th</span>e consistency and strength of this appeal to authority indicates that the subject was important to the early Christians. <span class="No-Ligatures">Th</span>e teaching on the roles of men and women, then, was not a casual matter, but a consciously adopted stand.</p>
<p class="BODY-STYLES_Body">We are, therefore, faced with texts which present teaching on men and women grounded in an understanding of God’s purpose for the human race and supported by authority. <span class="No-Ligatures">Th</span>e argumentation in these key texts—at least that in Ephesians&#160;5, <span class="Lining-Nums">1&#160;</span>Corinthians&#160;11, and <span class="Lining-Nums">1&#160;</span>Timothy&#160;2—would have to be considered theological and a matter of revelation. Moreover, it is based upon an understanding of some of the most fundamental truths in Christianity, for it concerns the purposes of creation as shown in the original acts of creation, the relationship of God and Christ, the relationship of Christ and the church, the fundamental meaning of the marriage relationship, the consequences of the coming of Christ, and the restoration of mankind to God’s original purposes. In addition, the scripture teaches role differences between men and women as an integral part of a wider approach to the life of the Christian people, an approach that will allow the Christian people to be the new humanity that God is recreating in Christ. Any interpretation of the New Testament teaching concerning the roles of men and women which does not recognize this fact is missing one of the most obvious features of the key texts and is missing the bulk of the evidence the texts themselves provide about their intent and motive.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e New Testament teaching about the roles of men and women is integral to its teaching about Christian personal relationships. It is not the most important of the teachings. <span class="No-Ligatures">Th</span>e teaching about Christian character and Christian love is much more important. However, the teaching about men’s and women’s roles is no addendum to basic Christian teaching that sticks out like an ill-constructed addition to a house. Rather, it is an integrated part of an important teaching about the unity of the body of Christ and the good order that makes that unity possible. It is also grounded in some of the most important doctrines in the New Testament—the doctrines about the creation of the new humanity in Christ, the new Adam. In short, it is a teaching that the New Testament does not give grounds for passing over easily.</p>

<div class="_idFootnotes">
<div id="footnote-096" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-096-backlink">219*</a>Some scholars propose that <span class="Lining-Nums">1&#160;</span>Corinthians 11 and&#160;14 were intended to counter specific problems in Corinth which had arisen as a result of some misapplication of Paul’s eschatological teaching. It is suggested that some people in the Corinthian church were attempting to live fully in the <span class="Italic-Caption">eschaton</span>, and were trying to realize in this life the lack of difference between men and women that would exist in the resurrection. <span class="No-Ligatures">Th</span>is opinion is not listed because it does not interpret the passages as dealing with a specific circumstance in the life of some early churches or in the ancient world. Like the other opinions, however, it does not rest on anything stated in the text. It would, however, support the opinions given here.</p>
</div>
<div id="footnote-095" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-095-backlink">220*</a>See the following footnote for the possible exception.</p>
</div>
<div id="footnote-094" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-094-backlink">220†</a>Both #6 on this list and #12 on the previous one cite the same reason for subordination in the same text. However, the context of the lists makes them different. In the first list this reason is cited as supporting subordination of Christian women to their husbands <span class="Italic-Caption">only</span> if their husbands are non-Christian. However, as was discussed in considering <span class="Lining-Nums">1&#160;</span>Peter&#160;3 such a view is unwarranted. In the latter list, incorporating the correct interpretation, the reason is only supportive of a wife’s subordination to her husband in a particular circumstance. It is not the sole basis for the subordination of Christian women to men.</p>
</div>
<div id="footnote-093" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-093-backlink">222*</a>Comparing the one key text traditionally attributed to Peter with those traditionally attributed to Paul reveals an interesting point. <span class="No-Ligatures">Th</span>e passages in the Pauline epistles primarily appeal to the teaching about Genesis and with some frequency make an appeal to the authority of the writer (apostle) and all the churches. <span class="No-Ligatures">Th</span>e passage in <span class="Lining-Nums">1&#160;</span>Peter, while holding the same position as passages in the Pauline epistles, uses a completely different reasoning. <span class="No-Ligatures">Th</span>e reasoning is less central to an argument and more homiletic (perhaps because no argument was needed for the audience of <span class="Lining-Nums">1&#160;</span>Peter). <span class="No-Ligatures">Th</span>e primary appeal, moreover, is to the example of Abraham and Sarah. <span class="No-Ligatures">Th</span>is would at least point to a close dependence of <span class="Lining-Nums">1&#160;</span>Timothy on Paul’s teaching. “<span class="No-Ligatures">Th</span>e woman was deceived” may not find an exact parallel in other Pauline writings, but the overall approach of <a id="_idIndexMarker552"></a><span class="Lining-Nums">1&#160;</span>Timothy 2:8<span class="No-Break">–1</span>5 does.</p>
</div>
</div>
