# Note on Method&#160;&#160;▷&#160; Exegesis {-}

<a id="_idParaDest-42"></a><a id="_idTextAnchor387"></a>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">Note to the Reader</h2>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>is section contains some comments on how the exegesis in this book relates to some of the main currents of exegesis of the scriptural writing about the roles of men and women. <span class="No-Ligatures">Th</span>is section is not essential to the argument of the book and can be skipped without missing any information or discussion that is needed for the later chapters or the main conclusions. <span class="No-Ligatures">Th</span>e section is included to provide some help in understanding how this book compares to the body of literature we now have on the roles of men and women in scripture. It is designed for those readers who have some acquaintance with that body of literature.</p>

<a id="_idTextAnchor388"></a><a id="_idParaDest-43"></a>

## <span class="No-Ligatures">Th</span>e Exegetical Approach {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">When </span>someone explains what one or more scripture passages are saying, that person is giving an exegesis of scripture. Exegesis includes not only a linguistic and literary explanation of the meaning of the words, but it also involves a judgment as to what those words are referring to and what they are meant to accomplish.<span class="Footnote-Ref"><span id="footnote-098-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-098">*</a></span></span> Normally, however, <a id="_idIndexMarker554"></a>exegesis is understood to mean the process of stating what the scripture says, and not the process of discussing how the scriptural statements are to be responded to or applied. <span class="No-Ligatures">Th</span>ere are views of exegesis which would extend the meaning of the word to include the application of scripture passages, but here the narrower definition is used. In other words, exegesis is one thing; application and response are something else.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e first part of this book has been concerned with the teaching of the scripture on the roles of men and women. It has not attempted to discuss how that teaching would be responded to or applied. <span class="No-Ligatures">Th</span>is discussion has been reserved for the last two parts of this book. A statement of teaching is not identical with a statement of exegesis. A study of New Testament teaching focuses on the authoritative statements in the New Testament that assert either what is to be believed or what is to be done, and attempts to synthesize them. An exegetical study simply describes what the New Testament says. Exegesis is foundational for a study of teaching. It is impossible to synthesize the directions the New Testament gives for an area of life without understanding what each of the relevant passages says. <span class="No-Ligatures">Th</span>is excursus is not concerned so much with the statement of the New Testament teaching as with the exegetical approach which provides the foundation for it. <span class="No-Ligatures">Th</span>e following comments are designed to clarify the orientation of the exegesis that went into the first part of this book.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e broad lines of the exegesis given in Chapters One to Nine of this book are relatively uncontroversial and rest on a solid support in exegetical works. <span class="No-Ligatures">Th</span>e basic statement of the social structures of the early Christian community in terms of the roles of men and women (the husbands being the overall heads of the Christian family and those who exercised ultimate responsibility and authority in Christian community being chosen from among the men) is strongly supported. Also strongly supported are the basic outlines of the sketch given here of the sameness of status between men and women in Christ and the description of the theological grounding for that position. <span class="No-Ligatures">Th</span>is is not to say that most of the particular points touched upon in the course of describing the New Testament approach are uncontroversial. <span class="No-Ligatures">Th</span>roughout Chapters One to Nine, an attempt was made to indicate the points of controversy and to give reasons for the approach taken to the point in question. Where this book takes controversial positions, it is almost never innovative; rather, the positions held here correspond to positions held by competent scripture scholars. However, the main outlines of the approach of the first part of this book never rest on strongly disputed exegetical positions. <span class="No-Ligatures">Th</span>e exegetical approach taken in the first nine chapters is, in substance, uncontroversial.<span class="Footnote-Ref"><span id="footnote-097-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-097">*</a></span></span> <span class="No-Ligatures">Th</span>ere is a stream of exegesis that could be called “liberationist exegesis” which would attempt to dispute what has been presented here, and that category of writings will be considered shortly.</p>
<p class="BODY-STYLES_Body">It would even be accurate to describe the kind of exegesis that has been done in the first part of this book as restressing the obvious or highlighting the more likely approaches in the exegesis of scripture in the area of the roles of men and women. An example of restressing the obvious is the development of the importance of the appeal to the example of Adam and Eve in the scriptural grounding of the roles of men and women. <span class="No-Ligatures">Th</span>e material in Chapter Six which states that Galatians 3:28 is an affirmation of the abolition of the spiritual differences taught by “the law” and not an affirmation of the abolition of social role differences between men and women would be an example of stressing the clearly more solid opinion. <span class="No-Ligatures">Th</span>at these positions might be considered uncommon in the flood of recent literature on the biblical approach to the roles of men and women is more of a comment on what is going on in current writing on the subject than it is on the positions taken by this book.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e exegesis in this book has some distinctive features. <span class="No-Ligatures">Th</span>ey do not lie so much in the positions taken on current points of controversy as they do in the attention given to an aspect of the exegetical process that could be called “restatement of what the text(s) say.”<a id="_idTextAnchor389"></a><span class="Endnote-Ref">[1](#_idTextAnchor1429)</span> Much attention in exegesis is given to the linguistic and literary study of the text. Much attention is also given to the study of the situation from which the text comes. <span class="No-Ligatures">Th</span>is includes a study of the events, trends, and history of ideas and institutions of the environment; a comparative analysis of the content of the passage with comparable texts in other religions and philosophies; and, when possible, a study of the author’s thought and development.<a id="_idTextAnchor390"></a><span class="Endnote-Ref">[2](#_idTextAnchor1430)</span> <span class="No-Ligatures">Th</span>e same amount of attention, however, is many times not given to the problems of restating the text accurately for someone in the twentieth century (even by those most concerned about “the hermeneutical question”).<a id="_idTextAnchor391"></a><span class="Endnote-Ref">[3](#_idTextAnchor1431)</span> To describe what a text from one culture and situation says to people in a different culture and situation involves a judgment about what is an equivalent.</p>
<p class="BODY-STYLES_Body">For instance, it is one thing to say that the scripture states that the wife should be subordinate to her husband. It is quite another thing to describe what that subordination consists of in such a way that a woman in twentieth-century America would know whether she was doing what the writer of the scripture had in mind. It is also another thing to know whether the subordination taught in scripture is the kind of relationship between husband and wife that official Chinese Communist ideology would oppose, or whether that subordination would be counted as discrimination according to some legal definitions of the equality of men and women. Yet much writing about men and women goes from exegesis of the text to a discussion of the application or relationship of the text without carefully considering the problems of relating the two different cultural situations. Nor does this problem appear solely in discussions of application. <span class="No-Ligatures">Th</span>e process of restatement goes on in the very actions of linguistic and literary study and in study of the situation of the text, because every statement of the meaning of the text that is not simply repeating the text includes some judgment of how that text should be translated into a different language and framework. Often such an exegesis is undertaken without adequately considering the problems involved in restatement.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker555"></a><span class="No-Ligatures">Th</span>ere are three aspects of the process of restatement that often cause difficulty in the exegesis of passages connected with the roles of men and women: (1)&#160;understanding the reality being referred to; (2)&#160;understanding what activities and relationships have similar functions in different cultural systems; and (3)&#160;translating accurately into a different conceptual system.</p>
<p class="BODY-STYLES_Body">First, New Testament discussion of and references to the roles of men and women or anything connected with or manifesting those roles can only be understood well by grasping the kind of reality being referred to there. <span class="No-Ligatures">Th</span>e roles of men and women in scripture are a question of social structures. <span class="No-Ligatures">Th</span>e exegesis given in this book has been based upon the view that the first step in intelligently speaking about New Testament passages on men and women is to understand the concerns of those passages in terms of the proper category—namely, social roles and social structure. It may be stimulating and aesthetically interesting to discuss the images of women in scriptural writing. It may be challenging to attempt to state the scriptural view of the “nature” of man and of woman. But the meaning of the New Testament texts cannot be restated accurately nor discussed with fairness unless it is first recognized that one is dealing with how a whole society or culture patterns itself in terms of sexual differences, and that such patterning has social purpose and utility.</p>
<p class="BODY-STYLES_Body">Much current writing on the roles of men and women misses the significance of social roles and of men-women differences as they relate to social roles. <span class="No-Ligatures">Th</span>e resulting restatements of the New Testament, as well as the evaluation and understanding of the New Testament, can be seriously distorted. For instance, exegeses of <a id="_idIndexMarker556"></a><span class="Lining-Nums">1&#160;</span>Corinthians 14:34<span class="No-Break">–3</span>5 are given which do not even take into account that the passage might be holding its position simply on the basis of the fact that it is women who are speaking and such speaking is incompatible with their role. Many authors do not seem to be able to understand why someone would want to make a ruling on that basis. To give a similar example, many speak very freely about the prejudice of the New Testament writers or of Jews or others against women without being able to distinguish between a personal prejudice and an instinctive understanding that comes from an approach to social roles. Or again, some use as a conceptual framework the categories of “advance” and “restriction” in their analysis of scriptural writing concerning men and women. <span class="No-Ligatures">Th</span>e result is that the area comes out as a simple conflict between greater or less favorableness to women. Such a view lacks an appreciation for the fact that a social role has a purpose, and ancient societies gave roles to men and women and made laws about these roles because they had a certain social structure within which those in the society were trying to live their lives.<a id="_idTextAnchor392"></a><span class="Endnote-Ref">[4](#_idTextAnchor1432)</span></p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ese remarks should not be taken to indicate that it is unfair to evaluate the way another society or culture approaches the roles of men and women. Rather, evaluation (and any process that involves restatement) should only be done with the understanding that the roles of men and women are part of a social structure, and that evaluation should be done by comparing two (or more) social structures and not simply isolated statements in texts.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker557"></a>Relatedly, it is impossible to restate accurately something in the New Testament and to speak about it intelligently without understanding its equivalent (if any) in a different social system. One has to be able to understand when two things function alike. For instance, many carry out discussions of <span class="Lining-Nums">1&#160;</span>Timothy 2:12 without adverting to the transformation in “teaching” over the last few hundred years. <span class="No-Ligatures">Th</span>e result is often an inability to understand the concerns of <span class="Lining-Nums">1&#160;</span>Timothy 2:12 and, normally, an inability to make a good judgment as to how the passage might be applied (if at all) to the contemporary situation. Something similar is true in relation to governing positions. Many discuss the prohibitions in the New Testament and early Christian tradition of women being elders without discussing how much governing positions have changed in social function. <span class="No-Ligatures">Th</span>e result is very often a lack of comprehension of either what is being said in the New Testament about governing positions or the reasons for it.</p>
<p class="BODY-STYLES_Body">Finally, restatement has to include careful attention to the conceptual framework used for understanding a restatement. Exegesis is often done without clarifying the terms, especially the social structural terms. For example, “equality” has a very different meaning in modern usage than in scripture. Today it has a weight of ideological meaning. Yet passages in scripture are labeled as teaching “equality” or as not teaching “equality” without so much as a pause for conceptual analysis. Whole books rest on the assumption that equality and personal subordination are incompatible, and that those passages in scripture which teach equality therefore contradict those which teach personal subordination. If the assumption were even argued for, the situation would be better, but often it is simply presumed. Most of what is in such books is so confused or arbitrary in its basic conceptual framework and the application of that framework to a different cultural situation that most of the exegesis put forth turns out to be of limited value.</p>
<p class="BODY-STYLES_Body">If this book has a distinctive approach to exegesis, that distinctiveness lies not so much in the uniqueness of its positions on various controversial points, but on the amount of attention paid to categorizing the New Testament concerns about men and women accurately and comparing the New Testament approach to social roles and structures with contemporary Western approaches. <span class="No-Ligatures">Th</span>e exegetical approach of this book also rests on the conviction that the differences in scriptural interpretation are rarely a matter of simple disagreement over the facts of what is in the New Testament, but rather are to be found in the antecedent understandings with which interpreters approach the facts.</p>

<a id="_idTextAnchor393"></a><a id="_idIndexMarker558"></a><a id="_idIndexMarker559"></a><a id="_idIndexMarker560"></a><a id="_idIndexMarker561"></a><a id="_idParaDest-44"></a>

## Christian Liberationist Exegesis {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>ere</span> is an obvious exception to the earlier statement in this excursus that the exegesis in this book is, in the main, uncontroversial. In comparison to one body of writing, it is very controversial. <span class="No-Ligatures">Th</span>at body of literature might be called “Christian Liberationist.” Christian Liberationist literature is the literature of those who could be described as part of the women’s liberation movement who profess to find their views in the scripture itself. Earlier, the term “Evangelical Feminist” might have been used to describe this literature, but many of the exegetical approaches of “Evangelical Feminism” have now been taken over by others who are not Evangelicals. Since the concerns and mentality of most of those who write from this perspective are from the women’s liberation sector of the feminist movement, the term “Christian Liberationist” is used here for lack of a better term. <span class="No-Ligatures">Th</span>is term will be used simply to characterize a configuration of exegetical approaches.<a id="_idTextAnchor394"></a><span class="Endnote-Ref">[5](#_idTextAnchor1433)</span></p>
<p class="BODY-STYLES_Body-SA"><a id="_idTextAnchor395"></a>In the last twenty years, especially within the last ten years, the discussion of the roles of men and women has been enormously polemicized, especially in the United States. <span class="No-Ligatures">Th</span>e rise of women’s liberation and other forms of radical feminism, and a vigorous effort to persuade society to change its approach to the roles of men and women, have had great impact on Christians of all denominations. As Christians began to be affected by these movements, they had to come to grips with scripture and other Christian writings that seemed to present obstacles to the adoption by Christians of many forms of feminist ideologies. Over the past twenty years, three strategies toward scripture and other Christian writings have been developed by some Christian feminists in order to remove those obstacles:</p>
<ol>
<li class="BODY-STYLES_L-O-Num-L1-1st"><!--<span class="Body-List-Counter-Float">1.</span>--><span class="Italic">Calling into question either the authority or the applicability of scripture, or both.</span> <span class="No-Ligatures">Th</span>is strategy concedes that scripture teaches a role difference between men and women, but argues that one does not have to take what scripture teaches seriously. Different authors choose different reasons for holding this view, for example, the “rabbinic origin” of such teachings, the “anti-feminism” of Paul, the “time-bound nature” of the scriptures, etc.</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">2.</span>--><span class="Italic">Reinterpreting the normal exegesis of the scripture passages that speak about the roles of men and women.</span> <span class="No-Ligatures">Th</span>is strategy would hold to, or at least profess, a respect for the authority of scripture, but it would protest that scripture has been misunderstood. For instance, Paul did not really mean that wives should be subordinate to their husbands; that is a sexist interpretation of the passage.</li>
<li class="BODY-STYLES_L-O-Num-L1-SA"><!--<span class="Body-List-Counter-Float">3.</span>--><span class="Italic">Finding contradictions in scripture.</span> <span class="No-Ligatures">Th</span>is strategy holds that scripture contains various lines of thought in the area of the roles of men and women, and that these lines of thought are mutually incompatible. We are therefore forced to choose among them. <span class="No-Ligatures">Th</span>e two key points of contradiction most often chosen are found to be between Galatians 3:28 and most of the key texts, and between Jesus and Paul.</li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>ese strategies are by no means mutually incompatible. In fact, they are often combined in the same author. But nonetheless, they are three distinct ways of dealing with the obstacle that the scriptures seem to present.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e first wave of Christians affected by the various currents in the recent upsurge in the feminist movement tended more readily to adopt the first strategy. Writers like Rosemary Ruether, Mary Daly, Josephine Ford, Albertus Magnus McGrath, and others expounded a version of women’s liberation for Christians that rested heavily, though not exclusively, on dismissing the applicability or authority of scripture when it spoke about the roles of men and women. A second wave began with the birth of Evangelical Feminism. Evangelical Feminists came from a Christian tradition that stresses the authority of scripture very highly, and hence they were not ready to call into question the authority of scripture or to speak of it with disrespect. Moreover, they also had a greater familiarity with earlier attempts to deal with the teachings of scripture when “women’s emancipation” was the issue in the nineteenth and early twentieth centuries, and they drew inspiration at times from writers like Katherine Bushnell and Jessie Penn-Lewis. Evangelical Feminists, especially at first, were careful to speak of the scripture with the highest respect, but they have held almost all the positions that other radical feminists have held (including sometimes the approval of homosexual relations and extramarital intercourse, although usually less commonly and more tentatively than other feminists). <span class="No-Ligatures">Th</span>e only strategy, therefore, that the Evangelical Feminists could successfully use was the re-exegesis of many passages. As a result, an approach to exegesis developed that was the first stage of what could be called “Christian Liberationist” exegesis. It is represented in the works of Letha Scanzoni, Nancy Hardesty, Phyllis Trible, Queenie Adams, and others. As Evangelical Feminism continued to develop, however, it became less respectful of scripture, and also influenced more writers who were not Evangelicals. Hence, the “Christian Liberationist” approach broadened and tended more and more to include the strategy of finding contradictions in the scripture. <span class="No-Ligatures">Th</span>us a writer could be the champion of Jesus, or of the “true” Paul, or of the “newness” in the Christian message, while dismissing most of what the canonized New Testament explicitly teaches about the roles of men and women. Later Christian feminists include Virginia Mollenkott, Paul Jewett, Robin Scroggs, Wayne Meeks, and others.</p>
<p class="BODY-STYLES_Body-SA"><span class="No-Ligatures">Th</span>e concern here is simply with the Christian Liberationist approach to exegesis, not with ways of calling into question the authority or applicability of scripture. A type of exegesis has developed in the area of the roles of men and women that is a distinctive exegesis, with a set of characteristic principles and opinions of its own, that can be historically attributed to the influence of the recent feminist movement. Many of the opinions set forth in this exegesis are ingenious and are based on a great deal of intricate scholarship, but they are basically unfounded and call for a restressing of the obvious or an underlining of the more likely opinion. <span class="No-Ligatures">Th</span>e following is a list of some of the opinions that have commonly been advanced in the literature of Christian Liberationist exegesis:</p>
<ul>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><a id="_idIndexMarker562"></a>Genesis&#160;2 does not indicate any subordination of woman to man when it uses the word “helper” to describe woman’s role, because the word “helper” itself does not necessarily imply subordination.<a id="_idTextAnchor396"></a><span class="Endnote-Ref">[6](#_idTextAnchor1434)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->When Adam names his new wife, he is not exercising any authori&#173;tative role (although he probably is when he names the animals).<a id="_idTextAnchor397"></a><span class="Endnote-Ref">[7](#_idTextAnchor1435)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Woman is the climax of creation in Genesis&#160;2.<a id="_idTextAnchor398"></a><span class="Endnote-Ref">[8](#_idTextAnchor1436)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>ere is no subordination of woman to man in Genesis&#160;2 at all.<a id="_idTextAnchor399"></a><span class="Endnote-Ref">[9](#_idTextAnchor1437)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Woman actually handled her part of the Fall in a fairly creditable way.<a id="_idTextAnchor400"></a><span class="Endnote-Ref">[10](#_idTextAnchor1438)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Adam represents the human race, even after the creation of woman, and not man as distinguished from woman.<a id="_idTextAnchor401"></a><span class="Endnote-Ref">[11](#_idTextAnchor1439)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Jesus was revolutionary in regard to Jewish custom in his relationships to women.<a id="_idTextAnchor402"></a><span class="Endnote-Ref">[12](#_idTextAnchor1440)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->In the parable of Martha and Mary in <a id="_idIndexMarker563"></a>Luke 10, Christ is teaching that women do not have to be bound by womanly tasks and roles.<a id="_idTextAnchor403"></a><span class="Endnote-Ref">[13](#_idTextAnchor1441)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Phoebe held a governing position in the Christian community.<a id="_idTextAnchor404"></a><span class="Endnote-Ref">[14](#_idTextAnchor1442)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Junias was a woman apostle.<a id="_idTextAnchor405"></a><span class="Endnote-Ref">[15](#_idTextAnchor1443)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>ere were eldresses in the early church, and <a id="_idIndexMarker564"></a><span class="Lining-Nums">1&#160;</span>Timothy 5:2 refers to them.<a id="_idTextAnchor406"></a><span class="Endnote-Ref">[16](#_idTextAnchor1444)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->Priscilla wrote Hebrews (probably or even possibly).<a id="_idTextAnchor407"></a><span class="Endnote-Ref">[17](#_idTextAnchor1445)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>e “Elect Lady” in <a id="_idIndexMarker565"></a><span class="Lining-Nums">2&#160;</span>John 1:1 was possibly a woman bishop.<a id="_idTextAnchor408"></a><span class="Endnote-Ref">[18](#_idTextAnchor1446)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->“She who is in Babylon” in <a id="_idIndexMarker566"></a><span class="Lining-Nums">1&#160;</span>Peter 5:13 was possibly a woman elder or bishop.<a id="_idTextAnchor409"></a><span class="Endnote-Ref">[19](#_idTextAnchor1447)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>e word “head” does not indicate any governing role or any subordination of the woman in <a id="_idIndexMarker567"></a><span class="Lining-Nums">1&#160;</span>Corinthians 11:3 or in <a id="_idIndexMarker568"></a>Ephesians&#160;5:23.<a id="_idTextAnchor410"></a><span class="Endnote-Ref">[20](#_idTextAnchor1448)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>-->“Subordination” does not involve obedience.<a id="_idTextAnchor411"></a><span class="Endnote-Ref">[21](#_idTextAnchor1449)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>e purpose of <a id="_idIndexMarker569"></a>Ephesians 5:21<span class="No-Break">–3</span>3 is solely to exhort the husband to care for his wife and not to exhort the wife to be subordinate to her husband.<a id="_idTextAnchor412"></a><span class="Endnote-Ref">[22](#_idTextAnchor1450)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>ere is no obedience of wife to husband being referred to in Ephesians 5:21<span class="No-Break">–3</span>3.<a id="_idTextAnchor413"></a><span class="Endnote-Ref">[23](#_idTextAnchor1451)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1"><!--<span class="Body-List-Counter-Float">▸</span>--><span class="No-Ligatures">Th</span>e headcoverings in <span class="Lining-Nums">1&#160;</span>Corinthians 11 are simply a symbol of woman’s authority and not at all of her subordination.<a id="_idTextAnchor414"></a><span class="Endnote-Ref">[24](#_idTextAnchor1452)</span></li>
<li class="BODY-STYLES_L-O-Bull-L1-SA"><!--<span class="Body-List-Counter-Float">▸</span>-->Paul argues poorly in <a id="_idIndexMarker570"></a><span class="Lining-Nums">1&#160;</span>Corinthians 11:2<span class="No-Break">–1</span>6 and knows it.<a id="_idTextAnchor415"></a><span class="Endnote-Ref">[25](#_idTextAnchor1453)</span></li>
</ul>
<p class="BODY-STYLES_Body-NI">More opinions like these could have been listed. Some of these can be traced back earlier than the beginnings of Evangelical Feminism. But, on the whole, these opinions either originated with Christian Liberationist exegesis or received a new prominence with it. <span class="No-Ligatures">Th</span>ere are, of course, other characteristic exegetical opinions in Christian Liberationist writings, but the above list was restricted to those opinions that are clearly unfounded or seemed to have been developed primarily for the sake of holding the new exegetical position.<a id="_idTextAnchor416"></a></p>
<p class="BODY-STYLES_Body-SA">Christian Liberationist exegesis is an extreme case of a basic trend in scriptural interpretation that operates when scripture seems to teach something directly at odds with current opinions or social trends. It surfaces not only in the area of the roles of men and women, but also in the areas of sexual morality, the exercise of authority, and similar areas. <a id="_idIndexMarker571"></a>Madeleine Boucher, herself something of a feminist, in commenting on Stendahl’s interpretation of <a id="_idIndexMarker572"></a>Galatians 3:28, expresses the trend this way:</p>
<p class="BODY-STYLES_Block-Quote-Single"><span class="No-Ligatures">Th</span>eologians are often led to fresh insight by the new factors operating in their own time, especially intellectual and social factors. <span class="No-Ligatures">Th</span>en, because they stand in the Judaeo-Christian tradition, they turn to the Bible in search of the texts with which to undergird these new insights. Yet, because they are seeking to answer contemporary questions, questions unknown to biblical writers, they sometimes interpret the biblical texts in a way which is more true to contemporary thought than to the thought of the biblical writers.<a id="_idTextAnchor417"></a><span class="Endnote-Ref">[26](#_idTextAnchor1454)</span></p>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>ere are some difficult questions to answer in approaching the issue of the roles of men and women as presented in the Bible and as lived today. Nonetheless, there is a clear tendency to interpret the Bible in a way consistent with a modern position that distorts the meaning of the biblical text. <span class="No-Ligatures">Th</span>ose who attempt to say that the actual text of the scripture itself holds that there does not have to be any subordination of woman to man will inevitably provide distorted exegesis.</p>
<p class="BODY-STYLES_Body-SA"><a id="_idIndexMarker573"></a>In 1951, all but one of the teachers holding academic positions in New Testament studies in the Swedish universities issued a statement in response to the efforts of the Swedish government to introduce the ordination of women into the Church of Sweden, a state church. <span class="No-Ligatures">Th</span>e statement is as follows:</p>
<p class="BODY-STYLES_Block-Quote-Single">We, the undersigned, professors and lecturers in the field of New Testament exegesis at our two universities, hereby declare as our definite opinion, based on careful investigation, that ordination of women would be incompatible with New Testament thought and would constitute disobedience to the Holy Scriptures. Both Jesus’ choice of apostles and Paul’s words concerning the position of women in the congregation have significance of principle, and are independent of circumstances and opinions conditioned by any particular time in history. <span class="No-Ligatures">Th</span>e current proposal that women should be admitted to priesthood in the Church of Sweden must therefore be said to meet with grave exegetical obstacles.<a id="_idTextAnchor418"></a><span class="Endnote-Ref">[27](#_idTextAnchor1455)</span></p>
<p class="BODY-STYLES_Body-NI">Twenty-five years later, it would be difficult to find one professor holding an academic position in exegesis at a university in Sweden who would endorse this statement. For some, the reason for their change has been a change in their view of the applicability of scripture. Such a change is creditable. But many writers today would dispute the exegetical results embodied in the statement. No significant new evidence has been found to warrant such a reversal. <span class="No-Ligatures">Th</span>e only explanation for it is that the climate of opinion has changed, influencing exegetes to come up with opinions that are acceptable nowadays. Either the Swedish exegetes in 1951 were determined by extra-exegetical factors, or the current exegetes are so determined. <span class="No-Ligatures">Th</span>e investigations in this book would indicate that the problem in this case lies more with the current exegetes. Twenty-five years ago, Christian Liberationist exegesis would have been dismissed out of hand by competent exegetes. Now it has influenced many of them and can be found in the most respectable journals. Social historians two hundred years from now will probably find this a good example of how scholarship can be influenced by political ideology and propaganda in the midst of a movement of social change.</p>
<p class="BODY-STYLES_Body">In summary, the exegetical position taken by this book is a basically uncontroversial one in its overall outlines. Only Christian Liberationist exegesis would dispute this assertion, but Christian Liberationist exegesis is not, for the most part, sound in its underlying principles and approach. <span class="No-Ligatures">Th</span>ere is a distinctive approach to the exegesis in this book, but the distinctiveness lies more in the attention paid to responsible restating of what the scripture says than in a distinctiveness of the positions taken on controversial points.</p>

<div class="_idFootnotes">
<div id="footnote-098" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-098-backlink">225*</a>A full exegesis for a Christian should involve not only a judgment about what the human author intends to assert and accomplish by the words, but also what the divine author intends to assert and accomplish.</p>
</div>
<div id="footnote-097" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-097-backlink">226*</a>In some of the more polemical works on women’s roles, a key argument often depends upon choosing one of a number of alternative reasonable interpretations of a passage. For instance, there are books on women’s roles that base the strength of their argumentation on the view that the author in <span class="Lining-Nums">1&#160;</span>Timothy 2:15 made women’s salvation consist in childbearing (and hence, the teaching in <span class="Lining-Nums">1&#160;</span>Tm 2:15 was in clear contradiction to the rest of New Testament teaching; see, for example, McGrath, 36<span class="No-Break">–3</span>7). While such an interpretation may have something to say for it, it is by no means the only possible interpretation, and any argumentation which asserts a contradiction, and claims to have definite evidence for it on the basis of such a disputed interpretation without making a strong case for its preferability, clearly moves in violation of good method. Perhaps one of the main reasons for not resting a case on a particular interpretation was the conviction that the main outline of the exegesis given in the first chapters of this book was well supported, and while it needed to be disentangled from confusing viewpoints, it did not need any special buttressing in terms of providing more evidence.</p>
</div>
</div>
