# [2]{.HEADS---SUBHEADS_Part-Number} Assess&#173;ing the Scrip&#173;tural Teach&#173;ing {-}

<a id="_idParaDest-45"></a><a id="_idTextAnchor419"></a>
<p class="BODY-STYLES_Part-Opening"><span>▶&#160;&#160;</span><span class="Opening-Drop-Words"><span class="No-Ligatures">Th</span>e first part of this book</span> surveyed the teaching of the scripture, especially in the New Testament, on the roles of men and women. It concluded with a synthesis of that teaching. <span class="No-Ligatures">Th</span>ere are, however, many further concerns touching upon that synthesis, some of which the second part of this book will attempt to address.</p>
<p class="BODY-STYLES_Body">Some of these concerns arise primarily from the historical perspective of modern scholarship, which examines the scripture as a collection of historical documents from the ancient world. <span class="No-Ligatures">Th</span>is perspective raises issues about the consistency and distinctiveness of the scriptural teaching, as well as its nature as an expression of an ancient culture. <span class="No-Ligatures">Th</span>ese issues will be taken up in Chapters Ten and Eleven.</p>
<p class="BODY-STYLES_Body">Some of these concerns which bear upon the preceding synthesis of scriptural teaching arise from the perspective of Christian tradition. <span class="No-Ligatures">Th</span>is perspective raises issues about the agreement of tradition subsequent to the New Testament with the interpretation of scriptural teaching given here, as well as about the approach of the Christian church through the centuries to teaching about the roles of men and women in circumstances different from those of the New Testament world. Chapters Twelve and <span class="No-Ligatures">Th</span>irteen will consider these issues.</p>
<p class="BODY-STYLES_Body">Finally, some concerns arise from the perspective of certain views about the nature and authority of scripture. <span class="No-Ligatures">Th</span>is perspective raises issues about how one should respond to scriptural teaching. <span class="No-Ligatures">Th</span>ese issues will be taken up in Chapters Fourteen and Fifteen.</p>
<p class="BODY-STYLES_Body">All of these chapters deal with the authority that the scriptural teaching has over Christians. <span class="No-Ligatures">Th</span>ey do not attempt to develop further the content of the scriptural teaching, but to assess its validity for determining Christian life.&#160;&#160;▶</p>
