# The New Tes&#173;ta&#173;ment Ap&#173;proach&#160;&#160;▹&#160; Jesus and Paul

<a id="_idParaDest-46"></a><a id="_idTextAnchor420"></a>
<p class="BODY-STYLES_Chapter-Opening"><span class="Opening-Drop-Words">If Christianity</span> is revelation of God and his ways and will, then this revelation comes to us in very human form. We receive it through a nation of Semites, the Jews, who seem somewhat superstitious, primitive, and “different” to the modern eye. In particular, this revelation comes to us through one Jew from the more backward part of Palestine who received neither a Greek education nor an education in the most advanced Jewish academies of his day. He was a Jew who probably never traveled more than 150 miles from his birthplace and who may not have spoken more than the languages of his own people. We learn this revelation from other Jews, of whom one in particular carried special influence. This second Jew, a diaspora Jew from Tarsus, traveled widely through the world, had the best education that Judaism could offer, spoke a number of languages, and was somewhat acquainted with Greco-Roman thought and philosophy. Finally, revelation was passed on to us by a very mixed collection of Jews and Gentiles spread throughout the Roman world. This group was made up mostly of people of the lower socioeconomic classes and of slaves, but it also included some wealthy and educated citizens who were trained in their culture and literature.</p>
<p class="BODY-STYLES_Body">If Christianity is revelation, then revelation of the divine comes to us mediated by human realities: human beings belonging to a particular age and culture; human languages with their distinctive thought forms and patterns of expression; human events revealing distinct personalities and cultural types. In the face of the humanness of Christianity, the temptation that recurrently and insistently presents itself is that of finding and then eliminating the human in order to reach the divine. And yet the revelation of Christianity is not simply a revelation of God, but also revelation which concerns the human. Christianity concerns God’s desire for the human race, his idea of what the human race should be. Relatedly, God’s revelation comes through human beings. To be sure, not everything in the words, people, and events mediating the revelation is part of the revelation. The gospel can be preached in English as well as in Aramaic or Greek. We may be called to imitate Paul, but not in his Jewish or Greek literary style, the peculiarities of his personality, or the mode of transportation he used in his missionary journeys. Nevertheless, Christian revelation comes to us not simply in universal truths, but through particular events at particular times and places, through particular individuals and communities that provide a pattern for us, and through particular formulations and statements of some universal truths.</p>
<p class="BODY-STYLES_Body">In other words, Christianity is historical revelation that comes at a particular point of human history and is conditioned by its circumstances. The historical nature of New Testament teachings is stronger in our consciousness now than in the consciousness of people three hundred years ago. Consequently, we raise questions about that teaching that would not have occurred to most people three hundred years ago. So far, this book has focused on patterns for the roles of men and women among the early Christians by examining the key New Testament texts that teach about these roles. In this and the following chapter, those teachings will be examined in their historical flow and setting. Questions of consistency, distinctiveness, and cultural conditioning will be considered.</p>
<h2 id="_idParaDest-47" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor421"></a>A Distinctive New Testament Approach</h2>
<p class="BODY-STYLES_Subhead-Opening-SA"><span class="MaWiC_Subhead-Drop-Words">The </span>previous chapter attempted to synthesize the New Testament teach&#173;ing on the roles of men and women. However, not everyone accepts the view that there is only one New Testament approach, or that the approach or approaches found in the New Testament are distinctively Christian. In fact, the view related in Chapter Nine is only one of four main views which have been taken of the New Testament teaching on the roles of men and women as seen in its historical setting:</p>
<ol>
<li class="BODY-STYLES_L-O-Num-L1-1st"><!--<span class="Body-List-Counter-Float">1.</span>-->The first of these four main views is the <span class="Italic">cultural conflict</span> view.<a id="_idTextAnchor422"></a><span class="Endnote-Ref">[1](#_idTextAnchor1456)</span> This view holds that Christian teaching in the New Testament was under a strong Hellenistic influence. The process began with Jesus, who was heavily influenced by the Hellenistic Gentiles living in Palestine, at least in the area of men’s and women’s roles. As a result of this influence, Jesus moved toward an approach to men-women relationships which pointed to an elimination of different roles for men and women. This same cultural influence also affected Paul somewhat, especially in <a id="_idIndexMarker574"></a>Galatians 3:28 and in the way women served in missionary work with him. However, Paul was also a converted rabbi, and his rabbinism showed itself in some aspects of his teaching. Hence there is a contradiction within New Testament teaching in the area of the roles of men and women. This contradiction is due to unresolved differences between the conflicting influences of Hellenistic thought and ways and rabbinic thought and ways.</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">2.</span>-->The second view could be called <span class="Italic">canonized rabbinism</span>.<a id="_idTextAnchor423"></a><span class="Endnote-Ref">[2](#_idTextAnchor1457)</span> According to this view, the teaching in the New Testament on the roles of men and women consists mainly of a residue of rabbinic influence on the early Christians. The New Testament teaching is identical to rabbinic teaching and is grounded in the same approach to theology used by the rabbis. Undoubtedly Paul and his rabbinic background are responsible for this. Many who take this approach want to see something distinctively Christian in Galatians 3:28, or in the way Jesus related to women, or perhaps in some other elements in the New Testament teaching on men and women. They would say that in the few places where we find the new Christian approach we can perceive a conflict with the residue of rabbinic teaching—that is, with most of the New Testament teaching on men and women. Thus, in its various forms, this approach attributes most or all of the New Testament teaching to rabbinic influence on the early church. This view is usually used to warrant the claim that contemporary Christians should ignore, or even root out, effects of this teaching.</li>
<li class="BODY-STYLES_L-O-Num-L1"><!--<span class="Body-List-Counter-Float">3.</span>-->The third view is the <span class="Italic">conformity to culture</span> view.<a id="_idTextAnchor424"></a><span class="Endnote-Ref">[3](#_idTextAnchor1458)</span> This view holds that the New Testament teaching on the roles of men and women was designed by Paul and other early Christians to help the early Christians blend more easily into the culture and customs around them, either for the purpose of avoiding conflict or for preaching the gospel more effectively. One variation on this view is the opinion that much New Testament teaching is based upon an underlying principle of acceptance of existing societal institutions and standards. Therefore, Christians should not cause disturbances but should do what society would regard as fitting and well-behaved. The thrust of such a view leads to the approach of changing Christian teaching when the order of society changes. Hence, contemporary Christians should so shape their approach to the roles of men and women that they adapt to the society in which they live.</li>
<li class="BODY-STYLES_L-O-Num-L1-SA"><!--<span class="Body-List-Counter-Float">4.</span>-->The fourth view could be called the <span class="Italic">distinctive approach</span>.<a id="_idTextAnchor425"></a><span class="Endnote-Ref">[4](#_idTextAnchor1459)</span> According to this position, the New Testament contains a distinctive approach to personal relationships and social structure, one that is neither reducible to Greek nor rabbinic influences, nor shaped by a principle of adaptation to societal practices. The teaching on the roles of men and women is part of that distinctive teaching. Moreover, in this view, both Jesus and Paul saw the Christian teaching on personal relationships as central to the purpose of Christianity. Hence this teaching is something that the early Christians would have experienced as being integral to their message to new Christians.</li>
</ol>
<p class="BODY-STYLES_Body">This chapter and the one following view the <span class="Italic">distinctive approach</span> as the one most in accord both with New Testament teaching and with a careful historical perspective on the subject. In order to show that Christians of the New Testament period adopted a distinctive approach to the roles of men and women, it is necessary to show that (1)&#160;the New Testament teaching is consistent and (2)&#160;that it can be clearly distinguished from rabbinic and Hellenistic teaching.</p>
<p class="BODY-STYLES_Body">The consistency of the New Testament approach is mainly challenged at two points. The first is within the Pauline writings themselves. As was noted above, many have held that Paul was either influenced by Hellenistic currents, or else formed by his new Christian insights enough to propound some teachings in disagreement with other elements likely inherited from his rabbinic training. Earlier chapters have shown, however, that the problem exists not within Paul’s writings themselves, but rather in the minds of people who want to attribute to Paul certain views of their own. Paul’s writings, as has been shown, do take a reasonably consistent approach.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker575"></a>The second point at which the consistency of the New Testament has been frequently challenged is that of the “conflict” between the teaching of Jesus and Paul. This chapter will consider the relationship between the teaching of Jesus and Paul on the roles of men and women. It will also examine how Jesus was situated in regard to rabbinic teaching and the customs of the time. The next chapter will consider the question of the distinctiveness of the New Testament approach in relationship to rabbinism and to Hellenism.</p>
<p class="BODY-STYLES_Body">Behind the discussion about the distinctiveness of the New Testament approach to the roles of men and women lies a search for a basis for evaluating New Testament teaching in general. This search for authority characterizes some modern New Testament scholars who have put aside the traditional approach to the authority of scripture and tradition in an attempt to discover what in the New Testament is authoritative in the midst of so much that seems unauthoritative. Often one can sense a desire to find a core of teaching not culturally conditioned or historically determined, as if that core would turn out to be the “true” revelation in the midst of the New Testament writings.</p>
<p class="BODY-STYLES_Body">Much of the discussion about the distinctiveness of the New Testament approach in this area also stems from an attempt to find a “reasonable” way of applying the teachings of the New Testament. Often, those who are concerned about this cannot conceive of themselves straightforwardly applying the teachings in anything like the sense in which the New Testament writers intended. Their hope is to find some elements of New Testament teaching that are timeless and hence applicable in every age and situation.</p>
<p class="BODY-STYLES_Body">Neither this chapter nor the next discuss the authority of scripture or the application of New Testament teaching. These two issues will be considered further on. Rather, these chapters investigate the existence of a distinctive approach in the New Testament to the roles of men and women. This investigation will be made primarily from a historical perspective. The results of this discussion will allow us to proceed with greater clarity to the discussion of the authority and the application of scripture. The next chapter will also include a discussion of the possibility of this distinctive approach being considered merely cultural.</p>
<h2 id="_idParaDest-48" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor426"></a><a id="_idIndexMarker576"></a>Jesus and First-Century Judaism</h2>
<p class="BODY-STYLES_Subhead-Opening"><a id="_idIndexMarker577"></a><span class="MaWiC_Subhead-Drop-Words">In </span>Israelite Jewish practice, an evolution occurred in the area of the roles of men and women. In the earlier texts of the Old Testament, women are not presented as being restricted to women’s quarters or normally separated from men in speech or activity.<a id="_idTextAnchor427"></a><span class="Endnote-Ref">[5](#_idTextAnchor1460)</span> Sarah, Rebecca, Rachel, Miriam, Deborah, Abigail, Huldah—not to mention Jezebel, Athaliah, and some other less distinguished figures—were women who enjoyed a fair amount of freedom of movement. Likewise, the women of that time seem to have played a relatively more significant role in public life.<a id="_idTextAnchor428"></a><span class="Endnote-Ref">[6](#_idTextAnchor1461)</span> These differences between earlier Israelite society and later Judaism, however, do not indicate that the basic order sketched out in the discussion of Genesis in Chapters One and Two was ever overthrown or discarded. The man was always the head of the family throughout the Old Testament period, and the woman “belonged” to him, either as wife or as daughter. Women did not hold governmental positions in Israelite society, nor were they part of the priesthood. Moreover, there were many Jewish customs which incarnated a role difference. While it does seem that the differentiation between men and women in the Old Testament has often been exaggerated, there did exist a deeply rooted, almost instinctive difference.</p>
<p class="BODY-STYLES_Body">The role of women began to change sometime during the Exilic or Post-exilic period. By the time of the Mishna and Talmud, one can see that a well-developed approach to the roles of men and women had evolved, an approach involving a great deal of separation along carefully worked out rules of conduct for relations between the sexes. This was the beginning of what could be called a rabbinic approach to the roles of men and women. This developing approach probably existed in its main outlines in Jesus’ time. However, it becomes clearly traceable only in the Mishnaic writings, writings which date from the second century in their written form.<a id="_idTextAnchor429"></a><span class="Endnote-Ref">[7](#_idTextAnchor1462)</span></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker578"></a>In rabbinic understanding, women were restricted to the women’s quarters of the home, at least ideally. They were not allowed to go out except for certain specified purposes and then their faces were to be fully veiled. Their duties consisted mainly of preparing meals, cleaning, bearing and feeding children, making beds, and working with wool. Women had few marital rights. A husband could legally marry more wives without the existing wife’s permission. While he could divorce his wife freely, only in very special situations did she have any rights of divorce. A fair amount of separation between husband and wife was present even within the home. Husbands were discouraged from talking much with their wives. There is little evidence that husbands and wives prayed together, except for certain family celebrations. When guests were present in the home, women were not supposed to be present or even to serve at meals.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker579"></a>The separation was even stronger in public life. A man was not supposed to speak to a woman in public if he could at all avoid it, and he was by no means to touch a woman who was not his wife. Women were separated from men at the synagogue and in <a id="_idIndexMarker580"></a>the Temple. Often, women were not able to see the services. For example, most of the worship in the Temple was conducted in a court to which women had no access. Women had a different set of religious obligations than men (see Chapter Six). They were obligated to the chief prayer, to the mezuzahs, and to table prayers (i.e., to domestic religious rites), but not to the <a id="_idIndexMarker581"></a>Shema (the prayer “Hear, O Israel”) or to the study of the law. Neither were women counted as part of the assembly. Lack of obligation in these matters did not mean actual exclusion from them, but women were not considered regular or full participants in them.</p>
<p class="BODY-STYLES_Body-SA">Finally, there is an unmistakable misogyny in rabbinic writings. Statements betraying a dislike or disrespect for women were by no means uncommon, as the following examples illustrate:</p>
<p class="BODY-STYLES_Block-Quote-Single">Ten qab of emptyheadedness have come upon the world, nine having been received by women and one by the rest of the world.<a id="_idTextAnchor430"></a><span class="Endnote-Ref">[8](#_idTextAnchor1463)</span></p>
<p class="BODY-STYLES_Block-Quote-Single">Without both male and female children the world could not exist, but blessed is he whose children are male and woe to him whose children are female.<a id="_idTextAnchor431"></a><span class="Endnote-Ref">[9](#_idTextAnchor1464)</span></p>
<p class="BODY-STYLES_Body-NI-SA">It would, however, be much too strong to say that misogyny was characteristic of the rabbis. Their writings also provide numerous instances of praise and honor for women. For example:</p>
<p class="BODY-STYLES_Block-Quote-Single">Our rabbis taught: Concerning a man who loves his wife as himself, who honours her more than himself, who guides his sons and daughters in the right path and arranges for them to be married near the period of their puberty, Scripture says, “And thou shalt know that thy tent is in peace” (<a id="_idIndexMarker582"></a>Job 5:24).<a id="_idTextAnchor432"></a><span class="Endnote-Ref">[10](#_idTextAnchor1465)</span></p>
<p class="BODY-STYLES_Block-Quote-Single">Our rabbis taught: Greater is the promise made by the Holy One, blessed be He, to the women than to the men; for it says, “Rise up, ye women that are at ease; ye confident daughters, give ear unto my speech.”<a id="_idTextAnchor433"></a><span class="Endnote-Ref">[11](#_idTextAnchor1466)</span></p>
<p class="BODY-STYLES_Body">We cannot be certain why this rabbinic approach to the roles of men and women developed. Possibly, the Jews were influenced in their approach by their close contact with Mesopotamian culture during the Exile, contact which would have continued after the first exiles returned. Increasing urbanization probably accounted for some of the change. Women’s quarters and strict separation of sexes appeared more commonly in urban areas than in rural ones, probably because of the requirements of farm work and possibly because of an increased need to protect women in cities. An additional factor may have been greater wealth, since such arrangements seem to have occurred more often among the wealthy. Some of the change was likely due to a greater strictness in legal matters. Men were protected from seeing women other than their wives out of a concern for sexual ethics, and women were protected from other men out of a concern for their chastity. Moreover, greater separation helped keep men from accidentally incurring ritual impurity when women had their times of menstruation. In addition, one could probably say that disrespect for women and their abilities was increasing.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker583"></a><a id="_idIndexMarker584"></a><a id="_idIndexMarker585"></a>We can contrast Jesus with the rabbis as seen in the Talmud and Midrash. Jesus does not behave the same way.<a id="_idTextAnchor434"></a><span class="Endnote-Ref">[12](#_idTextAnchor1467)</span> Women come to him and he helps them directly. He heals them (<a id="_idIndexMarker586"></a>Mk&#160;5:25<span class="No-Break">–3</span>4). On occasion he touches them (<a id="_idIndexMarker587"></a>Mt&#160;8:14<span class="No-Break">–1</span>5). He talks to them individually, regularly in private and sometimes in public (<a id="_idIndexMarker588"></a>Jn&#160;11:17<span class="No-Break">–4</span>4). On one occasion he even talks to a woman when both of them were unaccompanied (<a id="_idIndexMarker589"></a>Jn&#160;4:7<span class="No-Break">–2</span>4). He teaches women along with the men (<a id="_idIndexMarker590"></a>Lk&#160;10:38<span class="No-Break">–4</span>2). When he teaches, he speaks of women and uses womanly tasks as illustrations. On occasion, he makes use of two parables to illustrate the same point, one drawn from the activities of men, the other from the activities of women (<a id="_idIndexMarker591"></a>Lk&#160;15:3<span class="No-Break">–1</span>0). He never shows disrespect to women, nor does he ever speak about women in a disparaging way. He relates in a brotherly fashion to women whom he knows. He has some women traveling with him to serve him (<a id="_idIndexMarker592"></a>Lk&#160;8:1<span class="No-Break">–3</span>). Finally, he calls women “daughters of Abraham” (<a id="_idIndexMarker593"></a>Lk&#160;13:16), explicitly according them a spiritual status like that accorded to men. One might add here that after his resurrection Jesus appears to women first and lets them carry the news to the men (<a id="_idIndexMarker594"></a>Jn&#160;20:11<span class="No-Break">–1</span>9; <a id="_idIndexMarker595"></a>Mt&#160;28:9<span class="No-Break">–1</span>0).</p>
<p class="BODY-STYLES_Body">Jesus clearly related to women differently than the rabbis whose teaching about women one finds in the Talmud and Midrash. Yet this fact does not suffice to solve the question of how Jesus’ approach compared with the customs of his time. Some would hold that Jesus’ approach was revolutionary, that Jesus consciously and deliberately chose to break away from the dominant customs of the day, as recorded by rabbinic writings which reflected the normative Judaism of that time. By observing what he did more than what he said, it is argued, one can see how revolutionary he was and infer his real intentions in the area of men’s and women’s roles. The weak form of this view is that Jesus carefully broke with Jewish customs in a way that would not cause excitement. In this line of thought, it is assumed that Jesus would have gone further had he felt free to do so. An even stronger form of this view is sometimes also taken, namely, that Jesus was frankly egalitarian and treated women in a way identical to men.</p>
<p class="BODY-STYLES_Body">Still others would hold that Jesus was not revolutionary in his approach to women. They would point out that there is, in fact, little evidence that he departed significantly from Jewish customs. Jesus did not follow the rules for a strict Pharisaic rabbi—but then he was not a strict Pharisaic rabbi. He was not a Pharisee, nor even primarily a rabbi, but rather was more of an eschatological preacher. Moreover, they would point out, there is no evidence that the majority of the Jews in Palestine in Jesus’ day followed strict Talmudic practice either. If, in other words, Christianity produced a change from Palestinian Jewish custom, there is no evidence that Jesus began that change.</p>
<p class="BODY-STYLES_Body">Some people would modify this approach. While agreeing that Jesus was not revolutionary in respect to the prevailing customs of his day and that he did not want to radically change the social structure of Judaism in the area of roles for men and women, they would see as more significant the new way Jesus did relate with women. Not only was he more open than the later rabbis were, but he was more open with and interested in women than any other Jew of his century or the preceding two centuries. Moreover, Jesus consistently treated women as being as important as men in the eyes of God, and he felt free to alter or even break prevailing customs when he judged it proper to do so.</p>
<p class="BODY-STYLES_Body">The view that Jesus was not revolutionary in regard to social roles and customs for men-women relations, but that he accorded them a higher spiritual status than Jews who were his contemporaries, accords best with the available evidence. The view that he was revolutionary is normally advanced by those who wish to assert an inconsistency between Jesus and Paul. Thus, this view will be the focus of concern in the rest of this section. The view that Jesus was no different from his contemporaries at all seems to miss an important aspect of his work, but has not played a significant role in recent discussions of the roles of men and women.<a id="_idTextAnchor435"></a><span class="Endnote-Ref">[13](#_idTextAnchor1468)</span></p>
<h3 class="HEADS---SUBHEADS_Subsubhead">The Variety of First-Century Judaism</h3>
<p class="BODY-STYLES_Body-NI">If the Talmud and Midrash are accepted as presenting the normative approach of Judaism in Jesus’ time, one would have to say that Jesus was at least very eccentric, and possibly revolutionary, in his approach to women. One would have to place his approach to women in the same category of extraordinary behavior, relative to the prevailing practice, as his approach to tax collectors and sinners. Yet such a conclusion cannot be made easily. In recent years, largely because of the discovery of the <a id="_idIndexMarker596"></a>Dead Sea Scrolls, a clearer perception of Judaism in the time of Jesus has developed, a perception which would call such a simple conclusion into question. Before the discovery of the scrolls it was much more usual to assume that the Judaism of Jesus’ time was a fairly uniform phenomenon, dominated by the teaching of the scribe-rabbis (perhaps: Pharisaic scribes), who were the forebears of the rabbis who wrote the Talmud and Midrash. Their teaching was much the same as that of the later rabbis. It was known that other forms of Judaism existed in the period before the uprising against Rome, and that there was some question as to how far back it was possible to attribute a Mishnaic opinion, but the idea of “normative Judaism” as reconstructed through rabbinic material had a strong hold and often controlled the discussion of Jesus and his relations to Judaism.</p>
<p class="BODY-STYLES_Body">It is much clearer now that Judaism before 70&#160;<span class="OT-All-Small-Caps">AD</span> was a variegated phenomenon, and that the Pharisees were only one sect among a number, although they were the strongest.<a id="_idTextAnchor436"></a><span class="Endnote-Ref">[14](#_idTextAnchor1469)</span> The Pharisees were opposed not only by the Sadducees, but by groups as spiritually strong and respected as the Qumran community. Movements like that of John the Baptist could grow even in opposition to the Pharisees and still be enthusiastically supported by the people. In fact, the <span class="Italic">am ha-aretz</span>, the “people of the land” who did not follow the law in a way that was acceptable to the Pharisees, often included prominent and respected people not attached to any particular sect in Judaism. Possibly many of the scribes would not have accepted Pharisaic interpretations of laws such as those regarding purity and tithing. Finally, the influence of the Pharisees was probably weakest in Galilee—Jesus’ own area. In short, it is clearer now that the fact that Jesus did not follow the ways of Pharisaic scribe-rabbis is only one consideration in evaluating his relation to the approach(es) of the Judaism of his time.</p>
<p class="BODY-STYLES_Body">Moreover, there is the further question of just how much the material in the Talmud and Midrash clearly illustrates the approach of the scribe-rabbis of Jesus’ time. Some of the material that reflects the approach ascribed above to the rabbis in the area of men’s and women’s roles is attributed to rabbis of the period before 70&#160;<span class="OT-All-Small-Caps">AD</span>. However, most of this material comes from rabbis after that time. In 70&#160;<span class="OT-All-Small-Caps">AD</span>, the upheaval caused by the destruction of the Jewish commonwealth, the Temple, and the sacrificial system caused a break in the approach of the scribal-rabbinic tradition. Thus, it is not always clear how much of the teaching, even in the earlier Midrashim, can be attributed to the period before 70&#160;<span class="OT-All-Small-Caps">AD</span>. This might be particularly true for customs concerning the roles of men and women. After 70&#160;<span class="OT-All-Small-Caps">AD</span> a greater strictness was introduced into rabbinic customs and a greater strictness in regard to the roles of men and women could easily be another illustration of the same trend. Moreover, many of the customs cited above are not found directly in the law, nor are they decisions interpretive of laws; hence they were probably freer to change.<span class="Footnote-Ref"><span id="footnote-100-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-100">*</a></span></span></p>
<p class="BODY-STYLES_Body">Finally, the evidence indicates that in the time of Jesus the customs bearing on the roles of men and women varied according to social class and between urban or rural areas. While the wealthy Jerusalemites, Pharisee and non-Pharisee alike, probably had women’s quarters and practiced a fairly strict separation of women, the same was probably not true among poorer people or those in rural areas.<a id="_idTextAnchor437"></a><span class="Endnote-Ref">[15](#_idTextAnchor1470)</span> In other words, while one can say with some confidence that many of the practices described in the Talmud and Midrash were characteristic of scribe-rabbis in the time of Jesus, one cannot say that all of the practices were characteristic, or even that all scribes held them. Neither can one say that the practices characteristic of the scribes would have been considered normal for most of the Jewish people.</p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idTextAnchor438"></a>Jesus’ Treatment of Women</h3>
<p class="BODY-STYLES_Body-NI">The simplest and most striking fact to begin with in examining Jesus’ approach to women is the lack of apparent controversy created by it. The evidence—mostly from the gospels—indicates that his relations to women never caused the same kind of surprise and concern as did his relations to tax collectors and sinners. On one occasion, when he seemed to be acting toward a woman in a way that was deemed improper (his conversation with the Samaritan woman in <a id="_idIndexMarker597"></a>Jn&#160;4:27), the surprise shown by his disciples indicates that the incident was an exceptional event in Jesus’ life. The most likely interpretation of the disciples’ words would be that Jesus did not normally speak to women in public in the way he did with the Samaritan woman. While much is made of the fact that Jesus felt freer to speak with and deal with women than the scribe-rabbis did, it is not often observed that at the same time women in the gospel writings also felt freer to approach Jesus than would be expected if the customs portrayed in the Talmudic writings were the common Jewish practice at this time. One is dealing, in other words, with a freer situation altogether. The evidence indicates that Jesus’ normal behavior with regard to women was not understood to be revolutionary by people in his environment.</p>
<p class="BODY-STYLES_Body">Some of Jesus’ deviations from the norms of the rabbis as expressed in Talmud and Midrash can also be explained by Jesus’ role. Jesus did not view himself or act as merely a scribe-rabbi.<a id="_idTextAnchor439"></a><span class="Endnote-Ref">[16](#_idTextAnchor1471)</span> He acted like a popular preacher and prophet as well. He was not, in short, primarily engaged in teaching law and theology himself or in training others to teach law and theology so that they might become judges or lawyers. Rather, he was primarily engaged in calling the people of Israel to turn to God in a new way and to prepare for God’s kingdom. His message was for men and women alike. Therefore, he taught women, healed women, used examples of women and their work in his teaching, and had women accompany him in his travels. Jesus was also willing to reach out to a Samaritan woman to evangelize her and then let her share that news with her town. His willingness to touch women in healing them should probably be understood in this context. It was more a sign of his ability to bring the messianic salvation with its physical and spiritual wholeness for everyone than a sign of willingness in daily life to break with Jewish custom. We should also note that Jesus, unlike the scribe-rabbis, did not marry. This fact is not often mentioned in the contemporary discussions of Jesus’ approach to women, but it is surely one of the points of greatest difference between him and the scribe-rabbis of his day. He related to women more as prophets like Elijah and Elisha did than in a way prescribed by scribal tradition.<a id="_idTextAnchor440"></a><span class="Endnote-Ref">[17](#_idTextAnchor1472)</span></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker598"></a>This context provides a good framework for viewing the question of whether women were disciples of Jesus. Women are never referred to as disciples in the gospels. Only once in the New Testament is a woman referred to as a “disciple,” and that is the description of Tabitha in <a id="_idIndexMarker599"></a>Acts&#160;9:36. Throughout Acts, however, “disciple” is used as an equivalent of “believer” or “follower of Jesus,” meaning simply “Christian.” <a id="_idIndexMarker600"></a>Mary in <a id="_idIndexMarker601"></a>Luke 10:39 is sometimes cited as taking the position of a disciple, since she sits at the feet of Jesus and is taught by him. She is portrayed that way, and this feature of the story is important for understanding its message. However, this does not automatically mean that Mary was viewed as a disciple by Jesus or the other disciples. Even the later rabbis, who strictly separated women from men when guests were in the house for a meal, did not forbid the woman of the house from listening in.<a id="_idTextAnchor441"></a><span class="Endnote-Ref">[18](#_idTextAnchor1474)</span> Jesus may have allowed the women of the house to listen to his teaching as disciples would do without considering them disciples. The story in Luke&#160;10 would make its point adequately, and perhaps even better, if Mary were not considered a disciple, but rather one who took the position of a disciple at the feet of Jesus when he was in her home.</p>
<p class="BODY-STYLES_Body">However, the answer to the question of whether women were disciples of Jesus probably lies in understanding more clearly what the word “disciple” means.<a id="_idTextAnchor442"></a><span class="Endnote-Ref">[19](#_idTextAnchor1475)</span> In the New Testament, “disciple” could have been used (and probably often was) in close parallel to the rabbinic use of the word “disciple.” A “disciple” in this sense is someone who is being trained by a master (rabbi) to fulfill the same role the master himself holds, that is, someone being trained to be a rabbi or to fulfill rabbinic functions. In the Old Testament period, prophets seemed to train younger prophets in a similar way. Jesus was a prophet and teacher and he trained the twelve disciples to represent him and carry out a role similar to his own.</p>
<p class="BODY-STYLES_Body">The New Testament also seems to have the word “disciple” in a broader sense, closer to the English usage of “adherent” or “follower.” Acts uses the word in this broader sense. The disciples of John the Baptist were also, perhaps, disciples in this broader sense. The narrow and broader senses are related in Luke<span class="No-Break">–A</span>cts. One can see there that although those who came to believe in Jesus after the resurrection did not take up an apostolic ministry in the strict sense, they did succeed to the role of the disciples in their relationship with Jesus. They followed Jesus and related to him as their teacher. There is no evidence that Jesus chose women as disciples in the narrower sense. When he chose apostles or disciples to be trained, he chose only men. While women were near him serving, the circle of Jesus’ co-workers is exclusively male.<a id="_idTextAnchor443"></a><span class="Endnote-Ref">[20](#_idTextAnchor1476)</span> In short, the evidence would indicate that only men were disciples in the narrower sense of receiving training for specific ministry which involved being a teacher, but women as well as men were disciples in the broader sense. The account of Mary in Luke&#160;10 (part of Luke<span class="No-Break">–A</span>cts) then, simply exemplifies the way all believers could enter into the same relationship with Jesus that the Twelve did in that they could follow Jesus and receive his teaching.</p>
<p class="BODY-STYLES_Body">Very little of Jesus’ teaching in the gospels bears on the roles of men and women. Only passages on sex, marriage, and divorce are directly relevant. However, these passages are more concerned with either sexual purity or the nature of marriage than with men’s and women’s roles. Jesus’ teaching on divorce does put the man and woman in the same position in their marital rights, but the goal of this teaching seems to have been to increase the oneness between men and women in marriage, not to give equal rights to divorce. Elimination of the woman’s legal disadvantage in the area of divorce was merely a byproduct of Jesus’ new approach to marriage. His teaching in the sexual area (<a id="_idIndexMarker602"></a>Mt&#160;5:27<span class="No-Break">–3</span>1) might reasonably be interpreted as a support of the separation of men and women in daily life, but such a view goes beyond anything explicit in the text.</p>
<p class="BODY-STYLES_Body">The only explicit reference outside the gospels to Jesus’ teaching on the subject is the “command of the Lord” in <a id="_idIndexMarker603"></a>1&#160;Corinthians 14:37. This could well be a reference to proper order for women in meetings. If so, then Jesus did, at least in one area, teach a role difference for men and women that agreed with his own actions.</p>
<p class="BODY-STYLES_Body">In summary, if Jesus wanted to be revolutionary in his approach to the roles of men and women, one could expect something in his teaching that would point in that direction. However, there is no such evidence in his teaching. In fact, there is possibly even some evidence (1&#160;Cor&#160;14:37) that points in the opposite direction. Even without this evidence, however, the fact that he did not teach about role difference between men and women does not constitute evidence in support of the view that he did not accept the Old Testament role structure for men and women. To the contrary, it is evidence that he did accept it. Jesus did not teach against idolatry either, but that is evidence that he accepted the basic Old Testament teaching on the subject, not that he allowed idolatry.</p>
<p class="BODY-STYLES_Body">Jesus, then, in no way calls into question the basic Old Testament pattern of roles for men and women. There is no evidence that he even modifies the basic rules of daily Jewish custom for a man talking with, touching, or otherwise relating to a woman. He does relate to women differently than a scribe-rabbi would have done, but most of the differences can probably be explained by (1)&#160;the fact that he does not see himself as just a scribe-rabbi; and (2)&#160;the fact that the approach of Jewish society in his time was freer in this area than it was for rabbis in the Mishnaic and later Talmudic periods.</p>
<p class="BODY-STYLES_Body">Some have nevertheless held the view that Jesus would really have liked to have broken more decisively with the Jewish approach, but he kept silent because he knew that the people of his time could not have accepted it. As has been indicated, once the later rabbinic customs bearing on men’s and women’s roles as expressed in the Talmud and Midrash are no longer the standard of comparison with Jesus’ approach, there is no indication that Jesus would have wanted to make any significant change in the normal Jewish approach of his day. However, there is even less indication that Jesus would have held back some of his most revolutionary teaching because he was afraid of the reaction of those around him. Jesus did not seem to approach his relations with the Jewish people and the scribe-rabbis so timidly. His teaching on relating to tax collectors and “sinners” was no more acceptable than his teaching on women would have been, if this teaching had, in fact, been so revolutionary. If Jesus had wanted to avoid trouble, he certainly should have been more careful with his Sabbath teaching. His teaching on ritual purity was not acceptable to the Jews—it was truly revolutionary—yet he spoke it at a time when he was already in enough trouble. There is no indication that Jesus suppressed or restrained a desire to break with the approach of his society in the area of men’s and women’s roles. The fact that he did treat women very well, with love and respect, is by no means incompatible with acceptance of role differences between men and women. Only someone who believes that genuine love and respect must be incompatible with role differentiation would be able to detect a revolutionary intent in Jesus’ behavior despite the lack of evidence for it.</p>
<p class="BODY-STYLES_Body">Even though Jesus was not revolutionary in the sense of wanting to change the basic patterns of roles for men and women that are founded in the Old Testament, or even the daily life customs of his Palestinian environment, it would be a mistake to overlook that which was genuinely new in his approach to women. The fact that Jesus saw his role as being that of a prophet explains many of his differences from rabbinic customs in relating to women. But this also points to something more. The gospels, particularly those of Luke and John, preserve a portrait of Jesus’ relations with women that shows that he had markedly brotherly relationships with women and also a striking concern that they hear his message and understand it. Martha and Mary are not only close to him, but they both receive his teaching. Mary sits at his feet (Luke&#160;10), and Martha is the one whom Jesus teaches about the resurrection (John&#160;11). Jesus chooses the unknown Samaritan woman, the one called by the Greeks Photine, “the enlightened one,” to hear about himself and the gift of the Spirit. Not only does he teach her, but she then becomes the first “evangelist” to the Samaritans. When Jesus sees a woman who had a spirit of infirmity for eighteen years, he has compassion on her and heals her without her asking. He does so because she is a daughter of Abraham and is thus worthy of his concern. Jesus’ recognition of the woman’s spiritual status along with the sons of Abraham may not have been original, but it may well have been, since the first extant rabbinic parallel to such a phrase dates from about seventy years later.<a id="_idTextAnchor444"></a><span class="Endnote-Ref">[21](#_idTextAnchor1477)</span></p>
<p class="BODY-STYLES_Body">The interest Jesus shows in women is striking, both in his concern for their “religious” life and in his brotherly love for them. There are no parallels to it for his century or the century or two before. Were the historical sources fuller, perhaps one could find some parallels, but, nevertheless, none are known to exist. Jesus does not treat women as if only men were full Israelites. He treats women out of his role as preacher-teacher-prophet-healer whose message and concern is for the whole people of Israel. Jesus’ loving concern for women is quite likely another indication of his concern to return to “the beginning,” to God’s original creation, to the model of the patriarchs and prophets. His approach to women can also probably be traced to his message of repentance and faith, to his teaching about God’s desire for “mercy and not sacrifice,” to his impatience with the tradition of the elders, and their view that purity consists in “what goes into a person rather than what comes out.” The righteousness Jesus taught was for all of Israel, for men and women alike, without distinction. Jesus did not come to abolish the law, but he did come to restore it to its true place, and one aspect of that restoration was a change in status of women in Israel.<span class="Footnote-Ref"><span id="footnote-099-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-099">*</a></span></span> This does not mean that Jesus came to abolish role differences, any more than <a id="_idIndexMarker605"></a>Galatians 3:28 means this. But it does mean that he opened the kingdom of God to men and women alike.</p>
<p class="BODY-STYLES_Body">To summarize, Jesus related to women with love and respect. He spoke to them, taught them, healed them. He never spoke of them in a contemptuous or downgrading manner and never treated them as if they were unimportant. In his eyes, they had the same spiritual status as men. At the same time, the evidence is that he accepted a role difference for men and women and that he even respected the normal Jewish customs in the area. He was not, as one recent speaker claimed, “a man who breaks all categories, who goes beyond all accepted norms.”<a id="_idTextAnchor447"></a><span class="Endnote-Ref">[22](#_idTextAnchor1478)</span> He did break some categories and went beyond some accepted norms, but only the ones that were due to scribal or Pharisaic interpretation of God’s teaching that he judged to be erroneous. Jesus was not revolutionary with regard to the roles of men and women. His revolution lay rather in the area of what constituted true righteousness and of the spiritual relationship of men and women alike to God and to Israel. The consequence of his teaching and approach in this area was a very significant spiritual and social change for women, one that allowed them, as Christians, to have the same spiritual status as men, to be treated with the same “brotherly love” as men, a change that was described in Chapter Six.<a id="_idTextAnchor448"></a></p>
<h2 id="_idParaDest-49" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor449"></a><a id="_idIndexMarker606"></a><a id="_idIndexMarker607"></a>Paul and Pagan Culture</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">In</span> comparing Paul with Jesus as he appears in the gospels, a picture presents itself that overturns some recently popular prejudices. One recent author states the relationship of Paul to Jesus this way: “Actually, Jesus’ attitude toward women was completely unlike Paul’s.”<a id="_idTextAnchor450"></a><span class="Endnote-Ref">[23](#_idTextAnchor1479)</span> According to this writer, Paul is an anti-feminist, while Jesus was “woman’s best friend” and treated women as “persons.” The basis for this view is mainly the fact that most of the scriptural passages which enjoin a role difference between men and women are in Paul’s epistles. Therefore, many would draw a contrast between Jesus and Paul, and favor the approach of Jesus over that of Paul.</p>
<p class="BODY-STYLES_Body-SA">However, the evidence shows no basis for the contemporary prejudices against Paul; in fact, it points in the opposite direction. There is more evidence for Paul’s friendships with women than for Jesus’ and more examples of the way Paul “furthered” the woman’s role than of how Jesus did this. First, one can see from Paul’s letters a great deal of praise for women who have deserved it. Romans&#160;16 provides a full example of this:</p>
<p class="BODY-STYLES_Block-Quote-1st">I commend to you our sister Phoebe, a deaconess of the church at Cen&#173;chreae, that you may receive her in the Lord as befits the saints, and help her in whatever she may require from you, for she has been a helper of many and of myself as well.</p>
<p class="BODY-STYLES_Block-Quote-Last">Greet Prisca and Aquila, my fellow workers in Christ Jesus. .&#160;.&#160;. Greet Mary who has worked hard among you. .&#160;.&#160;. Greet those workers in the Lord, Tryphaena and Tryphosa. Greet the beloved Persis, who has worked hard in the Lord. Greet Rufus, eminent in the Lord, also his mother and mine. .&#160;.&#160;. Greet Philologus, Julia, Nereus and his sister, and Olympas, and all the saints who are with them. (Rom 16:1<span class="No-Break">–3</span>, 6, 12, 13,&#160;15)</p>
<p class="BODY-STYLES_Body-NI-SA"><a id="_idIndexMarker608"></a>Philippians 4:2<span class="No-Break">–3</span> provides a glimpse into Paul’s relations with some women who probably had worked with him, and exemplifies his concern for them:</p>
<p class="BODY-STYLES_Block-Quote-Single">I entreat Euodia and I entreat Syntyche to agree in the Lord. And I ask you also, true yokefellow, help these women, for they have labored side by side with me in the gospel together with Clement and the rest of my fellow workers, whose names are in the book of life. (Phil&#160;4:2<span class="No-Break">–3</span>)<a id="_idTextAnchor451"></a><span class="Endnote-Ref">[24](#_idTextAnchor1480)</span></p>
<p class="BODY-STYLES_Body-NI">Paul’s love and respect for women does not appear to be less than that of Jesus. In fact, it is probably not accidental that the Gospel of Luke, the Gospel that most clearly preserves the memory of Jesus’ love and concern for women, is the Gospel also associated with Paul.<a id="_idTextAnchor452"></a><span class="Endnote-Ref">[25](#_idTextAnchor1481)</span></p>
<p class="BODY-STYLES_Body">Moreover, the evidence indicates that Paul worked more actively with women in service than Jesus did. The examples given in Chapter Five in the discussion of the role of women as missionary workers come from Paul’s work. Paul possibly provides the earliest example of a Christian leader working with deaconesses.<a id="_idTextAnchor453"></a><span class="Endnote-Ref">[26](#_idTextAnchor1482)</span> In contrast, one does not find Jesus sending women out on mission the way he sent out the Twelve or the seventy-two. Neither does one find Jesus making use of women’s services in the course of his preaching in the way he made use of the services of the Twelve. The difference may be due to Paul’s innovativeness in the area, or else due simply to the fact that Jesus did not need the same kind of helpers that an apostle founding a new church in a predominantly Gentile environment did. Whatever the reason, Paul appears with active women co-workers while Jesus does not.</p>
<p class="BODY-STYLES_Body">Finally, there are no indications of any difference between Paul and Jesus in regard to speaking with, touching, teaching, traveling with, or respecting women. Both probably observed the normal Jewish customs in these areas. Both were willing to speak to and teach women in public when it was a matter of bringing them the gospel message. Both were respectful of women.<a id="_idTextAnchor454"></a><span class="Endnote-Ref">[27](#_idTextAnchor1483)</span></p>
<p class="BODY-STYLES_Body">All of this is not to say that Paul loved, respected, or “furthered” women more than Jesus. Rather, it is simply an indication of how far removed the popular prejudice against Paul is from the actual evidence. It shows once more that many contemporary lines of interpretation are inspired by the view that anyone seeing value in a role difference for men and women must somehow value women less.</p>
<p class="BODY-STYLES_Body">The key difference between Paul and Jesus, as far as the evidence is concerned, lies in the fact that we have explicit New Testament teaching on the roles of men and women from Paul and none from Jesus.<a id="_idTextAnchor455"></a><span class="Endnote-Ref">[28](#_idTextAnchor1484)</span> As stated earlier, rather than indicating that Jesus did not accept a role differentiation between men and women, this lack of teaching from Jesus indicates that Jesus did accept such role differentiation. The explanation for the difference between Jesus and Paul in this area lies in the fact that they dealt with different situations, not that they took different approaches.</p>
<p class="BODY-STYLES_Body">Jesus’ world was Palestinian Judaism. Those whom he taught and those to whom he preached were mostly Jews who lived in a Jewish culture and were committed to the teaching of the scriptures as they understood it to be. Jesus lived in an environment, in other words, where much of what we now know as “Christian teaching” was not only accepted but followed rigidly and zealously. Adultery was clearly condemned. Homosexuality was out of the question. The father was the undisputed head of the family. Women held no position of public authority. Of course, Jesus and the first Christians within Palestine were in contact with Gentiles, and had to deal in various ways with the Gentile influence upon Judaism.<a id="_idTextAnchor456"></a><span class="Endnote-Ref">[29](#_idTextAnchor1485)</span> Their predominant environment, however, was militantly Jewish, and their predominant task in ethical teaching was to relate themselves to other currents in Judaism. Jesus may have had to clarify his position on divorce, but he did not have to explain why he had not chosen a woman apostle.</p>
<p class="BODY-STYLES_Body"><a id="_idTextAnchor457"></a>Early in their history the Christians moved outside of the Palestinian Jewish environment to lands that were predominantly pagan. Thus they “inherited” a position equivalent to that of diaspora Judaism. The Christians were surrounded by pagan religions and philosophies and by a culture shaped by various forms of paganism and teachings that did not stem from the scriptures. They needed to distinguish themselves from the surrounding pagan society and establish a way of life that was different from that of their neighbors. The early Christians could draw on the model of diaspora Judaism, which had to deal with the threat of idolatry and with moral standards that were very different from those of “the law.” But Christians in pagan lands had to do more than just follow the example of the diaspora Jews; they had to develop a teaching for the “Christian diaspora” that was faithful to Christ and his interpretation of the scriptures and of Judaism.</p>
<p class="BODY-STYLES_Body">Paul, then, was handling a pagan environment in his epistles, as were most of the writers of the New Testament epistles. It was an environment that contained many diaspora Jews, but was predominantly pagan. It was an environment in which sexual ethics and the pattern of roles for men and women as the early Christians understood them were not being observed.<a id="_idTextAnchor458"></a><span class="Endnote-Ref">[30](#_idTextAnchor1486)</span> Pagan cults had priestesses. In fact, the Greco-Roman world of that time seemed to have been experiencing a dissolution of its own traditions in the area of family life and the roles of men and women. Family life seems to have been weakening in some areas, and women were playing roles in society that they would not have played in Palestinian Judaism or in earlier Greco-Roman society. There is some indication that Asia Minor, and Ephesus in particular—the place from which 1&#160;Corinthians was written and to which 1&#160;Timothy was probably directed—had moved particularly far from Judeo-Christian patterns of roles of men and women. Perhaps this was because the region was the center of forms of pagan worship in which female deities and priestesses were prominent. The same currents were affecting other places in the Hellenic world as well, Corinth and Macedonia being two of the more significant.<a id="_idTextAnchor459"></a></p>
<p class="BODY-STYLES_Body">Paul also had to face some movements within the new Christian communities he had founded that undermined what he considered basic Christian standards, both in the area of the roles of men and women and in other areas. These currents have been labeled “enthusiastic,” “proto-Gnostic,” and even “proto-Montanist.” Whatever the proper description and understanding of them, Paul and his co-workers and successors had to deal with them as these currents moved toward discarding many of the patterns and traditions Paul had taught.</p>
<p class="BODY-STYLES_Body">Thus, the explicit teaching on the roles of men and women in the New Testament arises from the development of Christianity in a Gentile-pagan environment. It arises in that environment not because it was first invented there or imposed on Christians by a nervous ex-rabbi. It arises in that environment because the universal practice of the Christian churches was challenged in that environment. Paul had to teach many things that Jesus did not teach, not because Paul was developing a different approach, but because he could not presuppose that his converts would always accept what the early followers of Jesus took as a matter of course. Had Jesus preached and taught in the same environment as Paul, he undoubtedly would have had to say many of the same things. The fact that the New Testament teaching on roles is Pauline and not explicitly from Jesus is no reason to call into question its authentic Christianity. One could just as logically reconsider the circumcision question because only Paul left explicit teaching on the subject. The teaching of the “key texts” arises in the context of the “Pauline” environment of the mission to the Gentiles and to the Jews who lived among them because those were the Christians who needed to hear such teaching. Paul shaped Christian teaching for the Gentile world, but he did it in continuity with the approach taken by Jesus.</p>

<div class="_idFootnotes">
<div id="footnote-100" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-100-backlink">249*</a>There are three types of material at issue. One is the written law, which would have been accepted equally before and after 70&#160;<span class="OT-All-Small-Caps">AD</span>. When something is in the written law, it can be assumed that it was accepted as valid, even though there may have been variation in interpretations. There is also the accepted interpretation of the written law, the interpretations of the sage-scribe-rabbis as found in the Talmud and Midrash. Some of this was probably the common law of Judaism before 70&#160;<span class="OT-All-Small-Caps">AD</span>. Some of it was possibly just the interpretation of the Pharisees and might not have been widely accepted outside of the numbers of the Pharisees. Some of it was a later development. Finally, there are manners and rules for proper behavior in the Talmud and Midrash. Some of this material may have dated from earlier times, but there is some indication that these manners became stricter in certain areas in the rabbinic period. Moreover, manners were freer to change than law or legal interpretation (halachic rulings).</p>
<p class="FOOTNOTES_Footnote-Next">Rules about speaking to women and touching women and questions of separation of women from men were probably in the category of manners for the most part. Rules about men relating to women that stemmed from concern for purity might well have been specifically Pharisaic interpretations, as were rules about associating with sinners, washing of hands before meals, etc. To the degree that questions about touching were based on fear of incurring impurity, they would be in the category of Pharisaic interpretation. Rules of the sort that were discussed in Chapter Six would probably be in the category of common law for all Jews.</p>
<p class="FOOTNOTES_Footnote-Next">The dating of rabbinic materials is a complex question. The material provides internal evidence for dating, both through actual attribution and through internal evidences of a ruling’s origin in the history of rabbinic tradition. However, some judgments can also be made of how likely material was to develop. Scriptural material was fixed before the New Testament period. Basic common law interpretation was probably fairly conservative, though in fact it was constantly adapted. Customs and behavior were more open to change.</p>
<p class="FOOTNOTES_Footnote-Next">For all these questions, the gospel records themselves are one of the main ways of determining whether the approach of the rabbinic material would have been normal before 70&#160;<span class="OT-All-Small-Caps">AD</span>. They are near-contemporary sources compared to the rabbinic material and contain more “normal-life” descriptions.</p>
</div>
<div id="footnote-099" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-099-backlink">254*</a><a id="_idTextAnchor445"></a>The discussion in this chapter has touched mainly on customs of separation between men and women and the manner in which a religious leader like Jesus or a scribe-rabbi would have included women in instructional situations. The reason for this has been primarily because this is the area which is most commonly given as illustration of Jesus’ revolutionary approach, mainly on the strength of the comparison with rabbinic materials. To raise the question about how Jesus approaches the halachic questions about women in regard to the law and to religious status would be more significant (cf. Chapter Six, pp.&#160;[151](#_idTextAnchor280)<span class="No-Break">–</span>[<span class="No-Break">152</span>](#_idTextAnchor281)). Would he, for instance, have accepted the view that women were not fully obligated to public worship? Would he have accepted the principle that women are only obligated to duties that did not occur at set times?</p>
<p class="FOOTNOTES_Footnote-Next">The answer is not easily given here. There is no widely accepted comprehensive scholarly treatment of Jesus’ approach to what could be understood as the common law of his time in religious matters. This is partly due to the difficulties in establishing what was the common law of his day in religious matters and in knowing how much of the rabbinic material is representative of earlier common law and not just Pharisaic or later developments (see Neusner, <span class="Italic-Caption">Rabbinic Traditions</span>, pt.&#160;3, 239<span class="No-Break">–3</span>13). Probably Jesus accepted common law and abided by it. Even his teaching on purity in <a id="_idIndexMarker604"></a>Mark 7:1<span class="No-Break">–2</span>3 does not necessarily imply that he would have taught his followers to disregard basic laws of purity in ritual situations (see David Flusser, <span class="Italic-Caption">J</span>é<span class="Italic-Caption">sus</span> [Paris: Editions du Seuil, 1970], 49<span class="No-Break">–5</span>3). On the other hand, we could well expect him to view the common law in a different framework than many of his contemporaries. His message of repentance and preparation for the kingdom and his baptism were for all the people—men and women alike, Pharisee and “sinner” alike. He desired to restore Israel to its condition before the onset of hardness of heart, to God’s purpose from “the beginning.” Hence we might well say that “neither male nor female” was a reflection of Jesus’ teaching as well as Paul’s.</p>
<p class="FOOTNOTES_Footnote-Next">Such a view, in addition, would raise the question of whether Paul himself would have accepted the normal Jewish common law of his time as it dealt with women and religious matters as something obligatory for the circumcised. Would he, in other words, have expected Jewish Christians, at least Jewish Christians in Palestine, to have observed the normal Jewish interpretation of what was obligatory for men and women? There is no well worked-out view of how Jewish Christians would have approached the halacha in various areas. We can only surmise that it must have been different from the way Pharisees approached the halacha and been somewhat different from the later rabbis, without always being able to specify the differences. However, there is a good chance that Paul would have expected Jewish-Christians to follow the normal common law approaches. If that were the case, the approach of Jesus and Paul to the status of women would have been identical, and everything that was said in Chapter Six would hold of Jesus as well.<a id="_idTextAnchor446"></a></p>
</div>
</div>
