# The Scrip&#173;tural Teaching in Contem&#173;porary Society {-}

<h1 class="HEADS---SUBHEADS_Part-Number">3</h1>
<h1 id="_idParaDest-67" class="HEADS---SUBHEADS_Part-3-Title"><a id="_idTextAnchor662"></a>The Scrip&#173;tural Teaching in Contem&#173;porary Society</h1>
</div>
<div>
<p class="BODY-STYLES_Part-Opening"><span>▸&#160;&#160;</span><span class="Opening-Drop-Words">The first part of this book</span> studied the scriptural teaching on men’s and women’s roles and concluded that the scripture enjoins a role difference between men and women. The second part assessed the scriptural teaching and concluded that it is unified, authoritative, and clearly supported by Christian tradition. But times have changed, and people today face the problem of applying in the modern world a teaching that was originally given in very different circumstances. The third part of this book, then, will treat issues that affect the application of the scriptural teaching today.</p>
<p class="BODY-STYLES_Body">In order to deal with the question of the applicability of the scriptural teaching, an assessment has to be made of the difference between the world of the New Testament and the modern world. Chapters Sixteen and Seventeen will take up the question of whether there is something about the sexual differentiation of the human race that has not changed with the passage of time. These chapters will primarily consist of a survey of the social scientific evidence for the differences between men and women. Chapters Eighteen and Nineteen will consider those aspects of society which have changed in the past two thousand years. They will examine the changes technological society has produced in both social circumstances and the way modern people think about social life. Finally, Chapter Twenty will discuss the principles that should be followed in applying the scriptural teaching to new circumstances. Part Four will then proceed to apply the scriptural teaching on men’s and women’s roles to Christian life in the modern world.&#160;&#160;▸</p>
</div>
