# Men’s and Women’s Differ&#173;ences&#160;&#160;▹&#160; Social Structural Charac&#173;teristics

<p class="BODY-STYLES_Chapter-Opening"><span class="Drop-Cap"><a id="_idIndexMarker874"></a></span><span class="Drop-Cap">M</span><span class="Opening-Drop-Words">en and w</span><span class="Opening-Drop-Words">omen</span> differ as individuals. They differ in the way they manifest traits such as aggression and nurturance, and they also differ in the way these traits are structured. These differences have been described and documented in Chapter Sixteen.</p>
<p class="BODY-STYLES_Body">Such individual differences—in traits and trait-patterns—are very useful, but they are only some of the many differences between men and women. Men and women cannot be adequately described, analyzed, and tested solely as individuals outside of their social context. One must also study the regularities men and women exhibit when engaged in the social fabric of daily life. These observations will yield a new set of important differences between men and women—differences in social structural characteristics. These are differences which emerge in the course of social interactions in groups. They are not always visible in observations of individual behavior.</p>
<p class="BODY-STYLES_Body">Social structural differences between men and women have been studied in two main ways: cross-cultural studies and psychological or sociological studies of group behavior. The cross-cultural study involves description of those roles and expressions of roles consistently assigned to men and women in all cultures. Anthropological field studies and historical sources reveal a large number of cross-cultural uniformities in the patterning of men’s and women’s roles. These uniformities show that men and women consistently differ, not only in individual traits and trait-patterning, but also in the structure of their social relations. The second type of investigation of social structural characteristics is the psychological or sociological study of group behavior. These studies show that all-male groups, all-female groups, and mixed groups differ considerably in their internal structure. In addition, ethological data obtained by methods similar to the two main types of investigation confirm these studies of human social structural characteristics. In short, all of this data together draws a helpful picture of the way men and women differ in their social structural characteristics.</p>
<p class="BODY-STYLES_Body">This chapter will examine data drawn from both cross-cultural studies and studies of group behavior as well as data drawn from ethological research. It will then present the various hypotheses which have been offered as explanations for this data. Finally the chapter will review the last two chapters and summarize the implications of social scientific research for a Christian approach to men’s and women’s roles in the twentieth century.</p>
<h2 id="_idParaDest-73" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor767"></a><a id="_idIndexMarker875"></a>The Social Structural Patterns of Men and Women</h2>
<h3 class="HEADS---SUBHEADS_Subsubhead-After-Subhead"><a id="_idIndexMarker876"></a><a id="_idIndexMarker877"></a><a id="_idIndexMarker878"></a><a id="_idTextAnchor768"></a>Consistent Cross-Cultural Patterns</h3>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">Knowledge</span> of other cultures has increased dramatically in the past hundred years. Anthropologists have studied the cultures of primitive peoples extensively, while the discipline of archaeology has developed methods of studying the earliest human societies. The new knowledge has often conveyed an impression of the stunning diversity of human life. What Western society has regarded as normative and universal often proves to be a unique practice or custom of Western culture. One example of this is the supernatural and corporate mentalities of primitive peoples.<a id="_idTextAnchor769"></a><span class="Endnote-Ref">[1](#_idTextAnchor1733)</span> Primitive peoples tend to view the world without clear-cut distinctions between the natural and supernatural and between the individual and the community. The modern Western mind finds it difficult to grasp this way of looking at the world, but the obstacle is largely the individualistic, naturalistic Western cultural mentality—a point of view which is not shared by other peoples. Similarly, studies have demonstrated a wide variety of expressions of family life from culture to culture, many of them drastically different from the independent nuclear family system of technological society.<a id="_idTextAnchor770"></a><span class="Endnote-Ref">[2](#_idTextAnchor1734)</span> Some family systems are polygamous, some monogamous, and a few polyandrous. Some societies trace descent through the father, some through the mother, while others trace it bilaterally. In some cultures a newly married couple lives with the man’s family (patrilocal residence); in others they live with the woman’s family (matrilocal residence); in still others they immediately establish their own residence (neolocal residence). Significant variations can also be observed in the expression of men’s and women’s roles. An activity (for example, painting) reserved for one sex in one society may be forbidden to that sex in another, and practiced by both sexes in still another.<a id="_idTextAnchor771"></a><span class="Endnote-Ref">[3](#_idTextAnchor1735)</span> Cultures also differ in the degree of female involvement they permit in political and economic affairs and the degree of male involvement in domestic duties such as childrearing. It is no wonder that anthropological evidence can create an impression of unlimited cultural diversity.</p>
<p class="BODY-STYLES_Body-SA"><a id="_idTextAnchor772"></a>Nevertheless, some human practices remain the same. Though cultures develop men’s and women’s roles differently, a careful examination of the anthropological evidence reveals that several significant underlying patterns can be discovered in all human societies. Four patterns appear to be especially significant:</p>
<p class="BODY-STYLES_L-O-Num-L1-1st"><span class="Body-List-Counter-Float">1.</span><a id="_idIndexMarker879"></a><span class="Italic">Sexual division of labor</span>. In every known society, past or present, the primary tasks of men and women are different. In his review of the anthropological literature related to men’s and women’s roles, Roy D’Andrade describes the pattern clearly: “One well-documented finding about behavioral sex differences is that men and women not only tend to perform different activities in every culture, but that men tend to perform particular types of activities and women to perform others. This division of labor is especially sharp for subsistence and other economic activities.”<a id="_idTextAnchor773"></a><span class="Endnote-Ref">[4](#_idTextAnchor1736)</span> Though the specific tasks assigned to men and women are not completely consistent from culture to culture (much consistency does exist), the fact that men and women perform different functions is a cross-cultural universal.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">2.</span><a id="_idIndexMarker880"></a><span class="Italic">Complementary roles in the communal and domestic spheres.</span> Men bear primary responsibility for the larger community. Women bear primary responsibility for domestic management and rearing of young children. Every known society, past or present, assigns to the men a primary responsibility for the government of the larger groupings within the society, and assigns to the women a primary responsibility for the daily maintenance of the household unit and the care of the younger children.<a id="_idTextAnchor774"></a><span class="Endnote-Ref">[5](#_idTextAnchor1737)</span> As stated by <a id="_idIndexMarker881"></a>Michelle Rosaldo, “.&#160;.&#160;.&#160;an opposition between ‘domestic’ and ‘public’ provides the basis of a structural framework necessary to identify and explore the place of male and female in psychological, cultural, social, and economic aspects of human life. ‘Domestic,’ as used here, refers to those minimal institutions and modes of activity that are organized immediately around one or more mothers and their children; ‘public’ refers to activities, institutions, and forms of association that link, rank, organize, or subsume particular mother-child groups. Though this opposition will be more or less salient in different social and ideological systems, it does provide a universal framework for conceptualizing the activities of the sexes.”<a id="_idTextAnchor775"></a><span class="Endnote-Ref">[6](#_idTextAnchor1738)</span> The degree of differentiation of male and female responsibility among communal/household lines varies from culture to culture. In almost all cultures, the father of a family or a father-surrogate exercises an overall responsibility for the family, and involves himself personally in the household life. In some cultures, women are allowed to participate actively in economic and political affairs. However, the general underlying pattern emerges universally regardless of the variations in expression.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">3.</span><a id="_idIndexMarker882"></a><span class="Italic">Some form of female subordination to the male.<a id="_idTextAnchor776"></a></span><span class="Endnote-Ref">[7](#_idTextAnchor1739)</span> In every known society, past or present, the female is in some sense subordinate to the male. As stated by <a id="_idIndexMarker883"></a>Sherry Ortner, “I would flatly assert that we find women subordinate to men in every known society. The search for a genuinely egalitarian, let alone matriarchal, culture has proved fruitless.”<a id="_idTextAnchor777"></a><span class="Endnote-Ref">[8](#_idTextAnchor1740)</span> This subordination is found on two levels. First, the females are subordinate to the male governing of the communal structures. The “public” sphere, which includes the exercise of overall governmental authority, is the domain of males in every known society. Secondly, females are also customarily subordinate to males on a more personal level within the family. In all known societies, women are personally subordinate to a husband, father, uncle, or other male figure.<a id="_idTextAnchor778"></a><span class="Endnote-Ref">[9](#_idTextAnchor1741)</span> This second type of subordination is usually minimal in societies in which adult males play only a peripheral role in family life, but it usually has at least some symbolic expression even in these societies. Personal subordination in the home appears to be related to communal subordination in the larger society. If the men are to effectively govern the society as a whole, they must also have some authority over the women who are managing the household units which make up the society. Once again, cultures express female subordination differently. However, the underlying pattern of female subordination is the same.</p>
<p class="BODY-STYLES_L-O-Num-L1-SA"><span class="Body-List-Counter-Float">4.</span><a id="_idIndexMarker884"></a><span class="Italic"><a id="_idTextAnchor779"></a>Cultural expression of gender differences between men and women</span>. Every known culture, past or present, includes some expressions of gender differences between men and women in its customs and traditions. Men and women dress differently, develop different character traits, and express respect with different customs. As stated by van&#160;den&#160;Berghe, “It seems that virtually all societies, not content with the moderate amount of sexual dimorphism with which we are born, further stress sex role differentiation through highly visible social means. Clothing styles stand out most obviously, but even in societies in which nudity or near nudity is the rule, gender differences are visibly expressed through body adornment such as tattooing, scarification, jewelry, tooth mutilation, and the like. .&#160;.&#160;. Beyond differences in dress and body adornment, sex roles are also symbolically differentiated in most societies through a combination of rituals, taboos (for example, menstrual or post partum), spatial segregation (separate sleeping quarters, men’s clubs), and rules of etiquette (for instance, ‘chivalry’ and ‘gallantry’ in the Western tradition).”<a id="_idTextAnchor780"></a><span class="Endnote-Ref">[10](#_idTextAnchor1742)</span> Some modern societies which have an ideological commitment to reduce male-female differentiation try to keep these cultural expressions to a minimum. For example, in China men and women dress in nearly identical ways.<a id="_idTextAnchor781"></a><span class="Endnote-Ref">[11](#_idTextAnchor1743)</span> However, even these modern societies include some ways of expressing gender differences between men and women.<a id="_idTextAnchor782"></a><a id="_idTextAnchor783"></a></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker885"></a><a id="_idTextAnchor784"></a>Some people respond skeptically to these assertions because they have a vague notion that some societies have been “matriarchal”—that is, the governing authorities have been women. However, anthropologists unanimously dismiss matriarchy as a characteristic of any known society, present or past. As stated by Rosaldo, “The issues involved here are complex, but the evidence of contemporary anthropology gives scant support to an argument for matriarchy.”<a id="_idTextAnchor785"></a><span class="Endnote-Ref">[12](#_idTextAnchor1744)</span> There are two main reasons for the persistent confusion about matriarchy. First, some primitive tribes have myths which tell of a time in their ancient past when women ruled. Anthropologists now generally regard these myths as justifications for some current aspect of the tribal life, such as male authority, and not as historically reliable tradition.<a id="_idTextAnchor786"></a><span class="Endnote-Ref">[13](#_idTextAnchor1745)</span> Myths about Amazonian warrior women are also considered unhistorical by anthropologists. Secondly, anthropologists once used the term “matriarchy” to describe societies which are today called matrilineal or matrifocal.<a id="_idTextAnchor787"></a><span class="Endnote-Ref">[14](#_idTextAnchor1746)</span> Matrilineal societies are those which trace lineage through the mother and not the father. Matrifocal societies are those in which the female role receives special attention and honor. Modern anthropologists no longer use the term “matriarchal” to describe these societies precisely because it implies that the women of the society actually govern the overall life of the group. In fact, men are the overall governing authorities in both matrilineal and matrifocal societies. Thus, the idea that matriarchal societies did or do exist is a popular misunderstanding, and a notion that modern anthropologists reject.<a id="_idTextAnchor788"></a></p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker886"></a>Diversity of Cross-Cultural Patterns</h3>
<p class="BODY-STYLES_Body-NI">While there is substantial anthropological evidence for these four universal patterns of men’s and women’s roles, one must still be impressed at the great variety of ways societies develop their patterns of men’s and women’s roles. Often this impression of variety does not concern the underlying approaches to men’s and women’s roles, but rather the distinctive elements of cultural expression in different societies. For example, customs of respect and honor between men and women are a feature of most cultures, but the particular expressions can be utterly different. A bow, a deferential silence, a recited prayer, a gift—all these can be expressions of respect in the symbolic language of different cultures. Like the spoken language, these symbols of respect will seem utterly different to the observer who does not know what they mean. However, two very different actions in two different cultures may express an identical social role or relationship, just as the same meaning can be expressed in two very different languages.</p>
<p class="BODY-STYLES_Body">Nevertheless, it must be acknowledged that diverse cultural expressions do not explain all the variety among various cultures in the fashioning of men’s and women’s roles. At times different customs do express different content; cultures do sometimes differ substantively from one another in their approaches to men’s and women’s roles. The four patterns described above always emerge, but with different emphasis. The diversity of cultural patterns for the roles of men and women is caused by the diversity of geographic, social, economic, political, and ideological forces operating within a society. These forces never totally erase the four cultural universals: sexual division of labor; different spheres of responsibility; female subordination and male government; and cultural expressions of distinct roles for men and women. However, these forces do determine the emphasis each of the four patterns will receive. Anthropologists have identified five environmental factors which appear especially significant. These are: (1)&#160;type of descent group, (2)&#160;type of economic system, (3)&#160;male absenteeism, (4)&#160;social complexity (including the scope and complexity of governmental institutions and technological development), and (5)&#160;religious and ideological commitment. To understand how societies develop the four universal patterns of men’s and women’s roles, these five factors must be understood.</p>
<p class="HEADS---SUBHEADS_Subsubsubhead-Paragraph"><span class="Semibold"><a id="_idIndexMarker887"></a><a id="_idIndexMarker888"></a></span><span class="Semibold">1. Descent Group Structure&#160;</span>▹ The nature of a society’s descent group structure greatly affects its pattern of men’s and women’s roles. Matrilineal societies—those which trace descent through the mother—tend to place less emphasis on male authority and often foster stronger personal relationships among women than patrilineal societies.<a id="_idTextAnchor789"></a><span class="Endnote-Ref">[15](#_idTextAnchor1747)</span> This is especially true when the residence pattern is matrilocal—where husband and wife live with the wife’s family. In such societies, the woman’s brother rather than her husband often becomes the key bearer of familial authority and position, though the woman does not live with him. The matrilineal, matrilocal system promotes female solidarity because a new wife will remain in the same household as her mother and sisters. The system avoids the competitive female relationships which exist under the patrilocal system when a new wife enters the household of her husband’s mother. However, the matrilineal system has other relationship conflicts caused by awkward and inconvenient organization of authority relationships, and is therefore far less common than the patrilineal descent system.<a id="_idTextAnchor790"></a><span class="Endnote-Ref">[16](#_idTextAnchor1748)</span> The authority of males in the family and the larger society still exists in the matrilineal system. It merely operates through different and more awkward channels than in patrilineal systems.</p>
<p class="HEADS---SUBHEADS_Subsubsubhead-Paragraph"><span class="Semibold">2. Economic System&#160;</span>▹ A society’s economic system also influences its form of men’s and women’s roles.<a id="_idTextAnchor791"></a><span class="Endnote-Ref">[17](#_idTextAnchor1749)</span> A subsistence economy which demands that men work together in close-knit collective groupings usually leads to a greater emphasis on male authority and more explicit customs of respect. Cultures which rely primarily on agriculture or pastoral labor usually fall within this category. Those forms of subsistence which demand less male interaction and cooperation and more interaction and cooperation among women and between men and women usually lead to a less intense focus on male authority. Horticulture is an example of such an economic system.<a id="_idTextAnchor792"></a><span class="Endnote-Ref">[18](#_idTextAnchor1750)</span> The locus of ownership and control of the key economic materials of a society also influences the shape of men’s and women’s roles. In some societies, women formally own land, houses, and other domestic property and play an important role in the larger economy. All of these economic factors seem to correlate highly with the type of descent grouping found in a society. That is, societies which depend heavily upon horticulture or those in which women own domestic property are often matrilineal in descent group structure. However, it must be emphasized again that “matrilineal” does not mean “matriarchal.” Regardless of the type of descent group structure or economic system, males still hold the overall governing positions, and the four universal patterns still exist.</p>
<p class="HEADS---SUBHEADS_Subsubsubhead-Paragraph"><span class="Semibold"><a id="_idIndexMarker889"></a></span><span class="Semibold">3. Male Absenteeism&#160;</span>▹ A third factor influencing a society’s form of men’s and women’s roles is male absenteeism.<a id="_idTextAnchor793"></a><span class="Endnote-Ref">[19](#_idTextAnchor1751)</span> In some societies most men are regularly absent from the family for extended periods of time. The economic structure of the society may require the men to travel long distances to work, and therefore to regularly reside apart from their families, as in some Indonesian tribes.<a id="_idTextAnchor794"></a><span class="Endnote-Ref">[20](#_idTextAnchor1752)</span> The men may engage in so much warfare that they are gone much of the time, as among the Iroquois or the ancient Spartans.<a id="_idTextAnchor795"></a><span class="Endnote-Ref">[21](#_idTextAnchor1753)</span> External pressures may cause a form of social disorganization in which the men no longer assume family roles, as in the Black American ghetto culture.<a id="_idTextAnchor796"></a><span class="Endnote-Ref">[22](#_idTextAnchor1754)</span> When the men are absent—for whatever reason—women must assume many of the male roles within the family. Female dominance and aggressiveness appear to increase in such situations. The men still govern the group as a whole, but their relationships with their women and families are brittle and unstable.</p>
<p class="HEADS---SUBHEADS_Subsubsubhead-Paragraph"><span class="Semibold"><a id="_idIndexMarker890"></a></span><span class="Semibold">4. Social Complexity&#160;</span>▹ A fourth factor influencing the form of men’s and women’s roles is the degree and scope of social complexity. This factor is actually a number of intimately related sociological, economic, political, and technological factors. The generalization which appears to emerge from these factors is this: The more complex the society, the more pronounced are the four universal patterns of men’s and women’s roles. The simpler the social system, the less pronounced are those patterns. (It should be pointed out immediately that the latter phase of technological society represents one significant exception to this generalization.)<span class="Footnote-Ref"><span id="footnote-139-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-139">*</a></span></span></p>
<p class="BODY-STYLES_Body">At least one reason for this correlation can be easily understood. Cultures with very rudimentary forms of social organization simply lack a means to strongly and clearly express distinct roles. Eskimo culture is an example. Elements of distinct and complementary roles are present, but, in a society so close to the margin of physical survival, practical considerations take precedence over expressions of role difference.<a id="_idTextAnchor797"></a><span class="Endnote-Ref">[23](#_idTextAnchor1755)</span> More complex societies with more developed spheres of social and economic life are better equipped to express complementary sex roles. As will be seen later, complex “traditional” (but non-technological) societies have found great practical use for distinct and complementary sex roles.</p>
<p class="BODY-STYLES_Body">In fact, the absence of a strong correlation between social complexity and distinct roles in advanced technological society can perhaps be partly understood in precisely these practical terms. Distinct sex roles serve useful functions in advanced non-technological traditional societies, but their advantage is less obvious in technological societies. There are few practical advantages to large families in an economy shaped by advanced technology. The services rendered by the large bureaucratic institutions of technological society have also replaced the family’s traditional educational, welfare, and health functions. Thus patterns such as division of labor by sex, male authority, complementary roles, and expressions of respect and deference fulfill fewer functions in technological society than they do in pre-technological or nascent technological societies.<a id="_idTextAnchor798"></a><span class="Endnote-Ref">[24](#_idTextAnchor1756)</span></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker891"></a><a id="_idTextAnchor799"></a>Michelle Zimbalist Rosaldo, an anthropologist, has proposed a theory which promises a comprehensive explanation of the relationship between social complexity and men’s and women’s roles.<a id="_idTextAnchor800"></a><span class="Endnote-Ref">[25](#_idTextAnchor1757)</span> Rosaldo suggests that there is a correlation between female subordination and the degree of separation between the public and private spheres of a society’s life. She suggests that female subordination is stronger and relationships among women less cohesive in those societies which demonstrate a greater separation of public and private spheres; roles are less distinct, male authority is less emphasized, and female relationships are more amiable and durable in those societies which tend to merge public and private spheres. In Rosaldo’s terms, “public sphere” means the world of religion, business, politics, and communal life, while “private sphere” means the life of a family or household.</p>
<p class="BODY-STYLES_Body">Rosaldo suggests that as societies divide into distinct and increasingly separate public and private spheres, men tend to predominate in the public sphere and women tend to predominate in the private sphere. The essence of her theory is that men’s and women’s roles vary according to the relationship of the household to the larger communal life of the society. Primitive societies tend to merge the household with the public sphere, and the patterns of men’s and women’s roles tend to be similarly merged. These patterns tend to be more distinct in societies which sharply distinguish the household from the public sphere of social life.</p>
<p class="BODY-STYLES_Body">Rosaldo’s theory may also explain the apparent anomaly—technological society. In most primitive societies, public and private spheres are merged because the public sphere hardly exists. In more complex societies, the public communal sphere expands in significance, and becomes distinct from the world of family. Among the middle class in the nascent technological society of Victorian England, the public and private spheres became almost completely detached from one another, though the private domestic sphere maintained some strength. This gulf between the two spheres may explain the traditional Victorian bourgeois approach to men’s and women’s roles, which represents one of the more rigid cultural manifestations of the four universal patterns.<a id="_idTextAnchor801"></a><span class="Endnote-Ref">[26](#_idTextAnchor1758)</span> However, as technological society develops, the private domestic sphere begins to lose its vitality as the public sphere expands and dominates more of human social existence. Ironically, technological society and primitive society both achieve a unity of public and private spheres. Primitive society does so by diminishing the public sphere to a minimal level. Technological society achieves a similar unity by diminishing the private domestic sphere to a minimal level. Those functions once assigned to the private sphere—education, health care, insurance, and so forth—are transferred to the public world of mass institutions. The anomalous position of advanced technological society may therefore be explained by the correlation between social complexity and men’s and women’s roles in the public and private spheres.<a id="_idTextAnchor802"></a></p>
<p class="HEADS---SUBHEADS_Subsubsubhead-Paragraph-SA"><span class="Semibold">5. Religion and Ideology&#160;</span>▹ A fifth factor influencing the shape of men’s and women’s roles in a society is the presence of culturally sanctioned religious or ideological commitments.<a id="_idTextAnchor803"></a><span class="Endnote-Ref">[27](#_idTextAnchor1759)</span> Some traditional religious systems, such as Islam, buttress a particular social structure and pattern of men’s and women’s roles. When such a religion is a vital and dynamic element in the culture, there will be little radical variation from the prescribed social pattern. For example, a strong form of female subordination and distinct sexual roles arises in most societies which hold to a traditional form of Islam. By contrast, modern ideologies such as Socialism and Communism include a commitment to equality in the relations between men and women, a commitment most often interpreted as meaning the elimination of distinct social roles. Such ideologies can lead to considerable changes in family structure, as has occurred in the Soviet Union, China, and the Israeli Kibbutzim.</p>
<p class="BODY-STYLES_Body-NI">Descent group structure, economic system, male absenteeism, social complexity, and religious or ideological commitment all influence the pattern of men’s and women’s roles in a society. An understanding of these influences is important for several reasons. First, these factors must be taken into account in any effort to apply scriptural teaching on men’s and women’s roles to modern societies. The remaining chapters of this book will be largely concerned with examining the environment of the modern world in relation to men’s and women’s roles. Special attention will be paid to the influence of technological society and modern ideologies. Secondly, an understanding of these influences explains much about the great variety of cultural approaches to men’s and women’s roles. Such variety is the inevitable consequence of variety in economic, sociological, political, technological, and ideological systems. Thirdly and finally, an understanding of these influences places the four universal patterns of men’s and women’s roles in their proper context. In many societies the descent group structure, economic system, degree of male absenteeism, level of social complexity, and ideological commitment do not favor the expression of these four patterns. In fact, one could even say that these factors at times actively work against the expression of sexual division of labor, division of sphere, female subordination, and the development of distinctive dress, character traits, and customs of honor and respect. Nevertheless, these patterns always appear; they tenaciously resist extinction. They appear in all societies, though sometimes in a subdued form. The strength of these patterns can best be appreciated in the light of the environmental forces which work against them.</p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idTextAnchor804"></a>The Strength of the Cross-Cultural Patterns</h3>
<p class="BODY-STYLES_Body-NI"><a id="_idIndexMarker892"></a>The tenacity of these four patterns of men’s and women’s roles in the midst of a hostile environment is especially visible in the light of opposing ideology. The Soviet Union, the People’s Republic of China, and the Israeli Kibbutzim have all embraced radical programs intended to bring social equality among men and women.<a id="_idTextAnchor805"></a><span class="Endnote-Ref">[28](#_idTextAnchor1760)</span> In these societies, Socialist or Communist ideology have at one time or another directly attacked each of the four universal patterns—division of labor by sex, complementary roles in the communal and domestic spheres, female subordination, and the cultural expression of men’s and women’s roles. Indeed, in important respects, men’s and women’s roles in these societies have been changed. Men and women in these societies live much differently today than they did in pre-Communist China or Russia or in traditional Jewish society. The changes have been particularly marked in China, for women and their social role had little respect in traditional Chinese society in comparison to other traditional societies. While Chinese Communist propaganda about the “bitter past” cannot be accepted on face value, it is certain that Chinese women no longer occupy such a role today. Significant, though not quite so striking, changes in the roles of men and women have also occurred in the Soviet Union and the Kibbutzim. However, despite these changes, the four universal patterns are preserved intact in all three societies. Neither Russia, China, nor the Kibbutzim have eliminated a sexual differentiation of labor. Women have greater job opportunities, but a division of labor still exists. Men still dominate the higher echelons of government, education, and the professions; women still dominate the care of children, though sometimes within a childcare institution rather than the family. There is still some sense of female subordination, though the ideological stand continues to assail it. There are still cultural expressions of men’s and women’s roles. It might be added that modern revolutionary societies such as Russia, China, and the Kibbutzim are better equipped than any previous societies to succeed in efforts to eradicate traditional social patterns. They possess new tools of propaganda such as mass state-controlled education, a new ideology which seeks to replace traditional social controls such as religion, and economic development plans which disrupt patterns of traditional life. Nevertheless, the universal patterns of men’s and women’s roles reassert themselves. They appear even in the midst of those societies which are earnestly seeking to undermine them.</p>
<p class="BODY-STYLES_Body">The Kibbutzim present an especially important subject for study.<a id="_idTextAnchor806"></a><span class="Endnote-Ref">[29](#_idTextAnchor1761)</span> Their potential to successfully reshape the roles of men and women is greater than either Communist China or the Soviet Union. The Kibbutz groupings are small, and thus are simpler and more manageable than a nation-state. Membership in the Kibbutzim is voluntary; and those who dislike the lifestyle can (and do) leave at any time. This ensures that the Kibbutz members will have a consistent and firm commitment to the ideals of the Kibbutz. Coercion is almost never necessary. Serious social problems rarely occur. The Kibbutzim need not deal with political subversion, criminality or insanity. Most men and women joining a Kibbutz have broken previous ties and are explicitly seeking to create a new society. Thus the Kibbutzim are in an excellent position to immediately establish a radical social policy regarding the family. The early founders of the Kibbutzim theoretically and practically dismantled the family unit. Children were reared corporately in common childcare facilities. Men and women shared an equal proportion of the labor of the Kibbutz and everyone had equal opportunity to share in the overall government of the group.</p>
<p class="BODY-STYLES_Body">The Kibbutzim are also important because social scientists have studied them adequately. Western social scientists do not have accurate and thorough data on the social life of Communist countries, especially Communist China. Governments of these countries generally forbid firsthand sociological study by Westerners, and official statistics and information are notoriously unreliable. Indeed, even if sociologists could freely study Russian and Chinese family life, the sheer size of the samples would complicate the researcher’s task. In contrast, the Kibbutzim present miniature societies suitable for study and open to objective research. They are the best laboratories for assessing the success of a powerful and determined attempt to alter the universal patterns of men’s and women’s roles.</p>
<p class="BODY-STYLES_Body">In their book <span class="Italic">Women in the Kibbutz</span>, Lionel Tiger and Joseph Shepher report on their research into the current social structure of the Kibbutzim. Their research has been extensive, employing computer analysis and other sociological techniques. Their results are extremely significant. Tiger and Shepher show that the universal patterns have once again appeared despite the Kibbutzim’s commitment to eliminate them. A division of labor exists in most occupations.<a id="_idTextAnchor807"></a><span class="Endnote-Ref">[30](#_idTextAnchor1762)</span> Certain tasks are viewed as male, others as female. Men hold most high political positions. Women prefer to care for children, especially their own children. The women have begun to pressure the Kibbutzim authorities—mostly men—to allow greater parental involvement in childrearing. The men appear to resist this trend and to reassert the Kibbutz ideal of eliminating family life and the distinctive roles of men and women. But the Kibbutz women persist. As Tiger and Shepher state it, “They (the women) have acted against the principles of their socialization and ideology, against the wishes of the men of their communities, against the economic interest of the Kibbutzim, in order to be able to devote more time and energy to private maternal activities rather than to economic and political public ones. Obviously these women have minds of their own; despite obstacles, they are trying to accomplish what women elsewhere have been periodically urged to reject by critics of traditional female roles.”<a id="_idTextAnchor808"></a><span class="Endnote-Ref">[31](#_idTextAnchor1763)</span></p>
<p class="BODY-STYLES_Body">It can therefore be confidently asserted that several important patterns of men’s and women’s roles have been consistently observed in every culture yet studied. The qualification “yet studied” is added for scientific precision, but in fact the evidence implies that these patterns have existed in every human society. One should not overlook the implications of these universal patterns. A later section of this chapter will fully treat the issue of the origins of these patterns, but it can be observed here that the universality and tenacity of these patterns implies that some powerful underlying force is behind them. As <a id="_idIndexMarker893"></a>Sherry Ortner, a feminist scholar with no “biodeterminist” sympathies, states it, “The universality of female subordination, the fact that it exists within every type of social and economic arrangement and in societies of every degree of complexity, indicates to me that we are up against something very profound, very stubborn, something we cannot root out simply by rearranging a few tasks and roles in the social system, or even by reordering the whole economic structure.”<a id="_idTextAnchor809"></a><span class="Endnote-Ref">[32](#_idTextAnchor1764)</span> In short, the unanimity and strength of the data concerning universal social structural patterns makes it one of the most significant areas in the study of the differences between men and women.<a id="_idTextAnchor810"></a><a id="_idTextAnchor811"></a></p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker894"></a><a id="_idIndexMarker895"></a><a id="_idTextAnchor812"></a><a id="_idTextAnchor813"></a>Studies of Group Interaction</h3>
<p class="BODY-STYLES_Body-NI"><a id="_idIndexMarker896"></a>Sociological and psychological studies of group interaction provide another useful source of data for the study of the social structural characteristics of men and women. These studies are usually conducted on groups within a particular culture, though some include cross-cultural samples. The aim of these studies is to better understand the nature of human social interaction in various types of groupings. These studies have not been conducted as extensively as anthropological studies of the four universal patterns. However, they do strongly suggest that men and women differ from one another in the way they relate in many social contexts.</p>
<p class="BODY-STYLES_Body">Studies of group interaction have been conducted in two types of settings: the family and groups of men or groups of women. The evidence from the second type of study indicates that men relate to men differently than women relate to women.<a id="_idTextAnchor814"></a><span class="Endnote-Ref">[33](#_idTextAnchor1765)</span> All-male groups tend to be larger than all-female groups. From an early age, males tend to form large “gangs,” while females tend to form smaller groups based on intimate friendship. Men also tend to establish more hierarchical order in their relationships than women appear to do. In all-male groups, leadership roles are assumed more readily, submitted to more eagerly, and executed more effectively. This propensity for hierarchical order is probably responsible in part for the greater average size of the male groupings. Finally, all-male groups appear to involve more stable commitment and loyalty than all-female groups. They are more continuous over time and also tend to be more important to the lives of the participants.</p>
<p class="BODY-STYLES_Body">The studies of family relationships also indicate that men relate to family groupings differently than women relate to these groupings.<a id="_idTextAnchor815"></a><span class="Endnote-Ref">[34](#_idTextAnchor1766)</span> Females tend to be more oriented to people they can care for, such as children and the needy, and to people who can care for them, such as husbands, fathers, and other personal authority figures.<span class="Footnote-Ref"><span id="footnote-138-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-138">*</a></span></span> On the other hand, males are more oriented to the male peer group. As a consequence of this difference in social orientation, females tend to be more intensely loyal than the adult male members to the small care-oriented group. Male loyalty tends to be divided between the same-sex peer group and the small care group. Finally, some evidence shows that females prefer male authority to female authority. If so, then the small care group drawing the greatest female loyalty will ideally contain at least one adult male. (This assertion is consistent with the universal patterns of men’s and women’s roles discussed earlier.) To sum up, the data suggests that the small care group—the family—is the locus of greatest female loyalty and commitment, whereas the male divides his loyalty between the family and his male peer group.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker897"></a><a id="_idIndexMarker898"></a><a id="_idTextAnchor817"></a>This presentation of the conclusions of group interaction research is an attempt to concisely summarize the results of many studies of ostensibly unrelated behaviors. One of the best sources for this evidence is the book <span class="Italic">The Psychology of Sex Differences</span> by Eleanor Maccoby and Carol Jacklin. This volume, published in 1974, is a comprehensive and detailed survey of the experimental literature in regard to the differences between men and women. The authors’ conclusions sometimes seem to be determined by factors other than the data itself; nonetheless, their basic summary of the data proves very helpful.<a id="_idTextAnchor818"></a><span class="Endnote-Ref">[36](#_idTextAnchor1768)</span> Particularly helpful are their observations about the existence of social structural patterns in the research they are reviewing.</p>
<p class="BODY-STYLES_Body">Though Maccoby and Jacklin point out many of these social structural patterns, these patterns do not always emerge clearly in their analysis. The reason may be that their basic framework of analysis is mainly oriented to individual trait differences. They do not often explicitly adopt a social structural perspective in examining their data, although social structural patterns of men’s and women’s differences can be discerned in the data.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker899"></a><a id="_idIndexMarker900"></a><a id="_idTextAnchor819"></a>A good example, and one which is relevant to the current discussion, is dependence behavior. Maccoby and Jacklin examine their data on dependence behavior from an individual trait perspective: they ask, “Are women more dependent than men?”<a id="_idTextAnchor820"></a><span class="Endnote-Ref">[37](#_idTextAnchor1769)</span> They answer, “Probably not.” The data does strongly indicate that both men and women are dependent on personal relationships, and both are affected by social pressure. In this sense, women do not seem <span class="Italic">more</span> dependent than men. However, the data also shows that men and women differ significantly in the type of dependence they prefer, and in the patterns of their expression of dependence. The most important of these differences are along social structural lines. Males are more dependent in their relationships with male peers; females are more dependent in their relationships with authority figures. Men associate strongly with their male peer group and are highly subject to the influence of this group. Women prefer smaller groups, and are more subject to the influence of an authority figure. It is clear that this is an important difference between men and women, one which is strongly related to the four universal patterns of men’s and women’s roles discussed earlier.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker901"></a><a id="_idIndexMarker902"></a>Another example of an important social structural difference noted by Maccoby and Jacklin concerns aggressive behavior. As we saw in Chapter Sixteen, men consistently exhibit higher levels of aggression than women. But an equally important finding is that particular configurations of social relationships affect the way men and women express aggression. Male aggression is rarely directed against females, but is instead usually directed against other males.<a id="_idTextAnchor821"></a><span class="Endnote-Ref">[38](#_idTextAnchor1770)</span> The presence of females in a social situation also affects the way men express aggression. Some element in the dynamic of male-female relationships inhibits aggression, and some element in the dynamic of all-male groups tends to release it. In other words, a social structural element is at work in the expression of this trait. This social structural element is at least as important in the understanding of aggressive behavior as is an understanding of the trait itself.</p>
<p class="BODY-STYLES_Body">Maccoby and Jacklin detect similar social structural differences in the studies of almost every personality variable which they survey. The key variable causing different patterns of social expression between men and women appears to be the nature of the group confronted: Is it a same-sex group or a mixed group? Does it include an authority figure or people in need? Such social structural differences between men and women appear in studies of compliance, dominance, affiliation, activity rates, achievement orientation, competition, and task and person orientation.<a id="_idTextAnchor822"></a><a id="_idTextAnchor823"></a><span class="Endnote-Ref">[39](#_idTextAnchor1771)</span></p>
<p class="BODY-STYLES_Body">Thus the data drawn from studies of social interaction highlights the importance of social structural characteristics. As mentioned earlier, this data can be organized and summarized in the form of observations concerning peer relationships and family relationships.<a id="_idTextAnchor824"></a></p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker903"></a><a id="_idIndexMarker904"></a><a id="_idTextAnchor825"></a>Evidence from Ethology</h3>
<p class="BODY-STYLES_Body-NI">Cross-cultural studies and group interaction studies provide most of the evidence which is useful for understanding the social structural characteristics of men and women. However, a new and expanding discipline known as ethology also provides helpful supporting evidence.<a id="_idTextAnchor826"></a><span class="Endnote-Ref">[40](#_idTextAnchor1772)</span></p>
<p class="BODY-STYLES_Body">Ethology is the study of the social behavior of non-human animal species. It utilizes methods similar to those examined in the previous pages of this chapter—comparative cross-species studies and group interaction studies. Those who relate ethological data to human social life are especially interested in the study of primates, for primate species resemble human beings more closely than do other species. Many connections have been made between human social behavior and primate social behavior. Nonetheless, the ethological evidence as a whole does not contribute anything strikingly new to an understanding of social structural patterns in humans. Its value consists mainly in the support that it gives to the evidence from human studies.</p>
<p class="BODY-STYLES_Body-SA">As one would expect, the ethological studies reveal a great diversity of social structures among animal societies. Variety is found in the amount and complexity of social behavior as well as in the particular structural arrangements from species to species.<a id="_idTextAnchor827"></a><span class="Endnote-Ref">[41](#_idTextAnchor1773)</span> However, several nearly uniform patterns underlie this variety among animal societies, just as they do among human societies. Among mammals, five significant patterns should be noted:</p>
<p class="BODY-STYLES_L-O-Num-L1-1st"><span class="Body-List-Counter-Float">1.</span><span class="Italic">A directive, aggressive, protective male role.<a id="_idTextAnchor828"></a></span><span class="Endnote-Ref">[42](#_idTextAnchor1774)</span> In most species the males assume a position of overall direction and protection. This characteristic is strongly pronounced among primate species, but it is common in many other species as well.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">2.</span><span class="Italic">Distinct male and female peer groupings.<a id="_idTextAnchor829"></a></span><span class="Endnote-Ref">[43](#_idTextAnchor1775)</span> Apart from the sexual relationship, males and females in many species segregate into distinct social groupings. Once again, this pattern appears most strongly and consistently among primates, but it is present in many other species as well.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">3.</span><span class="Italic">Formation of male-dominance hierarchies.<a id="_idTextAnchor830"></a></span><span class="Endnote-Ref">[44](#_idTextAnchor1776)</span> In many species, and in almost all primate species, the males vie with one another for leadership and the privilege of breeding with particular females. Out of this competition emerges a stable hierarchy of rank and privilege. Such a hierarchy of males often forms the core leadership of the group.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">4.</span><span class="Italic">A female maternal role.<a id="_idTextAnchor831"></a></span><span class="Endnote-Ref">[45](#_idTextAnchor1777)</span> This may be the closest to a universal mammalian pattern. Females almost always have the primary responsibility for bearing and nurturing the young. Male nurturing behavior varies from species to species. In some species the males relate extensively to the young, while in many other species the males preserve a constant distance between themselves and offspring. However, females appear to have the primary responsibility for the young in almost all mammalian species, and in most other animal species as well.</p>
<p class="BODY-STYLES_L-O-Num-L1-SA"><span class="Body-List-Counter-Float">5.</span><span class="Italic">Differential maternal response to male and female offspring.<a id="_idTextAnchor832"></a></span><span class="Endnote-Ref">[46](#_idTextAnchor1778)</span> This pattern has only become clear in recent studies of some primate species. Among those species studied, the female recognized a sex difference in her offspring, and proceeded to relate differently to the males and the females. It is not as yet known how widely this pattern recurs from species to species. However, the initial studies appear to be significant, since they reveal an explicit social structural characteristic of primate maternal behavior.</p>
<p class="BODY-STYLES_Body-NI">Each of these five patterns is directly parallel to the evidence discussed earlier concerning social structural characteristics in humans.<a id="_idTextAnchor833"></a></p>
<p class="BODY-STYLES_Body">The ethological data can be interpreted in several ways. Many scholars, applying an evolutionary perspective, see in this data support for the theory that human social structural characteristics developed from the primitive primate social structure.<a id="_idTextAnchor834"></a><span class="Endnote-Ref">[47](#_idTextAnchor1779)</span> Whatever one’s attitude toward this evolutionary hypothesis, it is clear that the ethological data, particularly from primate studies, has significance for the study of the social structural characteristics of human males and females. Analogies between primate and human behavior can sometimes help clarify patterns that are easily obscured by the complexity of human culture. In addition, when a pattern of primate behavior is found to resemble a pattern of human behavior, one can take this data as evidence that the pattern is deeply rooted in the human biological makeup. Therefore, the ethological data adds weight to the observations of human social structure from cross-cultural and group interaction studies.<a id="_idTextAnchor835"></a></p>
<p class="BODY-STYLES_Body">In fact, the evidence drawn from all of these sources proves remarkably consistent. The anthropological data, the data from studies of group interaction, and the ethological data provide a strong argument for paying serious and thoughtful attention to the social structural characteristics of men and women. Males and females differ in the way they behave in various social groups. These differences can be observed in consistent cross-cultural patterns, in narrower studies of human social interaction, and in studies of animal behavior. Examination of the individual psychological differences between men and women cannot uncover this important set of differences.</p>
<p class="BODY-STYLES_Body">At this point, the question of origins arises once again, as it did in the last chapter. What lies at the root of these social structural differences between men and women? How are the social structural characteristics of human societies related to the individual physical, intellectual, and psychological differences between men and women discussed in Chapter Sixteen? These questions must now be examined.<a id="_idTextAnchor836"></a></p>
<h2 id="_idParaDest-74" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor837"></a><a id="_idIndexMarker905"></a><a id="_idIndexMarker906"></a>Explaining the Social Structural Data</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">Much</span> of the effort to explain the strong and consistent evidence for the existence of important social structural differences between men and women has followed the classic nature/&#8203;nurture controversy. How much human behavior is programmed into the human genetic structure, making it part of human “nature”? How much behavior is learned—through early childhood training, nurturing customs, cultural conditioning, and other social and environmental factors? The different theories ascribe different degrees of biological contribution to the social structural patterns. However, it is important to note that no theory attributes all human social structural patterns purely to non-biological environmental factors. The evidence for some degree of biological influence is too strong. However, the various theories differ in their understanding of the specific mechanisms behind the development of the social structural patterns. A key question is the relationship among the individual psychological differences (such as aggression, nurturance, and visual-spatial ability), the individual physical differences (such as muscular strength and reproductive organs), and the social structural patterns. In what way are the three connected? Can any of these sets of differences be attributed directly to the action of one of the other sets?</p>
<p class="BODY-STYLES_Body">The most prominent theories which address these questions fall into four major categories. First, some social scientists explain the social structural differences as primarily caused by innate individual psychological differences. <a id="_idIndexMarker907"></a>Stephen Goldberg is a prominent advocate of this view. Goldberg begins by describing the patterns of men’s and women’s roles found in all cultures. He then presents the evidence from experimental psychology indicating a male advantage in aggression, and discusses the likelihood that male aggression is a biological fact, rooted in male hormones. Goldberg links the two sets of data together: Universal social patterns are explained in terms of male aggression. He does not say that aggression is the only significant innate individual difference between men and women. He even indicates that there are probably other important differences, such as a female advantage in nurturance. However, Goldberg maintains that his theory holds even if aggression is the only significant innate difference between men and women. Therefore, Goldberg’s formulation explains social structural differences in the following order: (1)&#160;individual psychological differences (mainly aggression); then, (2)&#160;social structural differences.</p>
<p class="BODY-STYLES_Body">A second theory is similar to Goldberg’s but adds physical differences to the chain of causation. The writings of many psychoanalysts provide the best expression of this view.<a id="_idTextAnchor838"></a><span class="Endnote-Ref">[48](#_idTextAnchor1780)</span> As described in Chapter Sixteen, psychoanalysts generally see the child’s early reaction to his sexual organs as a primary factor underlying most of the social structural and trait differences between men and women. Whether the psychoanalyst emphasizes womb envy or penis envy, the explanation of psychological differences and social structural differences follows the same order. Social structural differences between men and women are caused by either a male achievement-striving rooted in his frustration at not being able to bear children, or a female attachment to motherhood as a compensation for not having a penis. The psychoanalytic explanation adds another element to Goldberg’s chain: (1)&#160;physical differences (sexual organs); then, (2)&#160;psychological differences (achievement-striving or receptivity and an attachment to maternity); finally, (3)&#160;social structural differences.<a id="_idTextAnchor839"></a><span class="Endnote-Ref">[49](#_idTextAnchor1781)</span></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker908"></a><a id="_idTextAnchor840"></a>A third theory maintains the preeminence of the physical differences but reverses the positions of the psychological and the social structural differences. Michelle Rosaldo presents this view.<a id="_idTextAnchor841"></a><span class="Endnote-Ref">[50](#_idTextAnchor1782)</span> Rosaldo claims that the universal patterns of men’s and women’s roles spring primarily from the physical capabilities of men and women. Primitive human societies found that some group of people were needed to care for young children, and they assigned this role to women because they seemed best equipped physiologically to assume it. Women bore, fed, and raised the young children. In addition, the male’s greater size and muscular strength equipped him to be more effective in warfare and in certain types of subsistence behavior such as hunting. All the universal characteristics of men’s and women’s roles derive from this primitive division of labor. The social structure which evolved from this division of labor then socialized men and women so that their personalities and inclinations fit consistently with the structure. The sequence of causation in this theory thus follows clearly and logically: (1)&#160;physical differences (female reproductive and lactative capability; male superiority in muscular strength); lead to (2)&#160;social structural differences (men provide, defend, and govern; women manage the domestic sphere and care for the young children); finally, (3)&#160;psychological differences (differences in male and female personality).</p>
<p class="BODY-STYLES_Body">It is worth enumerating some limitations of this third theory. First, it does not take into account the most recent psychological and ethological data indicating that males and females differ biologically in significant areas other than those related to reproduction or muscular strength. Secondly, this theory does not squarely confront or explain the four universal patterns of men’s and women’s roles: the sexual division of labor, male responsibility for the community and female responsibility for the household, female subordination to the male, and cultural expression of role differences. Given the immense variety of social patterns that exist among different cultures, the universality of these patterns has great significance. Such constant and tenacious patterns cannot be adequately accounted for without positing a major biological influence.<span class="Footnote-Ref"><span id="footnote-137-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-137">*</a></span></span> Finally, the Rosaldo view does not adequately explain why these universal patterns of male-female differences persist in technological society. In modern society, small families, greater longevity, institutionalized childcare and childrearing, a predominance of jobs not demanding great muscular strength, and a liberal ideology remove much social significance from physical differences between men and women. Yet the social patterns remain, even in the face of determined efforts by socialist societies to eliminate them. Rosaldo’s hypothesis is logically constructed, and it helps point out the important impact that social structural characteristics have on individual personality. However, its ability to explain all of the evidence is limited.</p>
<p class="BODY-STYLES_Body">Despite its serious limitations, variations of the Rosaldo view are widely held, especially among those committed to an ideological viewpoint which calls for a serious reordering of traditional sexual roles. For example, an approach similar to Rosaldo’s, held by some radical feminists but rarely propounded in scholarly literature, locates the origin of the universal patterns of men’s and women’s roles exclusively in the male’s superior muscular strength.<a id="_idTextAnchor842"></a><span class="Endnote-Ref">[51](#_idTextAnchor1783)</span> According to this view, the origin of these roles was not social expedience, but the male thirst for power and prestige and his determination to prevent females from sharing this power with him. This position has a more polemical tone than the Rosaldo hypothesis. Both views are attractive to those committed to a radical feminist position. They both assert that the social structural characteristics of men and women originate in physical qualities that have little relevance in modern societies. Thus, one can easily argue that these universal social structural patterns are similarly irrelevant. In addition, both of these views perceive the psychological differences between men and women as almost totally the product of socialization and cultural conditioning. Distinct social roles, which originated either from expediency or male exploitation of females, were passed on to following generations by social processes of conditioning until the roles seemed natural, and even supernaturally preordained. Thus one can readily argue that a process of reconditioning will form male and female personalities into a pattern of roles more equitable and more expedient in modern society. One can easily see how these two explanations of male-female social structural characteristics can serve a particular ideological position. Thus, many who are committed to the ideology firmly hold to these views despite their serious limitations.<a id="_idTextAnchor843"></a></p>
<p class="BODY-STYLES_Body">To be fair, all of the three theories which attempt to explain the social structural patterns are inadequate. All contain limitations. None seems broad enough to account for all the data. Each theory attempts to explain weighty and detailed evidence by referring to only a few factors. This criticism affects the first theory least. Goldberg’s view that social structural characteristics can be explained by individual psychological differences at least leaves room for the possibility that many individual innate psychological factors lie at the root of the social structural patterns. However, even this view appears overly narrow. One would expect that many factors of many different types would underlie social patterns which are so firmly entrenched in the human species and so complex in nature. In short, the first three theories may contribute to a more comprehensive theory, but, as theories in themselves, they seem inadequate.</p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker909"></a><a id="_idIndexMarker910"></a>A Structuralist Hypothesis</h3>
<p class="BODY-STYLES_Body-NI">A fourth theory of the social structural characteristics of men and women comes closer to providing a comprehensive explanation. It could be called a “structuralist” approach. In the tradition of Gestalt theorists, structuralists focus their attention primarily on larger patterns; they find fault with the reductionist tendencies of the first three theories discussed above.<a id="_idTextAnchor844"></a><span class="Endnote-Ref">[52](#_idTextAnchor1784)</span> These three theories try to reduce social structural patterns to a simple process of causality: These patterns are <span class="Italic">caused</span> by physical and psychological differences. The three theories attribute these complex and durable structural patterns to either innate psychological differences, or to the relationship between environmental demands and simple physical capabilities. By contrast, the structuralist insists that social structural patterns be understood in their own right. To do so, the structuralist avoids attributing these patterns to other causes. He tends to view the social structural patterns independently of physical and psychological differences, and perhaps even as a cause of the psychological differences.</p>
<p class="BODY-STYLES_Body">The structuralist methodology has recently emerged as a significant intellectual force on the European continent.<a id="_idTextAnchor845"></a><span class="Endnote-Ref">[53](#_idTextAnchor1785)</span> Structuralism grows from the work of certain linguists in the early twentieth century, but has been applied to such disparate fields as anthropology, psychology, literary criticism, and biblical studies. Structuralists view all human communication and social life as systematic and ordered structures analogous to language. Like the Gestalt theorists, structuralists maintain that a whole cannot be adequately described simply by an analysis of its parts. They say that the structure or pattern which connects the parts is as important as the parts themselves. Many structuralists even assert that humans possess an innate structuring mechanism which produces regular cultural patterns. For example, Noam Chomsky, one of the more important linguists of the last twenty years, theorizes that all human languages have at their base one uniform “deep structure.” He claims that human beings have an innate capacity for structured verbal communication.<a id="_idTextAnchor846"></a><span class="Endnote-Ref">[54](#_idTextAnchor1786)</span> They are not blank slates that learn arbitrary language systems, but are programmed learners predisposed to assimilate those language structures which build upon their innate capacities. Many structuralists thus give primacy to the importance of social patterns, and accept that these patterns are part of the innate human biological endowment. The key difference between the structuralist approach and those discussed earlier is that the structuralist views social structural differences between men and women as primary phenomena. He does not necessarily attempt to explain these differences as the product of other phenomena.</p>
<p class="BODY-STYLES_Body-SA">In their joint work, <a id="_idIndexMarker911"></a>Robin Fox and <a id="_idIndexMarker912"></a>Lionel Tiger specifically apply many structuralist concepts to the roles of men and women. They theorize that men and women are differentially predisposed to form various relationships at various stages of the human life cycle.<span class="Footnote-Ref"><span id="footnote-136-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-136">*</a></span></span> They therefore directly connect the universal patterns of men’s and women’s roles to a biological root. Fox and Tiger state their views in the following manner:</p>
<p class="BODY-STYLES_Block-Quote-Single">.&#160;.&#160;.&#160;the human organism is “wired” in a certain way so that it can process and emit information about certain facts of social life such as language and rules about sex, and can process this information only at certain times and only in certain ways. The wiring is geared to the life cycle so that at any one moment in a population of homo sapiens there will be individuals with a certain “store” of behavior giving out information at another stage to others who are wired to treat this information in a particular way. The outcome of the interaction of these individuals will be certain “typical” relationships.<a id="_idTextAnchor847"></a><span class="Endnote-Ref">[55](#_idTextAnchor1787)</span></p>
<p class="BODY-STYLES_Block-Quote-Single">All social acts are patterned. They are as nonrandom as our physical structures. The patterns of social relationships into which they are formed can be predicted and explained. They are major regularities of the species—of any species. They can be called bonds. .&#160;.&#160;. This process of social bonding encompasses the formation and maintenance of certain relationships that appear stimulating, easy to learn, and in some cases necessary for the general health of the individuals concerned—to say nothing of the well-being of whole communities.<a id="_idTextAnchor848"></a><span class="Endnote-Ref">[56](#_idTextAnchor1788)</span></p>
<p class="BODY-STYLES_Block-Quote-Single">.&#160;.&#160;.&#160;The human being not only will proceed through a definable life cycle but also engage in social relationships—of foreseeable intensity and meaning—with predictable categories of people of predictable ages. Our behavior biogrammar underlies not only how we will act but how we will interact and with whom.<a id="_idTextAnchor849"></a><span class="Endnote-Ref">[57](#_idTextAnchor1789)</span></p>
<p class="BODY-STYLES_Body-NI-SA">Fox and Tiger treat the four universal social structural patterns of relationships between men and women as the outcome of a set of “typical relationships” stored in some fashion in the “behavior biogrammar” of the human species. For example, the fact that overall group leadership customarily resides in males relates to the “male bond,” a biological aspect of interaction in all-male groups. Tiger states this in the following paragraph:</p>
<p class="BODY-STYLES_Block-Quote-Single">More important from the social scientists’ point of view is the possibility that these male patterns lie at the heart of all community action and organization. Are the male bonds of politics, work, and war the behavioral mechanisms by which small-scale communities—perhaps of one adult male and females and young—link under certain circumstances to form the large communities in which many contemporary humans live? .&#160;.&#160;. My proposition, perhaps supported by data about political participation, would be that when human groups expand beyond, say, ten to thirty individuals, it becomes necessary to form some kind of bond of super- and subordination and some allocation of work and defence functions. This bond is typically male, and is observable in the rudimentary political arrangements of rural settlements in areas sufficiently beyond the subsistence level to sustain secondary economic institutions.<a id="_idTextAnchor850"></a><span class="Endnote-Ref">[58](#_idTextAnchor1790)</span></p>
<p class="BODY-STYLES_Body-NI">In similar fashion, Fox and Tiger view the mother-infant and male-female relationships as “typical relationships” formed by human biology.<a id="_idTextAnchor851"></a><span class="Endnote-Ref">[59](#_idTextAnchor1791)</span> According to Fox and Tiger, therefore, the social structural characteristics of men and women are not built solely on the foundation of individual psychological or physical differences, but are instead rooted directly in the innate biological endowment of the human species.</p>
<p class="BODY-STYLES_Body">The structuralist thesis of Fox and Tiger finds some support in the psychological evidence cited earlier in this chapter. First, this evidence shows not only that social structural differences exist, but also that they cannot be easily translated into inherent individual terms, as the first two theories imply. For example, male and female dependency patterns differ significantly when viewed in social structural terms. Males and females differ from one another according to the types of social situations and the types of relationships in which they develop some kind of dependency.<a id="_idTextAnchor852"></a><span class="Endnote-Ref">[60](#_idTextAnchor1792)</span> However, a generalized <span class="Italic">individual</span> difference does not exist. Females are not totally “dependent,” nor are males totally “independent.” Instead, they are dependent in different ways upon different people in different situations. The first two theories, which view social structural patterns as the product of generalized individual trait differences, do not account for this variety very well. On the other hand, Fox and Tiger’s concept of “typical relationships” and “social bonding” seems to be getting at the heart of the problem. Can the nature of, say, dependency behavior be explained by understanding the relationships and social situations in which it is observed? This seems to be a more promising avenue of inquiry than the reductionist tendency to focus on trait differences.</p>
<p class="BODY-STYLES_Body">Secondly, the psychological data provides support for the view that at least some social structural patterns are rooted in biological factors which influence modern as well as pre-technological societies. This evidence comes from studies of social interaction in children.<a id="_idTextAnchor853"></a><span class="Endnote-Ref">[61](#_idTextAnchor1793)</span> As soon as children are able to interact with other children, certain social structural patterns begin to form. Young boys prefer all-male groups, while girls prefer all-female groups. The activity rates of young boys rise dramatically when the boys are in the presence of other male peers. Young boys and girls also relate differently to adult authority figures such as parents and teachers. Several of these social structural patterns in children have been shown to be cross-cultural. This psychological evidence does not prove that these social structural characteristics have biological origins, but it does point in such a direction. The Rosaldo theory and its variations cannot deal adequately with this psychological data, whereas the structuralist approach predicts and explains it.</p>
<p class="BODY-STYLES_Body">Though their insights are often clothed in a confining mechanical terminology, the work of Fox and Tiger suggests a new and useful set of explanations for the social structural data. In the past, most of the discussion about the roots of the social structural patterns have revolved around the nature-nurture controversy: Are these social patterns caused primarily by biological factors that are relevant today, or are they stamped on human beings through generations of social conditioning? To be sure, the Fox/&#8203;Tiger hypothesis takes a stand on one side of the nature/nurture controversy; it comes down on the side of nature. However, the structuralist hypothesis is more sensitive to social realities than most theories proposing a biological hypothesis. Human behavior is not a determined, totally predictable given, but instead springs from a biologically formed response to a variety of social situations. The response differs according to the type of social situation confronted, and is therefore in some sense dependent upon and shaped by the social environment. The way the response is expressed also varies according to the unique qualities of the social environment. However, at the most basic level, the individual responses, and the larger social patterns built upon these responses, are formed predictably by the biological nature of the human species.</p>
<p class="BODY-STYLES_Body-SA">Some structuralists have proposed the concept of a “biogrammar,” a species-wide, biologically based predisposition to certain forms of social behavior. Biogrammar is analogous to the structural linguistic theory of a “deep structure” at the root of all human language. <a id="_idIndexMarker913"></a>Beatrix Hamburg uses this framework in the following manner:</p>
<p class="BODY-STYLES_Block-Quote-1st">.&#160;.&#160;.&#160;plasticity of gender behavior has been used to argue for an environmental determinism of the development of sex-role behaviors. However, can sex roles be said to be nonbiological even though they show the greatest possible impact of learning?</p>
<p class="BODY-STYLES_Block-Quote-Next">One might use the analogy of language. There is clearly a biological basis for language. No other animal has the adaptation of brain and vocal apparatus to make meaningful speech possible. The neurological basis of speech is well described. Despite this, language is clearly learned behavior. Langer has pointed out that man does not say even the first word by instinct.</p>
<p class="BODY-STYLES_Block-Quote-Last">As in the example of language, the important issue is not the biological behavior per se but rather the biological contribution to the shaping of what is learned.<a id="_idTextAnchor854"></a><span class="Endnote-Ref">[62](#_idTextAnchor1794)</span></p>
<p class="BODY-STYLES_Body-NI">Structural linguists such as Chomsky argue that a uniform basic structure of language is biologically embedded in the human species.<a id="_idTextAnchor855"></a><span class="Endnote-Ref">[63](#_idTextAnchor1795)</span> Languages thus differ from one another dramatically in sound and form, yet all adhere to certain universal structural principles. Fox and Tiger apply this model to the social structural characteristics of men and women, and make it the basis of a comprehensive explanation of their origins. They hold that it includes and transcends the other theories discussed previously.</p>
<p class="BODY-STYLES_Body">Indeed, the four theories explaining the social structural characteristics of men and women need not be mutually exclusive. Each theory singles out certain factors as being especially important in determining social structural patterns. None of the theories need rule out the possibility that other factors also play some role in the process. The weakness of the first three theories is not that they are plainly wrong, but that they cannot comprehensively explain the complex, detailed, and weighty evidence for social structural differences drawn from anthropological, psychological, and ethological studies. The structuralist theory may constitute a comprehensive theory, or may be an important element in such a theory, or may be simply a valuable attempt to produce the kind of theory needed. Nevertheless, it may be safely observed that any adequate theory must account for all of the physical, psychological, and social factors which these four theories identify.</p>
<p class="BODY-STYLES_Body">Earlier it was observed that none of these theories attribute the social structural differences entirely to non-biological factors. It is now apparent that this is true. All the theories note the influence of some biological factors on social behavior. The third theory relies on such factors least, but even this hypothesis sees physical differences between men and women as relevant in pre-technological societies. As has been seen, this approach also suffers from serious limitations.</p>
<p class="BODY-STYLES_Body">In summary, the evidence for social structural characteristics is too strong to allow for a purely environmental explanation. The anthropological data which documents the universal patterns of men’s and women’s roles in itself calls for some biological hypothesis, even apart from the psychological and ethological evidence which supports it. Therefore, it can be concluded that the social relationships of men and women, and the patterns which grow out of these relationships, are not merely produced by a process of socialization or cultural conditioning. The biological nature of the human race makes a considerable contribution to the development of men’s and women’s roles.</p>
<h2 id="_idParaDest-75" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor856"></a><a id="_idIndexMarker914"></a><a id="_idIndexMarker915"></a><a id="_idIndexMarker916"></a><a id="_idTextAnchor857"></a>Conclusion&#160;&#160;▹&#160; Individual Characteristics and Social Structural Characteristics</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">The</span> past two chapters have surveyed the findings of modern psychology and modern anthropology about the differences between the sexes. They have reviewed a large amount of data and evaluated the interpretations and explanations of this data. While no comprehensive theory explaining all the evidence has been found, it is nevertheless true that the data does converge and interconnect in a remarkable fashion. The data from the studies of individual differences between men and women harmonize with the data from the studies of social structural differences.</p>
<p class="BODY-STYLES_Body">Four main types of data have been discussed in the last two chapters. Chapter Sixteen presented data on individual characteristics obtained through descriptive and experimental methods; this chapter presented data on social structural characteristics obtained from cross-cultural and group interaction studies. (The ethological data in this chapter is only of a supportive nature.) The data from these four sources converge in two particularly significant patterns. One pattern forms around the male governing role, while the other forms around the female domestic role. The following table summarizes the convergence around these two patterns.</p>
<table id="table002" class="No-Table-Style _idGenTablePara-1">
<colgroup>
<col class="col1" />
<col class="col2" />
<col class="col3" />
<col class="col4" />
<col class="col5" />
</colgroup>
<tbody>
<tr class="No-Table-Style">
<th class="No-Table-Style" />
<th class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Individual Descriptive</p>
</th>
<th class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Individual Experimental</p>
</th>
<th class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Social Structural Group Interaction</p>
</th>
<th class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Social Structural Cross-Cultural</p>
</th>
</tr>
<tr class="No-Table-Style">
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Male ▹</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Differentiated personality, Goal oriented</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Aggression, Visual-spatial ability</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Male-peer bond (hierarchical, committed)</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Overall male authority</p>
</td>
</tr>
<tr class="No-Table-Style">
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Female&#160;▹</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Integrated personality, Personal need orientation</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Nurturance, Verbal ability</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Family bond</p>
</td>
<td class="No-Table-Style">
<p class="BODY-STYLES_Basic-Table-Text">Female responsibility in domestic sphere</p>
</td>
</tr>
</tbody>
</table>
<p class="BODY-STYLES_Body-NI">The cross-cultural evidence shows that men have held the overall governing position in every known society. The data from the other sources shows that men have characteristics which suit them for this role. The male bond allows a group of men to form a cohesive nucleus for governing a large community. Male aggressiveness equips men to protect and lead the social groupings. Superior visual-spatial ability may equip men to cope with broad social structural questions. The man’s differentiated personality, along with his accomplishment orientation, also harmonizes well with an overall governing role. A governor must be able to take a disciplinary perspective, to be detached, to order a situation, to move a group forward and advance its interests, to be ready to sacrifice individual needs and feelings to the common good. Thus it can be seen that the data clusters in a coherent pattern around the male governing role.<span class="Footnote-Ref"><span id="footnote-135-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-135">*</a></span></span></p>
<p class="BODY-STYLES_Body">The data clusters in a parallel way around the female domestic role. The cross-cultural evidence shows that in every known society women have cared for the young children and managed the domestic sphere. The female family bond certainly equips women for this role, as does female nurturance. Women’s superior verbal ability may be related to the focus on personal relationships in domestic life. Women’s integrated pattern of personality, expressed in an immediate and personal response to a social environment, also fits well with the role of caring for the young and making a home.</p>
<p class="BODY-STYLES_Body">The evidence summarized in the past two chapters leads to two important observations. First, men and women appear to differ from one another in many ways, along a wide spectrum of individual and social structural characteristics. These differences do not surface randomly, but instead cluster in a coherent pattern. No theoretical consensus has emerged on the exact nature of the relationship between the individual differences and the social structural differences. Nevertheless, no one seriously contests the existence of such a significant relationship. One could even say that individual and social structural differences are not two distinct sets of differences, but are rather one set of differences seen from two separate angles.</p>
<p class="BODY-STYLES_Body">Secondly, it is clear that many of the differences between men and women have some biological basis. The data from psychological studies most clearly points to this biological basis in the areas of aggression, nurturance, and visual-spatial ability. It is entirely possible—even likely—that further study will uncover a biological basis to other differences, including those where data is currently ambiguous. The social structural evidence, particularly as found in the cross-cultural studies, also points to biological factors as the basis for certain social relationship configurations. Once again, all of the specifics are not known. The precise biological mechanisms influencing each characteristic have not been isolated, though new research in endocrinology and neurology has begun to fill in the gaps. The development of new experimental techniques seems to be leading to a greater appreciation for the formative role of biological factors.</p>
<p class="BODY-STYLES_Body">In the light of these two observations, one can conclude that, though no overarching theory explains all of the data, and though most of the precise causal chains underlying the known differences remain hidden, the evidence from social science still contributes substantially to an understanding of the differences between men and women.</p>
<h2 id="_idParaDest-76" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor858"></a>Consequences and Directions</h2>
<p class="BODY-STYLES_Subhead-Opening-SA"><span class="MaWiC_Subhead-Drop-Words">In</span> the past two chapters, many conclusions have been drawn from the current social scientific data on the differences between men and women. These conclusions can be summarized as follows:</p>
<p class="BODY-STYLES_L-O-Num-L1-1st"><span class="Body-List-Counter-Float">1.</span>There are considerable differences between men and women, these differences have some biological roots, and they relate to the distinct social functions that men and women perform.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">2.</span>All known human societies have included stable patterns of role differences according to sex in their social structure, and these role differences have involved some subordination of the woman to the man. These role differences are expressed through division of labor, as well as through differences in dress, customs of respect, and character traits.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">3.</span>Social structural differences between men and women support and express their distinct social roles. Women are more oriented toward home and children, they form less-stable groupings with other women, and respond better to male authority than to female authority. Men are more oriented toward communal situations, they form stable hierarchically ordered groups with other men, and protect their women and children. These patterns correlate with social structures in which the men provide the backbone of the communal grouping and the women are primarily linked to the larger community through their husband, brother, or father.</p>
<p class="BODY-STYLES_L-O-Num-L1-SA"><span class="Body-List-Counter-Float">4.</span>There are a number of individual trait and trait-pattern differences between men and women, and these differences also support and express their distinct social roles. Men are more differentiated in their pattern of response, while women are more integrated. Men are more accomplishment oriented, while women are more helping oriented (another term might be “personal-service oriented”). Men are more aggressive than women and more oriented toward social dominance. Men are physically stronger than women. Women are more nurturant than men. In other words, men and women differ in the way they relate to other people and to social situations, and these differences correlate with a governor-protector-provider role for the man and a care-service role for the woman.</p>
<p class="BODY-STYLES_Body">One can confidently predict that many of the details of the scientific conclusions presented in these chapters will be modified in future years. However, one can also confidently predict that the main outlines of these conclusions will endure. The evidence solidly verifies the existence of differences between men and women that are not merely the product of culture or socialization. The evidence also solidly demonstrates that these differences are related to a structure of society and a set of role differences common to the entire human species. To be sure, these differences can be expressed in many ways and, in fact, this variety can be observed in the cultures of the world. But beneath this variety is a common pattern or fundamental structure which is rooted in human biology. One might say that a role difference between men and women was “created into” the human race.<a id="_idTextAnchor859"></a></p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker917"></a>The Argument against Biodeterminism</h3>
<p class="BODY-STYLES_Body-NI">An important question still remains: What is the proper attitude toward these differences between men and women? A strong movement today would pay as little attention as possible to these facts. This movement advances what could be described as “the argument against biodeterminism.” In its strongest form, the argument against biodeterminism denies that there are real or significant differences between men and women. As the past two chapters demonstrate, the evidence solidly refutes this strong form of the argument. A modified form of the argument against biodeterminism is more widely held. This is the view that some differences between men and women exist, but that we can and should recondition people so that they do not express these differences in any way other than in the physical necessities of sex and reproduction. This view holds that the human race is very malleable, that socialization and cultural conditioning are much more powerful in forming the human race than most biological factors, and hence that the human race should simply mold itself into whatever it wants to become.</p>
<p class="BODY-STYLES_Body">This form of the argument against biodeterminism possesses some plausibility. To a great extent, the human race does possess the ability to condition itself away from what could be described as its “natural state.” Humanity <span class="Italic">is</span> malleable. Socialization is powerful. Humans can determine their own destiny in a way that animals cannot. However, human malleability has definite limits. There are physical limitations. There also appears to be a tendency to cling to a “natural” order. For example, women in the Kibbutzim have returned to a more traditional pattern of men’s and women’s roles despite an ideology which points in the opposite direction. Nonetheless, it does seem possible that the human race, through diligent and ingenious effort, could condition itself away from the pattern of men’s and women’s roles that has appeared in every human society.</p>
<p class="BODY-STYLES_Body">However, the human race would attempt this change only at great risk. Developments in ecological studies in recent decades have demonstrated the fragility and complexity of the “natural” environment. Seemingly small changes in our physical environment can produce unexpected—even disastrous—consequences. The human race is not always adept at foreseeing the consequences of such changes because its understanding of the interrelationships of overall ecology lags well behind its technological ability to produce change.<a id="_idTextAnchor860"></a><span class="Endnote-Ref">[64](#_idTextAnchor1796)</span></p>
<p class="BODY-STYLES_Body">The radical feminist movement has by its success shown its ability to produce vast social change. However, this could be one of the most destructive changes in the history of human society. The roles of men and women have proven useful in previous societies; in fact, past societies functioned well only when these roles were operating properly. Today a strong movement would destroy these roles without a firmly established understanding of the ecological consequences. The rationale is simply that human nature is “unbelievably malleable.” In essence, the human race is told that it should make such changes simply because it is capable of doing so. In the face of such a claim, human beings would do well to acquire a humble sense of the limitations of human knowledge, and to recall recent lessons about some of the painful consequences of technological change.</p>
<p class="BODY-STYLES_Body-SA"><a id="_idIndexMarker918"></a>For many years now our society has been experiencing a gradual weakening of men’s and women’s roles. Recent ideological and social movements have begun to hasten this process in many countries and this trend will probably continue. One should attempt to analyze the effects of this change. This is a complex and difficult task, but one can already observe in countries where the process is most advanced several destructive social trends that can probably be traced in part to the breakdown of men’s and women’s roles.</p>
<p class="BODY-STYLES_L-O-Num-L1-1st"><span class="Body-List-Counter-Float">1.</span><a id="_idIndexMarker919"></a><span class="Italic">Family life is weakened.</span> The breakdown of men’s and women’s roles weakens family life in two main ways. First, it undermines the subordination of the wife and turns her attention to her own life and career apart from her husband’s career and apart from the life of the family.<a id="_idTextAnchor861"></a><span class="Endnote-Ref">[65](#_idTextAnchor1797)</span> This takes away from the unity of the family, and is associated with the family’s general loss of order and authority. Secondly, the breakdown of men’s and women’s roles leads men to take less responsibility for family groupings.<a id="_idTextAnchor862"></a><span class="Endnote-Ref">[66](#_idTextAnchor1798)</span> As family life becomes an undifferentiated responsibility of husband and wife together with no defined male role of leadership, men often lose the motivation and commitment needed to care for their families. They tend to relate to women predominantly for sexual gratification. The man no longer focuses his desire for accomplishment on the family, but instead directs his interest elsewhere. As a consequence of these two trends—the increasing independence of the wife and irresponsibility of the husband—the family becomes less of a stable, ordered, and cohesive group, and more of a collection of individuals living together. These weaker families then produce weaker children with significant personal problems.<a id="_idTextAnchor863"></a><span class="Endnote-Ref">[67](#_idTextAnchor1799)</span></p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">2.</span><a id="_idIndexMarker920"></a><span class="Italic">Sexual relationships become troubled.</span> Confusion about roles may be a factor in the apparent increase of sexual disorders in Western culture. Evidence indicates that impotence in men is tied to the way their partners relate to them.<a id="_idTextAnchor864"></a><span class="Endnote-Ref">[68](#_idTextAnchor1800)</span> When wives relate to their husbands in a challenging, aggressive, or dominating way, men often lose interest in sexual relationships and sometimes become impotent.<a id="_idTextAnchor865"></a><span class="Endnote-Ref">[69](#_idTextAnchor1801)</span> Some social scientists also believe that a breakdown in men’s and women’s roles is associated with homosexuality and confusion in sexual identity.<a id="_idTextAnchor866"></a><span class="Endnote-Ref">[70](#_idTextAnchor1802)</span></p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">3.</span><span class="Italic">Women often lose a sense of value.</span> The modern feminist movement—ostensibly a movement “for” women—normally devalues the very things that women feel the greatest desire to do: to be a wife and mother and have a home. Moreover, it often devalues precisely those elements of her personality that are most naturally feminine.<a id="_idTextAnchor867"></a><span class="Endnote-Ref">[71](#_idTextAnchor1803)</span> Ironically, the effect of the feminist movement is largely to make women feel the “disadvantage” of being female more acutely. It puts them under greater pressure to compete with men.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">4.</span><span class="Italic">Womanly roles are neglected.</span> Our society neglects or institutionalizes roles involving care for personal needs—the roles traditionally filled by women. Thus home and family life becomes less supportive and charitable service is more impersonal and less charitable.</p>
<p class="BODY-STYLES_L-O-Num-L1"><span class="Body-List-Counter-Float">5.</span><span class="Italic">Manly roles are neglected.</span> Our society provides less order, discipline, and personal protection in daily life than previous eras.<a id="_idTextAnchor868"></a><span class="Endnote-Ref">[72](#_idTextAnchor1804)</span> Men are taught to avoid these traditionally male responsibilities; in fact, many men have become incapable of bearing these responsibilities because they have lost what was once the characteristically male approach to emotions and personal relationships.<a id="_idTextAnchor869"></a><span class="Endnote-Ref">[73](#_idTextAnchor1805)</span></p>
<p class="BODY-STYLES_L-O-Num-L1-SA"><span class="Body-List-Counter-Float">6.</span><span class="Italic">Men and women develop psychological instabilities.</span> There is some evidence that those groups in modern society most directly affected by the feminist movement have been specially plagued by psychological problems. The lack of social roles appears to make life more difficult for both men and women.<a id="_idTextAnchor870"></a><span class="Endnote-Ref">[74](#_idTextAnchor1806)</span></p>
<p class="BODY-STYLES_Body-NI">It probably cannot be proven that all these trends are caused by the erosion of men’s and women’s roles in our society. However, a reasonable case can be made for this position, and this case should be taken seriously until it is disproved. These trends amount to a picture of increasing social weakness. The fabric of our society could be seriously weakened by the continued breakdown of men’s and women’s roles.</p>
<p class="BODY-STYLES_Body-SA"><a id="_idIndexMarker921"></a>Of the several social trends just described, the weakening of the family is of the greatest concern. Those who oppose the feminist program for restructuring society have long held that this program would undermine the most fundamental elements of family life. Radical adherents of the program agree with this analysis, and hail the undermining of the family as an essential step in social progress; more moderate adherents deny that the weakening of men’s and women’s roles must weaken the family. However, it is clear that the family in modern society is growing more fragile, and this fragility must stem at least in part from new approaches to men’s and women’s roles. This connection between weakened roles and a weakened family is illustrated in the following paragraph from <a id="_idIndexMarker922"></a>Barbara Seaman, a feminist journalist who is writing from her own experience about families whose wives were actively involved in the feminist movement:</p>
<p class="BODY-STYLES_Block-Quote-Single">I was in an early consciousness-raising group, which proved effective. We all went on to publish books, get PhDs, or rise up some way in the world. Years later, those of us who were mothers tried to reassemble in order to measure the price our families might have paid. The sessions were so painful that after five or six of them we quit. Too many husbands had deserted (one for a Playboy bunny), too many children had dropped out of school, turned gay, attempted suicide. To a man the divorced husbands, however affluent, were copping out on child support, college tuitions and psychiatrist bills. These were women, mind you, who never requested alimony for themselves.<a id="_idTextAnchor871"></a><span class="Endnote-Ref">[75](#_idTextAnchor1807)</span></p>
<p class="BODY-STYLES_Body-NI">Seaman’s chronicle of family dissolution, children’s problems, and male irresponsibility is a vivid testimony to some of the possible consequences of a feminist restructuring of society.</p>
<p class="BODY-STYLES_Body">The argument against biodeterminism and similar forms of argumentation are seriously flawed in their very structure. Built into these theories and ideologies is a faulty view of where the burden of proof lies. They begin with the undeniable malfunctioning of many aspects of men’s and women’s roles today, and proceed to argue that distinctive roles for men and women should be abolished or substantially reduced. To be sure, they produce much evidence for the malfunctioning of the current remains of traditional men’s and women’s roles. However, this evidence alone cannot lead them to the conclusion they assert. If they are advocating a radical restructuring of society, then it is not enough to merely substantiate the problems and disadvantages of the present structure. Those arguing for change should also be required to show that their proposed new pattern can more successfully accommodate the natural differences between men and women and can provide a better basis for the structuring of society. They should be asked to show that a new approach would work <span class="Italic">better than</span> the current system or the alternatives. If the present pattern of men’s and women’s roles is inadequate, but more promising than the alternatives, it would be a grave error to discard it in favor of a change that is even more inadequate. Nonetheless, those advocating the radical feminist positions today seldom try to show that their option is better. They are simply dismantling the remains of a traditional system of men’s and women’s roles without replacing this system with anything superior.<a id="_idTextAnchor872"></a><span class="Endnote-Ref">[76](#_idTextAnchor1808)</span></p>
<p class="BODY-STYLES_Body">The feminist line of argumentation has another weakness. The argument advocates the abolition or reduction of role differences by documenting the problems in the current system of men’s and women’s roles. However, it can also be argued that the weaknesses in the current system point instead to the need for a restoration of fuller role differences. The current system of men’s and women’s roles is merely a remnant of the traditional patterns of men’s and women’s roles. These traditional patterns have been under ideological and cultural assault for over a hundred years. Therefore, the system of men’s and women’s roles in technological society today is largely the product of the very forces which would now take change even further, removing even the remnants of a traditional pattern. If the current system is any indication of the desirability of further change, the radical feminist program must appear highly undesirable.</p>
<p class="BODY-STYLES_Body">Finally, the feminists are proposing sweeping, and untried, alternatives to a pattern of human life that has endured throughout all history. Surely the radicalness of their proposals puts the burden of proof upon them to justify the safety as well as the desirability of a program of eliminating all sexual role differences.</p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker923"></a><a id="_idTextAnchor873"></a>The Value of Social Roles</h3>
<p class="BODY-STYLES_Body-NI-SA"><a id="_idIndexMarker924"></a>There is an alternate approach to men’s and women’s roles today, an approach articulated in the following remarks of Margaret Mead. In the course of a discussion of the relationship between biological male-female differences and social roles, Mead asks the question, Must a society fashion distinct social roles for men and women?</p>
<p class="BODY-STYLES_Block-Quote-Single">We have here two different questions: Are we dealing not with a <span class="Italic">must</span> that we dare not flout because it is rooted so deep in our biological mammalian nature that to flout it means individual and social disease? Or with a <span class="Italic">must</span> that, although not so deeply rooted, still is so very socially convenient and so well tried that it would be uneconomical to flout it—a <span class="Italic">must</span> which says, for example, that it is easier to get children born and bred if we stylize the behavior of the sexes very differently, teaching them to walk and dress and act in contrasting ways and to specialize in different kinds of work? But there is still the third possibility. <span class="Italic">Are not sex differences exceedingly valuable, one of the resources of our human nature that every society has used but no society has as yet begun to use to the full? <a id="_idTextAnchor874"></a></span><span class="Endnote-Ref">[77](#_idTextAnchor1809)</span> (Emphasis added)</p>
<p class="BODY-STYLES_Body-NI">Mead proposes that society should not attempt to condition people away from all role differences, but instead develop a constructive approach to men’s and women’s roles. Instead of eliminating men’s and women’s roles, they might be developed so that they are more adapted to modern conditions, and thus continue to tap the “valuable .&#160;.&#160;. resources of our human nature.”</p>
<p class="BODY-STYLES_Body">As will be seen in the next chapter, a technological society presents a special challenge for developing an adequate approach to men’s and women’s roles—or any form of social roles. However, there is good reason to think that men and women in technological society should meet this challenge. In all human societies, social roles have been crucial for the formation of a viable society. As seen earlier in the present chapter, these social roles have been universally structured according to the difference between the sexes. Every society has not only recognized the need for social roles, but has also structured these roles differently for men and women.</p>
<p class="BODY-STYLES_Body">Furthermore, the evidence discussed in Chapter Sixteen indicates that human beings are still psychologically constructed to fit a pattern of role differences between men and women.<a id="_idTextAnchor875"></a><span class="Endnote-Ref">[78](#_idTextAnchor1810)</span> It would be foolish to ignore something so basic, so consistent, and so transcultural to the human race. It would be foolish to eliminate such a constant feature of human society without any certainty that something else would successfully replace it. In other words, the most sensible and constructive approach would be to form distinctive social roles adapted to the conditions of contemporary society.</p>
<p class="BODY-STYLES_Body">As stated at the beginning of Chapter Sixteen, any constructive approach to men’s and women’s roles (or to social roles in general) in contemporary society must take into account three factors. The first factor is the basic human realities that do not change as society changes. The past two chapters have examined these factors. The second factor is the conditions which contemporary society presents. Any attempt to structure men’s and women’s roles only according to the differences between men and women will only be partially successful. Full success depends on the degree to which a particular approach to roles effectively copes with the social environment. The third factor is the vision of the ideal human society. Neither the facts of human realities nor the demands of the contemporary social environment alone or together completely dictate what human society must be like. Both are important and both impose conditions, but human beings still have a fair amount of latitude to decide what their life will be like. Human beings will choose their direction by accident or according to an ideal. The following chapters will consider both the demands of the social environment and the various contemporary ideals which influence this question. Finally, a possible Christian approach to men’s and women’s roles in contemporary society will be proposed.<a id="_idTextAnchor876"></a></p>
<p class="BODY-STYLES_Body">The primary purpose of the past two chapters has been to survey the findings of modern science regarding men and women. However, these chapters also allow one to reflect upon the scriptural teaching on men’s and women’s roles. It is unclear to what extent the New Testament bases its teaching on the “nature” of man and woman. Several passages suggest that the “nature” of men and women is one factor in the New Testament approach. However, the primary foundation of the New Testament teaching is an understanding of the creation and what the creation reveals of God’s purposes for the human race. In the Genesis account, the first man and the first woman show God’s intention for man and woman in human community. God enjoined a difference in role between men and women for the sake of the order in their relationship.</p>
<p class="BODY-STYLES_Body">It does not necessarily follow from the creation account that God created men and women with the range of physical, psychological, and social structural differences that modern science can definitively establish. The creation account simply shows how God wants men and women to relate. It does not state that God made them so that they would have a strong inclination to relate the way he wished.<span class="Footnote-Ref"><span id="footnote-134-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-134">*</a></span></span> The person immersed in the thought-world of the Old and New Testaments would be impressed by the fact that God created man and woman for a purpose. He would be less likely to view as significant the fact that there are psychological differences between men and women with biological origins. These differences are more impressive to people of the twentieth century than they would have been to the early Christian writers. Most contemporary Christians who study this question will instinctively try to correlate the creation account with the results of empirical investigations in the social sciences.</p>
<p class="BODY-STYLES_Body">From the perspective that sees the results of creation in the biological makeup of the human race, modern science confirms the scriptural account. Man and woman differ from one another in their biological and socio-psychological makeup. These differences endure through great cultural diversity. The Christian can express this fact by saying that men and women were created differently by God. Of course, there is a problem when Christians make their faith or their Christian lives dependent on the results of modern science. Their faith is then no longer based on the Lord and on revelation. However, in a time when the scriptural teaching is dismissed as culturally relative and outmoded, it is helpful to observe that God’s purposes indeed seem to have been “created into” the human race.</p>
<div class="Next-Chapter"><a href="Man-and-Woman-in-Christ_ebook-export-24.xhtml">Skip footnotes ▸</a>
</div>
<div class="_idFootnotes">
<div id="footnote-139" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-139-backlink">428*</a>In one sense, all human social behavior is complex. However, societies differ in levels of complexity. These levels are functions of such variables as size, diversity of roles, and level of economic production. The complexity of economic systems ranges from small group subsistence at the most primitive level, through economies based on trade and commerce, to mass production and retail economies—the most complex. Similarly, governmental systems vary in complexity. A typical continuum of increasing complexity would be: tribal government, tribal confederation, the feudal kingdom, the centralized kingdom, and the modern nation-state. Residential patterns vary in complexity in a similar continuum: from societies based on spatially distinct kinship groupings, to those based on the village, the town, the city, the metropolis, and finally the megalopolis. Usually complexity in one social sphere correlates highly with complexity in the others. Those societies with subsistence economies are also likely to have tribal government and residential systems based on kinship groupings. The societies with the most complex economic systems usually have nation-state government and a megalopolis residential system. Thus whole societies can be roughly compared on a scale of social complexity. This concept underlies the above generalization: With the important exception of later technological society, high social complexity correlates with a strong expression of the four universal patterns of men’s and women’s roles, while low social complexity correlates with a weaker expression of these roles.</p>
</div>
<div id="footnote-138" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-138-backlink">435*</a>Men and women appear to differ from one another in the way they relate to authority. As mentioned in the text, men tend to form large, stable groups characterized by a pronounced hierarchical organization, or, in other words, an elaborated system of authority and subordination. Therefore, the relationship of “dominant/&#8203;subordinate” among males occurs within the context of a large peer group ordered and organized for the purpose of maintaining solidarity and achieving some functional goal. Many scholars see these hierarchies as connected in some way to male aggressiveness; the system may normalize and contain the competitive dominance and achievement-striving of males in relation to one another, and at the same time free them to express some form of aggression toward threatening elements external to the group.<a id="_idTextAnchor816"></a><span class="Endnote-Ref">[35](#_idTextAnchor1767)</span></p>
<p class="FOOTNOTES_Footnote-Next">On the other hand, female authority relationships occur within a very different context and involve a different set of dynamics. The relationship usually occurs within a smaller, mixed grouping. In addition, the other member of the relationship is not a peer in the same way as in male groups (although among men the person in authority is usually older, difference in age is not so important). When females are subordinate, the person in authority is most often either a member of the opposite sex (husband, father, uncle, brother, etc.), or a female who is much older. Also, the relationship is less characterized by the containment and channeling of aggression, and more by the desire to care for and be cared for, to provide for and be provided for, to protect and be protected.</p>
</div>
<div id="footnote-137" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-137-backlink">441*</a>Although this view adopts an evolutionary perspective to explain the temporal origin of social structural patterns, it does not deal adequately with the process of selection and adaptation which is an integral part of the evolutionary perspective. According to the theory presupposed by this third approach, the human species developed over millions of years. This development involved radical size and structure changes in the brain. Initial human social structural patterns may have originated in simple physical differences such as male muscular strength and female reproductive capability. However, the principle of selection and adaptation operating over the millions of years of evolutionary history would surely have embedded these differences more deeply in the male and female organisms. In other words, evolutionary theory would likely make these social structural differences more than a simple matter of physical factors. Evolution is more likely to cause a biological reordering of male and female psychological characteristics. For example, an evolutionary perspective would lead us to expect that the female nurturant advantage involves more than just the fact that the woman possesses breasts. It would probably include a biologically based psychological orientation which would make females adapted and inclined to a nurturant role, even when, in the course of technological development, bottles can replace breasts.</p>
</div>
<div id="footnote-136" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-136-backlink">444*</a>Linked closely to Fox and Tiger’s view of the biological origin of the social structural characteristics of men and women is a theory of the historical origins of these characteristics. They assert that the social structural characteristics grew out of the need of the hunting/&#8203;gathering society of primitive man. However, the structuralist approach to explaining social structural patterns need not be tied to any particular historical explanation of the origins of these patterns. In fact, the customary approach of structuralist methodology is “atemporal” (see Lane, 16<span class="No-Break">–1</span>7).</p>
</div>
<div id="footnote-135" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-135-backlink">449*</a>This is not to say that only men are able to assume a governing role. The key point being made here is that, according to the data surveyed in these chapters, men as a group have more of those characteristics suited to a governmental role than do women as a group.</p>
</div>
<div id="footnote-134" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-134-backlink">459*</a>In other words, though it may make most sense to see the revelation of God’s purposes for men and women as a revelation of their inherent nature, this is not the only possible interpretation. God could have created men and women in a less differentiated way and asked them to conform to his purposes solely out of obedience. On the other hand, it does not seem reasonable to hold that God made men and women so that they naturally reject his purposes. However, the main point is that it is not clear that the writers of scripture would have approached the discussion with the same view as contemporary people trained in modern science.</p>
</div>
</div>
