# A Christian Approach for Today {-}

<h1 class="HEADS---SUBHEADS_Part-Number">4</h1>
<h1 id="_idParaDest-95" class="HEADS---SUBHEADS_Part-4-Title"><a id="_idTextAnchor1109"></a>A Christian Approach for Today</h1>
</div>
<div>
<p class="BODY-STYLES_Part-Opening"><span>▸&#160;&#160;</span><span class="Opening-Drop-Words">The previous part of this book</span> treated the “gap” that exists between the times of the New Testament and the modern world, and laid the foundation for applying the scriptural teaching in the lives of Christians today. The concluding part develops a sketch for how Christians should approach the roles of men and women in the midst of the contemporary situation. This sketch could be seen as a pastoral proposal for how Christians can both be faithful to scriptural teaching and live viable and effective lives in the modern world. The concluding part begins with a chapter which sketches in the basic components of the pastoral approach. The next chapter presents more specific guidelines. Chapter Twenty-Three deals with certain issues involved in implementing the proposed pastoral approach. The final chapter treats some special areas of concern and the way in which the pastoral approach would touch upon those areas.&#160;&#160;▸</p>
</div>
