# The Bases of a Christian Approach Today

<p class="BODY-STYLES_Chapter-Opening"><span class="Drop-Cap"><a id="_idIndexMarker1086"></a></span><span class="Drop-Cap">L</span><span class="Opening-Drop-Words">ife in the second half of the twentieth century</span> poses many complex and challenging questions for the Christian people. Perhaps the primary question involves the issue of fidelity to scrip&#173;ture and Christian tradition. What is the proper response to the biblical teaching on morality and social structure? Should this teaching be applied in the modern world? However, even when one answers this question positively, many further questions still arise. It is not always easy to apply the teaching of the scripture to a modern technological society. What, in fact, is the Christian approach to living in the midst of a highly functionalized social environment? The Christian people are in great need of wisdom about how to follow the purposes of God in the modern world. The rest of this book will address this need.</p>
<p class="BODY-STYLES_Body">The approach to social structure and men’s and women’s roles that will be presented in the following chapters is designed primarily for Christians living in a technological society. However, not all of the human race lives today in circumstances created by a technological society. Some people even live in primitive societies. Christians living in societies that are more traditional face a different set of problems with men’s and women’s roles and will probably not find these chapters very helpful. Their problems more likely derive from a traditional view which defines and values strict roles for men and women, but perhaps not in a fully Christian fashion. Nonetheless, in most of the world, technological society is currently transforming traditional social patterns and producing a new kind of life. The approach developed in the following chapters will be helpful for a particular social situation to the degree that that situation is dominated by or coming under the influence of technological society.</p>
<p class="BODY-STYLES_Body">Many of the elements of the approach to social structure and men’s and women’s roles that will be presented in the following chapters are also designed primarily for a group of Christians living a corporate life according to the teaching found in the New Testament, what could be described as a full Christian community.<span class="Footnote-Ref"><span id="footnote-202-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-202">*</a></span></span> Underlying this approach is the understanding that the biblical social teaching requires a restored social fabric in order to be applied fully. Therefore, many of the practical recommendations found in these chapters on such matters as social roles and offices in the Christian community presume the context of a defined Christian communal environment. The practical scriptural teaching on social structure makes most sense when viewed against the background of a communal social ideal.</p>
<p class="BODY-STYLES_Body">Though these chapters primarily point to the need for a genuine Christian communal life, they also have much to say to those who currently do not experience such life in a full way. First, the following chapters present a scriptural ideal of the restoration of humanity in Christ that should be grasped and moved toward. God’s aim in creating and redeeming the human race is to form a people; to the degree possible, all Christians should live in a grouping of Christians that functions as a people. Secondly, these chapters discuss principles of communal life which are natural to the human race and can be applied in many social situations. These principles should not be applied rigidly outside of a community context, but they can be understood and applied in modified form. Finally, some of the issues discussed in these chapters do bear directly on the lives of all Christians regardless of the nature of the Christian groupings they belong to. These issues include family life, male and female character, and men’s and women’s roles in the occupational world. To be sure, the full Christian ideal depends upon the establishment of a corporate life in Christ, but those presently unable to belong to such a grouping of Christians should move toward living as much of the ideal as their situation allows.</p>
<p class="BODY-STYLES_Body">This chapter will present the basic perspective that Christians should take toward applying the New Testament teaching on social structure within modern technological society. The first component of this perspective is the vision of God’s purpose for the human race: the communal restoration of humanity in Jesus Christ. The second and third components of this basic perspective are the fundamental elements which allow this new humanity to maintain a communal life: Christian relationships and Christian social structure. Finally, this chapter will distinguish the Christian approach to corporate life from other rival approaches. From this basic perspective, the subsequent chapters will offer specific guidelines and address specific issues.</p>
<h2 id="_idParaDest-97" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1111"></a><a id="_idIndexMarker1087"></a><a id="_idIndexMarker1088"></a><a id="_idIndexMarker1089"></a>Becoming a People</h2>
<p class="BODY-STYLES_Subhead-Opening"><a id="_idIndexMarker1090"></a><span class="MaWiC_Subhead-Drop-Words">The</span> first step in applying Christian teaching on social structure in the modern world is to grasp the vision for human life contained in the scripture. As discussed in Chapter One, God created the human race to be united in such a way that it could act as a single person. This person, this human, was to be his son, formed in his image and likeness, created to serve as his representative over his visible creation.<span class="Footnote-Ref"><span id="footnote-201-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-201">*</a></span></span> Men and women alike were to be fully a part of the human race and of the divine sonship. Both were to share the image and likeness of God and both were to share in ruling over creation corporately on God’s behalf. They were created male and female so that the human race, the human community, could increase and fill the earth. When God sent his son Jesus to repair the damage from the Fall, his intent was to restore the human race to its original purpose by forming a new human race, a new creation, that could live as God’s son, the body of Christ on earth. God’s purpose in Jesus was to create a new humanity in which the image of God is restored and through which God is served. This new humanity consists of men and women who are united in Jesus. God’s purpose is to form a new community—the new human race.</p>
<p class="BODY-STYLES_Body">The new community has its own way of life. This way of life is not drawn from the surrounding peoples, nor is it simply inferred from a study of human nature or developed as an accommodation to the environment and circumstances. The way of life of the body of Christ originates in the nature and character of God himself. The new humanity is formed in the image and likeness of God, so it must look like him. It is holy as he is holy, because it is his own people. Christianity is not only a matter of doctrine and morals, but it is a way of life, a way of life that reflects the very nature of God himself. In particular, this way of life involves a special quality of relationship. The New Testament teaching on personal relations does not have an incidental place in the scripture. It is the very center of God’s purpose in giving the New Covenant, in writing his law on human hearts. “Make love your aim” (<a id="_idIndexMarker1091"></a>1&#160;Cor&#160;14:1).</p>
<p class="BODY-STYLES_Body">The first step in applying the Christian teaching on men’s and women’s roles, then, is to understand God’s purpose for the human race. Christians whose sole goal is to avoid the punishment of hell and gain admittance to heaven, to believe the basic doctrines and avoid breaking the essential commandments, cannot yet fully receive and adequately respond to the scriptural teaching on men’s and women’s roles. An adequate response requires an understanding of God’s full purpose: the creation of a new human race, a new community which lives according to God’s will and teaching. Any attempt to follow scriptural teaching on men’s and women’s roles apart from such an understanding of God’s purposes will suffer from the danger of legalism.</p>
<p class="BODY-STYLES_Body">It is possible to say that the Christian people are already the new human race, the body of Christ, a new community. From this perspective, Christians do not have to “become” the new community because they have already been joined to it through their spiritual position in Christ. Such a perspective has value and truth. If the basic reality has not already been established in Christ, it can never happen in our lives and in our world. It can only be a human imitation of a divine plan. Nonetheless, it must also be recognized that the Christian people today frequently do not look like the kind of humanity they have become in Christ. They often show few traces of the type of unity that would allow them to function as a body. Just as the appropriate instruction for an individual Christian is often to “be what you are,” “put on Christ .&#160;.&#160;. who is your life,” so the appropriate instruction for the Christian people today is to be the body of Christ, to commit themselves to God’s vision for his people—that they might live in reality as a new human race, united as one person and able to act accordingly.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1092"></a>If Christians are to live as the new humanity, the body of Christ, they need to pay a certain price. They need to commit themselves fully to Christ and to one another, and they need to invest enough of their personal lives in their life together as a Christian people that a cohesive community life can be established. Some form of personal subordination must be part of this commitment. Christians must subordinate their lives to the larger body of Christ if that body is to have any unity, and they must be personally subordinate to those responsible for representing that body and drawing it together. Without such subordination, the Christian people cannot form a social grouping that can live as the body of Christ. Christians should also be separate enough from the surrounding society that they can actually become a new people. Christians who identify primarily with the surrounding society and accept its authority as higher than any Christian authority will never become significantly different from non-Christian society. They will look more like the old Adam than the new. In short, the ideal basis for living the Christian teaching on men’s and women’s roles is to form a social grouping within which that teaching can be applied and within which those following it can be supported.</p>
<p class="BODY-STYLES_Body"><a id="_idTextAnchor1112"></a>In a predominantly non-Christian society, the body of Christ must live as a social grouping distinct in some way from the rest of society. However, there are still places in the world where an entire town or district or other social environment is Christian, in the sense that everyone professes Christian belief and perhaps even belongs to the same church. Christians in these places who want to live a full communal life may have to follow a slightly different approach. In such situations, forming a separate body within the society may not be the best strategy for living the life of the body of Christ. With the right circumstances, the entire environment could possibly be transformed into a full Christian community. Nonetheless, even in such situations Christians must have a clear consciousness of the difference between the Christian people and society as a whole so that they are not unknowingly formed by the influences of the broader non-Christian world. They must also be conscious of building the body of Christ, the new human race, with sufficient commitment and acceptance of Christian authority to allow the formation of a fully Christian life as a people. The dynamics may be somewhat different in an area where all or almost all the people are willing to acknowledge themselves as Christian, but the goal has to be the same.</p>
<p class="BODY-STYLES_Body">Though ideally forming a distinct community with its own way of life, the new humanity intended by God is not totally separate from the surrounding non-Christian society. Under the Old Covenant, God’s people were supposed to be totally separate from surrounding peoples—a nation with its own language, land, and political institutions. However, under the New Covenant, God’s people live among every nation to witness to the new life in Jesus, to offer all peoples the opportunity to live for God in the body of Christ. Therefore, the Christian people must always maintain close enough contact with non-Christian society that it can effectively proclaim God’s message of reconciliation and new life. However, though close enough to society to be an effective messenger, the way of life of the body of Christ must also be distinct enough to accurately reflect God’s nature and purposes. The new community will be neither “new” nor a “community” unless it maintains its distinct identity as God’s people and maintains a unique authority over its members.</p>
<p class="BODY-STYLES_Body">This is God’s full purpose for the human race—a restoration of corporate life in Christ. However, circumstances in modern society and in much of the modern church make it difficult to realize this ideal in a total way. To overcome these circumstances, some Christians have developed special Christian communities in the midst of the modern world. Though a challenging and difficult task, this approach has definite advantages as a strategy for realizing God’s purposes for human life.<a id="_idTextAnchor1113"></a><span class="Endnote-Ref">[1](#_idTextAnchor1973)</span> Many Christians may be unable to participate in such communities, but all Christians are called to grasp God’s total vision for human life, and to move toward it in whatever way possible.<a id="_idTextAnchor1114"></a></p>
<h2 id="_idParaDest-98" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1115"></a><a id="_idIndexMarker1093"></a><a id="_idIndexMarker1094"></a>Restoring Christian Relationships&#160;&#160;▹&#160; Relational Groupings<span class="Footnote-Ref"></span><span class="Footnote-Ref"><span id="footnote-200-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-200">*</a></span></span></h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">Those</span> who attempt to establish authentic Christian corporate life in the midst of technological society must recognize two fundamental aspects of the Christian communal lifestyle: Christian relationships and Christian social structure. These two aspects of communal life are essential for a full realization of God’s purposes for the new humanity. They are also both largely absent in the functional structures of technological society and the social models of modern ideologies. Any authentic Christian community must be built upon a pattern of Christian relationships and a Christian social structure.</p>
<p class="BODY-STYLES_Body">To be a body that is healthy and strong, the Christian people must have a pattern of personal relationships that operates on principles other than the modern functional principle. They must have a pattern of loving, committed personal relationships that is able to meet the needs of a body of human beings in their life together. The basis of any restoration of the corporate life of the Christian people has to be the restoration of Christian relationships. Christians must learn how to have loving, committed personal relationships as brothers and sisters in the Lord, and how to pattern these relationships so that all the needs for personal support, childrearing, and care of the older members of the body are met effectively. Many Christians in the twentieth century capture something of the vision of the new humanity, the corporate life of the body of Christ, and proceed to try to establish Christian community without understanding the inner dynamic of this communal life—Christian personal relationships. Most of these attempts to build Christian community either fail quickly or run into painful difficulties over time as human realities reassert themselves, and the wisdom of the Lord for each relationship-area of human life is missing.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1095"></a><a id="_idIndexMarker1096"></a>The restoration of Christian relationships implies a restoration of relational groupings. Only in such groupings can a pattern of personal relationships be established which fits the ideal lifestyle of the Christian people. As discussed in Chapter Eighteen, the social fabric of traditional society consisted almost exclusively of a pattern of interconnected relational groupings: the conjugal family, the extended kin network, the village, the neighborhood, the guild and other groupings formed on the basis of profession and class. These groupings combined a consideration for personal life with a concern for productive labor and task accomplishment. The functional and the personal spheres of life were not clearly demarcated, but were instead integrated in one set of committed personal relationships. The special needs of the young, the poor, the infirm, and the elderly were ordinarily cared for within such groupings rather than in large institutions. The early church, and, in fact, the Christian people throughout much of its history, followed a similar pattern. Evangelism, religious instruction, and charitable service were all integrally tied to the household, the basic communal grouping. Relational groupings were able to perform so many diverse functions and meet so many communal needs because they were founded on a network of personal relationships that were stable, committed, and loving (at least within the Christian community, if not always in society as a whole). It was this pattern of loving relationships which enabled the body of Christ to possess a close communal life.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1097"></a>As discussed in Chapter Eighteen, relationships in modern technological society follow a very different principle. The relational groupings found in traditional society have been greatly weakened and often destroyed. In their place has arisen a pattern of relationships which involves on the one hand functional, limited, contractual, “impersonal” relationships, and on the other informal, nonpurposeful, unstable, emotionally based “personal” relationships. The nuclear family is one of the few relational groupings which is still part of most people’s lives, but the family’s isolation from a broader relational context poses severe challenges to its continued success as a relational unit. The advancing functionalization of social relationships and social groupings leaves many human needs unsatisfied. The old, the young, the sick—all who are not fully competent or capable by the standards of technological society—are left to the care of functionally organized institutions which are largely unable to meet their needs effectively. The functional and emotionally based relationships that characterize a technological society also fail to meet the need for stable community and committed love felt by even the strongest members of society. The undermining of relational groupings has led to a loss of the sense of communal relationship and also to the loss of a setting in which the fundamental personal needs of human beings can be satisfied.</p>
<p class="BODY-STYLES_Body">The functionalization of society has deeply affected many of the Christian churches. Many modern churches have lost their communal life and instead become religious organizations. Personal and communal needs are attended to primarily by committees, programs, and specialized personnel rather than being met within the daily relationships of the community. This is especially evident in such areas as religious education, evangelism, charitable service, and care of the needs of the sick and the elderly. In addition, the relationships among members within a particular church often lack commitment and stability. They frequently bear little resemblance to the type of personal relationships that exist in relational groupings. As a consequence of the social changes brought by the development of technological society, many of the churches have lost the pattern of personal relationships which is at the basis of communal life.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1098"></a>In order for the Christian people to live as the new humanity, the body of Christ, genuine Christian personal relationships must be restored. Such relationships are essential for the establishment of authentic Christian communities. This does not mean that the social life of the Christian people in the twentieth century should be identical to that of Christians in past centuries. Some distinctively modern functional structures are necessary and useful for life in the modern world. For example, the modern development of Christian schools, hospitals, and charitable institutions (none of which actually originated in technological society) need not undermine the communal life of the Christian people.<span class="Footnote-Ref"><span id="footnote-199-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-199">*</a></span></span> The use of programs, rallies, and the media in evangelism can also have some value. Nonetheless, a functional approach to social life should not govern the overall life of the body of Christ. If the Christian people are to regain their communal life and identity, then the primary place of service and support should be the restored personal relationships of Christian relational groupings.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1099"></a>It is helpful to observe that the type of personal relationships which need to be restored if the Christian people are to live as the new humanity, a true community, are relationships which are needed by everyone in modern society, not just by Christians. The functionalization of social life in technological society has left many basic human needs unsatisfied. However, Christians are in a better position than non-Christians to restore loving, committed relationships to human life. An authentic commitment to Christianity involves everything in a person’s life; it therefore provides one of the few adequate bases in modern society for full human relationships. The longing for community felt by many people in the modern world is never enough to bring them together in real relationship, because it does not provide enough basis for forming their lives together. The restoration of relationship in Christ is therefore not an antiquarian retreat to “First Century Bibleland” or traditional society, but is instead a fidelity to the Bible that also meets one of the greatest needs of the twentieth century.</p>
<p class="BODY-STYLES_Body"><a id="_idTextAnchor1116"></a>In order to adequately understand and apply the biblical teaching on social structure—on authority relationships and social roles—one must recognize that the restoration of Christian relationships is fundamental to all the social teaching of the New Testament. The New Testament teaching on men’s and women’s roles and authority and subordination presupposes a certain set of relationships between men and women both in the family and the community. The scriptural directives in these areas of social structure are intended to give order to a set of loving committed relationships. The order presupposes the relationships. It is not enough to merely try to establish the husband as head of the family or to insist that children obey their parents. The entire Christian family relationship must be reestablished and Christian childrearing restored before the directives about governance and obedience can serve as the Lord intended. It is not enough to merely maintain the governing role of men as the elders of the Christian community without restoring the communal relationships that allow that governing role to function as the Lord intended. There needs to be a restoration of relationships of brotherhood and sisterhood, of a network of families committed together to support and care for one another, of a whole lifestyle based on relational groupings and able to meet the various human needs of individuals within the body. Christians cannot obey the few clear scriptural directives about order in personal relationships and live in every other respect according to the functional relationships of the modern world and still expect to experience the scriptural directives as an unqualified blessing. In fact, bare submission to legal commands may not even be genuine obedience if it does not also understand and respond to the intention of the command—in this case, to establish order in a particular set of loving committed relationships.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1100"></a><a id="_idIndexMarker1101"></a><a id="_idTextAnchor1117"></a>The main focus of the social teaching of the New Testament is on love, not on authority and subordination. Teaching on authority clearly exists. The New Testament Christian community is a community drawn up “in subordination,” and the Christian church followed the same pattern in the first centuries of its existence. Nonetheless, the main focus of the New Testament and early church teaching on relationships is not on subordination, but on love—on the service of one another modeled on the example of Christ as he laid down his life on the cross. The content of this teaching consists primarily of instruction in Christian character and on how to meet the many situations that are trials for love. The focus of early Christian teaching, then, is on establishing the loving committed relationships of brothers and sisters in the Lord (<a id="_idIndexMarker1102"></a><span class="Italic">philadelphia</span>). The focus is on creating a body of people who care for and serve one another, who put away resentment and hostility and self-seeking, who are firmly committed to one another. It is this body of people who can effectively appropriate the Christian teaching on order and obedience.<a id="_idTextAnchor1118"></a><a id="_idTextAnchor1119"></a></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1103"></a>Thus, the Christian task in the twentieth century is to reestablish truly Christian relationships. This task faces all Christians, not just those attempting to build Christian communities. Therefore, Christian leadership in the modern world must be understood in the light of this task. Many Christian leaders today take their models of leadership from the recent past when “Christendom” was still a usable term and when the social life of the churches and society as a whole was relatively stable. They see their role as primarily teaching and leading worship services and other ritual situations. Many Christian leaders have also added some new functions taken from contemporary technological society: the administrative functions that any leader in a modern institution must fulfill, and the counseling functions modeled on the modern helping professions. These functions leave out an essential aspect of Christian leadership in the twentieth century: creating and maintaining genuine Christian relationships among Christians. It is no longer enough to teach, lead services, administer, and counsel while taking the social situation as a given. The social circumstances of technological society are currently eroding the communal relationships which are at the basis of the way of life of the body of Christ. Unless Christian leaders know how to build relationships among Christians, how to establish social situations which are more conducive to Christian life, they will be unable to combat the erosion of the corporate life of the Christian people.</p>
<h2 id="_idParaDest-99" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1120"></a><a id="_idIndexMarker1104"></a><a id="_idTextAnchor1121"></a>Restoring Christian Social Structure&#160;&#160;▹&#160; Social Roles</h2>
<p class="BODY-STYLES_Subhead-Opening"><a id="_idIndexMarker1105"></a><a id="_idIndexMarker1106"></a><span class="MaWiC_Subhead-Drop-Words">The</span> third step in applying Christian social teaching in the modern world, after grasping the vision of God’s purposes for the human race and understanding the need for a restoration of Christian relationships, is the application of the biblical teaching on social structure. A Christian social structure is an essential aspect of the full communal life of the body of Christ. It is true that such a structure cannot compensate for the absence of genuine Christian personal relationships. However, it is also true that these personal relationships derive much of their direction, strength, and order from authentic Christian social structure.</p>
<p class="BODY-STYLES_Body">Every social group needs some type of structure. Every group needs a way to order relationships, divide responsibilities, handle problems, and govern its life. There are three main types of social structure, each corresponding to a type of social grouping.<span class="Footnote-Ref"><span id="footnote-198-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-198">*</a></span></span> In real human groups these three types of structure often overlap, but one type will almost always predominate. First, there is the functional social structure which appears in functional groupings. Most modern political, economic, and service institutions are ordered according to this model. Functional groupings are organized according to clearly defined tasks and positions. Roles and responsibilities are explicitly delineated, and one qualifies for a particular position by demonstrating one’s competence. Secondly, there is the informal social structure found in informal groupings. This type of structure is particularly common in the emotionally based “personal” relationships of technological society and also in instances of social dislocation in traditional society. It characterizes most modern friendship groupings and even some modern marriages. Roles and responsibilities in informal groupings are fluid and flexible, and depend upon the changing preferences of the individuals in the group. Such groupings usually lack a definite purpose other than the satisfaction of the group’s members. Finally, there is the relational social structure which is found in relational groups (the basic groupings of traditional societies as well as relational groupings like the family that still exist in technological society). The social structure taught in the New Testament is a version of this type of social structure.</p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idTextAnchor1122"></a>Effective Social Roles</h3>
<p class="BODY-STYLES_Body-NI">Social roles are the fundamental elements of the structure of relational groupings. They are the main patterns of stable behavior in these groupings. Though many people in modern society raise various objections to social roles, it is nonetheless true that effective social roles are responsible for much of the strength, depth, and durability of genuine personal relationships.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1107"></a>The term “social role” has several different meanings. First, the sociological literature often applies the term to key elements in the structure of every society or grouping, whether the grouping be functional, informal, or relational.<a id="_idTextAnchor1123"></a><span class="Endnote-Ref">[2](#_idTextAnchor1974)</span> Since leadership and childrearing patterns are found in every society, there is always something that could be described as the “social role” of leader or parent. This is true even if the “leader” is only the person who exercises the most influence on the group in an unacknowledged way (as in an informal group), or the “parent” is only the person who this year is taking responsibility for a group of children in a communal childrearing setting (as in a strictly functional group). A second and more restrictive definition applies the term “social role” particularly to clearly defined roles as found in clearly defined institutions. Under this definition, the term is sometimes seen as applying mainly to functional roles, and is even at times contrasted with the stable personal relationships of a genuine community.<a id="_idTextAnchor1124"></a><span class="Endnote-Ref">[3](#_idTextAnchor1975)</span> A third use of the term, the one adopted here, limits “social role” to those stable roles which structure personal relationships in relational groupings. This definition highlights the important differences between relational roles and functional or informal roles, and at the same time indicates that the relational roles are the only ones which make relational social structure possible.<a id="_idTextAnchor1125"></a><span class="Endnote-Ref">[4](#_idTextAnchor1976)</span></p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1108"></a>Social roles are considerably different from functional roles. A functional role defines a set of activities or tasks that an individual regularly performs within a functional grouping. A functional role can be formulated in terms of a job description, as in the position of assembly line foreman. Many functional roles involve a certain amount of social interaction, but the interaction is functional; it is geared explicitly to the accomplishment of a limited specialized task (as with the foreman) or to the alleviation of a defined localized need (as with the worker in a modern service institution). A functional role does not require a full personal commitment. The relationship structured by the role is limited and contractual in nature. All roles in functional groupings are primarily functional roles, though they sometimes display elements more characteristic of social roles, as in the roles found in a modern doctor-patient relationship or a teacher-student relationship.</p>
<p class="BODY-STYLES_Body">By contrast, a social role cannot be formulated in terms of a job description. Its main purpose is not to structure a set of activities, but to provide a stable order for relationships involving a broad-ranging personal commitment. For example, the role of father in a family is not defined adequately by the specific tasks he performs—working forty hours per week, paying for needed commodities, driving the family car, coaching a little league baseball team. The tasks that a father performs are expressions of his role as a man in relationship to a wife and a group of children; the tasks do not define the father’s role. The tasks may vary, but the role remains the same. In fact, a father’s tasks—his job description—change greatly over time. He acts differently toward a newborn baby son, a ten-year-old son, an adult son with a family of his own, and a middle-aged son who is caring for him in his old age. The tasks differ from stage to stage, but the relationship and role should remain through all the changing functions. In an important sense, the father’s role as father is sustained from the point when he cares for the newborn son to the point when the middle-aged son cares for him. In technological society, the role of father is assuming more of the aspects of a functional role, so that the relationship between father and son now often ceases to be actively expressed when the son reaches adulthood.<span class="Footnote-Ref"><span id="footnote-197-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-197">*</a></span></span> However, when a social role such as the role of father is fully expressed, it gives form and structure to a stable committed personal relationship which cannot be defined in functional terms.</p>
<p class="BODY-STYLES_Body">Social and functional roles can also be distinguished in terms of ascription and achievement.<a id="_idTextAnchor1126"></a><span class="Endnote-Ref">[5](#_idTextAnchor1977)</span> Almost all functional roles are achieved roles, that is, positions that an individual can assume because he has displayed some ability or accomplished some goal. For example, the position of corporation executive is normally an achieved role because the executive obtains the position by demonstrating his or her competence. On the other hand, most important social roles are ascribed roles, positions that are given and not earned. For example, family roles are normally ascribed—a son is a son regardless of what he has done to obtain the position. Roles associated with age and sex are also ascribed rather than achieved. Not all social roles are ascribed. Many leadership positions in genuinely communal groupings are achieved roles. An example is the position of elder in the early Christian community. Nonetheless, the most important social roles are ascribed, and for an important reason: True relationship is rarely earned or deserved, but is usually just given. The ascribed nature of many social roles can be understood mainly in terms of both the realities of human relationships and the importance given in community (especially Christian community) to people as they are born, before and apart from any competence they display.</p>
<p class="BODY-STYLES_Body-SA">A structure based on functional principles prefers achieved roles to ascribed roles. Since efficiency and production are the main concerns of the system, positions tailored according to competence have obvious advantages. Nonetheless, such a social structure fails to provide for many essential human needs. The human realities involved in family, reproduction, childrearing, and personal (rather than technical) formation cannot be structured successfully according to achieved functional roles. Age and sex are central concerns in these human realities; any social structure that provides for these realities adequately must rely at least partially on ascribed social roles. A failure to develop effective ascribed social roles causes the breakdown of genuine community and weakens family life. The neglect of ascribed social roles also leads to problems in childrearing, the care of the elderly, and the development of secure and confident human personalities. A human community will be impoverished if it is not structured according to age and sex. <a id="_idIndexMarker1109"></a>In <span class="Italic">Male and Female</span>, Margaret Mead writes:</p>
<p class="BODY-STYLES_Block-Quote-Single">If any human society—large or small, simple or complex, based on the most rudimentary hunting and fishing or on the whole intricate interchange of manufactured products—is to survive, it must have a pattern of social life that comes to terms with the differences between the sexes.<a id="_idTextAnchor1127"></a><span class="Endnote-Ref">[6](#_idTextAnchor1978)</span></p>
<p class="BODY-STYLES_Body-NI">The same remark could be applied to differences based on age. Human life is not improved by neglecting fundamental human realities for the sake of greater functional efficiency.</p>
<p class="BODY-STYLES_Body">To be effective, social roles must have several characteristics. First, they must be stable. Social roles provide the kind of long-term enduring consistency of expectation and relationship that gives an underlying peace and strength to people’s lives. Constant role change reduces the solidity and vitality of communal life. Secondly, social roles must be clear. They must be defined clearly enough so that each individual can understand them and know in various situations what is expected of him or her. An ambiguous social role can be more difficult than no social role at all. Thirdly, effective social roles must be uniform through a particular culture or communal grouping. To be strong, social roles need the support of a whole cultural grouping. Social roles also supply the larger grouping with a basis on which it can relate together without learning a new way of life. As clear parts that all can learn allow the spontaneous performance of a communal dance or song, so a uniform set of social roles provides a group with a way to come together for communal events without the need for lengthy practice sessions. Fourthly, effective social roles must be flexible. They should be able to accommodate the normal range of human relationships, and thus should have a built-in ability to make exceptions or adapt as needed.</p>
<p class="BODY-STYLES_Body">Social roles are primarily ideals for personal relationships; they are not merely collections of laws, rules, or instructions. Some imperatives are connected with social roles. Children must obey their parents. Parents must care for and teach their children. But the role of father or mother cannot be reduced to a set of rules or instructions. In fact, social roles are taught more by example than by rules. Knowing five good fathers and watching them relate to their families is more helpful than reading five good books on the principles of fathering. A social role is a way of being in a relationship, a way of being for other people. A social role is more of an ideal of how to relate to others than a set of rules or a set of specifications.</p>
<p class="BODY-STYLES_Body">Social roles are ideals, but they are also usually embodied in teaching which the communal grouping regards as authoritative. This teaching, whether in the form of oral tradition or written documents, provides the necessary authoritative foundation for the social structure. For Christians, authoritative teaching on social structure is to be found in the Bible, the writings which represent the highest revelation of God’s plan for human life. To downplay these teachings or to dismiss this source of authority not only causes spiritual damage to God’s people, it also severely limits their ability to live out a successful Christian social structure. The authority of scripture therefore has social as well as theological implications.</p>
<p class="BODY-STYLES_Body">All of these characteristics of effective social roles illustrate the fact that social roles depend upon a living social tradition. A community passes on its way of life, and it is only when a way of life is passed on as “our way of life” that it has the authority to provide the basis for a successful communal life. Of course, a community can start a tradition and it can change its tradition. A social grouping can change its way of life. But a community does not have a way of life until its basic patterns are accepted as “our way” or “the way the Lord gave us” and are passed on with this type of authority. Social roles do not yet exist if one must go to class to learn about them. They should be experienced by people and transmitted by living together. Only then do social roles have the stability, clarity, uniformity, and flexibility needed to give peace and solidity to social relationships.<a id="_idTextAnchor1128"></a><a id="_idTextAnchor1129"></a></p>
<h3 class="HEADS---SUBHEADS_Subsubhead"><a id="_idIndexMarker1110"></a><a id="_idIndexMarker1111"></a><a id="_idIndexMarker1112"></a>Objections to Social Roles</h3>
<p class="BODY-STYLES_Body-NI">People in technological society raise many objections to social roles. Some of this negative response amounts to simple aversion: The idea of social roles makes many modern people uncomfortable. Other objections to social roles are more developed. They derive from ideological positions or from other views about the appropriate social patterns on which society should be based. These objections will be discussed here. First, objections to social roles in general will be discussed. Then more specific objections to social roles based on sex differences will be examined.</p>
<p class="BODY-STYLES_Body">One of the more frequent objections to social roles in general is the view that social roles are limiting.<a id="_idTextAnchor1130"></a><span class="Endnote-Ref">[7](#_idTextAnchor1979)</span> They prescribe patterns of social behavior without consulting the preferences of the individuals involved and without allowing them the opportunity to take a previously uncharted course. Social roles <span class="Italic">are</span> limiting, but they are limiting in the way any structure is limiting. The human skeleton limits the human body in its movement, but it also makes the human being stronger and more versatile than the amoeba. A highway limits the places a car can go, but the observance of that limitation allows the development of a travel network that yields far greater mobility than overland travel at will. Roles too are limiting. Moreover, social roles are more limiting than functional roles because they are more stable, long-lasting, and affect almost every area of a person’s life. As with other effective structures, though, the limitations imposed by social roles reap great benefits—in this case, the establishment of a stable and peaceful pattern of social life which allows communal life to flourish and which provides for the group’s needs. Social roles do not have to be rigid, but they do have to be stable enough and uniform enough to provide a sound basis for personal relationships. Those who object to roles as being limiting do not understand the value of relational social structure in promoting communal life.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1113"></a><a id="_idTextAnchor1131"></a>Two other objections to social roles in general are often raised. They are similar to the objection that social roles limit the individual. The first rejects social roles as being inauthentic; the second argues that individuals should change their social roles as they see fit.<a id="_idTextAnchor1132"></a><span class="Endnote-Ref">[8](#_idTextAnchor1980)</span> Those who reject social roles as inauthentic object that they make an individual conform needlessly to the expectations of others. They force an individual to understand himself in relationship to others, rather than as a “real” person in his own right. They are imposed from outside, alien to the real inner person. As observed in Chapters Eighteen and Nineteen, this type of objection is partly a product of the dichotomy which technological society creates between the functional world with its highly structured relationships and the personal world, which ideally is supposed to be unstructured and spontaneous.<span class="Footnote-Ref"><span id="footnote-196-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-196">*</a></span></span> Most contemporary people have little or no experience of committed relationships within a large, cohesive, structured relational grouping, and they perceive such groupings as a threat to their identity. Another source of this objection to social roles is alienation from all traditional social groupings and relationships, often including the family and the church. This sense of alienation is produced in large part by modern ideologies whose goal is to form an individualized functionally efficient technological society.</p>
<p class="BODY-STYLES_Body">Social roles may look “inauthentic” from the vantage point of technological society, but those in a genuine communal grouping do not experience them as inauthentic. Social roles do not suppress the “true identity” of the individual, but instead provide the stable social context needed for personal identity to develop properly. Human beings cannot establish identity as individuals, apart from personal relationships and membership in various social bodies. An individual search for identity independent of other people will be unending. True identity, like true personality, does not precede relationship, but is instead <span class="Italic">produced</span> by relationship.<a id="_idTextAnchor1133"></a><span class="Endnote-Ref">[9](#_idTextAnchor1981)</span> The common expectations defined by social roles can also be experienced as a great aid to communal life, not as a stifling bondage. Social roles free people from tensions which arise from the constant effort of working or living around differing expectations. Rather than being humanly inauthentic, social roles correspond to a genuine inner hunger in the human race for stable, committed personal relationships.<a id="_idTextAnchor1134"></a></p>
<p class="BODY-STYLES_Body">The second objection involves only a partial denial of social roles. This objection is raised by people who understand the need for some form of social roles, but who feel that each person or group should create these roles according to their preferences or needs. Such a view betrays the basic individualism inherent in at least the Liberal approach to technological society. This approach to social life does not aim at establishing communal relationships on a broad scale, but at creating a number of small independent groups, each following different principles of social life.</p>
<p class="BODY-STYLES_Body">In reality, this approach is unworkable. Social roles cannot be successfully improvised or devised anew by every social grouping. To devise a successful set of social roles is a great challenge. Those who attempt to create social roles anew normally make serious “ecological errors,” errors that arise because of the complexity of the system and the difficulty of fully comprehending all the relevant factors. Unfortunately, such ecological errors are not discovered quickly. For example, only after a generation has passed can a group discover the damage done by a new theory of childrearing. Moreover, the task of devising new social roles demands a great deal of creativity and a breadth of wisdom that few people possess, and almost no one possesses alone. It is enlightening to see how many primitive and traditional peoples can handle birth, death, and marriage, and all occasions of celebration and mourning in a way which cares for the people’s needs and allows them to express their deepest thoughts and experiences. By contrast, people in technological society are often incapable of handling these occasions in anything more than a perfunctory manner that is traumatic or disappointing for those involved. The social roles and social structure needed for a successful corporate human existence cannot be devised anew by every social grouping.</p>
<p class="BODY-STYLES_Body">There are two other major reasons for approaching social roles in a stable and relatively uniform way within a society or a community. First, there is a great advantage, especially in a technological society, to not having to constantly work at developing social roles.<a id="_idTextAnchor1135"></a><span class="Endnote-Ref">[10](#_idTextAnchor1982)</span> People in technological society spend much of their time in situations which call for a high degree of change and often creativity. They need an area of life where they can rest from such effort, confident of stable support and commitment, with a clear understanding of how to behave in relationship to others. If social relationships are turned into as much of a task as work relationships are currently in our society, then much of their purpose and usefulness has been lost. Second, an isolated family or small group lacks the strength needed to develop a pattern of social roles different from the surrounding society. The family unit in technological society is not a total environment; it cannot singlehandedly resist the currents of society which influence its members through the school system, the work site, the neighborhood, friends, and the media. Social roles cannot be left to the discretion and ingenuity of each small societal unit, but must instead be developed and sustained consistently within a larger social grouping.</p>
<p class="BODY-STYLES_Body"><a id="_idTextAnchor1136"></a>In technological society, objections are raised to all types of social roles. Roles built on the parent-child relationship, the teacher-student relationship, the employer-employee relationship, and differences in age and sex are all dismissed or functionalized. Social roles based on differences in sex, in particular, evoke some of the most heated negative responses. Two types of objections to social roles in general arise especially in connection with men’s and women’s roles: that these roles are discriminatory, and that they foster stereotypes.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1114"></a><a id="_idIndexMarker1115"></a>The idea that social roles based on sex differences are discriminatory has been vigorously advanced within the feminist movement.<a id="_idTextAnchor1137"></a><span class="Endnote-Ref">[11](#_idTextAnchor1983)</span> Feminists have consistently attempted to equate racial differences and sex differences, and to say by analogy that making distinctions between people on the basis of sex is the same as making distinctions on the basis of race.<a id="_idTextAnchor1138"></a><span class="Endnote-Ref">[12](#_idTextAnchor1984)</span> The term “sexism” has been coined to express this similarity. Feminists have thus been able to capitalize on the widespread social disapproval of racism by portraying distinctions between men and women as “racism” against women.</p>
<p class="BODY-STYLES_Body">This equation of race and sex falsely presumes that the two issues are the same in all significant respects. However, racial distinctions occur <span class="Italic">between</span> social groupings, whereas sexual distinctions occur <span class="Italic">within</span> social groupings. Barring someone from a position solely on the basis of race is discrimination. It is a way of preserving an advantage for one’s own social group. Barring someone from a position because she is a woman might be discrimination, especially in a functionally organized grouping, such as a modern business firm. However, within a relational grouping, a sexual distinction may well be a useful and proper attempt to establish an effective social structure through social roles. Such roles need to be ascribed rather than achieved. In relational groupings, where the primary concern is for relationship and not function, the observance of certain distinctions between people on the basis of age and sex rather than competency is not necessarily discrimination. It is a way to maintain and strengthen social roles.</p>
<p class="BODY-STYLES_Body">The second objection often made to social roles based on sex differences is that such roles foster stereotypes.<a id="_idTextAnchor1139"></a><span class="Endnote-Ref">[13](#_idTextAnchor1985)</span> This objection also arises from the equation between race and sex. Stereotypes of different races often lead to discrimination or to the treatment of all members of a race as inferior. To be sure, there are stereotypes of men and women that are harmful and scientifically inaccurate. For example, an idea that women are deficient in intelligence or ability would be both disrespectful and false. As stated in Chapters Sixteen and Seventeen, the primary differences between men and women do not lie in ability but in their varying responses within personal relationships.<a id="_idTextAnchor1140"></a><span class="Endnote-Ref">[14](#_idTextAnchor1986)</span> However, the idea that women are primarily interested in family life and children should not be considered a stereotype. It strengthens a social role of great importance, and fits with much of the available scientific data. In effect, the attack on stereotypes of women is often an attack on recognizing the genuine differences between men and women and also an attack on the reinforcement of stable social roles.</p>
<p class="BODY-STYLES_Body">Though many people in modern society object to social roles, such roles play an integral part in the formation of any truly communal lifestyle and in the authentic Christian approach to social structure. Social roles are the backbone of all relational groupings. It is no accident that where social roles are weak, personal relationship is weak. Social roles are an important way of bringing strength to personal relationships. In fact, community disintegrates when a purely functional or informal approach to roles prevails. If the Christian people are to recapture a communal life, they must learn to structure their life together as a people around relational groupings based on social roles.<a id="_idTextAnchor1141"></a></p>
<h2 id="_idParaDest-100" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1142"></a><a id="_idIndexMarker1116"></a><a id="_idIndexMarker1117"></a><a id="_idTextAnchor1143"></a>Alternate Social Patterns&#160;&#160;▹&#160; Traditionalism and Socialism</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">The</span> body of Christ is intended by God to be a people, a community, with a defined structure and way of life. Many people in modern Western society completely reject this social pattern. They reject social roles, advocate minimal social control, and take an informal “laissez-faire” approach to social life, rooted in Western individualism and Liberal ideology. This approach is clearly inconsistent with God’s purposes for the new human race. It lacks corporate vision, and leads ultimately to a type of social disorganization which prevents the development of communal life.</p>
<p class="BODY-STYLES_Body">However, even given that God’s plan involves the building of a people, the scriptural approach to personal relationships and social structure outlined here is not the only option. There are two other common approaches to the structuring of a people that differ considerably from the scriptural approach. One pattern could be called “traditionalist,” the other “socialist.” Though differing from scriptural principles on several counts, both of these approaches have been adopted by Christians in the past and the present. In order to accurately understand the scriptural principles of social structure, it is helpful to perceive how these patterns differ from the scriptural pattern.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1118"></a>The first pattern is called “traditionalist” because it represents the approach of traditional Western society and of most other traditional societies. This pattern includes social roles, and it orders society on relational rather than functional lines. Loyalty to the family or clan is of extreme importance, sometimes to the disadvantage of other wider communal commitments. The traditionalist pattern also accepts status considerations that come from birth and wealth. Thus a traditionalist society normally has privileged classes and privileged social groupings. The traditionalist approach is no longer a strong force in Western society. Those who defend it do so more as a way to maintain the status quo than as a vision for a restoration of traditional society.</p>
<p class="BODY-STYLES_Body">A Christian approach to social structure based on the teachings of scripture differs from the traditionalist approach on several points. The scripturally based Christian approach values the family highly, but it places the family within the wider set of commitments of the body of Christ. Such an approach does not value the status quo for itself, nor does it defend a privileged class, a privileged social group, or the unmoderated accumulation of wealth. In fact, the scriptural approach to social structure articulates a significant principle of equality in goods and services. This principle runs counter to much within the traditionalist approach. “To each according to their needs” is a principle of Christian community (<a id="_idIndexMarker1119"></a>Acts 4:35), and applies especially to the sharing of material goods (<a id="_idIndexMarker1120"></a>1&#160;Cor 8:14). Behind this sharing of goods is a kind of joint ownership (<a id="_idIndexMarker1121"></a>Acts 4:32) that means that everyone’s goods belong to the brotherhood, even though each person will normally administer a certain amount of these goods as the steward of God and the community.</p>
<p class="BODY-STYLES_Body-SA">The scriptural principle of equality does not mean treating everyone the same, but rather treating everyone according to their need, relating to all with equal care. Behind the scriptural principle of equal care is an understanding of the equal value of all the brothers and sisters in the Lord (<a id="_idIndexMarker1122"></a>1&#160;Cor 12:21<span class="No-Break">–2</span>6) so that it is normally the weakest who receive the greatest care and often special honor. In the <a id="_idIndexMarker1123"></a><a id="_idIndexMarker1124"></a>Epistle to Diognetus, an early Christian writing from the first part of the second century, the teaching on equal care receives special attention:</p>
<p class="BODY-STYLES_Block-Quote-Single">Once you have grasped these truths, think how your joy will overflow, and what love you will feel for Him who loved you so. And if you love Him, you will become an imitator of His goodness. Do not be surprised that a man should be an imitator of God; he can, since God has willed it so. But happiness is not to be found in dominating one’s fellows, or in wanting to have more than his weaker brethren, or in possessing riches and riding rough-shod over his inferiors. No one can become an imitator of God like that, for such things are wholly alien to His greatness. But if a man will shoulder his neighbour’s burden; if he be ready to supply another’s need from his own abundance; if, by sharing the blessings he has received from God with those who are in want, he himself becomes a god to those who receive his bounty—such a man is indeed an imitator of God. And then you will see, as you walk the earth, that there is a God who is operative in heaven; then you will begin to dilate on His mysteries; and you will know love and admiration for those who incur persecution by their refusal to deny Him. Then, too, you will see through the deceitfulness and error of this world, once you have found what it is to live the true life of heaven&#160;.&#160;.&#160;.<a id="_idTextAnchor1144"></a><span class="Endnote-Ref">[15](#_idTextAnchor1987)</span></p>
<p class="BODY-STYLES_Body-NI">Christian community, as presented in early Christian writings and in scripture, militates against class distinctions (<a id="_idIndexMarker1125"></a>Jas&#160;2:1<span class="No-Break">–7</span>). This does not necessarily mean that the wealthy must give away all their wealth, but it does mean that they must relate to others in the body as their brothers and sisters and they must approach their wealth communally (<span class="Italic">koinōnikos</span>, <a id="_idIndexMarker1126"></a>1&#160;Tm 6:17<span class="No-Break">–1</span>9). The Christian principle of equality calls for a personal commitment of generosity and sharing from person to person on the basis of a committed relationship.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1127"></a>The second major approach to social structure is the “socialist” pattern, corresponding closely to the modern Socialist ideal for society. In the socialist pattern, relationships are highly functionalized. The group as a whole is treated as a collective of individuals. Equality is understood as a principle of treating everyone the same. Leaders function primarily as policy makers and administrators, and social control is exercised in a collective fashion. The family unit becomes attenuated. Patterns of relationship and order are explicitly developed and people are educated in living according to these patterns. In short, the socialist pattern is based on a consistent application of a functional approach to society as a whole.</p>
<p class="BODY-STYLES_Body">The scriptural approach to social structure differs considerably from the socialist approach.<a id="_idTextAnchor1145"></a><span class="Endnote-Ref">[16](#_idTextAnchor1988)</span> Rather than undermining the fundamental relational groupings of society, a scriptural approach builds its communal life upon these very groupings. The scriptural pattern values the natural human structures provided by age and sex, and puts priority on family life and social roles. It emphasizes personal relationships, not functional efficiency. Leadership is exercised in a personal relationship which involves subordination and individual direction. The scriptural principle of equality is also very different from the socialist version of the same principle. It does not undermine social roles or personal subordination, nor does it claim that all individuals should be treated identically except for ability or interest differences. The Christian principle of equality is preeminently a principle of equal love (equal care). It is not a principle that would collectivize and bureaucratize the community so that everyone can get a fair share even should the people not love one another. It is not a principle which eliminates social roles in favor of functional roles, but a principle which founds all social roles in personal relationships of brotherly love, care, and service.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1128"></a><a id="_idIndexMarker1129"></a>One traditional Christian model of social structure, the monastic model, bears a certain resemblance to the socialist approach.<span class="Footnote-Ref"><span id="footnote-195-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-195">*</a></span></span> In a monastic community, all property is held in common. All activities are pursued collectively. A principle of equality based on equal treatment receives special stress. The basic unit of the monastic collective is the individual, rather than a familial relational grouping structured according to social roles. In all these aspects the monastic model of social structure resembles the socialist approach. This resemblance exists because a monastic community is designed exclusively for adult celibates, and therefore eliminates many of the elements of the scriptural approach to communal life which are associated with family structure.<a id="_idTextAnchor1146"></a><span class="Endnote-Ref">[17](#_idTextAnchor1989)</span></p>
<p class="BODY-STYLES_Body">Nonetheless, it is deceiving to draw too close a parallel between a monastic and a socialist model of social structure. Though monastic communities operate without family groupings and family structures, many of the relationships and roles within a monastic community are patterned after a familial design. The primary relationship among the members of the community is a brotherly or sisterly relationship involving a personal commitment. Its model is the relationship between brothers and sisters in a family. In much of monastic tradition, the older brothers or sisters (those who have seniority at the monastery) receive special honor regardless of their gifts or the functional importance of their role in the community. In addition, the pattern of authority in monastic groupings traditionally resembles a relational Christian approach more than a functional socialist approach. The abbot or elder or superior is not merely a representative of the collective will, but is one who exercises authority within a personal relationship that involves personal subordination on the part of those under his authority. Furthermore, monastic authority relationships have frequently been modeled on the traditional master-disciple relationship, a close parallel to the father-son relationship.<span class="Footnote-Ref"><span id="footnote-194-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-194">*</a></span></span> In short, the underlying dynamic of the monastic model of social structure is analogous to the dynamic of family life—but to the dynamic of traditional family life built on commitment and enduring roles, not to modern family life built on emotional intensity and limiting the exercise of authority to the adult-child relationship. The monastic model superficially resembles the socialist approach because it is designed for a community of celibates, but at root it is merely a variation of the Christian approach found in scripture.<span class="Footnote-Ref"><span id="footnote-193-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-193">†</a></span></span></p>
<p class="BODY-STYLES_Body">The Christian approach to social structure differs from both a traditionalist approach and a socialist approach. The body of Christ is intended by God to be a people, a community, based upon personal relationships of committed love, structured as a relational grouping with social roles, and ordering the flow of goods and services according to a principle of equal care. Christians in the twentieth century should adopt this approach rather than an alternate approach for two primary reasons. First, this pattern is taught in the New Testament and by the Fathers of the church as the approach which is in harmony with God’s intention for the human race. Secondly, it is also the approach which best meets a need that technological society is incapable of satisfying. The Lord planted in the human heart a hunger for genuine family and community relationships. He intended to satisfy that hunger by sending his son Jesus to restore his creation and to form those who believe in him into a new people. If God’s full purpose for his people in the twentieth century is to be fulfilled, the Christian people must understand and apply the scriptural teaching on community, personal relationships, and social roles.<a id="_idTextAnchor1147"></a></p>
<div class="Next-Chapter"><a href="Man-and-Woman-in-Christ_ebook-export-30.xhtml">Skip footnotes ▸</a>
</div>
<div class="_idFootnotes">
<div id="footnote-202" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-202-backlink">590*</a>The term “community” is used here and elsewhere in this book to refer to a social environment with some real stability and cohesiveness. The term “community” is sometimes reserved to refer to smaller groupings of people who live together (in communal dwellings as on communal plots of land) and/or who own all property together. Here the term is used more broadly to refer to a social environment, that is, one in which people interact on more than a functional basis. However, the scriptural approach to the corporate life of the Christian people presupposes a particular type of social environment, namely, one in which the relationships among Christians have the kind of commitment that embraces the whole of a person’s life. Such commitments are more like modern family commitments than like modern functional relationships where commitments are limited and often contractual. Hence a full Christian community or full Christian communal life refers to a corporate life involving a stable cohesive social environment based on commitments embracing the totality of people’s lives, but not necessarily involving living together or common ownership of property.</p>
</div>
<div id="footnote-201" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-201-backlink">591*</a>See Chapter Two, pp.&#160;<a href="Man-and-Woman-in-Christ_ebook-export-5.xhtml#_idTextAnchor057">36</a><span class="No-Break">–</span><a href="Man-and-Woman-in-Christ_ebook-export-5.xhtml#_idTextAnchor062"><span class="No-Break">39</span></a>, for background to this section.</p>
</div>
<div id="footnote-200" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-200-backlink">594*</a>See Chapter Eighteen, pp.&#160;<a href="Man-and-Woman-in-Christ_ebook-export-25.xhtml#_idTextAnchor927">483</a><span class="No-Break">–</span><a href="Man-and-Woman-in-Christ_ebook-export-25.xhtml#_idTextAnchor940"><span class="No-Break">491</span></a>, for background to this section.</p>
</div>
<div id="footnote-199" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-199-backlink">596*</a>As mentioned in Chapter Eighteen, p.&#160;<a href="Man-and-Woman-in-Christ_ebook-export-25.xhtml#_idTextAnchor955">496</a>, Christian service institutions such as hospitals and orphanages antedate the rise of technological society by many centuries. Their existence did not disrupt the communal life of the medieval city, but instead supplemented the relational care systems of the various familial and extrafamilial groupings. However, it must also be acknowledged that the Christian service institutions of the twentieth century are very different from those of earlier centuries. The modern Christian service institutions have (perhaps of necessity) adopted many of the organizational and therapeutic techniques found in secular institutions. As a result, the modern Christian service institution is more functionally oriented than its predecessors.</p>
</div>
<div id="footnote-198" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-198-backlink">599*</a>For some background on these three types of structures and groupings, see Chapter Eighteen.</p>
</div>
<div id="footnote-197" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-197-backlink">601*</a>A pressure is exerted against all social roles in technological society, with the result that many traditional social roles begin to look more like functional roles. The father-son relationship is one example. Another example can be found in the role of the Christian pastor. One reason that modern Christians have a difficulty in understanding the meaning of “elder” or “pastor” in the New Testament is their tendency to see the position as a set of functions to be performed in a social institution rather than as a role of leadership and care in a communal relationship.</p>
</div>
<div id="footnote-196" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-196-backlink">605*</a>See Chapter Eighteen, pp.&#160;<a href="Man-and-Woman-in-Christ_ebook-export-25.xhtml#_idTextAnchor961">498</a><span class="No-Break">–</span><a href="Man-and-Woman-in-Christ_ebook-export-25.xhtml#_idTextAnchor962"><span class="No-Break">500</span></a>, and Chapter Nineteen, pp.&#160;<a href="Man-and-Woman-in-Christ_ebook-export-26.xhtml#_idTextAnchor1044">529</a><span class="No-Break">–</span><a href="Man-and-Woman-in-Christ_ebook-export-26.xhtml#_idTextAnchor1045"><span class="No-Break">530</span></a>.</p>
</div>
<div id="footnote-195" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-195-backlink">611*</a>The monastic communities gave rise to special “apostolic communities” such as the Dominicans and the Jesuits. These newer communities differ from the traditional monastic model in that they are formed for the purpose of fulfilling certain tasks of service within the church rather than merely for the purpose of living a way of life together. The apostolic community is a variation on the more basic model of the monastic community, and is not the major object of concern in these paragraphs.</p>
</div>
<div id="footnote-194" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-194-backlink">612*</a>While the father-son relationship is sometimes the model for the superior-brother relationship, this model is usually adopted only when there is an underlying view of the abbot or the elder as a master who is raising up disciples in the Lord. The more basic monastic model is that of a group of brothers or sisters living together, and many monasteries did not see the governor as an abbot (father). The spread of the father-son model within monastic groupings owes much to the influence of Benedict. Benedict took the word <span class="Italic-Caption">abbas</span> (commonly translated “abbot”) from the master-disciple relationship and applied it to the head of a coenobium. Eastern monasticism tended to use less paternal titles such as “ruler” (<span class="Italic-Caption">hēgoumenos</span>) and “superior” (<span class="Italic-Caption">proestos</span>). The Benedictine usage may have arisen because Benedict envisioned the monastery as primarily for training and saw the solitary life as the goal for the more mature.</p>
</div>
<div id="footnote-193" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-193-backlink">612†</a>Though the traditional monastic model is merely a variation of the Christian approach found in the scripture, it should be observed that there is movement among modern religious toward a more socialist approach and even at times toward a more informal “laissez-faire” approach.</p>
</div>
</div>
