# [4]{.HEADS---SUBHEADS_Part-Number} A Christian Approach for Today {-}

<a id="_idParaDest-95"></a><a id="_idTextAnchor1109"></a>
<p class="BODY-STYLES_Part-Opening"><span>▸&#160;&#160;</span><span class="Opening-Drop-Words"><span class="No-Ligatures">Th</span>e previous part of this book</span> treated the “gap” that exists between the times of the New Testament and the modern world, and laid the foundation for applying the scriptural teaching in the lives of Christians today. <span class="No-Ligatures">Th</span>e concluding part develops a sketch for how Christians should approach the roles of men and women in the midst of the contemporary situation. <span class="No-Ligatures">Th</span>is sketch could be seen as a pastoral proposal for how Christians can both be faithful to scriptural teaching and live viable and effective lives in the modern world. <span class="No-Ligatures">Th</span>e concluding part begins with a chapter which sketches in the basic components of the pastoral approach. <span class="No-Ligatures">Th</span>e next chapter presents more specific guidelines. Chapter Twenty-<span class="No-Ligatures">Th</span>ree deals with certain issues involved in implementing the proposed pastoral approach. <span class="No-Ligatures">Th</span>e final chapter treats some special areas of concern and the way in which the pastoral approach would touch upon those areas.&#160;&#160;▸</p>
