# Afterword {-}

<h1 id="_idParaDest-119" class="F-B-MATTER_F-B-Matter-Section-Name"><a id="_idTextAnchor1209"></a>Afterword</h1>
<p class="BODY-STYLES_Chapter-Opening"><span class="Drop-Cap">P</span><span class="Opening-Drop-Words">hysical exercise</span> has become popular in many places in the Western world as people have become aware of the fact that life in a technological society can have adverse effects on their physical well-being. Yet exercise seems to be a very strange activity. Human beings have worked for hundreds of years to develop techniques to free themselves from the necessity of physical exertion. Now many people are building extra physical exertion into their lives—and pointless physical exertion at that. Running, for example, does not bring a person to any destination in particular. Normally, in fact, runners return to the same point from which they started without doing anything—apart from exercising—to justify their trip.</p>
<p class="BODY-STYLES_Body">The popularity of exercise is a symptom of the fact that human beings were not designed to live in modern technological society. Modern society does not allow everything in human nature to work well. Human beings were designed to do more work involving physical exertion than what ordinary daily life allows for many of them today. Hence the exercise to compensate.</p>
<p class="BODY-STYLES_Body">Our modern technological society also “leaves out” other aspects of our human nature. The differences between men and women are one of those aspects. Men and women are different. Scripture teaches that they were created to be different, because God has a purpose for that difference. Common sense indicates that men and women are different—not only in the obvious physical ways but also in their psychological makeup. Modern social science has been able to confirm that indeed there are real, biologically rooted differences between men and women, and that these differences have led all human societies in the past to structure their life so that men and women had different social roles. To say that men and women are different seems like stressing the obvious. Indeed, in a less politicized time, this would be so. Much of what has been written in this book, in fact, amounts to restressing the obvious.</p>
<p class="BODY-STYLES_Body">We do need to find ways to live out our differences of age and sex in modern functionalized society, a society that tends to leave out these aspects of our humanity—or tends to see them as inconveniences. There are advantages to having both men and women. Men and women are able to make different, complementary contributions in human life. Perhaps the pastoral recommendations made in this book do not express the best way of living out these differences. But some way has to be found, some way that corresponds to what every human society has done in the past. Some guidelines like these, at least, have to be developed.</p>
<p class="BODY-STYLES_Body">Christians do not have to live like the nations around them. In a society that is losing its grasp on some basic human realities, Christians have the opportunity to show that God’s revelation allows them to live with greater wisdom. Christians should be able to have a life together that draws the full advantage from the differences God created into men and women. They are called, after all, to be fashioned in God’s image and likeness, to be the new Adam, to be human beings who reflect God’s purposes for the human race.</p>
