# Guide&#173;lines for a Modern Christian Approach to Men’s and Women’s Roles

<a id="_idParaDest-101"></a><a id="_idTextAnchor1148"></a>
<p class="BODY-STYLES_Chapter-Opening"><a id="_idIndexMarker1130"></a><span class="Drop-Cap">A</span><span class="Opening-Drop-Words">s stated in the last chapter</span>, it is not enough for modern Christians to merely apply the scriptural directives on the roles of men and women. In order to fully live out the social teaching contained in the scripture, Christians need to have their basic way of life reshaped. Only then can the scriptural teaching achieve its original purpose: the ordering of the life of a body of men and women who are followers of Christ and who form in him the new humanity. A full and ideal application of the scriptural teaching on men’s and women’s roles must be founded on both an understanding of God’s purpose—the formation of a new humanity in Christ—and on the establishment of committed communal relationships in Christ ordered by a genuinely Christian social structure.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e scriptural teaching on men’s and women’s roles presumes that this teaching will be applied within the context of a Christian body. It is true that some of this teaching, particularly the teaching on family life, can be applied even outside such a communal setting. Still, the scriptural approach to men’s and women’s roles can be expressed most effectively among a group of people who are living a communal life. Chapter Twenty-One set forth the basic principles of this communal life. <span class="No-Ligatures">Th</span>is chapter will offer some practical guidelines on how to translate these principles into a living Christian body where the roles of men and women will find a meaningful place. <span class="No-Ligatures">Th</span>ese guidelines are derived from several sources. Some are presumed in scripture; some are explicitly taught in scripture; some derive from the need to adapt the scriptural teaching to modern social conditions. Nonetheless, all of the guidelines have the same purpose: to set forth a specific, workable approach to the patterning of modern bodies of Christians so that they can conform to the intention of the scriptural teaching on corporate life and men’s and women’s roles.</p>
<p class="BODY-STYLES_Body">Most of the guidelines in this chapter can be applied fully only within a Christian body that has a communal life. <span class="No-Ligatures">Th</span>us the material in this chapter will be most directly relevant for those who can participate in such a body. For those not in this position, these guidelines will help to clarify the Christian teaching on men’s and women’s roles and its application in the modern world. Insight into God’s plan is valuable even when it cannot be fully acted upon. Also, the final set of guidelines in this chapter should prove particularly useful to people who do not belong to such a Christian body. <span class="No-Ligatures">Th</span>ese guidelines point out the need for flexibility in living out the Christian teaching on men’s and women’s roles in the modern technological world. <span class="No-Ligatures">Th</span>is flexibility is needed by Christian communities, but even more by those unable to participate in such communities.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is chapter contains four main sets of guidelines. <span class="No-Ligatures">Th</span>e first lays out social prerequisites for a Christian communal approach to men’s and women’s roles. <span class="No-Ligatures">Th</span>e second set of guidelines presents the main elements of the scriptural teaching on men’s and women’s roles in the family and the larger Christian community. <span class="No-Ligatures">Th</span>e third set offers some suggestions for meeting certain needs peculiar to the social conditions of technological society. Finally, the fourth set enunciates some simple principles for relating the scriptural teaching on men’s and women’s roles to the surrounding society. <span class="No-Ligatures">Th</span>ese guidelines represent an attempt to distill from the first twenty-one chapters of this book a collection of succinct practical pastoral principles for approaching men’s and women’s roles in the modern world.</p>

<a id="_idTextAnchor1149"></a><a id="_idParaDest-102"></a>

## Basic Prerequisites for Men’s and Women’s Roles {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> first set of guidelines describes in practical terms basic patterns of life which are essential prerequisites for a community life in which men’s and women’s roles can be expressed. <span class="No-Ligatures">Th</span>ese prerequisites involve “brother-sister love” and the need for a family-household unit operating as an integral part of the community.</p>
<ol>
<li value="1" class="BODY-STYLES_L-O-Num-L1-Subsubhead-1st"><!--<span class="Body-List-Counter-Float">1.</span>--><span class="Italic"><a id="_idIndexMarker1131"></a><a id="_idIndexMarker1132"></a>“Brother-sister love” (<span class="Italic">philadelphia</span>) is the basis for all social roles and social relationships among the Christian people.<span class="Footnote-Ref"><span id="footnote-216-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-216">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e basic relationship among members of the Christian community is the relationship that comes from their common identity as Christians born anew with the life of God—the relationship of brothers and sisters in the Lord. <span class="No-Ligatures">Th</span>ose who belong to the Christian people are committed to one another as members of the same body. Each member—male or female, Jew or Gentile—is entitled to receive the full care and service of the brothers and sisters. <span class="No-Ligatures">Th</span>us the fundamental principles which govern Christian relationships are identical for both men and women. <span class="No-Ligatures">Th</span>ese relationships should be conducted in kindness, patience, and humility, free of resentment, hostility, and lust. All relationships in the body of Christ should be built on committed love and should manifest the fruits of the Holy Spirit.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e importance of <span class="Italic">philadelphia</span>, brother-sister love, in the Christian community also means that men and women in the community should relate to one another primarily as brothers and sisters in the Lord and not as members of the opposite sex. Christian men and women are first of all human beings redeemed by Jesus Christ and placed in the same family; and they should be able to express the love, affection, and loyalty of brothers and sisters. <span class="No-Ligatures">Th</span>is does not mean that a person should relate exactly the same to men and women. Because human beings are sexual creatures, it is necessary to observe some rules of distance, of limited intimacy. However, such limitations need not diminish the expression of <span class="Italic">philadelphia</span>. While there are some differences that should exist in the manner of relating to men and to women, these differences should not overshadow the sameness of love and respect shown all Christians simply because they are brothers and sisters in the Lord.</p>
<ol>
<li value="2" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">2.</span>--><span class="Italic"><span class="No-Ligatures">Th</span>e home should be a center of care and service.<span class="Footnote-Ref"><span id="footnote-215-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-215">†</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e home and family have lost key functions in technological society, and hence the role of the household has diminished in significance. However, the home in the Christian community should be a center of social life, the primary place where people live their lives and serve and care for others. <span class="No-Ligatures">Th</span>us, in order to restore Christian family life and the roles of men and women, the family needs to assume a more prominent role as a center of Christian life, a place where many of the needs of the Christian community are met.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1133"></a>Many areas of service should be performed largely within a household setting. Childrearing is one of the primary responsibilities and services of the family household. A full Christian approach to childrearing involves more training and formation than is currently common in modern society, and this training should occur largely in the household. Also, the family unit can sometimes perform important community services by taking people in to live temporarily or even sometimes permanently. More normally, the household will provide community service by receiving guests, helping the needy, supporting community activities, evangelizing people outside the Christian community, and welcoming brothers and sisters in the Lord.</p>
<p class="BODY-STYLES_Body">An approach which makes the family a center of care and service has two particularly significant benefits. First, it will usually improve the quality of the service. Childrearing, charitable works, hospitality, evangelism, and many other services are best performed within a network of committed personal relationships rather than through special institutions. Secondly, the woman’s domestic role will become more significant in the community as the responsibilities of the household increase. <span class="No-Ligatures">Th</span>is frees the woman from the typical modern female dilemma: whether primarily to take responsibility for the household and thereby assume a role that has less and less importance and interest, or to primarily pursue a career and thereby abdicate domestic responsibility.</p>
<ol>
<li value="3" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">3.</span>--><span class="Italic"><a id="_idIndexMarker1134"></a><a id="_idIndexMarker1135"></a><a id="_idIndexMarker1136"></a><a id="_idTextAnchor1150"></a><a id="_idTextAnchor1151"></a><span class="No-Ligatures">Th</span>e Christian community should provide a supportive environment for family life.<span class="Footnote-Ref"><span id="footnote-214-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-214">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e forces of technological society have weakened the kinship network which traditionally provided a valuable supportive environment for the family. In technological society, the Christian community should assume those supportive functions once performed by the kinship network. <span class="No-Ligatures">Th</span>e community should be like an extended family. It should not compete with the family for the loyalty of the individual (as sometimes happens in socialist societies). Nor should it operate according to principles completely different from those obtaining in the family (as is the case in most technological societies). Instead, the Christian community should be a larger fabric of personal relationships into which the family unit is tightly integrated. Existing extended family relationships which are still cohesive need not be weakened, but can be fit into the broader community support system. In fact, a Christian community can often help restore healthy kinship structures.</p>
<p class="BODY-STYLES_Body">A Christian community can provide support for the family unit in many ways, most of which were once provided by the kinship network. <span class="No-Ligatures">Th</span>e community provides the larger social environment which supports family relationships and family order by maintaining a consistent and uniform pattern of social roles. Like the members of an extended family, the brothers and sisters in the larger Christian community should recognize their obligation to aid each individual family unit in times of crisis and special need. <span class="No-Ligatures">Th</span>e Christian community should also provide instruction on Christian family life. As in an extended family, this instruction should not be transmitted primarily through classes but through a network of personal relationships in which people can learn from those who are experienced in family life and have met the various life crises and life experiences in a Christian way. <span class="No-Ligatures">Th</span>e Christian community should also provide supportive relationships among the men (husbands) and among the women (wives) in the community. <span class="No-Ligatures">Th</span>ese relationships should strengthen the men and women in their distinctive responsibilities and also prevent the women from being isolated in their nuclear family units. In general, the community should provide women with ways to be fully a part of communal life.</p>
<p class="BODY-STYLES_Body">Many modern people, Christians and non-Christians alike, have attempted to strengthen the family by directly buttressing the nuclear family unit. In many ways this seems to be the most obvious course of action. However, the evidence from anthropology and social history indicates that the nuclear family is only strong when it exists in the context of a larger extended-family system. Such a system need not be completely built on lineage, but it must involve the commitment of the nuclear family to a larger social grouping.<a id="_idTextAnchor1152"></a></p>

<a id="_idTextAnchor1153"></a><a id="_idParaDest-103"></a>

## Key Biblical Teaching on Men’s and Women’s Roles {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> following five guidelines summarize the main body of biblical teaching on men’s and women’s roles. <span class="No-Ligatures">Th</span>ey point to essential features of communal life that have been seriously weakened and sometimes eliminated in modern technological society and in many modern churches. If Christian communal life is to be restored to full vitality in the modern world, these features must also be restored to their proper strength. <span class="No-Ligatures">Th</span>e following five guidelines therefore have as their aim a type of restoration—not necessarily a restoration of elements altogether lacking, but a restoration of these elements to their original vitality and strength.<a id="_idTextAnchor1154"></a></p>
<ol>
<li value="4" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">4.</span>--><span class="Italic"><a id="_idIndexMarker1137"></a><a id="_idIndexMarker1138"></a><a id="_idTextAnchor1155"></a><span class="No-Ligatures">Th</span>ere should be a system for raising people in the Lord with men having primary responsibility for men and women for women.<span class="Footnote-Ref"><span id="footnote-213-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-213">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>is guideline contains two main elements. First, there should be a system for raising people in the Lord. Children in the family and young or new people in the community should receive personal formation in the Christian life. <span class="No-Ligatures">Th</span>is formation should involve training in character, personal relationships, and social roles, as well as the passing on of practical and useful skills. Secondly, this system for raising people in the Lord should place the main responsibility for the young men in the hands of other men, and for the young women in the hands of other women. <span class="No-Ligatures">Th</span>is means that the father should primarily raise his sons and the mother raise her daughters, though the father-daughter relationship should be strong enough to give the daughter an experience of her father’s love and protection. <span class="No-Ligatures">Th</span>is also means that the mature men in the Christian community should raise the men who are younger in age and Christian experience in Christian living and service, and the more mature women should do likewise for the younger women.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>is approach to personal formation is a constant feature of societies that have not been affected by the spirit of technological society. Modern technological society is probably the first human society to entrust the rearing of younger men primarily to women and to mix the sexes together indiscriminately and give them the same instruction and education. <span class="No-Ligatures">Th</span>ere is some indication that this practice could cause significant social problems.<span class="Footnote-Ref"><span id="footnote-212-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-212">†</a></span></span> At least it is clear that it will be more difficult for young men to grow into mature Christian manhood if they are not reared by mature men, and it will be more difficult for young women to grow into mature Christian womanhood if they are not reared by mature Christian women. Roles must be learned if they are to function successfully. A full restoration of men’s and women’s roles will require a certain amount of role training. <span class="No-Ligatures">Th</span>is training must occur within personal relationships among older and younger people of the same sex in which older persons teach younger ones how to live as Christian men or women.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e model for raising people in the Lord followed in many modern churches involves women educating the children up to the age of ten or twelve years and men educating the adults. <span class="No-Ligatures">Th</span>e women staff most of the earlier grades in catechism classes and Sunday schools, while the men, in their positions as ministers and priests, do most of the teaching of adults. <span class="No-Ligatures">Th</span>is model, which is a fairly recent development, is not the ideal for Christian formation. Women should provide the primary care for both boys and girls during the first years of life, but at a certain point the men should take over the primary responsibility for the training of the boys. Similarly, the more mature Christian women in the community should assume responsibility for the care and training of the other adult women. Male pastors should not be doing all the adult training. In fact, close to half of the adult pastoral care, teaching, training, and counseling in the community—that provided for women—should ordinarily be done by women.</p>
<p class="BODY-STYLES_Body">One important consequence of this communal approach to personal formation is that people’s primary relationships should not mainly be with age-peers, but rather they should engage in significant relationships with people both older and younger than themselves. <span class="No-Ligatures">Th</span>e daily life of the community should be in large part lived in cross-generational groupings, involving children, younger men and women, older married men and women, and older single men and women. Young people therefore do not spend most of their time in specially segregated age groupings, but are instead integrated into the adult world of the community.<a id="_idTextAnchor1156"></a></p>
<ol>
<li value="5" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">5.</span>--><span class="Italic"><a id="_idIndexMarker1139"></a><a id="_idIndexMarker1140"></a><a id="_idIndexMarker1141"></a><span class="No-Ligatures">Th</span>ere should be different areas of responsibility for men and for women.<span class="Footnote-Ref"><span id="footnote-211-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-211">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI">In social systems that are uninfluenced by the spirit of technological society, men and women have distinct spheres of responsibility. <span class="No-Ligatures">Th</span>e nature of these responsibilities varies from culture to culture, but the distinction between male and female spheres is always clear. <span class="No-Ligatures">Th</span>is clear distinction of roles allows large social groupings to gather and function without extensive organizational planning. <span class="No-Ligatures">Th</span>e women naturally care for their responsibilities and the men do likewise. Normally there is also an understanding of precedence so that it is clear in any group who has the responsibility to take the lead. <span class="No-Ligatures">Th</span>is type of clear sexual division of labor should exist in the Christian community. <span class="No-Ligatures">Th</span>is pattern can be seen in scripture, although it is not described as explicitly as are some of the prescriptions for community order. However, this pattern of distinct responsibilities is one of the keys to developing a pattern of social roles for men and women that will strengthen the Christian community.</p>
<p class="BODY-STYLES_Body">A clear division of responsibilities between men and women has great benefits both for individuals and for the community as a whole. Such an approach to social life brings greater peace to men and women and to their interrelationships. A clear set of socially valued responsibilities promotes individual security and an assured sense of one’s importance and value within a group. Distinct male and female spheres also reduces competition between the sexes, and makes it clear in concrete, daily terms that both sexes are needed in order for life to go well. Moreover, the sexual division of labor normally assures that certain crucial needs within the community will be met most effectively. In particular, when women take primary concern for direct service to people’s needs, such care is normally of a much higher quality than when both sexes provide it equally. Charitable service, the rearing of young children, the training of other women, and the general daily management of the home as a center of care and service all work better when women take a primary concern for them.</p>
<p class="BODY-STYLES_Body">A workable sexual division of labor is often difficult in the modern world, but such a division is an essential aspect of a full functioning of men’s and women’s roles. Some of the elements of the division of labor seem clear. Women are primarily responsible for internal house management and the work which directly serves people’s immediate needs, such as the cooking and serving of food, care of clothing, and care of the living space. Men are responsible for heavy physical work, overall government, and seeing that the family is provided with food, clothing, and a place to live. However, it is not always easy to incorporate this division of labor into the daily life of a twentieth-century family. It is especially difficult to fully apply this approach in families where both the husband and wife work. A division of labor should still exist in such situations, but it should not mean that the women have to work twice as long and twice as hard as the men. Men should have their own set of household tasks so that the women do not have sole responsibility for household work. <span class="No-Ligatures">Th</span>is applies especially to families where both husband and wife work outside the household context, and in some measure also to families where only the husband works outside the family context.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ere is room for some flexibility in deciding which tasks are the man’s and which are the woman’s. However, there is no room for the type of flexibility which undermines the distinct line between male and female spheres of responsibility. <span class="No-Ligatures">Th</span>e very fact that modern society largely fails to assign secure roles to men and women is a chief reason why Christians should be insistent on this point. A type of flexibility which eliminates distinct spheres of responsibility only increases confusion and insecurity. Rigidity and absolute uniformity should not generally characterize the Christian approach to men’s and women’s roles. However, on the issue of distinct responsibilities for men and women, a firm adherence to a division of labor has many advantages.</p>
<p class="BODY-STYLES_Body">If a restoration of a sexual division of labor in the midst of technological society is to substantially increase the vitality of the Christian community, it must be accompanied by a new attitude toward female responsibilities. Technological society is marked by a tendency to devalue personal service, childrearing, and all domestic tasks, and to place great value on positions of political and economic “power.” <span class="No-Ligatures">Th</span>is scheme of values is directly contrary to the teaching of the scripture. <span class="No-Ligatures">Th</span>e female role is of central importance in shaping the quality of communal life. Women should experience satisfaction in meeting the personal needs of men and other women, and the men in the community should express their appreciation and respect for this service in tangible ways.</p>
<ol>
<li value="6" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">6.</span>--><span class="Italic"><a id="_idIndexMarker1142"></a><a id="_idIndexMarker1143"></a><a id="_idIndexMarker1144"></a><a id="_idIndexMarker1145"></a><a id="_idIndexMarker1146"></a><a id="_idTextAnchor1157"></a><span class="No-Ligatures">Th</span>ere should be a system of personal subordination among the Christian people with the elders (heads) of the community chosen from among the men and the husband serving as the head of the family, with women in complementary positions of leadership and subordinate government.<span class="Footnote-Ref"><span id="footnote-210-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-210">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>is guideline has three main elements. First, a system of personal subordination and the government of people should be restored in the Christian community. <span class="No-Ligatures">Th</span>e Christian people are meant to be a community and not merely a functional organization. A genuine Christian communal life built on scriptural social principles involves personal relationships of authority and subordination. Secondly, there should be male leadership in social groupings. Many men are eager to assume roles of functional leadership such as those found in politics and business, but most men are reluctant to assume responsibility for the life of social groups. Nonetheless, among the Christian people, men should be the overall heads or elders of the community and the family. <span class="No-Ligatures">Th</span>is does not mean that all women are subordinate to all men. Rather it means that government in the basic groupings of Christian life—the family and the community—is normally entrusted to a man. <span class="No-Ligatures">Th</span>irdly, there should be female roles of leadership and government corresponding to the male roles and subordinate to them. <span class="No-Ligatures">Th</span>e wife should be the second head of the family. Women should have leadership roles in the community under the direction of the overall heads, as is developed in the next guideline.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e type of subordination and government of the Christian people proposed here does not necessarily involve an obedience relationship covering all of a person’s life (except in the family) nor a directive counseling relationship. But it does involve a personal relationship between a head and those the head is caring for which allows the head to form those who need formation, to encourage what is right and correct what is wrong, and to give directions as appropriate. Relationships of personal subordination among the Christian people are built upon a personal love and loyalty between brothers and sisters in Christ or between members of the same family. <span class="No-Ligatures">Th</span>ese relationships are, in fact, a subordination to the community itself, as represented by the elders, and to the family, as represented by the parents, especially the father.</p>
<ol>
<li value="7" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">7.</span>--><span class="Italic"><a id="_idIndexMarker1147"></a><span class="Italic"><span class="No-Ligatures">Th</span>e role of “deaconess” and other female leadership roles should be </span>restored in the Christian community.<span class="Footnote-Ref"><span id="footnote-209-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-209">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e deaconess was a position in the early church and probably in the New Testament church which supplemented the male headship in the community with female pastoral assistance. <span class="No-Ligatures">Th</span>is office corresponds to a great need in modern Christian communities, a need which is perhaps even stronger now than in the past. A system for raising people in the Lord in which men care for men and women for women (guideline&#160;4) in itself creates a need for mature Christian women who can work alongside the male leaders of the community and who can watch over those aspects of community life primarily entrusted to the women. <span class="No-Ligatures">Th</span>e heads of the community also need the advice of capable female leaders when they are making important decisions.</p>
<p class="BODY-STYLES_Body">A modern Christian community existing within a technological society has an especially great need for visible female leadership that is respected and honored. Often such a system must be consciously developed, because most modern societies lack an operative clan system with an order of authority and honor among the women that can be put to Christian use. Also, as has been noted, modern society normally devalues the responsibilities and tasks that are part of the woman’s role. <span class="No-Ligatures">Th</span>is disrespect for the female role can be countered in the Christian community by a female leadership position which receives special honor and respect. <span class="No-Ligatures">Th</span>e type of honor given to male and female leaders should differ so as to express the difference and complementarity of role among men and women, but there should be positions of honor for women as well as for men. <span class="No-Ligatures">Th</span>e honor shown to female leaders will help to establish the value of the woman’s role in the community.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e deaconesses and other female leaders should not constitute a second network of government acting independently of the male elders. Rather, they should work under the elders as an extension of their care for the community, taking a complementary responsibility. <span class="No-Ligatures">Th</span>e same principle which leads to the restoration of the deaconess or of some equivalent should also serve as a basic principle for structuring the entire Christian community. Where male government exists in a community containing both men and women, there normally should be some form of female leadership that takes a complementary role. A contemporary Christian community needs strong, competent women to share responsibility with strong, competent men.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e role of deaconess in the sense in which it is discussed here can only be restored fully in the context of Christian communal relationships. Since modern churches often function as religious service institutions, this guideline is not the same as proposing a restoration of the office of deaconess in such churches as they currently exist. <span class="No-Ligatures">Th</span>e question of female leadership in such churches is not addressed in these guidelines. To satisfy the needs visualized in this guideline, the position of deaconess must be set within a structure of communal personal relationships.<a id="_idTextAnchor1158"></a></p>
<ol>
<li value="8" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">8.</span>--><span class="Italic"><a id="_idIndexMarker1148"></a><span class="No-Ligatures">Th</span>ere should be cultural expressions of role differences for men and women.<span class="Footnote-Ref"><span id="footnote-208-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-208">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI">A study of scripture and anthropology leads to the conclusion that men and women need to have definite cultural expressions for their role differences. <span class="No-Ligatures">Th</span>ey need a way of expressing, often in symbolic form, their manhood and womanhood. Cultural expressions are important because they constitute the language used by individual human beings to act out and communicate their roles to others and to themselves. <span class="No-Ligatures">Th</span>us they help establish a man’s or a woman’s personal identity. Most traditional cultures are rich in such gestures and customs, but technological society has lost much of this richness. For men’s and women’s roles to succeed fully in strengthening the lives of men and women and the life of the Christian community, some of these cultural expressions must be restored.</p>
<p class="BODY-STYLES_Body">Modern society tends to deprecate cultural modes of expression such as ritual, ceremony, and formal signs of affection and respect because they appear “arbitrary.” Of course, each individual cultural expression, like all symbols, is arbitrary, but the existence of some cultural expression is not arbitrary. It is humanly essential. <span class="No-Ligatures">Th</span>e meaning of a cultural expression may be determined by tradition rather than by the rationally calculated requirements of the situation. But in language, art, and other matters of cultural expression, much of the symbol’s effectiveness in strengthening a community derives from the community’s tradition. To reject a language because the meaning assigned to each sound is arbitrary misses the point. All languages are arbitrary, and there is no workable substitute for a common set of meanings passed on by a human tradition.</p>
<p class="BODY-STYLES_Body">Likewise, people in modern society can often deprecate cultural expressions as “inauthentic.” <span class="No-Ligatures">Th</span>is objection also ignores an important human truth. If each individual or grouping is expected to develop independently an “authentic” and rich system of symbolic expression, then such systems will never come to be. Instead, human life will be gradually impoverished of its means of expression, and the human realities that need regular expression will be left unprovided for. Cultural expressions are shared meanings, not unique creations.</p>
<p class="BODY-STYLES_Body">Cultural expressions of role differences between men and women need to exist. <span class="No-Ligatures">Th</span>ere should be signs of respect and honor shown differently to men and to women. <span class="No-Ligatures">Th</span>ere should be a variety of customs in which men and women play different parts. As much as possible, these customs should be congruent with the realities they express. <span class="No-Ligatures">Th</span>ey should be related as directly as possible to the meaning of the role differences. Nonetheless, there will always be an element of functional arbitrariness to most of the particular cultural expressions. In order to develop a rich system of cultural expression for the roles of men and women, most groups of modern Christians will have to penetrate beyond what many will experience as the functional arbitrariness of the different expressions until they reach the point of understanding the underlying human values being expressed. At that point they will understand experientially how essential are cultural expressions to the restoration of men’s and women’s roles and a Christian social structure.</p>

<a id="_idTextAnchor1159"></a><a id="_idIndexMarker1149"></a><a id="_idParaDest-104"></a>

## Adapting to Technological Society {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> teaching of scripture on men’s and women’s roles can be applied to modern technological society, but not by overlooking the differences between modern and biblical social conditions. If the scriptural teaching is to actually achieve its purpose of strengthening the Christian people, it must take certain forms which adequately address the special needs of technological society.</p>
<p class="BODY-STYLES_Body">One simple example of the need for adaptation of Christian life to contemporary society is the modern practice of scheduling. <span class="No-Ligatures">Th</span>ere is no indication from the scripture or from the records of the early church that the early Christians scheduled their time very closely. Family life and community life in traditional societies never required much concern for scheduling apart from the natural rhythms of the days and seasons. However, people in technological society who lack scheduling wisdom for daily life and work will encounter many problems. In similar fashion, a modern Christian community must make other innovations if it is to adapt the social patterns of the early church to the novel circumstances of technological society so that these patterns might actually serve and strengthen the Christian people. <span class="No-Ligatures">Th</span>e following two guidelines are given for this purpose.</p>
<ol>
<li value="9" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">9.</span>--><span class="Italic"><a id="_idIndexMarker1150"></a>A Christian community in technological society should have more fraternal and sororal groupings and structures than Christian communities of the past.<span class="Footnote-Ref"><span id="footnote-207-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-207">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>ere is a greater need in modern Christian communities for same-sex groupings of men and women organized along peer lines. <span class="No-Ligatures">Th</span>ough these groupings should bring together married men or married women of a similar age and position in life, they will be even more significant in providing support for single men, single women, and children.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e Christian community has always needed fraternal and sororal structures built along peer lines rather than family lines. Peer relationships, like other personal relationships, were at one time a normal part of the daily work life of men and women, although they were not as severely limited in age-span as they normally are in a technological society. <span class="No-Ligatures">Th</span>ey were not the predominant type of relationship, but they had a place in the life of the people. However, the social conditions of technological society increase the need for sororal and fraternal groupings in the Christian community and probably require more peer groupings within comparable age ranges. Today, there are many more older single people who cannot be cared for by families. <span class="No-Ligatures">Th</span>ere are also many more younger single people whose families are not in the Christian community or who need a supportive grouping to supplement their family life. Christian peer groups are also needed to help children and young people to resist the peer-group pressure exerted by the surrounding society. Such groupings are needed by people living a celibate life within the Christian community, and by married men and married women who would otherwise be isolated within the nuclear family and/or the functionalized business world. Fraternal and sororal groupings have always been needed in the Christian community, but they are needed especially in technological society.</p>
<p class="BODY-STYLES_Body">Although the modern Christian community needs special peer groupings, they should not become the primary structural units of the community. <span class="No-Ligatures">Th</span>e primary unit of the Christian community should always be the family. Moreover, these fraternal and sororal groupings should be ordered in such a way that they strengthen the basic lines of men’s and women’s roles in the community. <span class="No-Ligatures">Th</span>ey should therefore primarily be organized according to sex (either all-men or all-women), although there should be mutual support and social interaction between the groups. An environment for younger people in the Christian community that includes both men and women is helpful, but it must always be secondary to the same-sex peer groupings.</p>
<ol>
<li value="10" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">10.</span>--><span class="Italic"><a id="_idIndexMarker1151"></a>A Christian community in technological society should have more interaction between men and women than exists in most traditional societies.<span class="Footnote-Ref"><span id="footnote-206-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-206">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI">In most traditional societies, interaction between men and women is significantly less than in technological society. It is difficult to estimate the amount of interaction between men and women in the church of the New Testament, but it was undoubtably closer to the traditional model than to a modern model. In a Christian community in technological society, however, more interaction between men and women seems necessary.</p>
<p class="BODY-STYLES_Body">In most traditional societies, men associate mainly with other men and women associate mainly with other women. <span class="No-Ligatures">Th</span>is pattern of association in the community is reinforced by customs of separation between single men and women (for sexual reasons), a firm division of male and female spheres of responsibility, and a system of formation and initiation in which men raise the boys and women raise the girls. Moreover, in the family and other settings where men and women are together, communication is often kept to a minimum. For example, the rabbis in the time of Jesus thought that men should speak to their wives as little as possible. While such practices vary, almost all primitive and traditional societies place little emphasis on husband-wife communication. Because traditional societies change so slowly and have roles and responsibilities so well defined, such communication is not often experienced as essential even to the practical maintenance of the household life. Also, husbands and wives can maintain a personal and spiritual communion simply through sharing a common life in the same household and living as part of the same people. Extensive communication is not usually necessary in traditional societies for fulfilling this need.</p>
<p class="BODY-STYLES_Body">Such limited interaction between men and women may be workable within the social context of primitive and traditional societies, but it cannot be transferred to technological society without considerable modification. Many of the customs which reinforced a distance between men and women have dissolved. It is becoming more and more common for men and women to be educated together, to work together on the same jobs, and to associate informally in friendship groupings. <span class="No-Ligatures">Th</span>e Christian community needs to adapt to this social change. A Christian community should still retain some simple rules of distance between the sexes, and the primary relationships of formation and service should mainly place men with men and women with women. However, there must be sufficient opportunity for interaction between men and women. <span class="No-Ligatures">Th</span>e men and women in the Christian community need to learn how to relate to one another as brothers and sisters in the Lord.</p>
<p class="BODY-STYLES_Body">Similarly, husbands and wives must communicate more extensively in technological society than in traditional societies. Few aspects of childrearing and the practical maintenance of household life can be taken for granted in rapidly changing technological societies. More things need to be talked over and agreed upon. A husband cannot take responsibility for his household without receiving much input and advice from his wife. Moreover, life in technological society changes so quickly that marriage partners who do not communicate personally with one another can soon find themselves living in different worlds. <span class="No-Ligatures">Th</span>ey may sleep under the same roof, but it is difficult for them to share a fully common life without effective communication. <span class="No-Ligatures">Th</span>e spiritual and emotional communion that once came mainly from sharing a common life and belonging to the same people must now be strengthened in other ways. <span class="No-Ligatures">Th</span>erefore, husbands and wives need to communicate with one another regularly and with wisdom. In addition, such regular communication should also occur among the male and female leaders of the community. Leaders in a modern Christian community must be involved in more kinds of decision-making than in communities of the past, and, in that decision-making, women’s perspectives on important decisions need to be heard and taken into account.</p>

<a id="_idTextAnchor1160"></a><a id="_idIndexMarker1152"></a><a id="_idIndexMarker1153"></a><a id="_idParaDest-105"></a>

## Relating Outside of Christian Community {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">All</span> of the guidelines to this point have been directed toward establishing a Christian social system in the modern world which is faithful to traditional Christian teaching. Some elements of these guidelines, especially the ones concerning division of labor, cultural expression, and subordination, can apply outside of a Christian community with a social structure of its own, but even these elements can only be fully embodied in a comprehensive social system. <span class="No-Ligatures">Th</span>is raises a serious question: How should Christians living outside of a Christian community apply the teaching on men’s and women’s roles? Behind this question is an even more fundamental issue: How should Christians, whether living in community or not, apply this teaching in settings which operate according to principles other than those assumed in the present chapter? In other words, how should Christians relate to the culture of the society around them? <span class="No-Ligatures">Th</span>e following guidelines will provide some initial answers to these questions.</p>
<ol>
<li value="11" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">11.</span>--><span class="Italic">Christians should apply the scriptural teaching on men’s and women’s roles to Christian situations outside of Christian community to the degree that such application would be practical and helpful.<span class="Footnote-Ref"><span id="footnote-205-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-205">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI">Most Christians find themselves in various environments which include Christians but which are not Christian communities as the term is used here. <span class="No-Ligatures">Th</span>ey are then faced with the challenge of applying the traditional Christian teaching on men’s and women’s roles to these environments. <span class="No-Ligatures">Th</span>is question is especially pressing for Christian families that are not part of a Christian community, for Christian churches with limited communal relationships, and also in connection with businesses operated by Christians. Should the traditional Christian teaching on men’s and women’s roles be applied rigidly and firmly in these situations, or discarded as irrelevant to the new social circumstances? How should one deal with other Christians in these environments who refuse to accept this teaching?</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ree principles of application are very helpful in facing these questions. First, Christians should recognize the great value and importance of a full Christian approach to men’s and women’s roles. <span class="No-Ligatures">Th</span>is approach is founded upon truths about human nature and human relationships. <span class="No-Ligatures">Th</span>ese truths remain truths even though they are often forgotten in technological society. <span class="No-Ligatures">Th</span>e more that a full Christian approach can be preserved, the better. Moreover, this teaching on men’s and women’s roles is not only sound human wisdom, but also a pattern derived from scripture and Christian tradition. <span class="No-Ligatures">Th</span>e entire question is a matter of obedience to the Lord. <span class="No-Ligatures">Th</span>e more faithful the Christian, the more that Christian will want to work to mold daily life in accordance with God’s teaching.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e second principle could be stated in a form borrowed from Jesus’ comments about the Sabbath in <a id="_idIndexMarker1154"></a>Mark 2:27: “men’s and women’s roles were made for people, and not people for men’s and women’s roles.” Christians should attempt to be faithful to the scriptural teaching, but this faithfulness should impart life, and not lock Christians into a rigid and ineffective mold. <span class="No-Ligatures">Th</span>e traditional Christian teaching on men’s and women’s roles is an ideal of life that should be implemented as far as possible; it is not a law which brings final condemnation if disobeyed. If Christians apply the teaching flexibly and sensitively, it will usually produce benefits, since the teaching is built upon human and spiritual truths. On the other hand, a rigid application of this teaching can sometimes cause more problems than it solves. <span class="No-Ligatures">Th</span>e key rule is this: all things should be done for edification (<a id="_idIndexMarker1155"></a><span class="Lining-Nums">1&#160;</span>Cor 14:26). <span class="No-Ligatures">Th</span>e traditional Christian teaching on men’s and women’s roles should be applied in a constructive fashion. <span class="No-Ligatures">Th</span>ough a full application of this teaching is ideal, specific circumstances may make such an application impractical and ineffective.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ird, situations should be evaluated in accordance with two main criteria to measure their fitness for a fuller application of the scriptural teaching on men’s and women’s roles. First, the more the situation is formed on personal relationships rather than functional relationships, the more the scriptural teaching can be applied. Christian families and many Christian churches are therefore likely places to attempt to apply the scriptural teaching on men’s and women’s roles. Secondly, the more the Christians in the situation accept the teaching, the more readily it can be applied. Christians within a family or a church often disagree over fundamental aspects of men’s and women’s roles. Such disagreement means that the teaching should be applied with greater flexibility. <span class="No-Ligatures">Th</span>ese two criteria are helpful, but a sound judgment based on the criteria will also demand Christian wisdom and the leading of the Spirit.</p>
<p class="BODY-STYLES_Body">Sound judgment is especially needed for applying the scriptural teaching in functional environments which are staffed by Christians and organized for Christian purposes. Christians frequently decide to set up a modern business for Christian purposes or a hospital or counseling service that operates both on a Christian basis and also according to contemporary professional standards and procedures. In these settings it is essential to follow the norms of modern technological society. For example, positions will be filled with greater concern for functional competence and less concern for social role considerations. Nonetheless, Christian social roles can be a useful element even in this type of organization, especially if the environment allows for the development of Christian personal relationships among the workers. Some managerial positions in such organizations resemble the position of elder; they could be entrusted to men for pastoral reasons beyond the criteria of functional competence. Some managerial positions resemble the role of “deaconess” and could likewise be entrusted to women. In addition, some tasks in a functional organization are more manly and others more womanly according to a Christian role definition, although this judgment is often difficult to make in a strictly functional situation. A Christian functional organization cannot apply all of the scriptural teaching on men’s and women’s roles, but some elements of this teaching can probably be applied successfully.</p>
<ol>
<li value="12" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">12.</span>--><span class="Italic">In non-Christian settings, Christians should accept the prevailing order and customs of the situation as much as possible and not be obligated to press for the Christian view of men’s and women’s roles.<span class="Footnote-Ref"><span id="footnote-204-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-204">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e scriptural ideal for men’s and women’s roles accounts for basic human realities, and it is therefore potentially applicable to all people and not just Christians. Nonetheless, to its own detriment, modern non-Christian society tends to reject the traditional Christian teaching on men’s and women’s roles. In order to respond properly to this situation, Christians must first understand that they are a body of resident aliens in modern society. <span class="No-Ligatures">Th</span>e basic perspectives of modern society on social structure are not provided by the Christian people nor built upon scriptural or traditional Christian authority. <span class="No-Ligatures">Th</span>us Christians are not in a position to insist on the traditional Christian teaching regarding men’s and women’s roles, even though this teaching may represent the best human approach available.</p>
<p class="BODY-STYLES_Body">From the very beginning of Christian history, Christians have had to accept social principles in their surroundings that fall short of the Christian ideal. <span class="No-Ligatures">Th</span>e Roman government dictated to its subjects how they were expected to relate to the government, and the Christians accepted those principles—up to the point where acceptance involved transgression of the Lord’s commandments. Likewise, Christians in modern non-Christian social situations have to accept many of the governing principles, though they are less than ideal. <span class="No-Ligatures">Th</span>is is especially true in functional non-Christian groupings. For example, Christians should feel free to participate on a secular committee according to the rules of that committee, without urging that a man should preside over it.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ere are two main reasons for relating flexibly to functional non-Christian groupings. First, since the grouping is non-Christian, many issues of far greater seriousness than men’s and women’s roles will probably arise. For example, a Christian on a secular committee may face a situation in which the commandment to love is violated and in which political power maneuvers are the standard procedures for getting a program accepted. With such significant issues to confront, Christians should not hold out for a traditional Christian ideal which is important, but less important than observing the commandments. Secondly, it is not clear how much the New Testament teaching on men’s and women’s roles should apply to functional situations. <span class="No-Ligatures">Th</span>is teaching is primarily designed to order communal personal relationships. It does not necessarily apply to situations that are organized along functional lines. In short, Christians cannot adhere to the scriptural ideal for personal relationships in all their dealings with non-Christians. <span class="No-Ligatures">Th</span>ey should know what the Lord clearly forbids, but they must often simply do the best thing possible according to the principles of the situation in which they find themselves. Christians should realize that modern society is different from a Christian community; it is neither Christian nor a community. Once they accept this view, there is no necessary reason for objecting to a woman president or prime minister—at least from the point of view of Christian principles.</p>
<p class="BODY-STYLES_Body">One special case that deserves attention is the situation where a wife feels obligated to follow the scriptural teaching on the roles of men and women, but her husband does not wish to. <span class="Lining-Nums">1&#160;</span>Peter 3:1<span class="No-Break">–6</span> teaches that Christian women should be submissive even to husbands who are not Christian, both because submission is right for them (in fulfilling their role as wife) and because by so doing they can win their husbands. However, it is quite common in the modern world for Christian wives to attempt to be submissive to husbands who want no part of wifely submission (or more normally, want no part of the responsibilities of husbandly headship). In such cases, it would be somewhat incongruous for the submissive wife to insist that her unwilling husband be the head of the family. Instead, she should attempt to please her husband, though this will probably lead her to do certain things which might not conform to the ideal Christian model of the womanly role and wifely submission. She should attempt to be as submissive as possible in the scriptural sense, but she will have to maintain some flexibility in order to meet her husband’s expectations.</p>
<p class="BODY-STYLES_Body">Two general principles can guide Christians in their attempts to apply the traditional Christian teaching on men’s and women’s roles to modern non-Christian society. First, Christians should accept the principles of men’s and women’s roles observed in non-Christian situations as long as they themselves do not have to break God’s commandments. <span class="No-Ligatures">Th</span>ey should accept such principles, not as ideal, but as a practical necessity. <span class="No-Ligatures">Th</span>erefore, Christians could possibly accept the blurring of sexual distinctions in the curriculum of public secondary schools, but refuse to accept advocacy of immoral sexual relations or the practice of men dressing like women and women like men. To remain in the world involves putting up with ways of life that are not Christian. <span class="No-Ligatures">Th</span>e blurring of men’s and women’s roles is one of the less serious things that modern Christians have to put up with.</p>
<p class="BODY-STYLES_Body">Secondly, in general, Christians are not obligated to press or argue for the adoption in society of the Christian view of men’s and women’s roles. <span class="No-Ligatures">Th</span>is does not mean that Christians should avoid speaking to others about men’s and women’s roles at appropriate times, or that Christians should avoid attempting to develop a Christian approach to public policy questions related to men’s and women’s roles. It simply means that Christians are not obligated to propagate a particular view of men’s and women’s roles because of their Christian commitment. Non-Christian society as a whole needs many things of greater importance and priority than the traditional Christian approach to men’s and women’s roles, the gospel itself taking first place. <span class="No-Ligatures">Th</span>e good news is not primarily good news about the restoration of men’s and women’s roles. It is primarily good news about salvation in Jesus Christ. To be sure, one of the greatest benefits of Christianity is the better life that comes from following the teaching of the Lord. Christians can share about this better life as it comes through a restoration of men’s and women’s roles when such a sharing would be helpful. However, in the polemical atmosphere of modern society, discussions of men’s and women’s roles are often more of an obstacle to evangelism than a help to it. It is wiser to keep the focus on the Lord himself.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>e question underlying all of these challenging issues is whether the Lord wants his people living in the midst of the world. <span class="No-Ligatures">Th</span>ere are many reasons for believing that this is indeed the Lord’s desire for his people; the paramount reason is the Lord’s desire to draw the men and women of modern society to himself. If Christians are supposed to live in the midst of the modern non-Christian world, they need to see themselves as resident aliens, accepting and living in a social structure that is not established according to the Lord’s plan—without, however, compromising on essential principles of Christian life.</p>
<ol>
<li value="13" class="BODY-STYLES_L-O-Num-L1-Subsubhead"><!--<span class="Body-List-Counter-Float">13.</span>--><span class="Italic"><a id="_idIndexMarker1156"></a>Each attempt to apply the scriptural teaching on men’s and women’s roles, inside or outside the Christian community, should be guided by local cultural considerations.<span class="Footnote-Ref"><span id="footnote-203-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-203">\*</a></span></span></span></li>
</ol>
<p class="BODY-STYLES_Body-NI"><span class="No-Ligatures">Th</span>e formation of an effective pattern of men’s and women’s roles in the Christian community or Christian family should be determined primarily by the scriptural teaching as adapted to the circumstances of the modern world. However, this teaching also can and should be adapted as much as possible to the cultural surroundings of each particular group of Christians. <span class="No-Ligatures">Th</span>e expression of the scriptural teaching will be different among Chinese Christians, Mexican Christians, and Dutch Christians.</p>
<p class="BODY-STYLES_Body"><span class="No-Ligatures">Th</span>ere are two main areas where adaptation is possible. First, Christians should attempt to draw their cultural expressions of the differences between men’s and women’s roles from the society which surrounds them. <span class="No-Ligatures">Th</span>ey should use the culture’s customs in such areas as differences in clothing, hairstyle, and expressions of respect. Sometimes this need for adaptation places Christians in a difficult situation. For example, the recent trends toward unisex clothing and hairstyles in Western societies militate against the basic principles of a Christian approach to men’s and women’s roles. Also, with changes in sexual customs, Western Christians often seem forced to wear clothes which in past times would have been considered suggestive or immodest. However, in order to adapt to the surrounding culture, modern Christian men and women often need to wear clothing and hairstyles that are not ideal from a Christian viewpoint. Christians should wear clothes and hairstyles that manifest distinct roles and sexual modesty as much as possible, but their dress should not be clearly outmoded and socially unacceptable unless they are forced to appear this way for moral reasons.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1157"></a><span class="No-Ligatures">Th</span>e second area where cultural adaptation is possible is in secondary elements of social structure. For example, the customary division of labor between men and women differs from country to country. Some chores ascribed to men in one place may be ascribed to women in another place. In such matters, a Christian family or community should ordinarily conform to the dominant approach of their culture. Similarly, different cultures approach courtship and marriage differently, and have different systems of kinship and residence. <span class="No-Ligatures">Th</span>ough adaptation in such matters of social structure is unacceptable past a certain point, Christians have a considerable amount of latitude within which they can adapt the traditional Christian teaching to the local culture.</p>
<p class="BODY-STYLES_Body">At the same time, Christians should be free to supplement the expressions and structures of their local culture when that culture is impoverished. For example, much of American culture has lost an effective way of expressing honor and respect. In this case, American Christians must search elsewhere for ways to express these aspects of personal relationships. In short, Christians should select customs that will fit best within their cultural milieu, but they should not merely conform to the inadequacies of this milieu.</p>

<a id="_idTextAnchor1161"></a><a id="_idParaDest-106"></a>

## <span class="No-Ligatures">Th</span>e Feasibility of a Christian Restoration of Men’s and Women’s Roles {-}

<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> aim of most of the preceding guidelines has been the establishment or restoration of a Christian social structure within which the scriptural teaching on men’s and women’s roles can be lived. One reasonable response to these guidelines is the question: Is this approach really feasible? <span class="No-Ligatures">Th</span>ough it is admittedly very difficult to restore a fabric of Christian social relationships in a contemporary technological society, it is still possible in most places. However, another way of raising the question reveals the heart of the issue: How long can Christians in contemporary society continue to survive with any genuine faithfulness to Christian teaching if they do not create a new social structure? <span class="No-Ligatures">Th</span>e trend among many Christians is to modify Christian teaching whenever it conflicts with contemporary society and to reinterpret the scripture so that the growing gap between scriptural teaching and contemporary Christian living is not overly painful. How far can this go? Would it not be more honest to simply discard Christianity as unlivable? Moreover, the pressures of contemporary society not only persuade Christians to modify Christian teaching, but they also gradually erode in them the desire to be Christians in any sense. <span class="No-Ligatures">Th</span>e weaker forms of Christianity are fading away as Christians with weaker commitments drop away. Christianity in contemporary society will need to draw from people a higher commitment to the Lord and to the Christian community if it is to survive at all. <span class="No-Ligatures">Th</span>e crucial issue is not whether the restoration of a Christian social structure is feasible. <span class="No-Ligatures">Th</span>e issue is whether any Christianity is feasible without a restoration of a genuine Christian social structure.</p>

<div class="_idFootnotes">
<div id="footnote-216" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-216-backlink">616*</a>On “brother-sister love,” see Chapter Four, pp.&#160;[80](#_idTextAnchor132)<span class="No-Break">–</span>[<span class="No-Break">82</span>](#_idTextAnchor138), and footnote, pp.&#160;[81](#_idTextAnchor133)<span class="No-Break">–</span>[<span class="No-Break">81</span>](#_idTextAnchor134); Chapter Six, p.&#160;[158](#_idTextAnchor291); Chapter Nine, p.&#160;[213](#_idTextAnchor377); and Chapter Twenty-One, pp.&#160;[597](#_idTextAnchor1116)<span class="No-Break">–</span>[<span class="No-Break">598</span>](#_idTextAnchor1118).</p>
</div>
<div id="footnote-215" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-215-backlink">616†</a>On the home as a center of care and service, see Chapter <span class="No-Ligatures">Th</span>ree, pp.&#160;[48](#_idTextAnchor077)<span class="No-Break">–</span>[<span class="No-Break">49</span>](#_idTextAnchor079); Chapter Four, pp.&#160;[100](#_idTextAnchor179)<span class="No-Break">–</span>[<span class="No-Break">101</span>](#_idTextAnchor180); Chapter Five, pp.&#160;[114](#_idTextAnchor198)<span class="No-Break">–</span>[<span class="No-Break">115</span>](#_idTextAnchor199); Chapter Seventeen, pp.&#160;[429](#_idTextAnchor799)<span class="No-Break">–</span>[<span class="No-Break">443</span>](#_idTextAnchor843); and Chapter Eighteen, pp.&#160;[504](#_idTextAnchor975)<span class="No-Break">–</span>[<span class="No-Break">505</span>](#_idTextAnchor977).</p>
</div>
<div id="footnote-214" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-214-backlink">617*</a>On the family in Christian community, see Chapter <span class="No-Ligatures">Th</span>ree; Chapter Twelve, pp.&#160;[290](#_idTextAnchor504)<span class="No-Break">–</span>[<span class="No-Break">302</span>](#_idTextAnchor533); Chapter Eighteen, pp.&#160;[502](#_idTextAnchor969)<span class="No-Break">–</span>[<span class="No-Break">505</span>](#_idTextAnchor978); Chapter Nineteen, pp.&#160;[525](#_idTextAnchor1031)<span class="No-Break">–</span>[<span class="No-Break">526</span>](#_idTextAnchor1033); and Chapter Twenty-One, pp.&#160;[599](#_idTextAnchor1121)<span class="No-Break">–</span>[<span class="No-Break">604</span>](#_idTextAnchor1128).</p>
</div>
<div id="footnote-213" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-213-backlink">619*</a>On men being responsible for raising men, and women for raising women, see Chapter <span class="No-Ligatures">Th</span>ree, pp.&#160;[64](#_idTextAnchor105)<span class="No-Break">–</span>[<span class="No-Break">70</span>](#_idTextAnchor118); Chapter Four, pp.&#160;[96](#_idTextAnchor176)<span class="No-Break">–</span>[<span class="No-Break">97</span>](#_idTextAnchor177); Chapter Five, pp.&#160;[121](#_idTextAnchor215)<span class="No-Break">–</span>[<span class="No-Break">122</span>](#_idTextAnchor218), [124](#_idTextAnchor224), [135](#_idTextAnchor255); Chapter Nine, pp.&#160;[215](#_idTextAnchor380)<span class="No-Break">–</span>[<span class="No-Break">216</span>](#_idTextAnchor381); and Chapter Twenty-<span class="No-Ligatures">Th</span>ree, pp.&#160;[658](#_idTextAnchor1177)<span class="No-Break">–</span>[<span class="No-Break">659</span>](#_idTextAnchor1178), [664](#_idTextAnchor1186).</p>
</div>
<div id="footnote-212" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-212-backlink">619†</a><span class="No-Ligatures">Th</span>is point will be discussed more fully in Chapter Twenty-<span class="No-Ligatures">Th</span>ree, pp.&#160;[655](#_idTextAnchor1172)<span class="No-Break">–</span>[<span class="No-Break">657</span>](#_idTextAnchor1175), [660](#_idTextAnchor1181)<span class="No-Break">–</span>[<span class="No-Break">661</span>](#_idTextAnchor1182).</p>
</div>
<div id="footnote-211" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-211-backlink">620*</a>On different spheres of responsibility for men and for women, see Chapter One, pp.&#160;[22](#_idTextAnchor034)<span class="No-Break">–</span>[<span class="No-Break">23</span>](#_idTextAnchor037); Chapter <span class="No-Ligatures">Th</span>ree, pp.&#160;[48](#_idTextAnchor076)<span class="No-Break">–</span>[<span class="No-Break">64</span>](#_idTextAnchor102); Chapter Four, pp.&#160;[96](#_idTextAnchor175)<span class="No-Break">–</span>[<span class="No-Break">101</span>](#_idTextAnchor182); Chapter Twelve, pp.&#160;[290](#_idTextAnchor504)<span class="No-Break">–</span>[<span class="No-Break">302</span>](#_idTextAnchor533); Chapter Seventeen, pp.&#160;[423](#_idTextAnchor772)<span class="No-Break">–</span>[<span class="No-Break">425</span>](#_idTextAnchor782); and Chapter Twenty-One, pp.&#160;[607](#_idTextAnchor1136)<span class="No-Break">–</span>[<span class="No-Break">608</span>](#_idTextAnchor1141).</p>
</div>
<div id="footnote-210" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-210-backlink">622*</a>On governance of the Christian people, see Chapter Five, pp.&#160;[125](#_idTextAnchor227)<span class="No-Break">–</span>[<span class="No-Break">134</span>](#_idTextAnchor249); Chapter <span class="No-Ligatures">Th</span>irteen; Chapter Eighteen, pp.&#160;[495](#_idTextAnchor949)<span class="No-Break">–</span>[<span class="No-Break">496</span>](#_idTextAnchor953); Chapter Nineteen, pp.[526](#_idTextAnchor1035)<span class="No-Break">–</span>[<span class="No-Break">527</span>](#_idTextAnchor1040); Chapter Twenty-One, p.&#160;[598](#_idTextAnchor1117). On men as elders of the community and as heads of their families, see Chapter One, p.&#160;[27](#_idTextAnchor047); Chapter <span class="No-Ligatures">Th</span>ree, pp.&#160;[48](#_idTextAnchor075)<span class="No-Break">–</span>[<span class="No-Break">56</span>](#_idTextAnchor087); Chapter Four, pp.&#160;[96](#_idTextAnchor175)<span class="No-Break">–</span>[<span class="No-Break">101</span>](#_idTextAnchor182); Chapter Five, pp.&#160;[125](#_idTextAnchor227)<span class="No-Break">–</span>[<span class="No-Break">134</span>](#_idTextAnchor249); Chapter Seven, pp.&#160;[182](#_idTextAnchor326)<span class="No-Break">–</span>[<span class="No-Break">184</span>](#_idTextAnchor328); Chapter Eight, pp.&#160;[199](#_idTextAnchor349)<span class="No-Break">–</span>[<span class="No-Break">199</span>](#_idTextAnchor350); Chapter Twelve, pp.&#160;[290](#_idTextAnchor504)<span class="No-Break">–</span>[<span class="No-Break">302</span>](#_idTextAnchor533); Chapter <span class="No-Ligatures">Th</span>irteen, pp.&#160;[304](#_idTextAnchor535)<span class="No-Break">–</span>[<span class="No-Break">322</span>](#_idTextAnchor576); and Chapter Seventeen, pp.&#160;[422](#_idTextAnchor768)<span class="No-Break">–</span>[<span class="No-Break">434</span>](#_idTextAnchor810). On women in leadership, see Chapter <span class="No-Ligatures">Th</span>ree, pp.&#160;[56](#_idTextAnchor089)<span class="No-Break">–</span>[<span class="No-Break">64</span>](#_idTextAnchor103); Chapter Five, pp.&#160;[130](#_idTextAnchor235)<span class="No-Break">–</span>[<span class="No-Break">134</span>](#_idTextAnchor250); Chapter Eight, pp.&#160;[199](#_idTextAnchor348)<span class="No-Break">–</span>[<span class="No-Break">201</span>](#_idTextAnchor352); and Chapter Twelve, pp.&#160;[290](#_idTextAnchor504)<span class="No-Break">–</span>[<span class="No-Break">302</span>](#_idTextAnchor533).</p>
</div>
<div id="footnote-209" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-209-backlink">623*</a>On female leadership roles in the Christian community, see Chapter Four, pp.&#160;[97](#_idTextAnchor178)<span class="No-Break">–</span>[<span class="No-Break">101</span>](#_idTextAnchor181); Chapter Five, pp.&#160;[114](#_idTextAnchor196)<span class="No-Break">–</span>[<span class="No-Break">124</span>](#_idTextAnchor225), [134](#_idTextAnchor253)<span class="No-Break">–</span>[<span class="No-Break">139</span>](#_idTextAnchor260); Chapter Seven, pp.&#160;[189](#_idTextAnchor335)<span class="No-Break">–</span>[<span class="No-Break">190</span>](#_idTextAnchor336); and Chapter Seventeen, pp.&#160;[423](#_idTextAnchor772)<span class="No-Break">–</span>[<span class="No-Break">425</span>](#_idTextAnchor782).</p>
</div>
<div id="footnote-208" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-208-backlink">625*</a>On cultural expressions of role differences, see Chapter Seven, pp.&#160;[174](#_idTextAnchor317)<span class="No-Break">–</span>[<span class="No-Break">176</span>](#_idTextAnchor321), [192](#_idTextAnchor340); Chapter Nine, pp.&#160;[214](#_idTextAnchor378)<span class="No-Break">–</span>[<span class="No-Break">215</span>](#_idTextAnchor379); Chapter Eleven, pp.&#160;[277](#_idTextAnchor479)<span class="No-Break">–</span>[<span class="No-Break">279</span>](#_idTextAnchor483), [283](#_idTextAnchor491)<span class="No-Break">–</span>[<span class="No-Break">284</span>](#_idTextAnchor493); Chapter Seventeen, pp.&#160;[424](#_idTextAnchor779)<span class="No-Break">–</span>[<span class="No-Break">425</span>](#_idTextAnchor783); and Chapter Eighteen, pp.&#160;[508](#_idTextAnchor987)<span class="No-Break">–</span>[<span class="No-Break">509</span>](#_idTextAnchor992).</p>
</div>
<div id="footnote-207" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-207-backlink">627*</a>On male groups and female groups, see Chapter <span class="No-Ligatures">Th</span>irteen, pp.&#160;[314](#_idTextAnchor564)<span class="No-Break">–</span>[<span class="No-Break">316</span>](#_idTextAnchor567); Chapter Seventeen, pp.&#160;[434](#_idTextAnchor812)<span class="No-Break">–</span>[<span class="No-Break">439</span>](#_idTextAnchor836); Chapter Eighteen, pp.&#160;[514](#_idTextAnchor1002)<span class="No-Break">–</span>[<span class="No-Break">518</span>](#_idTextAnchor1009); Chapter Twenty-<span class="No-Ligatures">Th</span>ree, pp.&#160;[657](#_idTextAnchor1176)<span class="No-Break">–</span>[<span class="No-Break">660</span>](#_idTextAnchor1180), [664](#_idTextAnchor1186).</p>
</div>
<div id="footnote-206" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-206-backlink">628*</a>On male-female interaction, see Chapter Seventeen, pp.&#160;[434](#_idTextAnchor812)<span class="No-Break">–</span>[<span class="No-Break">439</span>](#_idTextAnchor836); Chapter Twenty-<span class="No-Ligatures">Th</span>ree, pp.&#160;[666](#_idTextAnchor1189)<span class="No-Break">–</span>[<span class="No-Break">669</span>](#_idTextAnchor1191); and the preceding guideline.</p>
</div>
<div id="footnote-205" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-205-backlink">630*</a>On applying the Christian teaching outside of Christian community, see Chapter Five, pp.&#160;[125](#_idTextAnchor228)<span class="No-Break">–</span>[<span class="No-Break">130</span>](#_idTextAnchor234); Chapter Fifteen, pp.&#160;[374](#_idTextAnchor660)<span class="No-Break">–</span>[<span class="No-Break">375</span>](#_idTextAnchor661); and Chapter Twenty-One, pp.&#160;[593](#_idTextAnchor1112)<span class="No-Break">–</span>[<span class="No-Break">594</span>](#_idTextAnchor1114).</p>
</div>
<div id="footnote-204" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-204-backlink">632*</a>On relating to a non-Christian social order, see Chapter Two, pp.&#160;[38](#_idTextAnchor061)<span class="No-Break">–</span>[<span class="No-Break">3</span>](#_idTextAnchor003); Chapter Four, pp.&#160;[90](#_idTextAnchor157)<span class="No-Break">–</span>[<span class="No-Break">91</span>](#_idTextAnchor158); Chapter Nine, pp.&#160;[218](#_idTextAnchor384)<span class="No-Break">–</span>[<span class="No-Break">221</span>](#_idTextAnchor385); Chapter Ten, p.&#160;[258](#_idTextAnchor457); Chapter Nineteen, pp.&#160;[536](#_idTextAnchor1061)<span class="No-Break">–</span>[<span class="No-Break">553</span>](#_idTextAnchor1068); and Chapter Twenty, pp.&#160;[558](#_idTextAnchor1073)<span class="No-Break">–</span>[<span class="No-Break">565</span>](#_idTextAnchor1083), [579](#_idTextAnchor1102)<span class="No-Break">–</span>[<span class="No-Break">584</span>](#_idTextAnchor1108).</p>
</div>
<div id="footnote-203" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-203-backlink">635*</a>On local considerations, see Chapter Ten, p.&#160;[258](#_idTextAnchor457); and Chapter Eleven, pp.&#160;[283](#_idTextAnchor491)<span class="No-Break">–</span>[<span class="No-Break">284</span>](#_idTextAnchor493); Chapter Twenty, pp.&#160;[583](#_idTextAnchor1105)<span class="No-Break">–</span>[<span class="No-Break">584</span>](#_idTextAnchor1106).</p>
</div>
</div>
