# Ordination, Occupation, Legislation

<a id="_idParaDest-114"></a><a id="_idTextAnchor1195"></a>
<p class="BODY-STYLES_Chapter-Opening"><span class="Opening-Drop-Words">The basic thrust of Christian pastoral concern</span> should be to foster an increasing degree of Christian community life, which includes developing a Christian social structure. But if Christians are going to live in the world and not be of it, they will face a wide variety of issues and challenges concerning the roles of men and women. Christians can take the initiative among themselves in developing a Christian social structure: They can shape Christian communal situations in a way that allows a sensible application of Christian teaching on the roles of men and women. However, in dealing with situations in modern society the initiative is rarely with Christians. Usually, Christians must respond to the prevailing social currents. Often they have to confront social situations that are already shaped in such a way that applying Christian teaching on the roles of men and women is unclear and difficult. This chapter will consider three such significant issues which face contemporary Christians in a Westernized society: ordination of women, occupations for women, and legislation on the roles of men and women.</p>
<p class="BODY-STYLES_Body">The present chapter is limited in its aims. It does not intend to offer an exhaustive treatment of each of these issues. Its primary concern is to draw out the implications of what has been said in the previous chapters of this study as it applies to these three issues. Far more remains to be said about each of these issues than will be said here, but it must be done according to principles other than those discussed in this study.</p>
<h2 id="_idParaDest-115" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1196"></a><a id="_idIndexMarker1198"></a>Ordination of Women<span class="Footnote-Ref"></span><span class="Footnote-Ref"><span id="footnote-240-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-240">*</a></span></span></h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">The</span> ordination of women is a recent issue for the Christian churches.<span class="Footnote-Ref"><span id="footnote-239-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-239">†</a></span></span> A woman was first ordained to the ministry of a recognized Christian denomination in 1863, in the Universalist Church.<span class="Footnote-Ref"><span id="footnote-238-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-238">‡</a></span></span> (At that time the Universalist Church would normally have been regarded as heterodox by most Christian churches, but it was more clearly a Christian denomination than it is now.) In general, the denominations which grew out of a revivalist tradition ordained women ministers first.<span class="Footnote-Ref"><span id="footnote-237-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-237">§</a></span></span> It was not, in general, until World War&#160;II that most of the historic mainline Protestant churches began to ordain women. The “liturgical churches” were the last, for the most part, to take this step (the 1958 decision of the Church of Sweden and the 1976 decision of the Protestant Episcopal Church in the USA were significant in this regard).<a id="_idTextAnchor1199"></a><span class="Endnote-Ref">[1](#_idTextAnchor2002)</span> On the other hand, the Roman Catholic Church and the Eastern Orthodox Churches have, to date, resisted the ordination of women. The Pope’s reaffirmation of the traditional Catholic position has been the most notable stand.<a id="_idTextAnchor1200"></a><span class="Endnote-Ref">[2](#_idTextAnchor2003)</span> The fact that the debate over ordaining women has arisen among Christians so recently, relatively speaking, indicates that its appearance as an issue has much more to do with the development of technological society and its influence on the Christian churches than with anything arising from within Christian tradition.</p>
<p class="BODY-STYLES_Body">A full treatment of the contemporary issue of ordination for women is outside the scope of this book. This book concerns the social roles of men and women, and these roles are only one aspect of the discussion about the ordination of women. In some ways, the most significant aspect of the ordination issue is the question of the nature of the ministry itself, especially the ministry of presbyter or priest. In this, the views of ministry taken by the various churches make a significant difference to the terms of the discussion.<a id="_idTextAnchor1201"></a><span class="Endnote-Ref">[3](#_idTextAnchor2004)</span> For example, when Roman Catholics discuss the ordination of women to the priesthood, there is often a great deal of discussion about the sacramental nature of the priesthood. A recent document of a Catholic study commission asserted that the New Testament is very clear on not allowing women to be the heads of the Christian community, but that the evidence it provides about the admissibility of ordaining women to the priesthood is inconclusive.<a id="_idTextAnchor1202"></a><span class="Endnote-Ref">[4](#_idTextAnchor2005)</span> From the Catholic perspective one might raise some questions about how good an understanding of the priesthood lay at the basis of this document, but there are other church traditions in which the very distinction and the terms of the argument would be incomprehensible. An exhaustive discussion of all the aspects of the question of the ordination of women, then, is beyond the range of this book. The material presented in this book, however, does allow some reflections on the ordination of women insofar as Christian social roles bear on the issue of ordination. This section will consider three such reflections.</p>
<p class="BODY-STYLES_Body">First, the study done here reveals that both scripture and tradition teach very clearly that the positions of overall government in the Christian community should be held by men.<span class="Footnote-Ref"><span id="footnote-236-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-236">*</a></span></span> This is one of the clearest and most consistent principles concerning the structure and order of the Christian people, from the time of Christ and the apostles until a very recent period of Christian history. If any authoritative statements about order among the Christian people are undisputed in scripture and tradition, this one is surely among them. To change it is not simply a matter of changing one rule: If this principle can be changed, the Christian people can change any feature of order, and they are not bound by scripture and tradition in shaping their life together. The judgment to ordain women, then, involves the judgment that modern society has reached the point where scripture and tradition cannot definitively guide the structuring of the common life of Christians.</p>
<p class="BODY-STYLES_Body">Secondly, the study done in this book indicates that the question of who should be heads of the Christian people is actually a question of God’s purposes for the human race and for how the new humanity should be formed. Government of the Christian people is not merely a secondary question of social roles that can be changed with little consequence. Rather, the question involves a broader vision of what human life should be like according to God’s ideal. The ordering of governmental responsibilities is only an expression of that underlying vision. Deciding to have women acting as heads of the Christian people means deciding that the scriptural vision of the life of humans together is no longer applicable or appropriate. A decision about structure and order in this area is a decision about what a body of Christians is trying to be.</p>
<p class="BODY-STYLES_Body">The decision to ordain women often arises from a perception that, sociologically speaking, the Christian churches have become something very different than they have been in the past. In the modern Western world, most Christian bodies function more as religious institutions providing religious services than as Christian communities.<a id="_idTextAnchor1203"></a><span class="Endnote-Ref">[5](#_idTextAnchor2006)</span> They have, in short, lost much of the relationship that makes a group a “people” in the sense in which the scriptures speak of a “people.” The governing officials of a church function less as heads over the people than as administrators and policy setters in a modern social institution, and their teaching is not received (or given) as being authoritative. Church bodies are conducted according to the principles of a service institution. Eliminating the restriction on women holding governing positions simply brings the structure of the church more in line with the principles that govern other service institutions in a modern society.</p>
<p class="BODY-STYLES_Body">Of course, the question is how the contemporary church bodies should respond to the current situation. Should they write into their constitutions, canons, and books of church order and discipline principles that ratify their current position as service institutions, or should they try to become communities? This is not an easy question to decide. There is much to be said for the value of service institutions which have accommodated structurally as much to the contemporary society as most church bodies have. As service institutions, they can preserve some Christian life among a broad number of people. To become communities like those of the early church would involve changing much more than some isolated principles of men’s and women’s roles. As was pointed out earlier, Christian churches today do not follow many other instructions given in the New Testament, such as instructions about Christian discipline and about relations with non-Christians and fallen-away Christians.<span class="Footnote-Ref"><span id="footnote-235-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-235">*</a></span></span> All these instructions make sense when Christians are viewed as a people, a social body with committed relationships. In short, to reverse the balance from being a religious institution accommodated to modern society to being more of a people would be both very difficult and quite risky for most Christian churches. The question, then, is whether the current situation in some way reflects an accommodation the Lord wants the churches to make. The key issue facing the churches today as they survey contemporary society and consider the scriptural view of the Christian people is: What kind of Christian bodies should they attempt to be?<a id="_idTextAnchor1204"></a><span class="Endnote-Ref">[6](#_idTextAnchor2007)</span></p>
<p class="BODY-STYLES_Body">Thirdly, the study in this book also points to a problem which faces those churches which are trying to maintain the view that women should not be ordained. For the most part, these churches are trying to maintain this position without attempting to provide a corresponding social structure to support it.<a id="_idTextAnchor1205"></a><span class="Endnote-Ref">[7](#_idTextAnchor2008)</span> For instance, they do not any longer normally teach very clearly about a difference in the roles of men and women. Yet, unless they do, their position on ordination will become more and more difficult for their people to understand and accept. When rules of order do not structure social life in a helpful way, such rules are often experienced as both restrictive and senseless. Of course, these churches could claim a basis other than social structure for holding that women should not be ordained. That is, they can, for example, insist that ordination is a sacramental matter which operates by an entirely different set of rules than the rest of life, and which should have no consequences for social structure. The effect of such an approach, however, would be to reinforce the already existing separation between “religion” (or “ritual”) and “real life.” Ordination can then be different because it operates in a different realm, one where only symbol is important and where sacramental actions have effects but do not order or structure the daily life of people. In short, if the churches that presently maintain the prohibition of women’s ordination do not (1)&#160;back up their position with clear instruction on family structure, and (2)&#160;provide their people with adequate social support to live a way of life different from the technological society around them (one which includes a role difference between men and women), these churches will fail to resolve the current controversy in the area. Either the issue of women’s ordination will remain a sore point, or it will contribute to an even greater separation between “sacramental” matters and the daily life of the Christian people.</p>
<p class="BODY-STYLES_Body">Obviously these three reflections do not cover the subject of women’s ordination. However, they help to place the issue in its social context—a crucial perspective if the issue is to be resolved properly. On the one hand, those favoring women’s ordination are confronted with the clear, consistent, authoritative statements of scripture and tradition. They are also faced with the prospect of choosing to become something that may be significantly different than the vision of God’s people outlined in the New Testament. On the other hand, those opposing women’s ordination must be ready to take more action than the mere defense of a single rule of order which seems to make little sense by itself in the present day. They, too, must face up to the full scriptural vision of the new humanity, and must be prepared to establish a whole Christian social order which will support and make sense of many of the individual prescriptions of authoritative Christian teaching.</p>
<h2 id="_idParaDest-116" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1206"></a><a id="_idIndexMarker1199"></a>Women and Occupations</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">The</span> question of occupations for women is often raised by Christians who take the scriptural teaching on the roles of men and women seriously. If, they ask, some differences should be maintained between the roles of men and women—differences which are expressed in household chores, for instance—should there not also be differences in the secular occupations of men and women? That is, should some occupations be particularly for men and others be particularly for women? The issue raised by these questions is actually not that of reshaping secular society, although it may appear to be so at first glance. For while certain de facto differences can be observed from occupation to occupation (some having considerably more men and others more women), there is little likelihood of reaching an agreement that any jobs in society should be restricted to one or another of the sexes. Technological society as it now exists is not amenable to being structured according to principles of sex roles, although in actual practice it normally has a certain amount of sexual differentiation. The practical issue which Christians face, then, is not that of restructuring modern technological society, but of establishing guidelines for Christian men and women in that society. In other words, the issue is whether Christian men and women should avoid certain occupations and enter others according to their sex.</p>
<p class="BODY-STYLES_Body">As a basis for discussing this issue, it might be helpful to call to mind some general observations which were made earlier in this book. These observations concern both scriptural teaching and modern social conditions. First and most importantly, the scripture does not lay down commandments about what kind of occupations men should have and what kind women should have, or about what occupations are forbidden to one sex or the other.<span class="Footnote-Ref"><span id="footnote-234-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-234">*</a></span></span> The only directives scripture clearly gives to men and women concern order in personal relationships. Moreover, women in scriptural times did far more than modern Christians, who have been influenced by the Victorian ideal, are sometimes led to believe. They worked hard, often at tasks that demanded physical strength. They engaged in a wide range of activities, including the sort of economic activities that are now sometimes considered to have been the domain of men (see <a id="_idIndexMarker1200"></a>Prv 31:10<span class="No-Break">–2</span>0). To be sure, they did most of these things in the context of the home. There was a sense in which, occupationally speaking, “the woman’s place was in the home.” On the other hand, however, the home was then a far different place than it is now, and it fulfilled many economic and social-welfare functions that it no longer fulfills today.</p>
<p class="BODY-STYLES_Body">A second observation from this book which bears on the issue of occupation is the importance of social roles. When scripture points to differences between men and women, it is concerned with social roles, not with particular activities and abilities.<span class="Footnote-Ref"><span id="footnote-233-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-233">†</a></span></span> Scripture teaches about order in social relationships within community situations. Even when it prohibits an activity for a woman—teaching, for example—the prohibition of that activity is not universal. Women are not forbidden all teaching. Nor does scripture state such prohibitions in terms of ability. An activity is prohibited for women when it expresses a social role that is reserved for certain men—namely, the role of being in overall personal authority over the lives of the men and women in the community. It could be misleading to say that scripture forbids certain activities to women. It would be more accurate to say that scripture enjoins certain social roles on men and women in communal situations, and that it forbids certain activities to women only in certain situations: when those activities are not appropriate to their social role.</p>
<p class="BODY-STYLES_Body">Thirdly, there do seem to be some real differences between men and women in areas of occupation.<span class="Footnote-Ref"><span id="footnote-232-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-232">‡</a></span></span> These differences involve ability, and also readiness to engage in particular tasks. Rather than being established through scriptural teaching, however, these differences are established empirically. Some of the empirical evidence along these lines comes from experimental research. Some evidence also comes from research which indicates that even when a social grouping makes a sustained effort to eliminate occupational differences between men and women, those differences will reassert themselves.<span class="Footnote-Ref"><span id="footnote-231-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-231">*</a></span></span> In other words, such differences are real, although they are not explicitly described in scripture.</p>
<p class="BODY-STYLES_Body">These three general observations provide useful background for the discussion of the issue of occupations for women. In handling this issue, the primary concern for Christians attempting to follow scriptural teaching on the roles of men and women is the preservation of social roles in family and community. In this the major concern will normally be the family because the life of the community should reflect the life of the family, and also because occupational considerations tend to affect family life more immediately than community life as a whole. There might, in addition, be the additional judgment that a type of work, or the environment in which that work occurs, de-feminizes women or makes it more difficult for them to function in womanly roles in family or community, but the analysis of modern occupations involved in such a judgment goes beyond the scope of this book. For our purposes, the criteria that come from the needs of Christian family life will be the main concern.</p>
<p class="BODY-STYLES_Body"><a id="_idIndexMarker1201"></a>A woman’s job or occupation, then, should not conflict with or disrupt her position in the family. This is an important criterion, but it will not normally determine what type of job or occupation she gets. Instead, it might more likely affect specific jobs. If certain job opportunities would adversely affect a woman’s social role relative to her husband, it would generally make sense for her to limit which positions she might choose. For instance, a woman who considers her relationship with her husband and family more important than occupational advancement would not be wise to hold a job involving significantly more managerial responsibility, prestige, or remuneration than that of her husband.</p>
<p class="BODY-STYLES_Body">More commonly, the criterion of protecting the woman’s position in the family is likely to indicate that she should not get a job which prevents her from “ruling the household” well or from making the home a center of childrearing and Christian service. In certain periods of her life, this criterion would point toward a part-time job at most. To be sure, economic survival is so difficult in some Christian families that they do not have the luxury to make this kind of choice, yet it is still the better choice when it is possible. For both men and women, then, their social roles should shape their approach to occupations, but, for the most part, their social roles will not dictate a limitation on types of occupation.</p>
<p class="BODY-STYLES_Body">While the primary concern in the area of occupations is the preservation of social roles, especially in the family, Christians must also be prepared to adapt the expression of these roles to certain elements of contemporary society. The need for this adaptation can be seen, for example, for the woman’s role in the home. While Christian teaching on social roles emphasizes the woman’s role in the home (her role of ruling the household), this teaching does not necessarily indicate that the women should always be at home. The significance of some women’s household responsibilities would indicate that they should work only at home, but in modern society it is unlikely that most women will be in that position. A significant change has occurred in traditional family functions, with the result that the majority of a woman’s traditional tasks (economic, social-welfare, educational) for the most part no longer occur at home. For women to remain at home under these circumstances would leave them underemployed and, in addition, underrepresented in some of the most vital areas of modern society. As a Christian community develops, more of these important activities might return to their traditional place in the home. Yet, short of a complete withdrawal of the Christian community from most modern social institutions, there will always be a significant need in technological society for women to work outside the home.</p>
<p class="BODY-STYLES_Body">As long as Christians remain within contemporary social institutions, they must also adapt to another aspect of contemporary society: Jobs and occupations are set up according to functional specifications, not according to relationship roles. Christian women, then, must be prepared to hold a modern job in the way their employers expect of them. While they need not become de-feminized in doing so, Christian women do need to be prepared to work with both men and women differently on the job than they might within the Christian community. In the various social situations they may encounter at their jobs, Christian women might still make service to people’s immediate needs a more major concern than men might, but their primary responsibility is still to do the jobs assigned to them.</p>
<p class="BODY-STYLES_Body">Christian women often choose jobs and occupations that are more womanly. For instance, women have a natural tendency toward teaching and caring for smaller children and toward certain secretarial positions. These tendencies are healthy, and Christian women would often do well to incline toward them. In general, Christian women would do well to find work in positions which are normally for women or for both women and men, while Christian men would do better to find work in positions which are normally for men or for both sexes. Christians should look for jobs that affirm their roles as men and women. They should generally support those things in society that strengthen an expression of the differences between men and women, rather than being among those who are trying to destroy such expression. This does not mean that Christians should be heavily invested in maintaining men-women differences in various occupations. But it does mean that in a quiet way (<a id="_idIndexMarker1202"></a>1&#160;Th 4:11) they should support what differences exist. As long as Christians intend to engage in contemporary technological society, and do not choose to withdraw from it or to work against its entire system, they must learn how to live within it.</p>
<p class="BODY-STYLES_Body">On the other hand, Christians who work at jobs within an organization sponsored by a Christian community can operate according to a somewhat different set of principles than they can in a secular job. In general, a Christian organization within a Christian community should normally reflect the social roles of the community more fully than if it were not part of the Christian community. Managers, for instance, are often more than mere administrators; they act as heads of groupings of Christian brothers and sisters.<span class="Footnote-Ref"><span id="footnote-230-backlink"><a class="_idFootnoteLink _idGenColorInherit" href="#footnote-230">*</a></span></span> In fact, the more a Christian organization is formed by the scripture’s instruction on relationships, the more the heads of the organization must function as elders as well as managers—taking a personal pastoral care for the workers. The social roles of the community will therefore be reflected in the Christian organization, and the organization will not be structured as much on functional lines as would a similar organization that was either secular or that was Christian but independent of a community context.</p>
<p class="BODY-STYLES_Body">Christians should always be guided by the ideal of personal relations revealed in the scriptures, even when they find themselves in secular situations. Yet they should follow that ideal wisely. It does not make sense to treat a secular situation as though it were part of the Christian community. Neither does it make sense to treat a functionally structured situation as though it were structured according to relationships. A wise accommodation must be made to the circumstances. Since the Fall, the world has not been an ideal place to live. Even before the Fall, it may not have been a fully ideal place to live. The Lord may have left the human race a fair amount of room to improve as part of their responsibility for creation. In any case, Christians must take their given situation and work with it wisely in order to bring life to the world. This can often mean accommodating themselves to their situation in order to bring the Lord’s life into it.</p>
<h2 id="_idParaDest-117" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1207"></a><a id="_idIndexMarker1203"></a><a id="_idIndexMarker1204"></a>Legislation</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">Another</span> difficult issue for Christians who hold to role differences between men and women is the question of governmental legislation. For one thing, very few people in contemporary society are willing to publicly defend or give legislative protection to social role differences of any sort. Moreover, from the Christian point of view, any piece of legislation is usually of mixed value. Legislation often attempts to deal with a real problem, but its proposed solution is often only partially acceptable from the Christian point of view. Normally, a Christian is forced to choose among the best of a number of imperfect alternatives. One alternative is to have no legislation. But it is often clear that some kind of action is needed, and a law which is a mixed blessing is frequently better than no law at all. A further difficulty is the pressure coming from a women’s movement which is hostile to all expression of, and regard for, role differences between men and women, even the most minimal of them. Because the movement exists by ideological principles, it is not an interest group which can be readily engaged in discussion. It can either be appeased or resisted. Finally, the issue of legislation is very complex, not easily understood or dealt with. Because of all these difficulties in the area of legislation, Christians who believe in some kind of role differences for men and women often avoid dealing with it.</p>
<p class="BODY-STYLES_Body">Evaluating legislation must begin with knowing the situation for which the laws are intended. In Westernized societies, legislation concerning roles for men and women is never intended for a community. Neither does it seek to structure good relationships among a group of people who have a personal commitment to one another. Rather, such legislation attempts to deal with a technological society and with the consequences of technological development. In a modern technological society, it is often the case, for example, that women need more legislation in order to “secure their rights.” (To take one instance, a woman who is responsible for children and is without a husband can find that society is not set up in such a way as to allow her to easily fulfill her responsibilities—regardless of why she is without a husband.) In other words, Western legislation concerning roles for men and women is intended for a situation which differs greatly from the one envisioned in the last few chapters.</p>
<p class="BODY-STYLES_Body">To know the situation in technological society well enough to evaluate different pieces of proposed legislation is certainly not an easy task. In recent years, the amount of sustained propaganda concerning men and women has made it very difficult to learn even the basic facts about how men-women differences affect their situation, and many “sociological studies” of what is currently happening to men and women are done to prove a preconceived point. Despite the many difficulties, however, the task of understanding the situation of our society should be attempted. The primary question for Christians facing the issue of legislation is not how a group of Christians should form a Christian community, but how a secular government can best care for the welfare of all its citizens in the midst of technological development. To answer that question, one should normally begin by understanding what is actually happening in society. One must then attempt to shape an intelligent legislative approach for the government in view of that understanding.</p>
<p class="BODY-STYLES_Body">At the same time as they are seeking to understand the legal needs of modern technological society in the area of roles for men and women, Christians should be aware of the fact that there are real differences between men and women which have been established by contemporary social sciences as well as such differences can be. A great deal of evidence also indicates that societies have functioned best when these differences were taken into account and worked with, rather than when they were simply ignored as though men and women were the same, and as though they were isolated individuals outside of any social structure. In addition to actually perceiving that differences between men and women do, in fact, exist, Christians should be aware that this truth is one of the points of most determined opposition from many segments of the women’s movement. For this reason, Christians can well be wary of most of that movement’s analyses of the situations that call for legislative action, because these analyses normally presume that men and women should not be treated differently in social life. Such analyses then lead to legislative proposals that would further the very trends in society which cause the analyses in the first place. An example of this process might be illuminating. A study claims to discover that women are being discriminated against in certain job situations. It is likely that those job situations were analyzed on the basic assumption that men and women should be doing the same things in approximately equal numbers; if this were found to be not the case, the obvious conclusion is that discrimination must be going on. Having collected evidence that men and women are not doing the same jobs in equal numbers, the study then proceeds to recommend certain legislation that would result in approximately the same numbers of men and women occupying those jobs. Such a study might just as well have skipped the step of collecting data: The legislative recommendations proceed fairly directly from the assumptions on which the study was made.</p>
<p class="BODY-STYLES_Body">One can see from the preceding discussion that it is not easy for a Christian to sort through the issue of legislation. Yet a rough guideline might be as follows: Legislation which provides protection for women should be supported by Christians, but legislation which takes active steps to make men and women the same should be resisted. Examples of legislation which provides protection for women are legislative efforts to guarantee women equal pay for equal work, and to protect women’s ability to establish good credit ratings. An example of legislation which takes active steps to make men and women the same is that legislation which presupposes and attempts to enforce the view that men and women should hold all positions in equal numbers (for instance, legislation which calls for governmental councils to be made up of men and women in approximately equal numbers). Other examples of this type of legislation are laws banning textbooks which show men and women having different interests or engaging in different activities, or which encourage women to be more interested in marriage and family than in outside careers. At times, the distinction between these two types of legislation is not easily made. While the guideline proposed here can, at times, be difficult to apply, it can also be very helpful in highlighting the significant difference between legislation which attempts to protect women from discrimination and that which attempts to eliminate such discrimination by erasing the differences between men and women.</p>
<p class="BODY-STYLES_Body">There is a good reason for suggesting that Christians should favor protective legislation. This reason, discussed in more detail in Chapter Eighteen, is a simple one: A technological society, unlike a Christian community, must provide protection for its members according to the kind of social relationships which form in a technological situation. The ideological principle that government should protect people’s rights is one somewhat well-accepted way of providing that protection. Christians would ordinarily do well to support the principle that certain rights of all individuals should be protected simply on the basis of their common humanity. This principle will lead to protection for Christians as well as for others. In the absence of a better means of protecting people in a secular technological society, Christians would be wise to support the most effective one available. However, Christians need not adopt that principle as coming from God. Nor should they assume that the approach to protecting people in Christian communal life should be the same as that adopted by a secular, functionalized society. Rather, they should understand that the principle is useful in certain social situations.</p>
<p class="BODY-STYLES_Body">On the other hand, there is also good reason for resisting legislation designed to make men and women the same. Such resistance is a matter of claiming the freedom for Christians and their views that their society allows. It is also a matter of making use of that wisdom taught by Christian revelation, but which applies to both Christian and secular concerns. Men and women are different. Normally, attempts to totally eliminate these differences between them end in failure. There is no reason why secular society cannot allow for those differences, and even foster them intelligently within the bounds set by modern technological life. In doing so, society can profit from them. What is more, there is no reason why the government should allow one particular ideology to have access to everyone’s life so as to condition people to support that ideology in the future. One of the areas where Christians should be most eager to see limits placed on the government is in its attempts to condition children through education and mold public opinion through media. Every time Christians support such an effort, they are helping to build a weapon that may easily be used against them.</p>
<p class="BODY-STYLES_Body">Although the area of legislation concerning roles of men and women is complex and difficult, it is an important area for Christians to understand properly. Genuine differences between men and women remain, despite pressures from various sectors of our society to level them. Wise and useful legislation will attempt to protect women in technological society, but it will not attempt to eliminate the differences between men and women. There is a tremendous difference between protecting the possibility of women being senators, and insisting that women compose half the senate. There is an even greater difference between offering women legislative protection, and conditioning both women and men to expect that social roles should be eliminated. It is here that the real battle over legislation must be fought.</p>
<p class="BODY-STYLES_Body">A few short pages can hardly do justice to issues like legislation, ordination, and occupations for women. Full treatments of these subjects, though, are well beyond the realm of this chapter or this book. The aim of the preceding discussions has been far more modest: to examine the considerations of social roles among men and women as these roles bear upon ordination, occupation, and legislation for women. Social roles considerations, however, offer only a single component of the solution to these broad-ranging issues; much of the discussion necessary to a full solution must be held on other grounds. Because of the limited scope of this discussion, the comments offered above remain somewhat sketchy and are not in themselves intended to add up to a set of clear, practical solutions. Instead, they are meant to illustrate one aspect of these issues, thereby contributing an important, and often neglected, perspective to the overall discussion.</p>
<h2 id="_idParaDest-118" class="HEADS---SUBHEADS_Subhead"><a id="_idTextAnchor1208"></a>Christians in the World</h2>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words">Christians</span> must live in the world, not solely in the Christian community. Thus they must have a dual subordination. They are citizens of heaven, and in their hearts they are subordinate to spiritual authority because they have accepted the Lord as the one they follow. But they are also subject to the governments and social systems of this earth, and out of reverence for the Lord they must be subordinate to them for the sake of good order. In their subordination to the governments and the social systems of this world, they will follow different principles than in their subordination to spiritual authority. They cannot treat society as though it were the Christian community, and they cannot treat the Christian community as though it were society—unless, of course, they find themselves in a place that is a Christian society (in which case the terms of the question are somewhat different). Christians should refrain from trying to make secular society act as if it follows the Lord; at the same time, they should serve society with the wisdom the Lord provides, to the extent that this wisdom can be put to good use. Christians must also live in a secular social system which follows very different principles than a Christian social system, and, at the same time, live in a Christian social system. They must, in other words, be in the world but not of it (<a id="_idIndexMarker1205"></a>Jn 17:15<span class="No-Break">–1</span>6), obey God and not men (<a id="_idIndexMarker1206"></a>Acts 5:29), and be submissive to rulers and authorities, ready for any honest work, showing perfect courtesy toward all men (<a id="_idIndexMarker1207"></a>Ti 3:1<span class="No-Break">–2</span>).</p>

<div class="_idFootnotes">
<div id="footnote-240" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-240-backlink">674*</a><a id="_idTextAnchor1197"></a>“Ordination” here refers specifically to ordination to the presbyterate. Because of different conceptions of the presbyterate in different churches, the understanding of ordination will vary somewhat.</p>
</div>
<div id="footnote-239" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-239-backlink">674†</a>As was previously noted in Chapter Thirteen, ordination is a recent issue as far as the practice of orthodox Christianity is concerned. Such heretical sects as the Montanists and the Collyridians appear to have ordained women. However, the practice was not accepted by any recognized Christian church (Eastern Orthodox, Catholic, or Protestant) until the last century.</p>
</div>
<div id="footnote-238" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-238-backlink">674‡</a>These smaller revivalist denominations were possibly among the earliest to ordain women because, beyond their core revival teaching, they were less grounded in Christian tradition than were, for instance, the historical mainline Protestant Churches, the Eastern Orthodox Churches, or the Roman Catholic Church.</p>
</div>
<div id="footnote-237" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-237-backlink">674§</a>Among the revivalist denominations a Congregationalist woman was first ordained, although unofficially, in 1853, a Wesleyan Methodist in the early 1850s, a Baptist by the late 1800s and a Pentecostal in the early 1900s. Among the more mainline Protestant Churches, Lutheran Churches in Scandinavia began ordaining women around World War&#160;II (Norway made the decision in 1938, Denmark in 1947, and as mentioned, Sweden in 1953). In the United States, the United Presbyterian Church decided to ordain women in 1956, the Lutheran Church in America and the American Lutheran Church in 1970, and the Protestant Episcopal Church in 1976.<a id="_idTextAnchor1198"></a></p>
</div>
<div id="footnote-236" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-236-backlink">675*</a>See above, Chapter Five, pp.&#160;[125](#_idTextAnchor227)<span class="No-Break">–</span>[<span class="No-Break">134</span>](#_idTextAnchor249); and Chapter Thirteen, pp.&#160;[304](#_idTextAnchor535)<span class="No-Break">–</span>[<span class="No-Break">322</span>](#_idTextAnchor576).</p>
</div>
<div id="footnote-235" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-235-backlink">676*</a>See Chapter Twenty, pp.&#160;[568](#_idTextAnchor1090)<span class="No-Break">–</span>[<span class="No-Break">571</span>](#_idTextAnchor1094).</p>
</div>
<div id="footnote-234" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-234-backlink">679*</a>See Chapter Five.</p>
</div>
<div id="footnote-233" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-233-backlink">680†</a>See Chapter Five.</p>
</div>
<div id="footnote-232" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-232-backlink">680‡</a>See above, Chapter Sixteen, the discussion on experimental psychology and the results. See also Chapter Seventeen.</p>
</div>
<div id="footnote-231" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-231-backlink">681*</a>See Chapter Seventeen, pp.&#160;[431](#_idTextAnchor804)<span class="No-Break">–</span>[<span class="No-Break">434</span>](#_idTextAnchor811).</p>
</div>
<div id="footnote-230" class="_idFootnote">
<p class="FOOTNOTES_Footnote"><a class="_idFootnoteAnchor _idGenColorInherit" href="#footnote-230-backlink">683*</a>On acting as “heads” of Christian groupings, see Chapter Five.</p>
</div>
</div>
