# Bibliography {-}

<a id="_idParaDest-120"></a><a id="_idTextAnchor1210"></a>
<p class="BODY-STYLES_Subhead-Opening"><span class="MaWiC_Subhead-Drop-Words"><span class="No-Ligatures">Th</span>e</span> notes in this book contain extensive bibliographical references. <span class="No-Ligatures">Th</span>e present bibliography offers a list of recommended works for further reading. To say that they are “recommended” does not indicate full approval of these books or articles, either in their approach or in their conclusions. Rather, it indicates that each book and article, in whole or in part, contains important material for understanding Christian social roles for men and women. <span class="No-Ligatures">Th</span>ese books and articles often contain useful substantiation for the positions taken in the present volume or fuller developments of some of its arguments. Taken together they cover the same ground as this book.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">On the New Testament Teaching</h2>
<p class="F-B-MATTER_Bibliography-Entry">Barth, Markus. “Excursus on Head and Body” in <span class="Italic">Ephesians 1</span><span class="No-Break">–3</span>, Section&#160;XI in <span class="Italic">Ephesians 4</span><span class="No-Break">–6</span>. Vols. 34 and 34a of <span class="Italic"><span class="No-Ligatures">Th</span>e Anchor Bible</span>. New York: Doubleday, 1974.</p>
<p class="F-B-MATTER_Bibliography-Annotation">In this study Barth offers a highly developed exegesis of Ephesians 5:21<span class="No-Break">–3</span>3. In doing so he goes beyond the passage itself to treat important issues which it raises. Overall, this is a very helpful study for the key New Testament texts.</p>
<p class="F-B-MATTER_Bibliography-Entry">Boucher, Madeleine. “Some Unexplored Parallels to <span class="Lining-Nums">1&#160;</span>Corinthians 11:11<span class="No-Break">–1</span>2 and Galatians 3:28: <span class="No-Ligatures">Th</span>e New Testament on the Role of Women.” <span class="Italic">Catholic Biblical Quarterly</span> 31, no.&#160;1 (January 1969): 50<span class="No-Break">–5</span>8.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is a brief, well-written article comparing some rabbinic texts with certain New Testament passages on men and women. It is most helpful for the clarity of its approach to Galatians 3:28, where Boucher distinguishes between issues the passage might raise in a first century mind and those it might raise for people in the twentieth century.</p>
<p class="F-B-MATTER_Bibliography-Entry">Ryrie, Charles. <span class="Italic"><span class="No-Ligatures">Th</span>e Role of Women in the Church</span>. Chicago: Moody Press, 1970.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>e best introductory survey of scripture and early church texts available. It is written from a conservative evangelical perspective and does not treat much of the recent discussion, scholarly or popular, on the subject, but it is more accurate than the feminist surveys that are available. His conclusions about the active role of women in community ministry differ from those here.</p>
<p class="F-B-MATTER_Bibliography-Entry">Sampley, J. Paul. <span class="Italic">And the Two Shall Become One Flesh</span>. Cambridge: Cambridge University Press, 1971.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is monograph is perhaps the best single exposition of Ephesians 5:21<span class="No-Break">–3</span>3. Its work substantiates the exegetical positions of this book, although, because it deals only with the exegesis of the text, it does not attempt to address many of the issues treated here.</p>
<p class="F-B-MATTER_Bibliography-Entry">Zerbst, Fritz. <span class="Italic"><span class="No-Ligatures">Th</span>e Office of Woman in the Church</span>. Translated by A.&#160;G. Merkens. St. Louis: Concordia, 1955.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Zerbst has written an excellent book on the subject. His very helpful survey, however, is intended to cover ministry in the church, and it treats only indirectly the issues concerning family. His work substantiates the positions taken in this book. Zerbst offers a useful European bibliographical survey, which unfortunately stops at 1955.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">Background to the New Testament Teaching</h2>
<p class="F-B-MATTER_Bibliography-Entry">Derrett, J. Duncan M. <span class="Italic">Jesus’s Audience</span>. New York: Seabury Press, 1973.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Derrett’s first lecture provides a good survey of the social history of the New Testament as important background to the key texts and issues.</p>
<p class="F-B-MATTER_Bibliography-Entry">Jeremias, Joachim. <span class="Italic">Jerusalem in the Time of Jesus</span>. London: SCM Press, 1969.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>e section of the book entitled “<span class="No-Ligatures">Th</span>e Maintenance of Racial Purity” is one of the most helpful surveys available of the role of birth and race insofar as they relate to Jewish social structure at the time of Jesus. <span class="No-Ligatures">Th</span>is provides useful background to underlying concepts of social structure in the New Testament.</p>
<p class="F-B-MATTER_Bibliography-Entry">Strack, Hermann L., and Paul Billerbeck. <span class="Italic">Kommentar zum Neuen Testament aus Talmud und Midrasch</span>. Munich: Beck, 1922<span class="No-Break">–2</span>6.</p>
<p class="F-B-MATTER_Bibliography-Annotation">All of the sections on the key texts are of value. <span class="No-Ligatures">Th</span>is is a standard reference work, but it is surprisingly often ignored by feminist writers. It is an essential tool for viewing the New Testament against the rabbinic background, and its commentary is often illuminating.</p>
<p class="F-B-MATTER_Bibliography-Entry">Vos, Clarence J. <span class="Italic">Woman in Old Testament Worship</span>. Delft: Judels &amp; Brinkman, 1968.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>e central thesis of this book—that woman held a position of honor and importance in Old Testament Israel, and that she engaged in worship (although not under obligation as did her husband, who represented the family)—substantiates the position of this book. Not all of Vos’s specific points are as sound as his main thesis, but the book is generally of value.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">Patristic Materials</h2>
<p class="F-B-MATTER_Bibliography-Entry">Daniélou, Jean. <span class="Italic"><span class="No-Ligatures">Th</span>e Ministry of Women in the Early Church</span>. London: Faith Press, 1961.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Daniélou gives the best short summary and analysis of New Testament and Patristic evidence as it relates to the ministry of women. His work substantiates the positions of this book.</p>
<p class="F-B-MATTER_Bibliography-Entry">Gryson, Roger. <span class="Italic">Le ministère des femmes dans l’Église ancienne</span>. Gembloux: Duculot, 1972.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Gryson offers the best full survey to date of the Patristic texts on the ministry of women in the church. His discussion of the issues involved, however, is often weak.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">On the Question of the Authority of Scripture and Modern Biblical Scholarship</h2>
<p class="F-B-MATTER_Bibliography-Entry">Childs, Brevard S. <span class="Italic">Biblical <span class="No-Ligatures">Th</span>eology in Crisis</span>. Philadelphia: <span class="No-Ligatures">Th</span>e Westminster Press, 1970.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is book contains a helpful analysis of the problems of interpretation and modern biblical criticism. <span class="No-Ligatures">Th</span>e analysis substantiates, in large part, and provides historical background for, the position of this book.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">On Differences between Men and Women</h2>
<p class="F-B-MATTER_Bibliography-Entry">Bardwick, Judith M. <span class="Italic">Psychology of Women</span>. New York: Harper &amp; Row, 1971.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is probably the best single book on the psychology of women. It harmonizes well with the position taken in the present volume.</p>
<p class="F-B-MATTER_Bibliography-Entry">Hutt, Corinne. <span class="Italic">Males and Females</span>. Ontario: Penguin, 1972.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is an excellent brief summary of the differences between men and women, mainly from the point of view of psychology.</p>
<p class="F-B-MATTER_Bibliography-Entry">Mead, Margaret. <span class="Italic">Male and Female</span>. New York: Dell, 1949.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is book includes penetrating and insightful reflections on the social roles of men and women based on many years of cross-cultural field experience.</p>
<p class="F-B-MATTER_Bibliography-Entry">Tiger, Lionel. <span class="Italic">Men in Groups</span>. New York: Vintage Books, 1969.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is book presents a challenging theory of the origin and function of men’s and women’s roles in the human social structure which has yet to be seriously answered. It goes beyond what is attempted in this book in its efforts to formulate a view of the origins of social structural differences between men and women, but presents a standpoint worth considering.</p>
<p class="F-B-MATTER_Bibliography-Entry">Tiger, Lionel, and Joseph Shepher. <span class="Italic">Women in the Kibbutz</span>. New York: Harcourt Brace Jovanovich, 1975.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is a key sociological study documenting the resistance of men’s and women’s roles to radical ideological change. It points to the biological origin of men’s and women’s roles.</p>
<p class="F-B-MATTER_Bibliography-Entry">van&#160;den&#160;Berghe, Pierre L. <span class="Italic">Age and Sex in Human Societies: A Biosocial Perspective</span>. Belmont, California: Wadsworth Publishing Company, 1973.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is a fine summary of the differences between men and women, including chapters on such areas as primatology, cross-cultural studies, and psychology. It is honest, useful, and clear, although it is sometimes colored by a leftist political viewpoint.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">Social History and Cultural Analysis</h2>
<p class="F-B-MATTER_Bibliography-Entry">Ariès, Philippe. <span class="Italic">Centuries of Childhood</span>. London: Jonathan Cape, 1962.</p>
<p class="F-B-MATTER_Bibliography-Entry"><span class="two-em-dash">——</span>—. “<span class="No-Ligatures">Th</span>e Family, Prison of Love.” <span class="Italic">Psychology Today</span>, August 1975: 53<span class="No-Break">–5</span>8.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>e above writings by Ariès give an eye-opening and currently very influential perspective on the social history of the family. <span class="No-Ligatures">Th</span>ey are useful for understanding social life in traditional societies and therefore for understanding social life in New Testament society.</p>
<p class="F-B-MATTER_Bibliography-Entry">Berger, Peter, Brigitte Berger, and Hansfried Kellner. <span class="Italic"><span class="No-Ligatures">Th</span>e Homeless Mind</span>. New York: Random House, 1973.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Berger et al. give a fine sociological analysis of the elements of technological society and its approach to personal relationships. <span class="No-Ligatures">Th</span>eir analysis supports much of what is said in this book.</p>
<p class="F-B-MATTER_Bibliography-Entry">Ellul, Jacques. <span class="Italic"><span class="No-Ligatures">Th</span>e Technological Society</span>. New York: Knopf, 1973.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is book is a profound analysis of the development of technological society. Its scope is much wider than that of the present volume, but its reservations about the quality of life in technological society support the conclusions drawn here.</p>
<p class="F-B-MATTER_Bibliography-Entry">Laslett, Peter. <span class="Italic"><span class="No-Ligatures">Th</span>e World We Have Lost</span>. London: Methuen, 1965.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Laslett describes concretely many of the differences between traditional society and technological society. <span class="No-Ligatures">Th</span>is book is helpful background for understanding the social context for traditional men’s and women’s roles.</p>
<p class="F-B-MATTER_Bibliography-Entry">Levy, Marion&#160;J., Jr. <span class="Italic">Modernization: Latecomers and Survivors</span>. New York: Basic Books, 1972.</p>
<p class="F-B-MATTER_Bibliography-Annotation">A prominent sociologist points out many of the important but unnoticed social novelties of modern society. <span class="No-Ligatures">Th</span>is book is short, readable, and helpful.</p>
<p class="F-B-MATTER_Bibliography-Entry">Lutzbetak, Louis J. <span class="Italic"><span class="No-Ligatures">Th</span>e Church and Cultures</span>. South Pasadena: William Carey Library, 1975.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is book is a basic presentation of cultural anthropology as applied to Christian pastoral and missionary work. It provides a perspective on culture that is the same as the framework of this book.</p>
<p class="F-B-MATTER_Bibliography-Entry">Nisbet, Robert. <span class="Italic"><span class="No-Ligatures">Th</span>e Quest for Community</span>. New York: Oxford University Press, 1969.</p>
<p class="F-B-MATTER_Bibliography-Annotation">An excellent work of social and intellectual history with an analysis very similar to that found in this volume. <span class="No-Ligatures">Th</span>is book traces the loss of community in modern society to the rise of individualism, the modern nation-state, and the destruction of important intermediate groupings such as the family, the church community, and the guild.</p>
<h2 class="HEADS---SUBHEADS_Less-Than-Subhead">Men’s and Women’s Roles in the Modern World&#160;&#160;▷&#160; Special Problems</h2>
<p class="F-B-MATTER_Bibliography-Entry">Gilder, George F. <span class="Italic">Sexual Suicide</span>. New York: Quadrangle, 1973.</p>
<p class="F-B-MATTER_Bibliography-Annotation"><span class="No-Ligatures">Th</span>is is a helpful analysis of modern problems in the area of men’s and women’s roles. Gilder takes a different approach from the present volume, but provides a useful view on the dangers of the feminist program.</p>
<p class="F-B-MATTER_Bibliography-Entry">Sexton, Patricia Cayo. <span class="Italic"><span class="No-Ligatures">Th</span>e Feminized Male</span>. New York: Vintage, 1969.</p>
<p class="F-B-MATTER_Bibliography-Entry"><span class="two-em-dash">——</span>—. “How the American Boy Is Feminized.” <span class="Italic">Psychology Today</span> 3, no.&#160;8 (January 1970): 23<span class="No-Break">–2</span>9, 66<span class="No-Break">–6</span>7.</p>
<p class="F-B-MATTER_Bibliography-Annotation">Sexton raises important questions about modern changes in the American male. <span class="No-Ligatures">Th</span>e book provides a helpful analysis of the difficulties, though it is almost completely lacking in an understanding of social roles.</p>
