# Scripture Index {-}

<a id="_idParaDest-122"></a><a id="_idTextAnchor2009"></a>
<p class="Index-Note">Page numbers in italics indicate an important discussion or citation of the passage.</p>
<p class="Index-Bible-Book">Genesis</p>
<p class="Index-Level-2">1:26<span class="No-Break">–3</span>1, <span class="Italic">[11](#_idIndexMarker019)<span class="No-Break">–1</span>4</span></p>
<p class="Index-Level-2">1:27, [145](#_idIndexMarker373), [162](#_idIndexMarker418)</p>
<p class="Index-Level-2">1:27<span class="No-Break">–2</span>8, [46](#_idIndexMarker100)</p>
<p class="Index-Level-2">2, <span class="Italic">[15](#_idIndexMarker028)<span class="No-Break">–28</span></span>, [180](#_idIndexMarker453), [181](#_idIndexMarker455), [182](#_idIndexMarker457), [233](#_idIndexMarker562)</p>
<p class="Index-Level-2">2:15, [33](#_idIndexMarker063)</p>
<p class="Index-Level-2">2:24, <span class="Italic">[85](#_idIndexMarker207)<span class="No-Break">–88</span></span>, [145](#_idIndexMarker371)</p>
<p class="Index-Level-2">3, <span class="Italic">[29](#_idIndexMarker053)<span class="No-Break">–45</span></span></p>
<p class="Index-Level-2">3:9, [26](#_idIndexMarker047)</p>
<p class="Index-Level-2">3:15, [209](#_idIndexMarker515)</p>
<p class="Index-Level-2">3:16, <span class="Italic">[31](#_idIndexMarker056)<span class="No-Break">–32</span></span>, [35](#_idIndexMarker072), [191](#_idIndexMarker465), [209](#_idIndexMarker514)</p>
<p class="Index-Level-2">3:21, [26](#_idIndexMarker048)</p>
<p class="Index-Level-2">4:7, [34](#_idIndexMarker065)</p>
<p class="Index-Level-2">5:1<span class="No-Break">–2</span>, [11](#_idIndexMarker017)</p>
<p class="Index-Level-2">5:1<span class="No-Break">–3</span>, [16](#_idIndexMarker031)</p>
<p class="Index-Level-2">5:3, [12](#_idIndexMarker021)</p>
<p class="Index-Level-2">5:29, [35](#_idIndexMarker067)</p>
<p class="Index-Level-2">9:20, [35](#_idIndexMarker068)</p>
<p class="Index-Level-2">12:10<span class="No-Break">–2</span>0, [90n*](#_idIndexMarker216)</p>
<p class="Index-Level-2">13:12, [90](#_idIndexMarker215)</p>
<p class="Index-Level-2">28:40, [35](#_idIndexMarker070)</p>
<p class="Index-Level-2">49:19, [35](#_idIndexMarker071)</p>
<p class="Index-Bible-Book">Leviticus</p>
<p class="Index-Level-2">19:2, [651](#_idIndexMarker1168)</p>
<p class="Index-Level-2">19:18, [81n](#_idIndexMarker192)</p>
<p class="Index-Level-2">19:34, [81n](#_idIndexMarker193)</p>
<p class="Index-Level-2">25:35<span class="No-Break">–4</span>6, [267n](#_idIndexMarker624)</p>
<p class="Index-Bible-Book">Deuteronomy</p>
<p class="Index-Level-2">15:1<span class="No-Break">–6</span>, [267n](#_idIndexMarker621)</p>
<p class="Index-Level-2">15:12<span class="No-Break">–1</span>8, [267n](#_idIndexMarker622)</p>
<p class="Index-Level-2">17:18<span class="No-Break">–2</span>0, [55](#_idIndexMarker131)</p>
<p class="Index-Level-2">23:19<span class="No-Break">–2</span>0, [267n](#_idIndexMarker623)</p>
<p class="Index-Level-2">24:1<span class="No-Break">–4</span>, [4](#_idIndexMarker004)</p>
<p class="Index-Bible-Book">1 Samuel</p>
<p class="Index-Level-2">3:13, [54](#_idIndexMarker129)</p>
<p class="Index-Bible-Book">2 Kings</p>
<p class="Index-Level-2">2:19, [138](#_idIndexMarker357)</p>
<p class="Index-Bible-Book">Job</p>
<p class="Index-Level-2">5:24, [245](#_idIndexMarker582)</p>
<p class="Index-Level-2">29:2<span class="No-Break">–2</span>5, <span class="Italic">[51](#_idIndexMarker125)<span class="No-Break">–53</span></span></p>
<p class="Index-Bible-Book">Psalms</p>
<p class="Index-Level-2">32, [76n](#_idIndexMarker179)</p>
<p class="Index-Level-2">101, <span class="Italic">[53](#_idIndexMarker126)<span class="No-Break">–54</span></span></p>
<p class="Index-Bible-Book">Proverbs</p>
<p class="Index-Level-2">1:8, [62](#_idIndexMarker143)</p>
<p class="Index-Level-2">6:20, [62](#_idIndexMarker144)</p>
<p class="Index-Level-2">12:1, [69n*](#_idIndexMarker163)</p>
<p class="Index-Level-2">31, [346](#_idIndexMarker761)</p>
<p class="Index-Level-2">31:6<span class="No-Break">–7</span>, [35](#_idIndexMarker069)</p>
<p class="Index-Level-2">31:10<span class="No-Break">–2</span>0, [679](#_idIndexMarker1200)</p>
<p class="Index-Level-2">31:10<span class="No-Break">–3</span>1, <span class="Italic">[58](#_idIndexMarker140)<span class="No-Break">–63</span></span></p>
<p class="Index-Bible-Book">Isaiah</p>
<p class="Index-Level-2">8:12<span class="No-Break">–1</span>3, [<span class="Italic">92</span>](#_idIndexMarker223)</p>
<p class="Index-Level-2">45:9<span class="No-Break">–1</span>2, [<span class="Italic">343</span>](#_idIndexMarker756)</p>
<p class="Index-Level-2">56:3<span class="No-Break">–5</span>, [572](#_idIndexMarker1064)</p>
<p class="Index-Bible-Book">Jeremiah</p>
<p class="Index-Level-2">40:17, [149](#_idIndexMarker386)</p>
<p class="Index-Bible-Book">Joel</p>
<p class="Index-Level-2">2:28<span class="No-Break">–2</span>9, [105](#_idIndexMarker248)</p>
<p class="Index-Bible-Book">Sirach</p>
<p class="Index-Level-2">2:15<span class="No-Break">–1</span>7, [345](#_idIndexMarker758)</p>
<p class="Index-Level-2">34:14<span class="No-Break">–1</span>6, [92](#_idIndexMarker224)</p>
<p class="Index-Level-2">36:23<span class="No-Break">–2</span>7, [63](#_idIndexMarker145)</p>
<p class="Index-Bible-Book">Matthew</p>
<p class="Index-Level-2">5:23, [95](#_idIndexMarker234)</p>
<p class="Index-Level-2">5:27<span class="No-Break">–3</span>1, [252](#_idIndexMarker602), [574n](#_idIndexMarker1073)</p>
<p class="Index-Level-2">5:48, [651](#_idIndexMarker1169)</p>
<p class="Index-Level-2">8:9, [174n†<span class="Footnote-Ref">(173)</span>](#_idIndexMarker428)</p>
<p class="Index-Level-2">8:14<span class="No-Break">–1</span>5, [246](#_idIndexMarker587)</p>
<p class="Index-Level-2">10:26<span class="No-Break">–3</span>1, [92n](#_idIndexMarker221)</p>
<p class="Index-Level-2">10:35<span class="No-Break">–3</span>6, [49](#_idIndexMarker109)</p>
<p class="Index-Level-2">16:3, <span class="Italic">[560](#_idIndexMarker1039)<span class="No-Break">–561</span></span></p>
<p class="Index-Level-2">19:3<span class="No-Break">–9</span>, <span class="Italic">[3](#_idIndexMarker000)<span class="No-Break">–4</span></span></p>
<p class="Index-Level-2">19:8, [142](#_idIndexMarker362)</p>
<p class="Index-Level-2">22:16, [50n](#_idIndexMarker115)</p>
<p class="Index-Level-2">23:23, [345](#_idIndexMarker760)</p>
<p class="Index-Level-2">27:2, [127n*](#_idIndexMarker313)</p>
<p class="Index-Level-2">28:9<span class="No-Break">–1</span>0, [246](#_idIndexMarker595)</p>
<p class="Index-Level-2">28:19<span class="No-Break">–2</span>0, [337](#_idIndexMarker736)</p>
<p class="Index-Bible-Book">Mark</p>
<p class="Index-Level-2">2:27, [630](#_idIndexMarker1154)</p>
<p class="Index-Level-2">4:38, [50n](#_idIndexMarker116)</p>
<p class="Index-Level-2">5:25<span class="No-Break">–3</span>4, [246](#_idIndexMarker586)</p>
<p class="Index-Level-2">7:1<span class="No-Break">–2</span>3, [254n](#_idIndexMarker604)</p>
<p class="Index-Level-2">12:14, [50n](#_idIndexMarker117)</p>
<p class="Index-Bible-Book">Luke</p>
<p class="Index-Level-2">2:2, [127n*](#_idIndexMarker314)</p>
<p class="Index-Level-2">3:1, [127n*](#_idIndexMarker315)</p>
<p class="Index-Level-2">3:2, [106n](#_idIndexMarker256)</p>
<p class="Index-Level-2">3:38, [16](#_idIndexMarker033)<span class="No-Break">–1</span>7</p>
<p class="Index-Level-2">5:1, [106n](#_idIndexMarker257)</p>
<p class="Index-Level-2">7:30, [564](#_idIndexMarker1043)</p>
<p class="Index-Level-2">8:1<span class="No-Break">–3</span>, [246](#_idIndexMarker592)</p>
<p class="Index-Level-2">9:36, [76n](#_idIndexMarker174), [198n*](#_idIndexMarker485)</p>
<p class="Index-Level-2">10, [233](#_idIndexMarker563)</p>
<p class="Index-Level-2">10:33<span class="No-Break">–3</span>5, <span class="Italic">[50](#_idIndexMarker121)<span class="No-Break">–51</span></span></p>
<p class="Index-Level-2">10:34<span class="No-Break">–3</span>5, [50n](#_idIndexMarker113)</p>
<p class="Index-Level-2">10:38<span class="No-Break">–4</span>2, [246](#_idIndexMarker590)</p>
<p class="Index-Level-2">10:39, [251](#_idIndexMarker601)</p>
<p class="Index-Level-2">13:16, [246](#_idIndexMarker593)</p>
<p class="Index-Level-2">14:4, [198n*](#_idIndexMarker477)</p>
<p class="Index-Level-2">14:26, [81n](#_idIndexMarker190)</p>
<p class="Index-Level-2">15:3<span class="No-Break">–1</span>0, [246](#_idIndexMarker591)</p>
<p class="Index-Level-2">15:28<span class="No-Break">–3</span>1, <span class="Italic">[65](#_idIndexMarker153)<span class="No-Break">–66</span></span></p>
<p class="Index-Level-2">16:13, [81n](#_idIndexMarker191)</p>
<p class="Index-Level-2">18:39, [198n*](#_idIndexMarker486)</p>
<p class="Index-Level-2">20:26, [198n*](#_idIndexMarker487)</p>
<p class="Index-Level-2">20:34<span class="No-Break">–3</span>6, [164](#_idIndexMarker420)</p>
<p class="Index-Level-2">22:24, [34](#_idIndexMarker066)</p>
<p class="Index-Level-2">22:24<span class="No-Break">–2</span>7, [276](#_idIndexMarker644)</p>
<p class="Index-Level-2">23:56, [198n*](#_idIndexMarker478)</p>
<p class="Index-Bible-Book">John</p>
<p class="Index-Level-2">4:7<span class="No-Break">–2</span>4, [246](#_idIndexMarker589)</p>
<p class="Index-Level-2">4:27, [250](#_idIndexMarker597)</p>
<p class="Index-Level-2">5:19<span class="No-Break">–2</span>0, <span class="Italic">[64](#_idIndexMarker152)<span class="No-Break">–65</span></span></p>
<p class="Index-Level-2">5:19<span class="No-Break">–2</span>3, [94](#_idIndexMarker232)</p>
<p class="Index-Level-2">10:10<span class="No-Break">–1</span>5, [<span class="Italic">51</span>](#_idIndexMarker122)</p>
<p class="Index-Level-2">11:17<span class="No-Break">–4</span>4, [246](#_idIndexMarker588)</p>
<p class="Index-Level-2">13:34<span class="No-Break">–3</span>5, [158](#_idIndexMarker408)</p>
<p class="Index-Level-2">15:18<span class="No-Break">–2</span>5, [582](#_idIndexMarker1083)</p>
<p class="Index-Level-2">17:15<span class="No-Break">–1</span>6, [687](#_idIndexMarker1205)</p>
<p class="Index-Level-2">20:11<span class="No-Break">–1</span>9, [246](#_idIndexMarker594)</p>
<p class="Index-Level-2">20:31, [338](#_idIndexMarker741)</p>
<p class="Index-Bible-Book">Acts</p>
<p class="Index-Level-2">1:14, [105](#_idIndexMarker249)</p>
<p class="Index-Level-2">1:20<span class="No-Break">–2</span>2, [<span class="Italic">131</span>](#_idIndexMarker333)</p>
<p class="Index-Level-2">2:1<span class="No-Break">–4</span>, [105](#_idIndexMarker250)</p>
<p class="Index-Level-2">2:17<span class="No-Break">–1</span>8, [<span class="Italic">105</span>](#_idIndexMarker247)</p>
<p class="Index-Level-2">4:32, [569](#_idIndexMarker1057), [609](#_idIndexMarker1121)</p>
<p class="Index-Level-2">4:35, [609](#_idIndexMarker1119)</p>
<p class="Index-Level-2">5:29, [687](#_idIndexMarker1206)</p>
<p class="Index-Level-2">8:26<span class="No-Break">–2</span>9, [572](#_idIndexMarker1065)</p>
<p class="Index-Level-2">9:36<span class="No-Break">–3</span>9, [<span class="Italic">111</span>](#_idIndexMarker280), [251](#_idIndexMarker599)</p>
<p class="Index-Level-2">12:12, [134](#_idIndexMarker350)</p>
<p class="Index-Level-2">12:17, [198n*](#_idIndexMarker488)</p>
<p class="Index-Level-2">13:1, [107](#_idIndexMarker262)</p>
<p class="Index-Level-2">14:14, [116](#_idIndexMarker285)</p>
<p class="Index-Level-2">15:5, [268](#_idIndexMarker629)</p>
<p class="Index-Level-2">15:12<span class="No-Break">–1</span>3, [198n*](#_idIndexMarker489)</p>
<p class="Index-Level-2">15:32, [106](#_idIndexMarker255)</p>
<p class="Index-Level-2">16:1, [109](#_idIndexMarker274)</p>
<p class="Index-Level-2">16:4, [179](#_idIndexMarker438)</p>
<p class="Index-Level-2">16:15, [134](#_idIndexMarker348)</p>
<p class="Index-Level-2">16:40, [134](#_idIndexMarker347)</p>
<p class="Index-Level-2">18:24<span class="No-Break">–2</span>8, [<span class="Italic">108</span>](#_idIndexMarker268), [117](#_idIndexMarker291)</p>
<p class="Index-Level-2">21:9, [<span class="Italic">104</span>](#_idIndexMarker244)</p>
<p class="Index-Level-2">21:17<span class="No-Break">–2</span>6, [160](#_idIndexMarker411)</p>
<p class="Index-Level-2">21:40, [198n*](#_idIndexMarker490)</p>
<p class="Index-Level-2">23:6, [268](#_idIndexMarker630)</p>
<p class="Index-Bible-Book">Romans</p>
<p class="Index-Level-2">1:18<span class="No-Break">–3</span>2, [267n](#_idIndexMarker619), <span class="Italic">[282](#_idIndexMarker655)<span class="No-Break">–283</span></span>, [<span class="Italic">563</span>](#_idIndexMarker1041)</p>
<p class="Index-Level-2">2:12<span class="No-Break">–1</span>6, [267n](#_idIndexMarker620)</p>
<p class="Index-Level-2">5:14, <span class="Italic">[36](#_idIndexMarker076)<span class="No-Break">–37</span></span></p>
<p class="Index-Level-2">5:17<span class="No-Break">–1</span>8, [<span class="Italic">37</span>](#_idIndexMarker080)</p>
<p class="Index-Level-2">6:16<span class="No-Break">–2</span>3, [340](#_idIndexMarker747)</p>
<p class="Index-Level-2">7:7<span class="No-Break">–1</span>2, [341](#_idIndexMarker750)</p>
<p class="Index-Level-2">8:26, [76n](#_idIndexMarker175)</p>
<p class="Index-Level-2">12:8, [111](#_idIndexMarker279), [127n†](#_idIndexMarker325)</p>
<p class="Index-Level-2">13:1, [127n](#_idIndexMarker326)</p>
<p class="Index-Level-2">13:8<span class="No-Break">–1</span>0, [156](#_idIndexMarker395)</p>
<p class="Index-Level-2">14:1<span class="No-Break">–1</span>5, [160](#_idIndexMarker409)</p>
<p class="Index-Level-2">16:1<span class="No-Break">–2</span>, <span class="Italic">[120](#_idIndexMarker301)<span class="No-Break">–121</span></span></p>
<p class="Index-Level-2">16:1<span class="No-Break">–7</span>, [<span class="Italic">116</span>](#_idIndexMarker288)</p>
<p class="Index-Level-2">16:5, [133](#_idIndexMarker344)</p>
<p class="Index-Level-2">16:6, [309](#_idIndexMarker695)</p>
<p class="Index-Level-2">16:7, [132](#_idIndexMarker338)</p>
<p class="Index-Level-2">16:23, [134](#_idIndexMarker349)</p>
<p class="Index-Level-2">16:25, [198n*](#_idIndexMarker491)</p>
<p class="Index-Bible-Book">1 Corinthians</p>
<p class="Index-Level-2">3:1<span class="No-Break">–3</span>, [156](#_idIndexMarker397)</p>
<p class="Index-Level-2">4:16<span class="No-Break">–1</span>7, [179](#_idIndexMarker442), [180](#_idIndexMarker449)</p>
<p class="Index-Level-2">4:18<span class="No-Break">–2</span>1, [342](#_idIndexMarker754)</p>
<p class="Index-Level-2">5:1<span class="No-Break">–2</span>, [544](#_idIndexMarker1018)</p>
<p class="Index-Level-2">5:1<span class="No-Break">–5</span>, [568](#_idIndexMarker1049)</p>
<p class="Index-Level-2">5:9<span class="No-Break">–1</span>3, [568](#_idIndexMarker1047), [582](#_idIndexMarker1085)</p>
<p class="Index-Level-2">6:1<span class="No-Break">–1</span>1, [568](#_idIndexMarker1048)</p>
<p class="Index-Level-2">7:12<span class="No-Break">–2</span>4, [91](#_idIndexMarker218), <span class="Italic">[148](#_idIndexMarker382)<span class="No-Break">–149</span></span>, <span class="Italic">[156](#_idIndexMarker401)<span class="No-Break">–157</span></span></p>
<p class="Index-Level-2">7:17, [180](#_idIndexMarker450)</p>
<p class="Index-Level-2">7:18, [160](#_idIndexMarker413)</p>
<p class="Index-Level-2">7:22, [162](#_idIndexMarker415)</p>
<p class="Index-Level-2">8:14, [609](#_idIndexMarker1120)</p>
<p class="Index-Level-2">9:5, [117n*](#_idIndexMarker294)</p>
<p class="Index-Level-2">9:9, [50n](#_idIndexMarker118)</p>
<p class="Index-Level-2">9:9<span class="No-Break">–1</span>0, [572n](#_idIndexMarker1066)</p>
<p class="Index-Level-2">9:17<span class="No-Break">–2</span>3, [272](#_idIndexMarker634)</p>
<p class="Index-Level-2">9:22, [285](#_idIndexMarker657)</p>
<p class="Index-Level-2">10:1<span class="No-Break">–1</span>3, [544](#_idIndexMarker1019)</p>
<p class="Index-Level-2">10:32<span class="No-Break">–3</span>3, [272](#_idIndexMarker633)</p>
<p class="Index-Level-2">11, [85](#_idIndexMarker205)</p>
<p class="Index-Level-2">11:2, [179](#_idIndexMarker439), [221](#_idIndexMarker540)</p>
<p class="Index-Level-2">11:2<span class="No-Break">–1</span>6, [5](#_idIndexMarker006), [153](#_idIndexMarker392), <span class="Italic">[169](#_idIndexMarker426)<span class="No-Break">–187</span></span>, [191](#_idIndexMarker464), [214](#_idIndexMarker524), [234](#_idIndexMarker570), [360](#_idIndexMarker786), [361](#_idIndexMarker788), [569](#_idIndexMarker1061)</p>
<p class="Index-Level-2">11:3, [221](#_idIndexMarker541), [233](#_idIndexMarker567), [273](#_idIndexMarker636)</p>
<p class="Index-Level-2">11:5, [<span class="Italic">105</span>](#_idIndexMarker246), [221](#_idIndexMarker545)</p>
<p class="Index-Level-2">11:7<span class="No-Break">–9</span>, [221](#_idIndexMarker542)</p>
<p class="Index-Level-2">11:8<span class="No-Break">–9</span>, [25](#_idIndexMarker046), [204](#_idIndexMarker509), [361](#_idIndexMarker787)</p>
<p class="Index-Level-2">11:10, [221](#_idIndexMarker543)</p>
<p class="Index-Level-2">11:11<span class="No-Break">–1</span>2, [<span class="Italic">165</span>](#_idIndexMarker422), [210](#_idIndexMarker516), [211](#_idIndexMarker518), [221](#_idIndexMarker544), [365](#_idIndexMarker792)</p>
<p class="Index-Level-2">11:16, [180](#_idIndexMarker452), [193](#_idIndexMarker467), [203](#_idIndexMarker505), [273](#_idIndexMarker637), [348](#_idIndexMarker764)</p>
<p class="Index-Level-2">11:18, [188](#_idIndexMarker461)</p>
<p class="Index-Level-2">11:22, [179](#_idIndexMarker440)</p>
<p class="Index-Level-2">12:12<span class="No-Break">–1</span>3, [25](#_idIndexMarker045), <span class="Italic">[146](#_idIndexMarker377)<span class="No-Break">–147</span></span></p>
<p class="Index-Level-2">12:13, [<span class="Italic">149n</span>](#_idIndexMarker388)</p>
<p class="Index-Level-2">12:21<span class="No-Break">–2</span>6, [610](#_idIndexMarker1122)</p>
<p class="Index-Level-2">12:22<span class="No-Break">–2</span>5, [94](#_idIndexMarker233)</p>
<p class="Index-Level-2">12:28, [107](#_idIndexMarker260)</p>
<p class="Index-Level-2">14, [<span class="Italic">204n</span>](#_idIndexMarker508), [310](#_idIndexMarker699)</p>
<p class="Index-Level-2">14:1, [592](#_idIndexMarker1091)</p>
<p class="Index-Level-2">14:26, [631](#_idIndexMarker1155)</p>
<p class="Index-Level-2">14:33<span class="No-Break">–3</span>6, [179](#_idIndexMarker446), [180](#_idIndexMarker451), <span class="Italic">[187](#_idIndexMarker460)<span class="No-Break">–193</span></span>, [198](#_idIndexMarker475), [214](#_idIndexMarker525), [221](#_idIndexMarker546), [320](#_idIndexMarker721)</p>
<p class="Index-Level-2">14:34, [33n*](#_idIndexMarker062), [106](#_idIndexMarker254), [273](#_idIndexMarker638)</p>
<p class="Index-Level-2">14:34<span class="No-Break">–3</span>5, [229](#_idIndexMarker556), [569](#_idIndexMarker1060)</p>
<p class="Index-Level-2">14:34<span class="No-Break">–3</span>6, [108](#_idIndexMarker266), [273](#_idIndexMarker639), [348](#_idIndexMarker765)</p>
<p class="Index-Level-2">14:37, [221](#_idIndexMarker547), [252](#_idIndexMarker603)</p>
<p class="Index-Level-2">14:38, [221](#_idIndexMarker548)</p>
<p class="Index-Level-2">14:40, [186](#_idIndexMarker459)</p>
<p class="Index-Level-2">15:1<span class="No-Break">–5</span>, [179](#_idIndexMarker432)</p>
<p class="Index-Level-2">15:20<span class="No-Break">–2</span>8, [87](#_idIndexMarker209)</p>
<p class="Index-Level-2">15:24<span class="No-Break">–2</span>7, [41](#_idIndexMarker093)</p>
<p class="Index-Level-2">15:28, [76n](#_idIndexMarker176)</p>
<p class="Index-Level-2">15:47<span class="No-Break">–4</span>9, <span class="Italic">[37](#_idIndexMarker082)<span class="No-Break">–38</span></span></p>
<p class="Index-Level-2">16:9, [133](#_idIndexMarker345)</p>
<p class="Index-Level-2">16:16, [127n†](#_idIndexMarker317)</p>
<p class="Index-Level-2">16:19, [117](#_idIndexMarker292)</p>
<p class="Index-Bible-Book">2 Corinthians</p>
<p class="Index-Level-2">3, [350](#_idIndexMarker771)</p>
<p class="Index-Level-2">3:3, [342](#_idIndexMarker752)</p>
<p class="Index-Level-2">5:15, [352](#_idIndexMarker774)</p>
<p class="Index-Level-2">8:1<span class="No-Break">–1</span>5, [569](#_idIndexMarker1058)</p>
<p class="Index-Bible-Book">Galatians</p>
<p class="Index-Level-2">1:6, [544](#_idIndexMarker1016)</p>
<p class="Index-Level-2">1:9, [179](#_idIndexMarker430)</p>
<p class="Index-Level-2">1:12, [179](#_idIndexMarker431)</p>
<p class="Index-Level-2">2:9, [180](#_idIndexMarker448)</p>
<p class="Index-Level-2">2:11<span class="No-Break">–1</span>4, [160](#_idIndexMarker410)</p>
<p class="Index-Level-2">2:12, [142](#_idIndexMarker363)</p>
<p class="Index-Level-2">3:1, [544](#_idIndexMarker1017)</p>
<p class="Index-Level-2">3:21, [142](#_idIndexMarker361)</p>
<p class="Index-Level-2">3:23<span class="No-Break">–2</span>9, <span class="Italic">[142](#_idIndexMarker360)<span class="No-Break">–145</span></span></p>
<p class="Index-Level-2">3:23<span class="No-Break">–4</span>:7, [342](#_idIndexMarker753)</p>
<p class="Index-Level-2">3:26<span class="No-Break">–2</span>8, [5](#_idIndexMarker007), [365](#_idIndexMarker793)</p>
<p class="Index-Level-2">3:28, [32](#_idIndexMarker059), <span class="Italic">[142](#_idIndexMarker359)<span class="No-Break">–167</span></span>, [223](#_idIndexMarker553), [234](#_idIndexMarker572), [241](#_idIndexMarker574), [255](#_idIndexMarker605), [269](#_idIndexMarker631), [295](#_idIndexMarker675), [369](#_idIndexMarker795), [371](#_idIndexMarker798)</p>
<p class="Index-Level-2">4:4, [211](#_idIndexMarker519)</p>
<p class="Index-Level-2">4:4<span class="No-Break">–7</span>, [<span class="Italic">147</span>](#_idIndexMarker380)</p>
<p class="Index-Level-2">4:12, [179](#_idIndexMarker445)</p>
<p class="Index-Level-2">5:3, [143](#_idIndexMarker367), [160](#_idIndexMarker412)</p>
<p class="Index-Level-2">5:13, [341](#_idIndexMarker751)</p>
<p class="Index-Level-2">5:14, [143](#_idIndexMarker365), [156](#_idIndexMarker396)</p>
<p class="Index-Level-2">5:16<span class="No-Break">–2</span>6, [156](#_idIndexMarker398)</p>
<p class="Index-Level-2">5:23, [93](#_idIndexMarker227)</p>
<p class="Index-Level-2">6:2, [143](#_idIndexMarker366)</p>
<p class="Index-Level-2">6:6, [573](#_idIndexMarker1071)</p>
<p class="Index-Level-2">6:15, [145](#_idIndexMarker374)</p>
<p class="Index-Bible-Book">Ephesians</p>
<p class="Index-Level-2">1:9<span class="No-Break">–1</span>0, [<span class="Italic">38</span>](#_idIndexMarker084)</p>
<p class="Index-Level-2">1:22, [183](#_idIndexMarker458)</p>
<p class="Index-Level-2">2:12, [262](#_idIndexMarker611)</p>
<p class="Index-Level-2">2:13<span class="No-Break">–1</span>6, [147](#_idIndexMarker379)</p>
<p class="Index-Level-2">2:14<span class="No-Break">–1</span>6, [<span class="Italic">37</span>](#_idIndexMarker081)</p>
<p class="Index-Level-2">3:5, [107](#_idIndexMarker261)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–3</span>, [651](#_idIndexMarker1172)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–6</span>, [39](#_idIndexMarker086)</p>
<p class="Index-Level-2">4:7<span class="No-Break">–1</span>6, [85](#_idIndexMarker206)</p>
<p class="Index-Level-2">4:17<span class="No-Break">–2</span>4, [276](#_idIndexMarker643), <span class="Italic">[281](#_idIndexMarker649)<span class="No-Break">–283</span></span></p>
<p class="Index-Level-2">4:22<span class="No-Break">–2</span>4, [<span class="Italic">38</span>](#_idIndexMarker083)</p>
<p class="Index-Level-2">5:21, [220](#_idIndexMarker532)</p>
<p class="Index-Level-2">5:21<span class="No-Break">–3</span>3, [233](#_idIndexMarker569)</p>
<p class="Index-Level-2">5:22<span class="No-Break">–3</span>1, [5](#_idIndexMarker008), [220](#_idIndexMarker533)</p>
<p class="Index-Level-2">5:22<span class="No-Break">–3</span>3, [47](#_idIndexMarker102), <span class="Italic">[73](#_idIndexMarker169)<span class="No-Break">–88</span></span>, [147](#_idIndexMarker378), [370](#_idIndexMarker796), [549](#_idIndexMarker1029)</p>
<p class="Index-Level-2">5:23, [233](#_idIndexMarker568), [301](#_idIndexMarker681)</p>
<p class="Index-Level-2">5:28<span class="No-Break">–3</span>0, [220](#_idIndexMarker534)</p>
<p class="Index-Level-2">5:31, [220](#_idIndexMarker535)</p>
<p class="Index-Level-2">5:31<span class="No-Break">–3</span>2, [145](#_idIndexMarker372)</p>
<p class="Index-Level-2">5:32, [39](#_idIndexMarker088)</p>
<p class="Index-Level-2">5:33, [39](#_idIndexMarker089)</p>
<p class="Index-Level-2">6:1, [68](#_idIndexMarker159)</p>
<p class="Index-Level-2">6:2, [68](#_idIndexMarker158)</p>
<p class="Index-Level-2">6:4, [<span class="Italic">69</span>](#_idIndexMarker162)</p>
<p class="Index-Level-2">6:5<span class="No-Break">–9</span>, [<span class="Italic">157</span>](#_idIndexMarker402)</p>
<p class="Index-Bible-Book">Philippians</p>
<p class="Index-Level-2">1:27, [569](#_idIndexMarker1055)</p>
<p class="Index-Level-2">2:2, [569](#_idIndexMarker1056)</p>
<p class="Index-Level-2">2:3, [127n†](#_idIndexMarker320)</p>
<p class="Index-Level-2">2:6, [86](#_idIndexMarker208)</p>
<p class="Index-Level-2">3:17, [179](#_idIndexMarker441)</p>
<p class="Index-Level-2">3:20, [537](#_idIndexMarker1006)</p>
<p class="Index-Level-2">4:2<span class="No-Break">–3</span>, [<span class="Italic">116</span>](#_idIndexMarker290), [<span class="Italic">256</span>](#_idIndexMarker608)</p>
<p class="Index-Level-2">4:9, [179](#_idIndexMarker437)</p>
<p class="Index-Bible-Book">Colossians</p>
<p class="Index-Level-2">1:18, [220](#_idIndexMarker536)</p>
<p class="Index-Level-2">2:5, [80](#_idIndexMarker184)</p>
<p class="Index-Level-2">2:6<span class="No-Break">–8</span>, [179](#_idIndexMarker434)</p>
<p class="Index-Level-2">2:17, [572n](#_idIndexMarker1067)</p>
<p class="Index-Level-2">3:9<span class="No-Break">–1</span>1, <span class="Italic">[145](#_idIndexMarker375)<span class="No-Break">–146</span></span></p>
<p class="Index-Level-2">3:11, [<span class="Italic">149n</span>](#_idIndexMarker387), [156](#_idIndexMarker399)</p>
<p class="Index-Level-2">3:12<span class="No-Break">–1</span>7, [651](#_idIndexMarker1173)</p>
<p class="Index-Level-2">3:18<span class="No-Break">–1</span>9, [47](#_idIndexMarker103), [74](#_idIndexMarker171), <span class="Italic">[77](#_idIndexMarker182)<span class="No-Break">–88</span></span></p>
<p class="Index-Level-2">3:22, [569](#_idIndexMarker1062)</p>
<p class="Index-Level-2">3:22<span class="No-Break">–4</span>:1, [153](#_idIndexMarker393)</p>
<p class="Index-Level-2">4:5, [582](#_idIndexMarker1084)</p>
<p class="Index-Level-2">4:15, [133](#_idIndexMarker346)</p>
<p class="Index-Bible-Book">1 Thessalonians</p>
<p class="Index-Level-2">2:6, [116](#_idIndexMarker286)</p>
<p class="Index-Level-2">2:13, [179](#_idIndexMarker435)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–2</span>, [337](#_idIndexMarker738)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–8</span>, [276](#_idIndexMarker645)</p>
<p class="Index-Level-2">4:11, [93](#_idIndexMarker228), [198n*](#_idIndexMarker479), [682](#_idIndexMarker1202)</p>
<p class="Index-Level-2">5:12, [127n†](#_idIndexMarker323)</p>
<p class="Index-Bible-Book">2 Thessalonians</p>
<p class="Index-Level-2">2:15, [179](#_idIndexMarker433)</p>
<p class="Index-Level-2">3:6, [179](#_idIndexMarker436)</p>
<p class="Index-Level-2">3:7<span class="No-Break">–9</span>, [179](#_idIndexMarker443)</p>
<p class="Index-Level-2">3:12, [198n*](#_idIndexMarker480)</p>
<p class="Index-Bible-Book">1 Timothy</p>
<p class="Index-Level-2">1:6<span class="No-Break">–7</span>, [544](#_idIndexMarker1020)</p>
<p class="Index-Level-2">1:18, [286](#_idIndexMarker659)</p>
<p class="Index-Level-2">2:1<span class="No-Break">–2</span>, [568](#_idIndexMarker1054)</p>
<p class="Index-Level-2">2:2, [127n†](#_idIndexMarker322), [198n*](#_idIndexMarker481)</p>
<p class="Index-Level-2">2:8<span class="No-Break">–1</span>5, [109](#_idIndexMarker275), <span class="Italic">[194](#_idIndexMarker468)<span class="No-Break">–211</span></span>, [223n](#_idIndexMarker552)</p>
<p class="Index-Level-2">2:9, [349](#_idIndexMarker767)</p>
<p class="Index-Level-2">2:9<span class="No-Break">–1</span>5, [5](#_idIndexMarker009)</p>
<p class="Index-Level-2">2:11, [93](#_idIndexMarker226), [198n*](#_idIndexMarker482), [214](#_idIndexMarker527)</p>
<p class="Index-Level-2">2:11<span class="No-Break">–1</span>2, [569](#_idIndexMarker1059)</p>
<p class="Index-Level-2">2:12, [106](#_idIndexMarker253), [108](#_idIndexMarker267), [189](#_idIndexMarker463), [198n*](#_idIndexMarker483), [221](#_idIndexMarker549), [273](#_idIndexMarker640), <span class="Italic">[308](#_idIndexMarker694)<span class="No-Break">–309</span></span>, [313](#_idIndexMarker709), [320](#_idIndexMarker720)</p>
<p class="Index-Level-2">2:13, [221](#_idIndexMarker550)</p>
<p class="Index-Level-2">2:13<span class="No-Break">–1</span>4, [359](#_idIndexMarker785)</p>
<p class="Index-Level-2">2:14, [33n*](#_idIndexMarker061), [221](#_idIndexMarker551)</p>
<p class="Index-Level-2">2:19, [354](#_idIndexMarker781)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–7</span>, <span class="Italic">[49](#_idIndexMarker110)<span class="No-Break">–53</span></span></p>
<p class="Index-Level-2">3:2, [131](#_idIndexMarker336)</p>
<p class="Index-Level-2">3:4, [<span class="Italic">68</span>](#_idIndexMarker157), [82](#_idIndexMarker197), [568](#_idIndexMarker1052)</p>
<p class="Index-Level-2">3:5, [50n](#_idIndexMarker114)</p>
<p class="Index-Level-2">3:8<span class="No-Break">–1</span>3, <span class="Italic">[119](#_idIndexMarker300)<span class="No-Break">–120</span></span></p>
<p class="Index-Level-2">3:9, [568](#_idIndexMarker1050)</p>
<p class="Index-Level-2">3:15, [136](#_idIndexMarker356)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–3</span>, [544](#_idIndexMarker1021)</p>
<p class="Index-Level-2">4:3, [209](#_idIndexMarker513)</p>
<p class="Index-Level-2">4:11, [199](#_idIndexMarker495)</p>
<p class="Index-Level-2">4:16<span class="No-Break">–5</span>:2, [199](#_idIndexMarker496)</p>
<p class="Index-Level-2">5:1<span class="No-Break">–2</span>, [<span class="Italic">136</span>](#_idIndexMarker354)</p>
<p class="Index-Level-2">5:2, <span class="Italic">[132](#_idIndexMarker340)<span class="No-Break">–133</span></span>, [233](#_idIndexMarker564)</p>
<p class="Index-Level-2">5:3<span class="No-Break">–1</span>6, <span class="Italic">[111](#_idIndexMarker282)<span class="No-Break">–112</span></span></p>
<p class="Index-Level-2">5:10, [<span class="Italic">56</span>](#_idIndexMarker136)</p>
<p class="Index-Level-2">5:13<span class="No-Break">–1</span>6, <span class="Italic">[56](#_idIndexMarker135)<span class="No-Break">–57</span></span></p>
<p class="Index-Level-2">5:14, <span class="Italic">[56](#_idIndexMarker137)<span class="No-Break">–57</span></span></p>
<p class="Index-Level-2">5:17, [127n†](#_idIndexMarker324)</p>
<p class="Index-Level-2">6:1<span class="No-Break">–2</span>, [157](#_idIndexMarker403)</p>
<p class="Index-Level-2">6:14, [286](#_idIndexMarker660)</p>
<p class="Index-Level-2">6:17<span class="No-Break">–1</span>9, [610](#_idIndexMarker1126)</p>
<p class="Index-Bible-Book">2 Timothy</p>
<p class="Index-Level-2">1:5, [<span class="Italic">109</span>](#_idIndexMarker272)</p>
<p class="Index-Level-2">2:2, [286](#_idIndexMarker661)</p>
<p class="Index-Level-2">2:18, [203](#_idIndexMarker504)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–5</span>, <span class="Italic">[563](#_idIndexMarker1042)<span class="No-Break">–564</span></span></p>
<p class="Index-Level-2">3:6<span class="No-Break">–1</span>5, [337](#_idIndexMarker737)</p>
<p class="Index-Level-2">3:10, [179](#_idIndexMarker444)</p>
<p class="Index-Level-2">3:15, [<span class="Italic">109</span>](#_idIndexMarker273)</p>
<p class="Index-Level-2">3:16, [336](#_idIndexMarker733), [572n](#_idIndexMarker1069)</p>
<p class="Index-Level-2">3:16<span class="No-Break">–1</span>7, [338](#_idIndexMarker744)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–4</span>, [199](#_idIndexMarker497)</p>
<p class="Index-Level-2">4:1<span class="No-Break">–5</span>, [286](#_idIndexMarker662)</p>
<p class="Index-Level-2">4:19, [117](#_idIndexMarker293)</p>
<p class="Index-Bible-Book">Titus</p>
<p class="Index-Level-2">1, [68](#_idIndexMarker161)<span class="No-Break">–6</span>9</p>
<p class="Index-Level-2">1:6, [50](#_idIndexMarker112), [82](#_idIndexMarker198), [131](#_idIndexMarker337)</p>
<p class="Index-Level-2">2:1<span class="No-Break">–2</span>, [568](#_idIndexMarker1053)</p>
<p class="Index-Level-2">2:1<span class="No-Break">–6</span>, <span class="Italic">[108](#_idIndexMarker271)<span class="No-Break">–109</span></span></p>
<p class="Index-Level-2">2:3, [203n](#_idIndexMarker507)</p>
<p class="Index-Level-2">2:3<span class="No-Break">–4</span>, [<span class="Italic">309</span>](#_idIndexMarker696)</p>
<p class="Index-Level-2">2:4<span class="No-Break">–6</span>, [<span class="Italic">57</span>](#_idIndexMarker138)</p>
<p class="Index-Level-2">2:15, [199](#_idIndexMarker498)</p>
<p class="Index-Level-2">3:1, [127n†](#_idIndexMarker327)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–2</span>, [687](#_idIndexMarker1207)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–7</span>, [582](#_idIndexMarker1082)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–8</span>, [262](#_idIndexMarker612)</p>
<p class="Index-Level-2">3:3<span class="No-Break">–8</span>, [276](#_idIndexMarker646)</p>
<p class="Index-Level-2">3:8<span class="No-Break">–1</span>1, [199](#_idIndexMarker499)</p>
<p class="Index-Bible-Book">Hebrews</p>
<p class="Index-Level-2">2:8, [76n](#_idIndexMarker177)</p>
<p class="Index-Level-2">3:5<span class="No-Break">–6</span>, [<span class="Italic">66</span>](#_idIndexMarker154)</p>
<p class="Index-Level-2">7:9, [16](#_idIndexMarker032), [36](#_idIndexMarker078)</p>
<p class="Index-Level-2">10:1, [572n](#_idIndexMarker1068)</p>
<p class="Index-Level-2">10:25, [573](#_idIndexMarker1072)</p>
<p class="Index-Level-2">11:8<span class="No-Break">–1</span>6, [537](#_idIndexMarker1004)</p>
<p class="Index-Level-2">12:10, [651](#_idIndexMarker1171)</p>
<p class="Index-Level-2">13:14, [537](#_idIndexMarker1005)</p>
<p class="Index-Level-2">13:17, [54](#_idIndexMarker128), [127n†](#_idIndexMarker319)</p>
<p class="Index-Bible-Book">James</p>
<p class="Index-Level-2">2:1<span class="No-Break">–7</span>, [175](#_idIndexMarker429), [610](#_idIndexMarker1125)</p>
<p class="Index-Level-2">4:4, [<span class="Italic">282</span>](#_idIndexMarker653)</p>
<p class="Index-Level-2">5:16, [76n](#_idIndexMarker178)</p>
<p class="Index-Bible-Book">1 Peter</p>
<p class="Index-Level-2">1:1, [537](#_idIndexMarker1002)</p>
<p class="Index-Level-2">1:13<span class="No-Break">–1</span>7, [651](#_idIndexMarker1170)</p>
<p class="Index-Level-2">2:9, [262](#_idIndexMarker610)</p>
<p class="Index-Level-2">2:11, [537](#_idIndexMarker1003)</p>
<p class="Index-Level-2">2:13, [127n†](#_idIndexMarker321), [573](#_idIndexMarker1070)</p>
<p class="Index-Level-2">2:13<span class="No-Break">–1</span>4, [127n†](#_idIndexMarker328)</p>
<p class="Index-Level-2">2:16, [162](#_idIndexMarker416)</p>
<p class="Index-Level-2">2:18, [82](#_idIndexMarker199)</p>
<p class="Index-Level-2">2:18<span class="No-Break">–2</span>5, [162](#_idIndexMarker417)</p>
<p class="Index-Level-2">3, [82](#_idIndexMarker200)<span class="No-Break">–8</span>3</p>
<p class="Index-Level-2">3:1<span class="No-Break">–2</span>, [220](#_idIndexMarker537)</p>
<p class="Index-Level-2">3:1<span class="No-Break">–7</span>, [47](#_idIndexMarker104), <span class="Italic">[88](#_idIndexMarker211)<span class="No-Break">–95</span></span>, [91](#_idIndexMarker219), [370](#_idIndexMarker797)</p>
<p class="Index-Level-2">3:3, [349](#_idIndexMarker768), [354](#_idIndexMarker782), [568](#_idIndexMarker1051)</p>
<p class="Index-Level-2">3:3<span class="No-Break">–6</span>, <span class="Italic">[196](#_idIndexMarker471)<span class="No-Break">–198</span></span></p>
<p class="Index-Level-2">3:4, [198n*](#_idIndexMarker484), [214](#_idIndexMarker526), [221](#_idIndexMarker538)</p>
<p class="Index-Level-2">3:6, [191](#_idIndexMarker466)</p>
<p class="Index-Level-2">3:7, [147](#_idIndexMarker381), [214](#_idIndexMarker528), [221](#_idIndexMarker539)</p>
<p class="Index-Level-2">3:14<span class="No-Break">–1</span>6, [<span class="Italic">92</span>](#_idIndexMarker222)</p>
<p class="Index-Level-2">5:1, [120](#_idIndexMarker303)</p>
<p class="Index-Level-2">5:5, [127n†](#_idIndexMarker318)</p>
<p class="Index-Level-2">5:7, [50n](#_idIndexMarker119)</p>
<p class="Index-Level-2">5:13, [233](#_idIndexMarker566)</p>
<p class="Index-Bible-Book">2 Peter</p>
<p class="Index-Level-2">1:19<span class="No-Break">–2</span>1, [338](#_idIndexMarker742)</p>
<p class="Index-Level-2">3:15<span class="No-Break">–1</span>7, [338](#_idIndexMarker743), [<span class="Italic">351</span>](#_idIndexMarker773)</p>
<p class="Index-Bible-Book">1 John</p>
<p class="Index-Level-2">2:7<span class="No-Break">–8</span>, [158](#_idIndexMarker407)</p>
<p class="Index-Level-2">2:15<span class="No-Break">–1</span>7, <span class="Italic">[281](#_idIndexMarker652)<span class="No-Break">–282</span></span></p>
<p class="Index-Level-2">5:4<span class="No-Break">–5</span>, <span class="Italic">[281](#_idIndexMarker651)<span class="No-Break">–282</span></span></p>
<p class="Index-Bible-Book">2 John</p>
<p class="Index-Level-2">1:1, [233](#_idIndexMarker565)</p>
<p class="Index-Level-2">1:5, [158](#_idIndexMarker406)</p>
<p class="Index-Bible-Book">Jude</p>
<p class="Index-Level-2">1:9<span class="No-Break">–1</span>5, [268](#_idIndexMarker627)</p>
<p class="Index-Bible-Book">Revelation</p>
<p class="Index-Level-2">1:2, [106n](#_idIndexMarker258)</p>
<p class="Index-Level-2">8:1, [198n*](#_idIndexMarker492)</p>
<p class="Index-Level-2">14:9, [350](#_idIndexMarker770)</p>
<p class="Index-Level-2">19:10, [106n](#_idIndexMarker259)</p>
<p class="Index-Level-2">21:14, [180](#_idIndexMarker447), [336](#_idIndexMarker735)</p>
