# Topical Index {-}

<a id="_idParaDest-123"></a><a id="_idTextAnchor2010"></a>
<p class="Index-Level-1">abbesses</p>
<p class="Index-Level-2">authority of, [316](#_idIndexMarker717)<span class="No-Break">–3</span>18</p>
<p class="Index-Level-2">priesthood of, [317](#_idIndexMarker718)<span class="No-Break">–3</span>18</p>
<p class="Index-Level-1">Abraham and Sarah, [89](#_idIndexMarker214)<span class="No-Break">–9</span>0</p>
<p class="Index-Level-1">achievement orientation (in technological society), [497](#_idIndexMarker961)</p>
<p class="Index-Level-1"><span class="Italic">Acts of Paul</span>, [118](#_idIndexMarker296)</p>
<p class="Index-Level-1"><span class="Italic">adam</span>, [12](#_idIndexMarker022)<span class="No-Break">–1</span>3, [16](#_idIndexMarker030), [36](#_idIndexMarker077)</p>
<p class="Index-Level-1">Adam (as type of Jesus), [36](#_idIndexMarker074)<span class="No-Break">–3</span>9</p>
<p class="Index-Level-1">adornment</p>
<p class="Index-Level-2">New Testament injunction, [196](#_idIndexMarker472)</p>
<p class="Index-Level-2">women and subordination, [92](#_idIndexMarker225)<span class="No-Break">–9</span>3</p>
<p class="Index-Level-1"><span class="Italic">agapē</span>, [80](#_idIndexMarker186), [158](#_idIndexMarker405)</p>
<p class="Index-Level-1">aggression</p>
<p class="Index-Level-2">animal studies, [413](#_idIndexMarker869)</p>
<p class="Index-Level-2">cross-cultural studies, [411](#_idIndexMarker867)<span class="No-Break">–4</span>12</p>
<p class="Index-Level-2">male character, [658](#_idIndexMarker1181)</p>
<p class="Index-Level-2">man/woman differences, [404](#_idIndexMarker835)<span class="No-Break">–4</span>05, [436](#_idIndexMarker902)</p>
<p class="Index-Level-1"><span class="Italic">ahab</span> (root of <span class="Italic">agapē</span>), [81n](#_idIndexMarker189)</p>
<p class="Index-Level-1">Ambrose, Bishop of Milan, [296](#_idIndexMarker677)<span class="No-Break">–2</span>97</p>
<p class="Index-Level-1"><span class="Italic">anēr</span> (male), [13n](#_idIndexMarker026), [131](#_idIndexMarker334)</p>
<p class="Index-Level-1"><span class="Italic">anthrōpos</span> (human), [13n](#_idIndexMarker025), [131](#_idIndexMarker335)</p>
<p class="Index-Level-1">anxiety, [517](#_idIndexMarker983), [663](#_idIndexMarker1188)<span class="No-Break">–6</span>64</p>
<p class="Index-Level-2">man/woman differences, [407](#_idIndexMarker842)</p>
<p class="Index-Level-1">Apollos, [108](#_idIndexMarker269)</p>
<p class="Index-Level-1">apostle, [116](#_idIndexMarker287), [130](#_idIndexMarker331)</p>
<p class="Index-Level-1"><span class="Italic">Apostolic Church Order</span>, [312](#_idIndexMarker702)</p>
<p class="Index-Level-1"><span class="Italic">Apostolic Constitutions</span>, [312](#_idIndexMarker703)</p>
<p class="Index-Level-1">Aquila, [108](#_idIndexMarker270), [116](#_idIndexMarker289), [133](#_idIndexMarker343)</p>
<p class="Index-Level-1">ascetic movement, [314](#_idIndexMarker715)<span class="No-Break">–3</span>16</p>
<p class="Index-Level-1">Augustine, [299](#_idIndexMarker679)<span class="No-Break">–3</span>00</p>
<p class="Index-Level-1"><span class="Italic">authentein</span> (authority), [199](#_idIndexMarker500)<span class="No-Break">–2</span>01</p>
<p class="Index-Level-1">authenticity, [500](#_idIndexMarker963)<span class="No-Break">–5</span>01, [546](#_idIndexMarker1026)<span class="No-Break">–5</span>47, [605](#_idIndexMarker1113)<span class="No-Break">–6</span>06</p>
<p class="Index-Level-1">authority</p>
<p class="Index-Level-2">biblical vs. contemporary views of, [55](#_idIndexMarker130)<span class="No-Break">–5</span>6</p>
<p class="Index-Level-2">bypassing scriptural, [358](#_idIndexMarker784)<span class="No-Break">–3</span>75</p>
<p class="Index-Level-2">of scripture, [333](#_idIndexMarker729)<span class="No-Break">–3</span>57</p>
<p class="Index-Level-2">socialism and, [527](#_idIndexMarker992)</p>
<p class="Index-Level-2">and teaching, [201](#_idIndexMarker501)</p>
<p class="Leading-Entry-Leading">baptism, [144](#_idIndexMarker368)</p>
<p class="Index-Level-1">Bardwick, Judith, [475](#_idIndexMarker934)<span class="No-Break">–4</span>76</p>
<p class="Index-Level-1">Basil of Caesarea, [321](#_idIndexMarker723)</p>
<p class="Index-Level-1">behavioral psychology. <span class="Index-Cross-reference">See</span>&#160;<a href="#behaviorism">behaviorism</a></p>
<p class="Index-Level-1" id="behaviorism">behaviorism, [465](#_idIndexMarker926)</p>
<p class="Index-Level-1">Bem, Sandra, [468](#_idIndexMarker928)</p>
<p class="Index-Level-1">Bernard, Jessie, [470](#_idIndexMarker931)</p>
<p class="Index-Level-1">biodeterminism, [452](#_idIndexMarker917)<span class="No-Break">–4</span>56</p>
<p class="Index-Level-1">bodily experience (man/&#8203;woman differences), [395](#_idIndexMarker822)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-1">Boucher, Madeleine, [165](#_idIndexMarker423)<span class="No-Break">–1</span>66, [234](#_idIndexMarker571)</p>
<p class="Index-Level-1">brain (man/&#8203;woman differences), [409](#_idIndexMarker865)</p>
<p class="Index-Level-1">Buytendijk, F.&#160;J.&#160;J., [390](#_idIndexMarker811)<span class="No-Break">–3</span>91, [395](#_idIndexMarker823), [399](#_idIndexMarker828)<span class="No-Break">–4</span>01</p>
<p class="Leading-Entry-Leading">canon. <span class="Index-Cross-reference">See</span>&#160;<a href="#canonicity">scripture: canonicity of</a></p>
<p class="Index-Level-1">care-subordination, [41](#_idIndexMarker094)</p>
<p class="Index-Level-1">celibacy/&#8203;celibates</p>
<p class="Index-Level-2">order of virgins, [315](#_idIndexMarker716)</p>
<p class="Index-Level-2">and personal relationships, [669](#_idIndexMarker1197)<span class="No-Break">–6</span>71</p>
<p class="Index-Level-2">value of, [163](#_idIndexMarker419)<span class="No-Break">–1</span>64</p>
<p class="Index-Level-1">Chafetz, Janet, [469](#_idIndexMarker930)</p>
<p class="Index-Level-1">charitable service, [110](#_idIndexMarker278)<span class="No-Break">–1</span>13</p>
<p class="Index-Level-1">childbearing, [31](#_idIndexMarker055), [208](#_idIndexMarker512)<span class="No-Break">–2</span>11</p>
<p class="Index-Level-1">childrearing</p>
<p class="Index-Level-2">discipline, [69](#_idIndexMarker164)</p>
<p class="Index-Level-2">guidelines for, [617](#_idIndexMarker1133)</p>
<p class="Index-Level-2">New Testament practice, [64](#_idIndexMarker147)<span class="No-Break">–7</span>0</p>
<p class="Index-Level-1">Christian character, [650](#_idIndexMarker1167)<span class="No-Break">–6</span>53</p>
<p class="Index-Level-1">Christian community. <span class="Index-Cross-reference">See</span>&#160;<a href="#christian-community">community (Christian)</a></p>
<p class="Index-Level-1">Christian ethics, [544](#_idIndexMarker1015)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-1">Christian Liberationist</p>
<p class="Index-Level-2">approach to culture, [274](#_idIndexMarker642)<span class="No-Break">–2</span>85</p>
<p class="Index-Level-2">exegesis, [230](#_idIndexMarker561)<span class="No-Break">–2</span>35</p>
<p class="Index-Level-1">Christianity</p>
<p class="Index-Level-2">challenged in twentieth century, [589](#_idIndexMarker1086)<span class="No-Break">–5</span>91, [598](#_idIndexMarker1103)<span class="No-Break">–5</span>99</p>
<p class="Index-Level-2">historical challenges to, [537](#_idIndexMarker1001)<span class="No-Break">–5</span>40</p>
<p class="Index-Level-2">modern ethics and, [548](#_idIndexMarker1028)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-2">modern ideologies and, [539](#_idIndexMarker1009)<span class="No-Break">–5</span>40</p>
<p class="Index-Level-2">modern secular influences on, [540](#_idIndexMarker1010)<span class="No-Break">–5</span>43</p>
<p class="Index-Level-2">and non-Christian ethical systems, [544](#_idIndexMarker1014)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-1">Chrysostom, John, [61](#_idIndexMarker142), [91](#_idIndexMarker220), [136](#_idIndexMarker355), [297](#_idIndexMarker678)<span class="No-Break">–2</span>99, [308](#_idIndexMarker693)<span class="No-Break">–3</span>09</p>
<p class="Index-Level-1">church Fathers. <span class="Index-Cross-reference">See</span>&#160;<span class="Italic">specific topics</span></p>
<p class="Index-Level-1">church, modern</p>
<p class="Index-Level-2">community in, [596](#_idIndexMarker1098)<span class="No-Break">–5</span>97</p>
<p class="Index-Level-2">leadership in, [642](#_idIndexMarker1162)<span class="No-Break">–6</span>50</p>
<p class="Index-Level-1">Church of Sweden, [234](#_idIndexMarker573)<span class="No-Break">–2</span>35</p>
<p class="Index-Level-1">church orders, [194](#_idIndexMarker470)<span class="No-Break">–1</span>95, [311](#_idIndexMarker700)<span class="No-Break">–3</span>12</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<span class="Italic">specific councils and synods</span></p>
<p class="Index-Level-1">circumcision, [144](#_idIndexMarker370)</p>
<p class="Index-Level-1">Clement of Alexandria, [117](#_idIndexMarker295)<span class="No-Break">–1</span>18, [293](#_idIndexMarker672)<span class="No-Break">–2</span>94</p>
<p class="Index-Level-1">Clement of Rome, [127](#_idIndexMarker329)<span class="No-Break">–1</span>28, [291](#_idIndexMarker669)<span class="No-Break">–2</span>92, [337](#_idIndexMarker739)</p>
<p class="Index-Level-1">commitment (in technological society), [497](#_idIndexMarker962)<span class="No-Break">–4</span>98</p>
<p class="Index-Level-1" id="christian-community">community (Christian)</p>
<p class="Index-Level-2">as a people, [591](#_idIndexMarker1089)<span class="No-Break">–5</span>94</p>
<p class="Index-Level-2">authority in, [202](#_idIndexMarker502)<span class="No-Break">–2</span>04</p>
<p class="Index-Level-2">cultural considerations, [635](#_idIndexMarker1156)</p>
<p class="Index-Level-2">defined, [39](#_idIndexMarker085)</p>
<p class="Index-Level-2">early vs. contemporary church, [124](#_idIndexMarker310)<span class="No-Break">–1</span>30</p>
<p class="Index-Level-2">family in, [617](#_idIndexMarker1136)<span class="No-Break">–6</span>18</p>
<p class="Index-Level-2">governance, [125](#_idIndexMarker312)<span class="No-Break">–1</span>30, [203](#_idIndexMarker503)<span class="No-Break">–2</span>04, [348](#_idIndexMarker763)<span class="No-Break">–3</span>49</p>
<p class="Index-Level-2">leadership in, [303](#_idIndexMarker683)<span class="No-Break">–3</span>32, [642](#_idIndexMarker1161)<span class="No-Break">–6</span>50</p>
<p class="Index-Level-2">modern society and, [608](#_idIndexMarker1117)<span class="No-Break">–6</span>13</p>
<p class="Index-Level-2">need for, [580](#_idIndexMarker1081)<span class="No-Break">–5</span>84</p>
<p class="Index-Level-2">order in New Testament, [347](#_idIndexMarker762)<span class="No-Break">–3</span>48</p>
<p class="Index-Level-2">restoration of, [591](#_idIndexMarker1088)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-2">role differences in, [214](#_idIndexMarker523)<span class="No-Break">–2</span>16</p>
<p class="Index-Level-2">roles in New Testament, [102](#_idIndexMarker241)<span class="No-Break">–1</span>03, [135](#_idIndexMarker353)<span class="No-Break">–1</span>36</p>
<p class="Index-Level-2">service roles in, [134](#_idIndexMarker352)<span class="No-Break">–1</span>39</p>
<p class="Index-Level-2">social roles in, [599](#_idIndexMarker1104)<span class="No-Break">–6</span>04, [648](#_idIndexMarker1166)<span class="No-Break">–6</span>50</p>
<p class="Index-Level-2">social structure in New Testament church, [261](#_idIndexMarker609)<span class="No-Break">–2</span>67</p>
<p class="Index-Level-2">and socialism, [611](#_idIndexMarker1129)<span class="No-Break">–6</span>12</p>
<p class="Index-Level-2">subordination in, [42](#_idIndexMarker096), [80](#_idIndexMarker183)</p>
<p class="Index-Level-2">in technological society, [617](#_idIndexMarker1135)<span class="No-Break">–6</span>18, [626](#_idIndexMarker1149)<span class="No-Break">–6</span>29</p>
<p class="Index-Level-2">and traditionalism, [608](#_idIndexMarker1116)<span class="No-Break">–6</span>10</p>
<p class="Index-Level-2">women’s participation in worship, [169](#_idIndexMarker425)<span class="No-Break">–1</span>93, [189](#_idIndexMarker462)<span class="No-Break">–1</span>93</p>
<p class="Index-Level-1">community order, [194](#_idIndexMarker469)<span class="No-Break">–1</span>95</p>
<p class="Index-Level-1">complementarity, [23](#_idIndexMarker039), [211](#_idIndexMarker517)</p>
<p class="Index-Level-1">Council of Laodicea, [313](#_idIndexMarker705)</p>
<p class="Index-Level-1">Council of Saragossa, [313](#_idIndexMarker707)</p>
<p class="Index-Level-1">Council of Toledo, [313](#_idIndexMarker710)</p>
<p class="Index-Level-1">creation account</p>
<p class="Index-Level-2">historicity, [5](#_idIndexMarker011)<span class="No-Break">–8</span></p>
<p class="Index-Level-2">man and woman, [24](#_idIndexMarker042)<span class="No-Break">–2</span>6</p>
<p class="Index-Level-2">sexes and, [10](#_idIndexMarker016)<span class="No-Break">–2</span>3</p>
<p class="Index-Level-2">truth value, [7](#_idIndexMarker014)<span class="No-Break">–9</span></p>
<p class="Index-Level-1">cross-cultural patterns, [422](#_idIndexMarker878)<span class="No-Break">–4</span>34</p>
<p class="Index-Level-1">culture</p>
<p class="Index-Level-2">attitudes toward, [279](#_idIndexMarker647)<span class="No-Break">–2</span>81</p>
<p class="Index-Level-2">Christian truth and, [284](#_idIndexMarker656)<span class="No-Break">–2</span>85</p>
<p class="Index-Level-2">Christianity as God’s, [281](#_idIndexMarker650)</p>
<p class="Index-Level-2">evolution and, [280](#_idIndexMarker648)</p>
<p class="Index-Level-2">expression of sex differences in, [424](#_idIndexMarker884)<span class="No-Break">–4</span>25</p>
<p class="Index-Level-2">in relationship to God, [282](#_idIndexMarker654)<span class="No-Break">–2</span>83</p>
<p class="Index-Level-1">current practice of the church, [568](#_idIndexMarker1046)<span class="No-Break">–5</span>71</p>
<p class="Leading-Entry-Leading">deacon, [118](#_idIndexMarker299)<span class="No-Break">–1</span>19</p>
<p class="Index-Level-2">charitable service and, [110](#_idIndexMarker277)<span class="No-Break">–1</span>13</p>
<p class="Index-Level-2">position, [122](#_idIndexMarker306)<span class="No-Break">–1</span>23</p>
<p class="Index-Level-1">deaconess, [115](#_idIndexMarker283), [313](#_idIndexMarker704)</p>
<p class="Index-Level-2">authority of, [123](#_idIndexMarker307)<span class="No-Break">–1</span>24</p>
<p class="Index-Level-2">restoration of, [623](#_idIndexMarker1147)<span class="No-Break">–6</span>24</p>
<p class="Index-Level-2">role, [118](#_idIndexMarker298)<span class="No-Break">–1</span>24</p>
<p class="Index-Level-1">Dead Sea Scrolls, [247](#_idIndexMarker596)<span class="No-Break">–2</span>48</p>
<p class="Index-Level-1">Deborah (prophetess), [105](#_idIndexMarker251)<span class="No-Break">–1</span>06, [349](#_idIndexMarker769)</p>
<p class="Index-Level-1">dependence (man/&#8203;woman differences), [436](#_idIndexMarker900)</p>
<p class="Index-Level-1">descent group structure, [426](#_idIndexMarker888)<span class="No-Break">–4</span>27</p>
<p class="Index-Level-1">development of doctrine, [565](#_idIndexMarker1044)<span class="No-Break">–5</span>68</p>
<p class="Index-Level-1"><span class="Italic">Didascalia Apostolorum</span>, [121](#_idIndexMarker304), [311](#_idIndexMarker701)</p>
<p class="Index-Level-1">Diognetus (Epistle to), [610](#_idIndexMarker1124)</p>
<p class="Index-Level-1">disciples, [250](#_idIndexMarker598)<span class="No-Break">–2</span>52</p>
<p class="Index-Level-1">discrimination (objection to social roles), [607](#_idIndexMarker1115)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-1">division of labor. <span class="Index-Cross-reference">See</span>&#160;labor, division of</p>
<p class="Index-Level-1">divorce, [148](#_idIndexMarker383)</p>
<p class="Index-Level-2">Jesus’ approach, [3](#_idIndexMarker001)<span class="No-Break">–5</span></p>
<p class="Index-Level-1">domestic roles (man/&#8203;woman division), [423](#_idIndexMarker880)<span class="No-Break">–4</span>24</p>
<p class="Index-Level-1" id="domination">domination (oppressive subordination), [32](#_idIndexMarker060), [41](#_idIndexMarker092)</p>
<p class="Leading-Entry-Leading">early church. <span class="Index-Cross-reference">See</span>&#160;<span class="Italic">specific topics</span></p>
<p class="Index-Level-1">education, [619](#_idIndexMarker1138)<span class="No-Break">–6</span>20</p>
<p class="Index-Level-1">effeminacy, [654](#_idIndexMarker1178)<span class="No-Break">–6</span>55</p>
<p class="Index-Level-1" id="elders">elders, [130](#_idIndexMarker330)<span class="No-Break">–1</span>31, [644](#_idIndexMarker1164)<span class="No-Break">–6</span>48</p>
<p class="Index-Level-2">guidelines for, [622](#_idIndexMarker1146)<span class="No-Break">–6</span>23</p>
<p class="Index-Level-2">social roles and, [304](#_idIndexMarker686)</p>
<p class="Index-Level-2">women as, [130](#_idIndexMarker332)<span class="No-Break">–1</span>34, [304](#_idIndexMarker685)<span class="No-Break">–3</span>06, [645](#_idIndexMarker1165)<span class="No-Break">–6</span>50</p>
<p class="Index-Level-1">Ellul, Jacques, [494](#_idIndexMarker953)<span class="No-Break">–4</span>95</p>
<p class="Index-Level-1">emotions</p>
<p class="Index-Level-2">female dependence on men, [664](#_idIndexMarker1191)<span class="No-Break">–6</span>65</p>
<p class="Index-Level-2">man/&#8203;woman differences, [390](#_idIndexMarker810)<span class="No-Break">–3</span>91, [394](#_idIndexMarker817), [406](#_idIndexMarker839)<span class="No-Break">–4</span>08</p>
<p class="Index-Level-1">empathy, [392](#_idIndexMarker815)</p>
<p class="Index-Level-1">Enlightenment, the, [538](#_idIndexMarker1008)</p>
<p class="Index-Level-1"><span class="Italic">epimeleomai</span> (care for), [50](#_idIndexMarker120)</p>
<p class="Index-Level-1">Epiphanius of Salamis, [123](#_idIndexMarker308), [307](#_idIndexMarker691)<span class="No-Break">–3</span>08</p>
<p class="Index-Level-1"><span class="Italic">episkopos</span> (bishop), [84](#_idIndexMarker204)</p>
<p class="Index-Level-1">Epistle to Diognetus, [610](#_idIndexMarker1123)</p>
<p class="Index-Level-1">equality, [154](#_idIndexMarker394), [545](#_idIndexMarker1023)</p>
<p class="Index-Level-2">church Fathers on, [295](#_idIndexMarker674)</p>
<p class="Index-Level-1">Erikson, Erik, [391](#_idIndexMarker812)</p>
<p class="Index-Level-1"><span class="Italic">eros</span>, [81n](#_idIndexMarker187)</p>
<p class="Index-Level-1">ethics (Christian vs. non-Christian), [544](#_idIndexMarker1013)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-1">ethology, [437](#_idIndexMarker904)<span class="No-Break">–4</span>39</p>
<p class="Index-Level-1">Eusebius, [104](#_idIndexMarker245)<span class="No-Break">–1</span>05</p>
<p class="Index-Level-1">Evangelical Feminism, [230](#_idIndexMarker560)<span class="No-Break">–2</span>35</p>
<p class="Index-Level-1">Eve, [205](#_idIndexMarker511)<span class="No-Break">–2</span>08</p>
<p class="Index-Level-1">exegesis</p>
<p class="Index-Level-2">definition, [225](#_idIndexMarker554)</p>
<p class="Index-Level-2">difficulties in, [228](#_idIndexMarker555)<span class="No-Break">–2</span>30</p>
<p class="Index-Level-2">Liberationist, [230](#_idIndexMarker559)<span class="No-Break">–2</span>35</p>
<p class="Index-Level-2">restatement, [229](#_idIndexMarker557)<span class="No-Break">–2</span>30</p>
<p class="Index-Level-1"><span class="Italic">ezer</span>, [24n](#_idIndexMarker043)</p>
<p class="Leading-Entry-Leading">Fall, the, [29](#_idIndexMarker052)<span class="No-Break">–3</span>1</p>
<p class="Index-Level-2">impact on man-woman relationship, [205](#_idIndexMarker510)<span class="No-Break">–2</span>13</p>
<p class="Index-Level-1" id="family">family (the), [72](#_idIndexMarker167)<span class="No-Break">–7</span>3</p>
<p class="Index-Level-2">childrearing in, [64](#_idIndexMarker146)<span class="No-Break">–7</span>1</p>
<p class="Index-Level-2">in Christian tradition, [290](#_idIndexMarker667)<span class="No-Break">–3</span>02</p>
<p class="Index-Level-2">community and, [617](#_idIndexMarker1134)<span class="No-Break">–6</span>18</p>
<p class="Index-Level-2">extended family, [48](#_idIndexMarker108)<span class="No-Break">–4</span>9</p>
<p class="Index-Level-2">feminism and, [455](#_idIndexMarker921)</p>
<p class="Index-Level-2">guidelines for strengthening, [616](#_idIndexMarker1132)<span class="No-Break">–6</span>18, [638](#_idIndexMarker1158)<span class="No-Break">–6</span>42</p>
<p class="Index-Level-2">husband’s role in, [48](#_idIndexMarker107)<span class="No-Break">–5</span>6</p>
<p class="Index-Level-2">male/&#8203;female relationships and, [434](#_idIndexMarker896)<span class="No-Break">–4</span>35</p>
<p class="Index-Level-2">New Testament roles, [95](#_idIndexMarker237)<span class="No-Break">–1</span>03, [134](#_idIndexMarker351)<span class="No-Break">–1</span>39</p>
<p class="Index-Level-2">role breakdown in, [453](#_idIndexMarker919)<span class="No-Break">–4</span>55</p>
<p class="Index-Level-2">roles in, [46](#_idIndexMarker101)<span class="No-Break">–7</span>1</p>
<p class="Index-Level-2">structure, [46](#_idIndexMarker099)</p>
<p class="Index-Level-2">subordination in, [622](#_idIndexMarker1145)<span class="No-Break">–6</span>23</p>
<p class="Index-Level-2">in technological society, [484](#_idIndexMarker947), [502](#_idIndexMarker965)<span class="No-Break">–5</span>10</p>
<p class="Index-Level-2">in traditional society, [484](#_idIndexMarker946)</p>
<p class="Index-Level-2">wife’s role in, [56](#_idIndexMarker133)<span class="No-Break">–6</span>4, [97](#_idIndexMarker239)<span class="No-Break">–1</span>01</p>
<p class="Index-Level-2">working mothers and, [680](#_idIndexMarker1201)</p>
<p class="Index-Level-1">Fascism, [525](#_idIndexMarker991)</p>
<p class="Index-Level-1">father</p>
<p class="Index-Level-2">childrearing, [64](#_idIndexMarker149)<span class="No-Break">–7</span>0</p>
<p class="Index-Level-2">role, [48](#_idIndexMarker106)<span class="No-Break">–5</span>6</p>
<p class="Index-Level-1">father-son relationship, [64](#_idIndexMarker151)<span class="No-Break">–6</span>8</p>
<p class="Index-Level-1">Fathers of the church. <span class="Index-Cross-reference">See</span>&#160;<span class="Italic">specific topics</span></p>
<p class="Index-Level-1">fear (man/&#8203;woman differences), [407](#_idIndexMarker843)</p>
<p class="Index-Level-1">female characteristics (summarized), [448](#_idIndexMarker916)<span class="No-Break">–4</span>50</p>
<p class="Index-Level-1">female personality, [661](#_idIndexMarker1184)<span class="No-Break">–6</span>65</p>
<p class="Index-Level-1" id="feminism">feminism</p>
<p class="Index-Level-2">and Christianity, [561](#_idIndexMarker1040)<span class="No-Break">–5</span>62</p>
<p class="Index-Level-2">the Fall and, [30n](#_idIndexMarker054)</p>
<p class="Index-Level-2">female personality and, [662](#_idIndexMarker1186)<span class="No-Break">–6</span>63</p>
<p class="Index-Level-2">social science methodology, [469](#_idIndexMarker929)<span class="No-Break">–4</span>77</p>
<p class="Index-Level-2">women’s rights, [512](#_idIndexMarker976)<span class="No-Break">–5</span>13</p>
<p class="Index-Level-1">feminized male, [640](#_idIndexMarker1159), [653](#_idIndexMarker1177)<span class="No-Break">–6</span>57</p>
<p class="Index-Level-1">Firmilian, [307](#_idIndexMarker690)</p>
<p class="Index-Level-1">Fox, Robin, [444](#_idIndexMarker911)<span class="No-Break">–4</span>47</p>
<p class="Index-Level-1">freedom, [341](#_idIndexMarker749)<span class="No-Break">–3</span>42, [545](#_idIndexMarker1024)<span class="No-Break">–5</span>46</p>
<p class="Index-Level-1">Freud, Sigmund, [416](#_idIndexMarker873)<span class="No-Break">–4</span>17</p>
<p class="Index-Level-1">Freudianism, [465](#_idIndexMarker927)</p>
<p class="Index-Level-1">frustration (man/&#8203;woman differences), [402n*](#_idIndexMarker833), [407](#_idIndexMarker845)<span class="No-Break">–4</span>08</p>
<p class="Index-Level-1">full person (ethical principle), [547](#_idIndexMarker1027)</p>
<p class="Index-Level-1">functional principle, [483](#_idIndexMarker940)<span class="No-Break">–4</span>91</p>
<p class="Index-Level-2">bureaucracy, [486](#_idIndexMarker948)</p>
<p class="Index-Level-2">defined, [483](#_idIndexMarker944)<span class="No-Break">–4</span>84</p>
<p class="Index-Level-1">functional roles, [601](#_idIndexMarker1108)<span class="No-Break">–6</span>03</p>
<p class="Index-Level-1">Fundamentalism, [352](#_idIndexMarker778)<span class="No-Break">–3</span>57</p>
<p class="Index-Level-2">defined, [353](#_idIndexMarker780)<span class="No-Break">–3</span>55</p>
<p class="Leading-Entry-Leading">gap between the centuries, [558](#_idIndexMarker1037)<span class="No-Break">–5</span>60</p>
<p class="Index-Level-1">gay liberation, [532](#_idIndexMarker999)</p>
<p class="Index-Level-1">Gelasius I, Pope, [313](#_idIndexMarker712)<span class="No-Break">–3</span>14</p>
<p class="Index-Level-1">Genesis</p>
<p class="Index-Level-2">historicity, [5](#_idIndexMarker010)<span class="No-Break">–9</span></p>
<p class="Index-Level-2">subordination in, [32](#_idIndexMarker058)<span class="No-Break">–3</span>5</p>
<p class="Index-Level-1">Gentile Christians, [150](#_idIndexMarker390)<span class="No-Break">–1</span>51</p>
<p class="Index-Level-1">goal orientation, [398](#_idIndexMarker827)<span class="No-Break">–4</span>02</p>
<p class="Index-Level-1">Goldberg, Stephen, [440](#_idIndexMarker907)</p>
<p class="Index-Level-1" id="government">government</p>
<p class="Index-Level-2">in early Christian community, [303](#_idIndexMarker682)<span class="No-Break">–3</span>32</p>
<p class="Index-Level-2">guidelines for in Christian community, [622](#_idIndexMarker1144)<span class="No-Break">–6</span>23</p>
<p class="Index-Level-2">in traditional society, [495](#_idIndexMarker954)<span class="No-Break">–4</span>96</p>
<p class="Index-Level-1">group behavior, [434](#_idIndexMarker895)<span class="No-Break">–4</span>37</p>
<p class="Leading-Entry-Leading">hair styles, [197](#_idIndexMarker473)</p>
<p class="Index-Level-1">Hamburg, Beatrix, [447](#_idIndexMarker913)</p>
<p class="Index-Level-1"><span class="Italic">Haustafel</span>. <span class="Index-Cross-reference">See</span>&#160;<a href="#household-codes">household codes</a></p>
<p class="Index-Level-1">head (Pauline understanding), [182](#_idIndexMarker456)<span class="No-Break">–1</span>84</p>
<p class="Index-Level-1">headcovering, [169](#_idIndexMarker424)<span class="No-Break">–1</span>87, [273](#_idIndexMarker635)</p>
<p class="Index-Level-1">headship, [83](#_idIndexMarker202)<span class="No-Break">–8</span>8</p>
<p class="Index-Level-1">health (man/&#8203;woman differences), [409](#_idIndexMarker859)</p>
<p class="Index-Level-1">Hellenistic culture, [272](#_idIndexMarker632)<span class="No-Break">–2</span>74</p>
<p class="Index-Level-1"><span class="Italic">hesed</span>, [81n](#_idIndexMarker188)</p>
<p class="Index-Level-1"><span class="Italic">hēsychia</span> (quietness), [198](#_idIndexMarker476)</p>
<p class="Index-Level-1" id="hildebrand">Hildebrand, Dietrich von, [389](#_idIndexMarker807), [401n](#_idIndexMarker831)</p>
<p class="Index-Level-1">Hillel, school of, [4](#_idIndexMarker002)</p>
<p class="Index-Level-1">history</p>
<p class="Index-Level-2">Genesis and, [6](#_idIndexMarker012)<span class="No-Break">–8</span></p>
<p class="Index-Level-2">Marxist view of, [527](#_idIndexMarker993)<span class="No-Break">–5</span>28</p>
<p class="Index-Level-1">honor, [94](#_idIndexMarker231)<span class="No-Break">–9</span>5</p>
<p class="Index-Level-1">hormones, [409](#_idIndexMarker863), [413](#_idIndexMarker871)<span class="No-Break">–4</span>14</p>
<p class="Index-Level-1" id="household-codes">household codes, [74](#_idIndexMarker170)<span class="No-Break">–8</span>9, [263](#_idIndexMarker616)<span class="No-Break">–2</span>64</p>
<p class="Index-Level-1">Huldah (prophetess), [106](#_idIndexMarker252)</p>
<p class="Index-Level-1">humanity</p>
<p class="Index-Level-2">as a people, [591](#_idIndexMarker1087)<span class="No-Break">–5</span>94</p>
<p class="Index-Level-2">creation of, [11](#_idIndexMarker018)<span class="No-Break">–1</span>4</p>
<p class="Index-Level-2">purpose of, [36](#_idIndexMarker075)</p>
<p class="Index-Level-1">husband</p>
<p class="Index-Level-2">authority in family, [54](#_idIndexMarker127)</p>
<p class="Index-Level-2">cares for family, [51](#_idIndexMarker123)<span class="No-Break">–5</span>5</p>
<p class="Index-Level-2">provider, [81](#_idIndexMarker194)<span class="No-Break">–8</span>2, [96](#_idIndexMarker238)<span class="No-Break">–9</span>7</p>
<p class="Index-Level-2">role of, [48](#_idIndexMarker105)<span class="No-Break">–5</span>6</p>
<p class="Index-Level-2">ruler (head), [50](#_idIndexMarker111)</p>
<p class="Index-Level-1"><span class="Italic">hypostassō</span> (subordination), [23](#_idIndexMarker041)</p>
<p class="Leading-Entry-Leading">ideology</p>
<p class="Index-Level-2">defined, [520](#_idIndexMarker984)</p>
<p class="Index-Level-2">ethical principles, [544](#_idIndexMarker1012)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-2">importance in modern world, [533](#_idIndexMarker1000)<span class="No-Break">–5</span>35</p>
<p class="Index-Level-2">Liberalism, [521](#_idIndexMarker986)<span class="No-Break">–5</span>25</p>
<p class="Index-Level-2">liberation movements, [532](#_idIndexMarker998)<span class="No-Break">–5</span>33</p>
<p class="Index-Level-2">modern Christianity and, [538](#_idIndexMarker1007)<span class="No-Break">–5</span>40, [550](#_idIndexMarker1031)<span class="No-Break">–5</span>51</p>
<p class="Index-Level-2">romantic reaction, [529](#_idIndexMarker995)<span class="No-Break">–5</span>32</p>
<p class="Index-Level-2">Socialism, [525](#_idIndexMarker990)<span class="No-Break">–5</span>29</p>
<p class="Index-Level-1">Ignatius of Antioch, [292](#_idIndexMarker670)</p>
<p class="Index-Level-1">image of God</p>
<p class="Index-Level-2">humanity as, [11](#_idIndexMarker020)<span class="No-Break">–1</span>4</p>
<p class="Index-Level-2">restored through Christ, [146](#_idIndexMarker376)</p>
<p class="Index-Level-1">individualism, [492](#_idIndexMarker952)<span class="No-Break">–4</span>95</p>
<p class="Index-Level-1">inferiority, [43](#_idIndexMarker098)<span class="No-Break">–4</span>4</p>
<p class="Index-Level-1">insecurity, [517](#_idIndexMarker982)</p>
<p class="Index-Level-1">inspiration of scripture, [336](#_idIndexMarker732)</p>
<p class="Index-Level-1">integration/&#8203;differentiation (trait-pattern), [388](#_idIndexMarker806)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-1">intellectual differences, [392](#_idIndexMarker814)<span class="No-Break">–3</span>95, [408](#_idIndexMarker847)</p>
<p class="Index-Level-1"><span class="Italic">ish</span> (human), [13n](#_idIndexMarker027), [19n*](#_idIndexMarker036)</p>
<p class="Index-Level-1"><span class="Italic">ishshah</span> (woman), [19n*](#_idIndexMarker035)</p>
<p class="Index-Level-1">isolation, [505](#_idIndexMarker967)<span class="No-Break">–5</span>06</p>
<p class="Leading-Entry-Leading">Jacklin, Carol, [435](#_idIndexMarker898)<span class="No-Break">–4</span>37</p>
<p class="Index-Level-1">Jehuda, Rabbi, [149](#_idIndexMarker385)</p>
<p class="Index-Level-1">Jesus</p>
<p class="Index-Level-2">behavior toward women, [246](#_idIndexMarker585)<span class="No-Break">–2</span>55</p>
<p class="Index-Level-2">new Adam, [36](#_idIndexMarker073)<span class="No-Break">–3</span>9</p>
<p class="Index-Level-2">restorer of new humanity, [37](#_idIndexMarker079)<span class="No-Break">–3</span>9</p>
<p class="Index-Level-1">Job, [51](#_idIndexMarker124)<span class="No-Break">–5</span>4</p>
<p class="Index-Level-1">Judaism</p>
<p class="Index-Level-2">effect on early church, [267](#_idIndexMarker626)<span class="No-Break">–2</span>71</p>
<p class="Index-Level-2">first-century, [243](#_idIndexMarker577)<span class="No-Break">–2</span>49</p>
<p class="Index-Level-2">religious obligations, [244](#_idIndexMarker579)<span class="No-Break">–2</span>45</p>
<p class="Index-Level-2">women in, [243](#_idIndexMarker576)<span class="No-Break">–2</span>55</p>
<p class="Index-Level-2">worship in temple, [244](#_idIndexMarker580)</p>
<p class="Index-Level-1">Jung, Carl, [651n](#_idIndexMarker1174)</p>
<p class="Index-Level-1">Junia(s), [132](#_idIndexMarker339)</p>
<p class="Leading-Entry-Leading"><span class="Italic">kephalē</span> (head), [83](#_idIndexMarker201)<span class="No-Break">–8</span>5</p>
<p class="Index-Level-1">Kibbutzim, [431](#_idIndexMarker892)<span class="No-Break">–4</span>33</p>
<p class="Index-Level-1">kinship bonds, [502](#_idIndexMarker966)<span class="No-Break">–5</span>04</p>
<p class="Leading-Entry-Leading">labor, division of, [423](#_idIndexMarker879)</p>
<p class="Index-Level-1">Laodicea, Council of, [313](#_idIndexMarker706)</p>
<p class="Index-Level-1">leadership</p>
<p class="Index-Level-2">approaches to, [643](#_idIndexMarker1163)<span class="No-Break">–6</span>48</p>
<p class="Index-Level-2">early church and, [124](#_idIndexMarker309)<span class="No-Break">–1</span>34</p>
<p class="Index-Level-2">early vs. contemporary church, [125](#_idIndexMarker311)<span class="No-Break">–1</span>30</p>
<p class="Index-Level-2">strengthening of, [642](#_idIndexMarker1160)<span class="No-Break">–6</span>50</p>
<p class="Index-Level-2">subordination and, [127](#_idIndexMarker316)</p>
<p class="Index-Level-2">women in, [622](#_idIndexMarker1143)<span class="No-Break">–6</span>25</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#elders">elders</a>; <a href="#government">government</a></p>
<p class="Index-Level-1">legalism, [349](#_idIndexMarker766)<span class="No-Break">–3</span>52</p>
<p class="Index-Level-1">legislation, [683](#_idIndexMarker1204)<span class="No-Break">–6</span>87</p>
<p class="Index-Level-1">Levy, Marion J., [655](#_idIndexMarker1179)<span class="No-Break">–6</span>56</p>
<p class="Index-Level-1">Liberalism, [521](#_idIndexMarker985)<span class="No-Break">–5</span>25</p>
<p class="Index-Level-1">liberationist exegesis, [230](#_idIndexMarker558)<span class="No-Break">–2</span>35</p>
<p class="Index-Level-1">liberation movements, [532](#_idIndexMarker997)<span class="No-Break">–5</span>33</p>
<p class="Index-Level-1">Lloyd, Barbara, [470](#_idIndexMarker932)</p>
<p class="Index-Level-1">love, [80](#_idIndexMarker185)<span class="No-Break">–8</span>2, [598](#_idIndexMarker1100)</p>
<p class="Index-Level-1">Lutheranism, [350](#_idIndexMarker772)<span class="No-Break">–3</span>51n</p>
<p class="Leading-Entry-Leading">Maccoby, Eleanor, [435](#_idIndexMarker897)<span class="No-Break">–4</span>37</p>
<p class="Index-Level-1">machismo, [660](#_idIndexMarker1182)<span class="No-Break">–6</span>61</p>
<p class="Index-Level-1">male absenteeism, [427](#_idIndexMarker889)<span class="No-Break">–4</span>28</p>
<p class="Index-Level-1">male characteristics (summarized), [448](#_idIndexMarker915)<span class="No-Break">–4</span>50</p>
<p class="Index-Level-1">male personality, [653](#_idIndexMarker1176)<span class="No-Break">–6</span>63</p>
<p class="Index-Level-1">man</p>
<p class="Index-Level-2">creation of, [15](#_idIndexMarker029)<span class="No-Break">–1</span>6</p>
<p class="Index-Level-2">first-born, [25](#_idIndexMarker044)</p>
<p class="Index-Level-1">man/&#8203;woman differences</p>
<p class="Index-Level-2">aggression, [404](#_idIndexMarker834)<span class="No-Break">–4</span>05, [436](#_idIndexMarker901)</p>
<p class="Index-Level-2">anxiety, [407](#_idIndexMarker841)</p>
<p class="Index-Level-2">bodily experience, [395](#_idIndexMarker821)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-2">brain, [409](#_idIndexMarker864)</p>
<p class="Index-Level-2">causes of, [410](#_idIndexMarker866)<span class="No-Break">–4</span>17, [439](#_idIndexMarker906)<span class="No-Break">–4</span>48</p>
<p class="Index-Level-2">cross-cultural patterns, [422](#_idIndexMarker877)<span class="No-Break">–4</span>25</p>
<p class="Index-Level-2">dependence, [436](#_idIndexMarker899)</p>
<p class="Index-Level-2">emotional, [390](#_idIndexMarker809)<span class="No-Break">–3</span>91, [394](#_idIndexMarker816), [406](#_idIndexMarker838)<span class="No-Break">–4</span>08</p>
<p class="Index-Level-2">ethological evidence, [437](#_idIndexMarker903)<span class="No-Break">–4</span>39</p>
<p class="Index-Level-2">fear, [407](#_idIndexMarker840)</p>
<p class="Index-Level-2">frustration, [402](#_idIndexMarker832), [407](#_idIndexMarker844)<span class="No-Break">–4</span>08</p>
<p class="Index-Level-2">goal/&#8203;personal need orientation, [398](#_idIndexMarker826)<span class="No-Break">–4</span>02</p>
<p class="Index-Level-2">group behavior, [434](#_idIndexMarker894)<span class="No-Break">–4</span>37</p>
<p class="Index-Level-2">health, [409](#_idIndexMarker858)</p>
<p class="Index-Level-2">hormonal rhythm, [409](#_idIndexMarker862)</p>
<p class="Index-Level-2">individual, [379](#_idIndexMarker801)<span class="No-Break">–4</span>20</p>
<p class="Index-Level-2">integration/&#8203;differentiation, [388](#_idIndexMarker805)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-2">intellectual, [392](#_idIndexMarker813)<span class="No-Break">–3</span>95, [408](#_idIndexMarker846)</p>
<p class="Index-Level-2">maturation, [409](#_idIndexMarker861)</p>
<p class="Index-Level-2">nurturance, [405](#_idIndexMarker837)<span class="No-Break">–4</span>06</p>
<p class="Index-Level-2">physical, [408](#_idIndexMarker853)<span class="No-Break">–4</span>10</p>
<p class="Index-Level-2">sexuality, [395](#_idIndexMarker820)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-2">size, [409](#_idIndexMarker857)</p>
<p class="Index-Level-2">social structural, [421](#_idIndexMarker874)<span class="No-Break">–4</span>59</p>
<p class="Index-Level-2">spatial ability, [408](#_idIndexMarker850)</p>
<p class="Index-Level-2">strength, [409](#_idIndexMarker856)</p>
<p class="Index-Level-2">summary of, [448](#_idIndexMarker914)<span class="No-Break">–4</span>52</p>
<p class="Index-Level-2">talking about, [382](#_idIndexMarker802)<span class="No-Break">–3</span>85</p>
<p class="Index-Level-2">verbal ability, [408](#_idIndexMarker849)</p>
<p class="Index-Level-1">marriage. <span class="Index-Cross-reference">See</span>&#160;<a href="#family">family</a></p>
<p class="Index-Level-1">Marxism, [525](#_idIndexMarker989)<span class="No-Break">–5</span>29</p>
<p class="Index-Level-1">Mary (disciple of Jesus), [251](#_idIndexMarker600)</p>
<p class="Index-Level-1">masculinized woman, [661](#_idIndexMarker1185)<span class="No-Break">–6</span>62</p>
<p class="Index-Level-1"><span class="Italic">mashal</span> (rule), [34](#_idIndexMarker064)</p>
<p class="Index-Level-1">matriarchy, [425](#_idIndexMarker885)</p>
<p class="Index-Level-1">matrilineal society, [426](#_idIndexMarker887)<span class="No-Break">–4</span>27</p>
<p class="Index-Level-1">maturation, [409](#_idIndexMarker860)</p>
<p class="Index-Level-1">Mead, Margaret</p>
<p class="Index-Level-2">cross-cultural studies, [412](#_idIndexMarker868)</p>
<p class="Index-Level-2">goal/&#8203;personal need trait-pattern, [400](#_idIndexMarker829)<span class="No-Break">–4</span>01</p>
<p class="Index-Level-2">man/&#8203;woman sexual diffusion, [397](#_idIndexMarker824)</p>
<p class="Index-Level-2">social order, [602](#_idIndexMarker1109)<span class="No-Break">–6</span>03</p>
<p class="Index-Level-2">value of social roles, [457](#_idIndexMarker924)</p>
<p class="Index-Level-1">menstrual cycle, [414](#_idIndexMarker872)<span class="No-Break">–4</span>15</p>
<p class="Index-Level-1">Midrash, [246](#_idIndexMarker584)<span class="No-Break">–2</span>49</p>
<p class="Index-Level-1">Mill, John Stuart, [522](#_idIndexMarker987)</p>
<p class="Index-Level-1">missionary work, [115](#_idIndexMarker284)<span class="No-Break">–1</span>18</p>
<p class="Index-Level-1">Modernism, [352](#_idIndexMarker777)<span class="No-Break">–3</span>57</p>
<p class="Index-Level-1">monasticism</p>
<p class="Index-Level-2">social structure in, [611](#_idIndexMarker1128)<span class="No-Break">–6</span>12</p>
<p class="Index-Level-2">women in, [314](#_idIndexMarker714)<span class="No-Break">–3</span>18</p>
<p class="Index-Level-1">Money, John, [413](#_idIndexMarker870)<span class="No-Break">–4</span>14</p>
<p class="Index-Level-1">Montanism, [307](#_idIndexMarker692)</p>
<p class="Index-Level-1">Mosaic Law</p>
<p class="Index-Level-2">Gentiles and, [150](#_idIndexMarker389)<span class="No-Break">–1</span>51</p>
<p class="Index-Level-2">women in, [148](#_idIndexMarker384)<span class="No-Break">–1</span>52</p>
<p class="Index-Level-1">mother, [64](#_idIndexMarker148)<span class="No-Break">–7</span>0</p>
<p class="Index-Level-1">mother-daughter relationship, [68](#_idIndexMarker156), [664](#_idIndexMarker1190)</p>
<p class="Index-Level-1"><span class="Italic">musar</span> (training), [69](#_idIndexMarker166)</p>
<p class="Index-Level-1">mutual subordination, [75](#_idIndexMarker172)<span class="No-Break">–7</span>6n</p>
<p class="Index-Level-1"><span class="Italic">mystērion</span> (mystery), [88](#_idIndexMarker210)</p>
<p class="Leading-Entry-Leading"><span class="Italic">neqaybah</span> (female), [12n†](#_idIndexMarker024)</p>
<p class="Index-Level-1">new humanity, [591](#_idIndexMarker1090)<span class="No-Break">–5</span>94</p>
<p class="Index-Level-1" id="new-testament">New Testament</p>
<p class="Index-Level-2">authority of teaching, [216](#_idIndexMarker529)<span class="No-Break">–2</span>19</p>
<p class="Index-Level-2">intent of teaching, [218](#_idIndexMarker531)<span class="No-Break">–2</span>22</p>
<p class="Index-Level-2">man/&#8203;woman roles, [212](#_idIndexMarker520)<span class="No-Break">–2</span>24, [577](#_idIndexMarker1077)<span class="No-Break">–5</span>79</p>
<p class="Index-Level-2">pastoral approach, [580](#_idIndexMarker1079)<span class="No-Break">–5</span>84</p>
<p class="Index-Level-2">principles of application, [579](#_idIndexMarker1078)<span class="No-Break">–5</span>84</p>
<p class="Index-Level-2">social teaching of, [598](#_idIndexMarker1101)</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#scripture">scripture</a></p>
<p class="Index-Level-1">Newman, John Henry, [565](#_idIndexMarker1045)<span class="No-Break">–5</span>66</p>
<p class="Index-Level-1">nurturance (man/&#8203;woman differences), [405](#_idIndexMarker836)<span class="No-Break">–4</span>06</p>
<p class="Leading-Entry-Leading">obedience, [82](#_idIndexMarker196)<span class="No-Break">–8</span>3, [89](#_idIndexMarker213)<span class="No-Break">–9</span>0</p>
<p class="Index-Level-1">occupations, [678](#_idIndexMarker1199)<span class="No-Break">–6</span>82</p>
<p class="Index-Level-1"><span class="Italic">oikodespotein</span> (ruler of home), [57](#_idIndexMarker139)</p>
<p class="Index-Level-1">oneness of man/&#8203;woman, [217](#_idIndexMarker530)<span class="No-Break">–2</span>18</p>
<p class="Index-Level-1" id="ordination-of-women">ordination of women, [674](#_idIndexMarker1198)<span class="No-Break">–6</span>78</p>
<p class="Index-Level-1">Origen, [294](#_idIndexMarker673)<span class="No-Break">–2</span>95, [306](#_idIndexMarker689)<span class="No-Break">–3</span>07</p>
<p class="Index-Level-1" id="original-sin">original sin, [29](#_idIndexMarker051)<span class="No-Break">–3</span>6</p>
<p class="Index-Level-1">Ortner, Sherry, [394](#_idIndexMarker818), [424](#_idIndexMarker883), [434](#_idIndexMarker893), [475](#_idIndexMarker933)</p>
<p class="Leading-Entry-Leading"><span class="Italic">paideia</span> (discipline), [69](#_idIndexMarker165)</p>
<p class="Index-Level-1">parent-child relationships, [506](#_idIndexMarker969)<span class="No-Break">–5</span>07</p>
<p class="Index-Level-1">pastoral care, [619](#_idIndexMarker1137)<span class="No-Break">–6</span>20</p>
<p class="Index-Level-1">patristic literature, [103n](#_idIndexMarker242), [291](#_idIndexMarker668)<span class="No-Break">–3</span>01, [304](#_idIndexMarker684)<span class="No-Break">–3</span>11</p>
<p class="Index-Level-1">Paul (apostle)</p>
<p class="Index-Level-2">attitude toward women, [255](#_idIndexMarker607)<span class="No-Break">–2</span>59</p>
<p class="Index-Level-2">circumcision, [144](#_idIndexMarker369)</p>
<p class="Index-Level-2">consistency of teaching, [242](#_idIndexMarker575)</p>
<p class="Index-Level-2">freedom, [341](#_idIndexMarker748)<span class="No-Break">–3</span>42</p>
<p class="Index-Level-2">Mosaic law, [143](#_idIndexMarker364)<span class="No-Break">–1</span>44</p>
<p class="Index-Level-2">and pagan culture, [255](#_idIndexMarker606)<span class="No-Break">–2</span>59</p>
<p class="Index-Level-2">rabbinic influence on, [268](#_idIndexMarker628)<span class="No-Break">–2</span>69</p>
<p class="Index-Level-2">role teaching, [140](#_idIndexMarker358)<span class="No-Break">–1</span>67</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<span class="Italic">Paul’s letters in [Scripture Index](#scripture-index)</span></p>
<p class="Index-Level-1">personal care, [496](#_idIndexMarker955)<span class="No-Break">–4</span>97</p>
<p class="Index-Level-1">personal need orientation, [398](#_idIndexMarker825)<span class="No-Break">–4</span>02</p>
<p class="Index-Level-1">personal relationships</p>
<p class="Index-Level-2">Christian teaching on, [262](#_idIndexMarker614)<span class="No-Break">–2</span>64</p>
<p class="Index-Level-2">in technological society, [497](#_idIndexMarker959)<span class="No-Break">–5</span>02</p>
<p class="Index-Level-1">personal subordination, [543](#_idIndexMarker1011)</p>
<p class="Index-Level-1">personality</p>
<p class="Index-Level-2">female characteristics, [661](#_idIndexMarker1183)<span class="No-Break">–6</span>65</p>
<p class="Index-Level-2">male characteristics, [653](#_idIndexMarker1175)<span class="No-Break">–6</span>63</p>
<p class="Index-Level-1"><span class="Italic">philadelphia</span> (brotherly love), [158](#_idIndexMarker404), [598](#_idIndexMarker1102), [616](#_idIndexMarker1131)</p>
<p class="Index-Level-1">Philip, daughters of (prophetesses), [104](#_idIndexMarker243)<span class="No-Break">–1</span>05</p>
<p class="Index-Level-1">Phoebe (deaconess), [120](#_idIndexMarker302)<span class="No-Break">–1</span>21</p>
<p class="Index-Level-1">Photius of Constantinople, [314](#_idIndexMarker713)</p>
<p class="Index-Level-1">physical differences, [408](#_idIndexMarker852)<span class="No-Break">–4</span>10</p>
<p class="Index-Level-1">Pius&#160;X, Pope, [353](#_idIndexMarker779)</p>
<p class="Index-Level-1">Pius&#160;XI, Pope, [301](#_idIndexMarker680)<span class="No-Break">–3</span>02</p>
<p class="Index-Level-1">Polycarp of Smyrna, [292](#_idIndexMarker671)</p>
<p class="Index-Level-1"><span class="Italic">presbyteras</span> (older women), [132](#_idIndexMarker342)<span class="No-Break">–1</span>33</p>
<p class="Index-Level-1"><span class="Italic">presbyteros</span> (elder/&#8203;older man), [132](#_idIndexMarker341)<span class="No-Break">–1</span>33</p>
<p class="Index-Level-1">priesthood, [305](#_idIndexMarker687)<span class="No-Break">–3</span>06</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#ordination-of-women">ordination of women</a></p>
<p class="Leading-Entry-Leading">quietness, [198](#_idIndexMarker474)</p>
<p class="Leading-Entry-Leading">rabbinic teaching</p>
<p class="Index-Level-2">attitudes toward women, [244](#_idIndexMarker578)<span class="No-Break">–2</span>45</p>
<p class="Index-Level-2">effects on early church, [267](#_idIndexMarker625)<span class="No-Break">–2</span>71</p>
<p class="Index-Level-2">New Testament reflects, [363](#_idIndexMarker790)<span class="No-Break">–3</span>64</p>
<p class="Index-Level-1">relational principle, [483](#_idIndexMarker939)<span class="No-Break">–4</span>91, [594](#_idIndexMarker1094)<span class="No-Break">–5</span>99</p>
<p class="Index-Level-1">relationships</p>
<p class="Index-Level-2">brother-sister, [667](#_idIndexMarker1194)<span class="No-Break">–6</span>68</p>
<p class="Index-Level-2">celibates, [669](#_idIndexMarker1196)<span class="No-Break">–6</span>71</p>
<p class="Index-Level-2">Christian community and, [214](#_idIndexMarker522), [594](#_idIndexMarker1093)<span class="No-Break">–5</span>99</p>
<p class="Index-Level-2">father-son, [64](#_idIndexMarker150)<span class="No-Break">–6</span>8</p>
<p class="Index-Level-2">husband-wife, [26](#_idIndexMarker050)<span class="No-Break">–2</span>8, [73](#_idIndexMarker168)<span class="No-Break">–1</span>01, [290](#_idIndexMarker666)<span class="No-Break">–3</span>02, [666](#_idIndexMarker1193)<span class="No-Break">–6</span>69</p>
<p class="Index-Level-2">man-woman, [666](#_idIndexMarker1192)<span class="No-Break">–6</span>69</p>
<p class="Index-Level-2">mother-daughter, [68](#_idIndexMarker155), [664](#_idIndexMarker1189)</p>
<p class="Index-Level-2">outside Christian community, [629](#_idIndexMarker1153)<span class="No-Break">–6</span>36</p>
<p class="Index-Level-2">single people, [669](#_idIndexMarker1195)<span class="No-Break">–6</span>71</p>
<p class="Index-Level-2">in technological society, [483](#_idIndexMarker943), [497](#_idIndexMarker958)<span class="No-Break">–5</span>02</p>
<p class="Index-Level-2">in traditional society, [483](#_idIndexMarker942), [595](#_idIndexMarker1095)</p>
<p class="Index-Level-1">rights</p>
<p class="Index-Level-2">Christian, [342](#_idIndexMarker755)<span class="No-Break">–3</span>43</p>
<p class="Index-Level-2">women’s, [512](#_idIndexMarker974)<span class="No-Break">–5</span>13</p>
<p class="Index-Level-1" id="roles">roles</p>
<p class="Index-Level-2">cross-cultural patterns of, [422](#_idIndexMarker876)<span class="No-Break">–4</span>34</p>
<p class="Index-Level-2">cultural expression of, [625](#_idIndexMarker1148)<span class="No-Break">–6</span>26</p>
<p class="Index-Level-2">guidelines for, [614](#_idIndexMarker1130)<span class="No-Break">–6</span>36</p>
<p class="Index-Level-2">New Testament teaching on, [95](#_idIndexMarker236)<span class="No-Break">–1</span>01, [213](#_idIndexMarker521)<span class="No-Break">–2</span>16, [264](#_idIndexMarker617)<span class="No-Break">–2</span>67</p>
<p class="Index-Level-2">objections to, [604](#_idIndexMarker1112)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-2">social, defined, [599](#_idIndexMarker1106)<span class="No-Break">–6</span>04</p>
<p class="Index-Level-1">romantic reaction, [529](#_idIndexMarker994)<span class="No-Break">–5</span>32</p>
<p class="Index-Level-1"><span class="Italic">ros</span> (head), [84](#_idIndexMarker203)</p>
<p class="Index-Level-1">Rosaldo, Michelle Zimbalist, [423](#_idIndexMarker881), [429](#_idIndexMarker891)<span class="No-Break">–4</span>30, [440](#_idIndexMarker908)<span class="No-Break">–4</span>42</p>
<p class="Index-Level-1">Ryder, Norman, [506](#_idIndexMarker968)<span class="No-Break">–5</span>07, [508](#_idIndexMarker970), [509](#_idIndexMarker971)<span class="No-Break">–5</span>10</p>
<p class="Leading-Entry-Leading">Saragossa, Council of, [313](#_idIndexMarker708)</p>
<p class="Index-Level-1" id="scripture">scripture</p>
<p class="Index-Level-2">apostolic, [336](#_idIndexMarker734)<span class="No-Break">–3</span>37</p>
<p class="Index-Level-2">application of, [374](#_idIndexMarker800)<span class="No-Break">–3</span>75, [554](#_idIndexMarker1033)<span class="No-Break">–5</span>55, [557](#_idIndexMarker1035), [577](#_idIndexMarker1076)<span class="No-Break">–5</span>83; objections to,[ 557](#_idIndexMarker1036)<span class="No-Break">–5</span>71; principles for,[ 580](#_idIndexMarker1080)<span class="No-Break">–5</span>84</p>
<p class="Index-Level-2">approach to, [4](#_idIndexMarker005)<span class="No-Break">–5</span>, [333](#_idIndexMarker728)</p>
<p class="Index-Level-2">authority of, [333](#_idIndexMarker727)<span class="No-Break">–3</span>57, [575](#_idIndexMarker1074)<span class="No-Break">–5</span>76</p>
<p class="Index-Level-2">bypasses of authority of, [358](#_idIndexMarker783)<span class="No-Break">–3</span>75</p>
<p class="Index-Level-2" id="canonicity">canonicity of, [335](#_idIndexMarker730)</p>
<p class="Index-Level-2">contradictions in, [368](#_idIndexMarker794)<span class="No-Break">–3</span>71</p>
<p class="Index-Level-2">Fundamentalism, [352](#_idIndexMarker776)<span class="No-Break">–3</span>57</p>
<p class="Index-Level-2">inspiration of, [336](#_idIndexMarker731)</p>
<p class="Index-Level-2">intent of, [571](#_idIndexMarker1063)<span class="No-Break">–5</span>73</p>
<p class="Index-Level-2">interpretation of, [7](#_idIndexMarker013), [352](#_idIndexMarker775)<span class="No-Break">–3</span>57, [576](#_idIndexMarker1075)<span class="No-Break">–5</span>77; individualistic,[ 365](#_idIndexMarker791)<span class="No-Break">–3</span>67</p>
<p class="Index-Level-2">meaning for now, [556](#_idIndexMarker1034)<span class="No-Break">–5</span>58</p>
<p class="Index-Level-2">rabbinic influences on, [363](#_idIndexMarker789)<span class="No-Break">–3</span>64</p>
<p class="Index-Level-2">submission to, [339](#_idIndexMarker745)<span class="No-Break">–3</span>41, [344](#_idIndexMarker757)<span class="No-Break">–3</span>49, [372](#_idIndexMarker799)<span class="No-Break">–3</span>73</p>
<p class="Index-Level-2">understanding, [345](#_idIndexMarker759)<span class="No-Break">–3</span>49</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#new-testament">New Testament</a></p>
<p class="Index-Level-1">Seaman, Barbara, [455](#_idIndexMarker922)</p>
<p class="Index-Level-1" id="second-vatican-council">Second Vatican Council, [289n‡](#_idIndexMarker665), [338](#_idIndexMarker740)</p>
<p class="Index-Level-1">self-fulfillment, [546](#_idIndexMarker1025)</p>
<p class="Index-Level-1">sexism, [607](#_idIndexMarker1114)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-1">sexuality</p>
<p class="Index-Level-2">effects of role breakdown on, [454](#_idIndexMarker920)</p>
<p class="Index-Level-2">man/&#8203;woman differences, [395](#_idIndexMarker819)<span class="No-Break">–3</span>98</p>
<p class="Index-Level-1">Shammai, school of, [4](#_idIndexMarker003)</p>
<p class="Index-Level-1">Shema, [245](#_idIndexMarker581)</p>
<p class="Index-Level-1">signs of the times, [560](#_idIndexMarker1038)<span class="No-Break">–5</span>64</p>
<p class="Index-Level-1">sin. <span class="Index-Cross-reference">See</span>&#160;<a href="#original-sin">original sin</a></p>
<p class="Index-Level-1">size (man/&#8203;woman differences), [409](#_idIndexMarker855)</p>
<p class="Index-Level-1">slavery, [156](#_idIndexMarker400)<span class="No-Break">–1</span>57, [161](#_idIndexMarker414)<span class="No-Break">–1</span>64, [265](#_idIndexMarker618)<span class="No-Break">–2</span>66</p>
<p class="Index-Level-1">social complexity, [428](#_idIndexMarker890)<span class="No-Break">–4</span>30</p>
<p class="Index-Level-1">social responsibility, [657](#_idIndexMarker1180)<span class="No-Break">–6</span>58</p>
<p class="Index-Level-1">social roles</p>
<p class="Index-Level-2">characteristics of, [599](#_idIndexMarker1105)<span class="No-Break">–6</span>04</p>
<p class="Index-Level-2">and functional roles, [600](#_idIndexMarker1107)<span class="No-Break">–6</span>04</p>
<p class="Index-Level-2">guidelines for, [620](#_idIndexMarker1141)<span class="No-Break">–6</span>22, [627](#_idIndexMarker1150)<span class="No-Break">–6</span>28</p>
<p class="Index-Level-2">objections to, [604](#_idIndexMarker1111)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-2">value of, [164](#_idIndexMarker421)<span class="No-Break">–1</span>67, [457](#_idIndexMarker923)<span class="No-Break">–4</span>59</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#roles">roles</a></p>
<p class="Index-Level-1">social science methodoloy, [460](#_idIndexMarker925)<span class="No-Break">–4</span>77</p>
<p class="Index-Level-1" id="social-structure">social structure</p>
<p class="Index-Level-2">Christian community and, [597](#_idIndexMarker1099)<span class="No-Break">–6</span>04</p>
<p class="Index-Level-2">Christianity and, [635](#_idIndexMarker1157)<span class="No-Break">–6</span>36</p>
<p class="Index-Level-2">diversity of, [426](#_idIndexMarker886)<span class="No-Break">–4</span>31</p>
<p class="Index-Level-2">early church, [263](#_idIndexMarker615)<span class="No-Break">–2</span>64</p>
<p class="Index-Level-2">explaining differences in, [439](#_idIndexMarker905)<span class="No-Break">–4</span>48</p>
<p class="Index-Level-2">guidelines for, [620](#_idIndexMarker1140)<span class="No-Break">–6</span>22</p>
<p class="Index-Level-2">man/&#8203;woman differences, [422](#_idIndexMarker875)<span class="No-Break">–4</span>39</p>
<p class="Index-Level-2">role breakdown in, [453](#_idIndexMarker918)<span class="No-Break">–4</span>56</p>
<p class="Index-Level-2">socialist, [610](#_idIndexMarker1127)<span class="No-Break">–6</span>11</p>
<p class="Index-Level-2">structuralist hypothesis, [443](#_idIndexMarker910)<span class="No-Break">–4</span>48</p>
<p class="Index-Level-2">in technological society, [483](#_idIndexMarker938)<span class="No-Break">–4</span>90</p>
<p class="Index-Level-2">in traditional society, [483](#_idIndexMarker937)<span class="No-Break">–4</span>90</p>
<p class="Index-Level-1">Socialism, [525](#_idIndexMarker988)<span class="No-Break">–5</span>29</p>
<p class="Index-Level-1">society. <span class="Index-Cross-reference">See</span>&#160;<a href="#social-structure">social structure</a></p>
<p class="Index-Level-1">sociology</p>
<p class="Index-Level-2">descriptive methods, [385](#_idIndexMarker803)<span class="No-Break">–3</span>86</p>
<p class="Index-Level-2">experimental methods, [386](#_idIndexMarker804)<span class="No-Break">–3</span>87</p>
<p class="Index-Level-1">spatial ability (man/&#8203;woman differences), [408](#_idIndexMarker851)</p>
<p class="Index-Level-1">specialization, [488](#_idIndexMarker951)<span class="No-Break">–4</span>89</p>
<p class="Index-Level-1">standardization, [488](#_idIndexMarker950)<span class="No-Break">–4</span>89</p>
<p class="Index-Level-1">Stein, Edith, [389](#_idIndexMarker808), [401](#_idIndexMarker830)</p>
<p class="Index-Level-1">strength (man/&#8203;woman differences), [409](#_idIndexMarker854)</p>
<p class="Index-Level-1">structuralism, [443](#_idIndexMarker909)<span class="No-Break">–4</span>48</p>
<p class="Index-Level-1">submission, [339](#_idIndexMarker746)</p>
<p class="Index-Level-1">subordination, [76](#_idIndexMarker181)<span class="No-Break">–1</span>01</p>
<p class="Index-Level-2">Abraham and Sarah, [89](#_idIndexMarker212)<span class="No-Break">–9</span>0</p>
<p class="Index-Level-2">character trait, [93](#_idIndexMarker229)</p>
<p class="Index-Level-2">as cultural universal, [424](#_idIndexMarker882)</p>
<p class="Index-Level-2">Genesis and, [23](#_idIndexMarker040)<span class="No-Break">–2</span>8</p>
<p class="Index-Level-2">and Gn 3 curses, [32](#_idIndexMarker057)<span class="No-Break">–3</span>5</p>
<p class="Index-Level-2">guidelines for, [622](#_idIndexMarker1142)<span class="No-Break">–6</span>23</p>
<p class="Index-Level-2">husband-wife, [76](#_idIndexMarker180)<span class="No-Break">–1</span>01</p>
<p class="Index-Level-2">inferiority and, [43](#_idIndexMarker097)<span class="No-Break">–4</span>5</p>
<p class="Index-Level-2">Israelite society and, [26](#_idIndexMarker049)<span class="No-Break">–2</span>8</p>
<p class="Index-Level-2">mutual, [75](#_idIndexMarker173)<span class="No-Break">–7</span>6n</p>
<p class="Index-Level-2">New Testament teaching on, [95](#_idIndexMarker235)<span class="No-Break">–1</span>01</p>
<p class="Index-Level-2">oppressive (<span class="Index-Cross-reference">see</span>&#160;<a href="#domination">domination</a>)</p>
<p class="Index-Level-2">and submissiveness, [93](#_idIndexMarker230)</p>
<p class="Index-Level-2">types of, [40](#_idIndexMarker091)<span class="No-Break">–4</span>5</p>
<p class="Index-Level-2">and unchristian spouse, [90](#_idIndexMarker217)<span class="No-Break">–9</span>1</p>
<p class="Index-Level-2">value of in church, [592](#_idIndexMarker1092)<span class="No-Break">–5</span>93</p>
<p class="Index-Level-1">Swidler, Arlene, [8](#_idIndexMarker015)<span class="No-Break">–9</span>n*<span class="Footnote-Ref">(8)</span></p>
<p class="Leading-Entry-Leading">Tabitha, [111](#_idIndexMarker281)</p>
<p class="Index-Level-1">Talmud, [246](#_idIndexMarker583)<span class="No-Break">–2</span>49</p>
<p class="Index-Level-1">task efficiency, [483](#_idIndexMarker945)<span class="No-Break">–4</span>84, [487](#_idIndexMarker949)</p>
<p class="Index-Level-1">teacher, office of, [107](#_idIndexMarker265)<span class="No-Break">–1</span>08</p>
<p class="Index-Level-1">teaching</p>
<p class="Index-Level-2">function of, [199](#_idIndexMarker494)</p>
<p class="Index-Level-2">in New Testament church, [107](#_idIndexMarker264)<span class="No-Break">–1</span>10</p>
<p class="Index-Level-2">women and, [107](#_idIndexMarker263)<span class="No-Break">–1</span>10, [198](#_idIndexMarker493)<span class="No-Break">–1</span>99, [203](#_idIndexMarker506)<span class="No-Break">–2</span>04</p>
<p class="Index-Level-1">technological society, [478](#_idIndexMarker935)<span class="No-Break">–5</span>18</p>
<p class="Index-Level-2">achievement orientation in, [497](#_idIndexMarker960)</p>
<p class="Index-Level-2">adapting to, [629](#_idIndexMarker1152)<span class="No-Break">–6</span>36</p>
<p class="Index-Level-2">ethics in, [545](#_idIndexMarker1022)<span class="No-Break">–5</span>50</p>
<p class="Index-Level-2">evaluation of, [514](#_idIndexMarker979)<span class="No-Break">–5</span>18, [551](#_idIndexMarker1032)<span class="No-Break">–5</span>53</p>
<p class="Index-Level-2">psychological problems, [516](#_idIndexMarker981)<span class="No-Break">–5</span>17</p>
<p class="Index-Level-2">relationships in, [595](#_idIndexMarker1097)<span class="No-Break">–5</span>96</p>
<p class="Index-Level-2">social problems, [514](#_idIndexMarker980)<span class="No-Break">–5</span>16</p>
<p class="Index-Level-2">social roles in, [604](#_idIndexMarker1110)<span class="No-Break">–6</span>08</p>
<p class="Index-Level-2">values in, [497](#_idIndexMarker957)<span class="No-Break">–5</span>02</p>
<p class="Index-Level-1">Tertullian, [295](#_idIndexMarker676)<span class="No-Break">–2</span>96, [306](#_idIndexMarker688), [325](#_idIndexMarker725)<span class="No-Break">–3</span>26</p>
<p class="Index-Level-1">Thecla (evangelist), [118](#_idIndexMarker297)</p>
<p class="Index-Level-1">Theodore of Mopsuestia, [310](#_idIndexMarker697)</p>
<p class="Index-Level-1">Theodoret of Cyrus, [310](#_idIndexMarker698)</p>
<p class="Index-Level-1">the “world,” [550](#_idIndexMarker1030)</p>
<p class="Index-Level-1">Tiger, Lionel, [444](#_idIndexMarker912)<span class="No-Break">–4</span>47</p>
<p class="Index-Level-1">Toledo, Council of, [313](#_idIndexMarker711)</p>
<p class="Index-Level-1">tradition</p>
<p class="Index-Level-2">authority of, [288](#_idIndexMarker664)<span class="No-Break">–2</span>89</p>
<p class="Index-Level-2">defined, [288](#_idIndexMarker663)<span class="No-Break">–2</span>90</p>
<p class="Index-Level-2">interpretation of, [326](#_idIndexMarker726)<span class="No-Break">–3</span>28</p>
<p class="Index-Level-2">objections to, [318](#_idIndexMarker719)<span class="No-Break">–3</span>19</p>
<p class="Index-Level-2">strength of, [322](#_idIndexMarker724)<span class="No-Break">–3</span>23</p>
<p class="Index-Level-2">value of, [286](#_idIndexMarker658)<span class="No-Break">–2</span>87</p>
<p class="Index-Level-1">traditional roles, influence of, [510](#_idIndexMarker972)<span class="No-Break">–5</span>11</p>
<p class="Index-Level-1">traditional society, [479](#_idIndexMarker936)<span class="No-Break">–4</span>83</p>
<p class="Index-Level-2">Christian society and, [609](#_idIndexMarker1118)<span class="No-Break">–6</span>10, [628](#_idIndexMarker1151)<span class="No-Break">–6</span>29</p>
<p class="Index-Level-2">relationships in, [483](#_idIndexMarker941), [595](#_idIndexMarker1096)</p>
<p class="Index-Level-1">training of children, [68](#_idIndexMarker160)<span class="No-Break">–6</span>9</p>
<p class="Index-Level-1">Trilling, Lionel, [500](#_idIndexMarker964)<span class="No-Break">–5</span>01n</p>
<p class="Leading-Entry-Leading">unity</p>
<p class="Index-Level-2">and community, [39n†](#_idIndexMarker087)</p>
<p class="Index-Level-2">God’s desire, [39](#_idIndexMarker090)<span class="No-Break">–4</span>0</p>
<p class="Index-Level-2">subordination and, [41](#_idIndexMarker095)</p>
<p class="Leading-Entry-Leading">values (in technological society), [497](#_idIndexMarker956)<span class="No-Break">–5</span>02</p>
<p class="Index-Level-1">Vatican&#160;II. <span class="Index-Cross-reference">See</span>&#160;<a href="#second-vatican-council">Second Vatican Council</a></p>
<p class="Index-Level-1">verbal ability, [408](#_idIndexMarker848)</p>
<p class="Index-Level-1">Victorian caricature, [513](#_idIndexMarker978)</p>
<p class="Index-Level-1">von Hildebrand, Dietrich. <span class="Index-Cross-reference">See</span>&#160;<a href="#hildebrand">Hildebrand, Dietrich von</a></p>
<p class="Leading-Entry-Leading">widows</p>
<p class="Index-Level-2">charitable service and, [110](#_idIndexMarker276)<span class="No-Break">–1</span>13</p>
<p class="Index-Level-2">order of, [56](#_idIndexMarker134)<span class="No-Break">–5</span>7, [122](#_idIndexMarker305)</p>
<p class="Index-Level-1">wife</p>
<p class="Index-Level-2">role of, [56](#_idIndexMarker132)<span class="No-Break">–6</span>4, [97](#_idIndexMarker240)<span class="No-Break">–1</span>01</p>
<p class="Index-Level-2">subordinate to husband, [60](#_idIndexMarker141), [82](#_idIndexMarker195)<span class="No-Break">–8</span>3</p>
<p class="Index-Level-1">woman</p>
<p class="Index-Level-2">companion to man, [20](#_idIndexMarker037)<span class="No-Break">–2</span>1</p>
<p class="Index-Level-2">creation of, [17](#_idIndexMarker034)<span class="No-Break">–1</span>9</p>
<p class="Index-Level-2">glory of man, [181](#_idIndexMarker454)<span class="No-Break">–1</span>82</p>
<p class="Index-Level-2">helper, [22](#_idIndexMarker038)</p>
<p class="Index-Level-2">Victorian caricature of, [513](#_idIndexMarker977)</p>
<p class="Index-Level-2">weakness of, [320](#_idIndexMarker722)<span class="No-Break">–3</span>21</p>
<p class="Index-Level-1">womanhood, [663](#_idIndexMarker1187)</p>
<p class="Index-Level-1">women’s liberation, [532](#_idIndexMarker996)<span class="No-Break">–5</span>33</p>
<p class="Index-Level-2"><span class="Index-Cross-reference">See also</span>&#160;<a href="#feminism">feminism</a></p>
<p class="Index-Level-1">women’s rights, [511](#_idIndexMarker973)<span class="No-Break">–5</span>13, [512](#_idIndexMarker975)<span class="No-Break">–5</span>13, [683](#_idIndexMarker1203)<span class="No-Break">–6</span>87</p>
<p class="Index-Level-1">work (guidelines for), [620](#_idIndexMarker1139)<span class="No-Break">–6</span>22</p>
<p class="Index-Level-1">worship, [151](#_idIndexMarker391)<span class="No-Break">–1</span>52, [171](#_idIndexMarker427)<span class="No-Break">–1</span>87, [274](#_idIndexMarker641)</p>
<p class="Leading-Entry-Leading">zakar, [12n†](#_idIndexMarker023)</p>
