# Publication Info {-}

<p id="_idParaDest-124" class="F-B-MATTER_Copyright-Info-1st"><a id="_idTextAnchor2011"></a><span class="ALL-CAPS">Warhorn Media</span></p>
<p class="F-B-MATTER_Copyright-Info">2401 S Endwright Rd.</p>
<p class="F-B-MATTER_Copyright-Info">Bloomington, Indiana 47403</p>
<p class="F-B-MATTER_Copyright-Info-SA"><a href="https://warhornmedia.com"><span class="OT-All-Small-Caps">WarhornMedia.com</span></a></p>
<p class="F-B-MATTER_Copyright-Info-SA">©&#160;1980, 2006, and 2021 by Stephen B. Clark. All rights reserved. Originally published 1980 by Servant Books. Published 2006 by Tabor House. This edition published 2021 by Warhorn Media by permission of the author, with special thanks to John Yocum, Servants of the Word, and Jeff Smith for their assistance in obtaining the rights of publication.</p>
<p class="F-B-MATTER_Copyright-Info"><span class="OT-All-Small-Caps">ISBN-13</span>: 978-1-940017-32-7 (EPUB)</p>
<p class="F-B-MATTER_Copyright-Info-SA"><span class="OT-All-Small-Caps">ISBN-13</span>: 978-1-940017-33-4 (Kindle)</p>
<p class="F-B-MATTER_Copyright-Info-SA">Unless otherwise indicated, all scripture quotations are from the Revised Standard Version of the Bible (<span class="OT-All-Small-Caps">RSV</span>), copyright ©&#160;1946, 1952, and 1971 by the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.</p>
<p class="F-B-MATTER_Copyright-Info-SA">Design by Alex McNeilly. Cover image by Tim&#160;Mossholder on Unsplash.</p>
<p class="F-B-MATTER_Copyright-Info">This edition owes its publication to the labor of the following individuals:</p>
<p class="F-B-MATTER_Copyright-Info-Indented"><span class="OT-All-Small-Caps">Acquisition</span>: Joseph Bayly, Tim Bayly</p>
<p class="F-B-MATTER_Copyright-Info-Indented"><span class="OT-All-Small-Caps">Manuscript prep</span>: Ben Sulser</p>
<p class="F-B-MATTER_Copyright-Info-Indented-SA"><span class="OT-All-Small-Caps">Proofreading</span>: David Canfield, Daniel Meyer</p>
<p class="F-B-MATTER_Copyright-Info">This 2021 edition of <span class="Italic">Man and Woman in Christ</span> is available in hardcover (<span class="No-Break">ISBN-13</span>: 978-1-940017-30-3) on <a href="https://www.amazon.com/dp/1940017300/ref=cm_sw_em_r_mt_dp_E8EBSPCHBCXJH1FSTSE7">Amazon</a> and at discounted bulk rates directly from <a href="https://warhornmedia.com/contact-us/">Warhorn Media</a>.</p>
<div class="Buy-Buttons">
<p class="Buy-Button"><a href="https://www.amazon.com/dp/1940017300/ref=cm_sw_em_r_mt_dp_E8EBSPCHBCXJH1FSTSE7">Buy on Amazon</a></p>
<p class="Buy-Button"><a href="https://warhornmedia.com/contact-us/">Contact WARHORN Sales</a></p>
</div>
